const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
async function start(main,variant,day,flow){await p.evaluate(async({main,variant,day,flow})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main});barGame.reset(day,'full',1,false);c.session.day=day;c.session.route=flow;c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day,flow,place:'home',variant});await outsidePlaytest.start();c.screen(c.playView);outsidePlaytest.model.x=3.364;outsidePlaytest.model.updateNear();outsidePlaytest.tick(0);},{main,variant,day,flow});}
for(const [main,variant]of [[true,'original'],[false,'original'],[false,'gpt']])for(const day of [0,1,2,3])for(const flow of ['in','out']){await start(main,variant,day,flow);assert.equal(await p.evaluate(()=>outsidePlaytest.model.targets().some(t=>t.id==='terrace')),false);assert.equal(await p.evaluate(()=>outsidePlaytest.model.near),null);assert.equal(await p.locator('.outside-interact').isVisible(),false);await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),main?'game':'developer');assert.equal(await p.evaluate(()=>lunaCampaign.memoryTransition||null),null);const unchanged=await p.evaluate(()=>{const c=lunaCampaign,m=outsidePlaytest.model,view=c.view;c.interactOutside(m,{id:'terrace'});c.action('sleep-confirm');return c.view===view&&!c.dialog&&!c.memoryTransition;});assert(unchanged);}
// Only the sofa confirmation may begin main sleep; repeated input never requeues a scene.
await start(true,'original',1,'out');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=2.557;m.updateNear();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'sleep');await p.locator('[data-campaign="sleep-confirm"]').click();assert.equal(await p.evaluate(()=>lunaCampaign.dialog.background),'black');const same=await p.evaluate(()=>{const c=lunaCampaign,d=c.dialog;for(let i=0;i<5;i++)c.action('sleep-confirm');return c.dialog===d&&c.nightStarted;});assert(same);
async function finishDay(main){await p.evaluate(()=>{const c=lunaCampaign;while(c.dialog?.background==='black'){c.dialog.chars=1e5;c.next();}});await p.waitForFunction(()=>lunaCampaign.view==='scene'&&!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.background),'terrace');assert(await p.evaluate(()=>{const c=lunaCampaign,d=c.dialog;c.sleep();c.sleepOutsideTest(outsidePlaytest.model);return c.dialog===d;}));await p.evaluate(()=>{const c=lunaCampaign;while(c.view==='scene'&&!c.dayTransition){c.dialog.chars=1e5;c.next();}});await p.waitForFunction(main=>!lunaCampaign.dayTransition&&lunaCampaign.view===(main?'game':'developer')&&outsidePlaytest.model.config.day===2,main);assert.equal(await p.evaluate(()=>outsidePlaytest.model.near.id),'sofa');await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'notice');assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.day),2);}
await finishDay(true);await start(false,'original',1,'out');await p.evaluate(()=>{outsidePlaytest.model.x=2.557;outsidePlaytest.model.updateNear();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.background),'black');await finishDay(false);
const allowed=await p.evaluate(()=>{const list=LunaOutsideQA.catalog();return{door:list.some(c=>c.id==='terrace'),nightQA:list.some(c=>c.id==='runtime:night0')};});assert.deepEqual(allowed,{door:false,nightQA:true});
assert.deepEqual(errors,[]);console.log('TERRACE_SLEEP_ONLY_OK main/developer/GPT, days0-3 both routes, no door target/E/popup, stale handler blocked, sofa-only main confirmation, duplicate sleep guarded, explicit QA preview retained');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
