const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
async function start(main=false,variant='original',cfg={}){await p.evaluate(async({main,variant,cfg})=>{const c=lunaCampaign,a=outsidePlaytest;c.outside.exit(true);c.session.uninstall();c.session.install({developer:!main});barGame.reset(2,'full',1,false);c.session.day=2;c.session.route='in';c.session.carry=structuredClone(barGame.progress);Object.assign(a.config,{day:2,flow:'in',place:'bar',variant,...cfg});await a.start();c.screen(c.playView);const m=a.model;m.x=-7.15;m.updateNear();a.snapCamera();a.tick(0);},{main,variant,cfg});}
async function enter(){await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.encounter?.kind==='day2-samho-commute');await p.keyboard.up('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line?.text==='뭐야, 넌. 못 보던 얼굴인데?');}
for(const [main,variant] of [[false,'original'],[false,'gpt'],[true,'original']]){
 await start(main,variant);assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);assert.equal(await p.evaluate(()=>outsidePlaytest.model.targets().some(t=>t.id==='story-samho')),false);await enter();assert.equal(await p.evaluate(()=>lunaCampaign.view),main?'game':'developer');assert.equal(await p.locator('.campaign-scene').count(),0);assert.equal(await p.locator('.outside-speech strong').count(),0);
 const x=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyD');await p.waitForTimeout(250);await p.keyboard.up('KeyD');assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),x);
 await p.evaluate(()=>{outsidePlaytest.model.story.speech.elapsed=99;outsidePlaytest.refreshHUD();});await p.screenshot({path:'/private/tmp/day2-samho-'+(main?'main':variant)+'.png'});
 const dialogue=await p.evaluate(()=>{const m=outsidePlaytest.model,seen=[];for(let i=0;m.story.speech?.line&&i<40;i++){seen.push(m.story.speech.line.text);m.story.speech.elapsed=99;m.story.advance();}return {seen,stage:m.encounter.stage,index:m.story.speech.index};});assert.equal(dialogue.seen.length,26);assert.equal(dialogue.stage,'depart');assert(dialogue.seen[20].includes('듣게 될 거야'));
 await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.index),dialogue.index);await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line?.text==='…서비스?');assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter.alpha),0);
 await p.evaluate(()=>{outsidePlaytest.model.story.speech.elapsed=99;outsidePlaytest.refreshHUD();});await p.keyboard.press('KeyE');await p.waitForFunction(()=>outsidePlaytest.model.encounter===null);assert.equal(await p.evaluate(()=>LunaOutsideSamhoCommute.visible(outsidePlaytest.model)),false);await p.keyboard.down('KeyA');await p.waitForTimeout(200);await p.keyboard.up('KeyA');assert(await p.evaluate(x=>outsidePlaytest.model.x<x,x));
 await p.evaluate(()=>{outsidePlaytest.model.x=-6.5;outsidePlaytest.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);
 if(main){assert(await p.evaluate(()=>barGame.progress.flags.samho_met&&lunaCampaign.session.carry.flags.day2_samho_done));await p.evaluate(()=>{outsidePlaytest.model.start({day:2,flow:'in'});outsidePlaytest.model.x=-6.5;outsidePlaytest.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);}
}
await start();const guards=await p.evaluate(()=>{const m=outsidePlaytest.model,out=[];for(const [day,flow,place]of [[0,'in','bar'],[1,'in','bar'],[2,'out','bar'],[3,'in','bar'],[2,'in','homeDoor'],[2,'in','home']]){m.start({day,flow,place});m.x=-6.5;outsidePlaytest.tick(.05);out.push(!!m.encounter);}return out;});assert.deepEqual(guards,[false,false,false,false,false,false]);
for(const activation of ['source','manual','proximity']){await start(false,'original',{day:99,qaCase:'runtime:commute2',qaActivation:activation});await p.evaluate(activation=>{const a=outsidePlaytest,m=a.model;m.x=0;m.updateNear();a.snapCamera();if(activation==='manual')m.interact();a.tick(.05);},activation);await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line?.text==='뭐야, 넌. 못 보던 얼굴인데?');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.auto),false);await p.evaluate(()=>{const m=outsidePlaytest.model;for(let i=0;m.story.speech?.line&&i<40;i++){m.story.speech.elapsed=99;m.story.advance();}});await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line?.text==='…서비스?');await p.evaluate(()=>{const s=outsidePlaytest.model.story;s.speech.elapsed=99;s.advance();});await p.waitForFunction(()=>outsidePlaytest.model.encounter===null);assert(await p.evaluate(()=>outsidePlaytest.model.qa.done));}
assert.deepEqual(errors,[]);console.log('DAY2_LIVE_OK main/original/GPT/QA, auto trigger, dialogue27, movement lock, departure before final line, camera return, once/run, day guards');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
