const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 for(const [main,version]of [[true,'A'],[true,'B'],[false,'A']]){
  await p.evaluate(async({main,version})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main,serviceVersion:version});barGame.reset(3,'full',10,false,{serviceVersion:version});barGame.progress.money=2300;c.session.day=3;c.session.route='in';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:3,flow:'in',place:'bar',variant:'original'});await outsidePlaytest.start();c.screen(c.playView);const m=outsidePlaytest.model;m.x=LunaResidence.layout.elevatorX+.2;m.updateNear();outsidePlaytest.snapCamera();},{main,version});
  await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.encounter);await p.keyboard.up('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line?.text==='어, 루나. 출근해?');assert.equal(await p.locator('.campaign-scene,.outside-speech strong').count(),0);const x=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyD');await p.waitForTimeout(150);await p.keyboard.up('KeyD');assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),x);
  if(main&&version==='A')await p.screenshot({path:'/private/tmp/day3-commute.png'});
  const lines=await p.evaluate(()=>{const m=outsidePlaytest.model,seen=[];for(let i=0;i<20&&m.story.speech?.line;i++){seen.push(m.story.speech.line.text);m.story.speech.elapsed=99;m.story.advance();}return seen;});assert.equal(lines.length,7);await p.waitForFunction(()=>!outsidePlaytest.model.encounter);await p.evaluate(()=>outsidePlaytest.tick(.05));assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);
  await p.evaluate(async()=>{const c=lunaCampaign;c.session.route='out';outsidePlaytest.exit(true);Object.assign(outsidePlaytest.config,{day:3,flow:'out',place:'home'});await outsidePlaytest.start({wakeAtSofa:true});c.screen(c.playView);});await p.keyboard.press('KeyE');if(main)await p.locator('[data-campaign="sleep-confirm"]').click();await p.waitForFunction(()=>!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows.length),14);
  await p.evaluate(()=>{const c=lunaCampaign;for(let i=0;i<20&&!c.memoryTransition;i++){c.dialog.chars=1e5;c.next();}});await p.waitForFunction(()=>lunaCampaign.view==='prologue'&&!lunaCampaign.memoryTransition,null,{timeout:60000});assert.equal(await p.evaluate(()=>lunaCampaign.cinema.memoryKey),'terraceMemory3');assert.deepEqual(await p.evaluate(()=>lunaCampaign.cinema.scene.lines.map(l=>l.actor)),['luna','yuna','yuna','luna','yuna']);assert.equal(await p.locator('.campaign-cinema-ui strong,.campaign-cinema-ui .speaker').count(),0);
  await p.evaluate(()=>{const c=lunaCampaign.cinema,l=c.scene.lines[1];c.time=l.t+l.dur-.1;c.player.render(c.time,null,false,0);});if(main&&version==='A')await p.screenshot({path:'/private/tmp/day3-terrace-memory.png'});
  await p.keyboard.press('Escape');const t=await p.evaluate(()=>lunaCampaign.cinema.time);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>lunaCampaign.cinema.time),t);await p.keyboard.press('Escape');
  if(version==='B'){await p.keyboard.down('Space');await p.waitForTimeout(3200);await p.keyboard.up('Space');}else await p.evaluate(()=>{const c=lunaCampaign;c.cinema.time=c.cinema.scene.end-.01;c.tick(.05);});
  await p.waitForFunction(()=>lunaCampaign.view==='scene'&&!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),7);assert.equal(await p.evaluate(()=>barGame.progress.money),2300);
  const tail=await p.evaluate(()=>{const c=lunaCampaign,seen=[];for(let i=0;i<20&&c.view==='scene';i++){seen.push(c.dialog.rows[c.dialog.index].text);c.dialog.chars=1e5;c.next();}return seen;});assert.equal(tail.at(-1),'네. 보스.');assert.equal(tail.length,7);assert.equal(await p.evaluate(()=>lunaCampaign.view),main?'ending':'notice');
 }
 assert.deepEqual(errors,[]);console.log('DAY3_UI_OK A/B/developer: lift-side forced7, move lock, once/run, terrace14 -> Yuna memory5, text-only, pause, 3s skip/natural finish, exact resume, requested ending');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
