const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const dir=path.resolve(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(dir+'/data.js','utf8'),ctx);const D=ctx.window.LUNA_DATA,C=require(dir+'/core.js'),R=require(dir+'/remix.js'),pour=require('./pour-test-driver.cjs');
const original=JSON.stringify(D);require(dir+'/remix-experience.js');
function create(){const g=new C.Game(C.millilitreData(D));R.attach(g);g.reset(0,'episode',7,true,{variant:'gpt'});g.dialogSpeed=20;return g;}
function tick(g,t){for(let n=0;n<t;n+=.05)g.tick(.05);assert.equal(g.error,null);}
function waitOrder(g){tick(g,2.2);g.coaster();tick(g,9);assert.equal(g.seats.L.state,'WAIT_SERVE');}
function craft(g,id){g.openRecipes();g.selectCocktail(id);g.prep.glass=g.cocktail(id).glass;g.prep.ingredients=g.t.recipes.filter(r=>r.context===id&&!r.auto_apply).map(r=>r.ingredient);g.startCraft();while(g.screen==='gimmick'){if(g.remix.hold){tick(g,1);continue;}pour(g);}tick(g,1.4);assert.equal(g.result.grade,'excellent');g.offer();g.serve('L','drag');tick(g,15);assert(g.finished);}
let g=create();assert.equal(g.queue.length,1);waitOrder(g);tick(g,650);assert.equal(g.lost,0);craft(g,'gin_tonic');assert.equal(g.remix.episodeReaction,'……딱 원하던 맛이네요. 이제야 오늘 일이 끝난 것 같아요.');assert.equal(g.remix.bonus,0);assert.equal(g.remix.goalBonus,0);assert.equal(g.dailySettlement.upkeep,0);assert.equal(g.transactions.length,1);assert(global.LunaRemixExperience.lastEpisode.text.includes('오늘 일이'));assert(!global.LunaRemixExperience.lastEpisode.debug);
g=create();waitOrder(g);g.openRecipes();g.selectCocktail('gin_tonic');g.debugCraft('poor');tick(g,1.5);g.offer();g.serve('L','drag');tick(g,15);assert(g.finished);assert(g.remix.episodeReaction.includes('맛이 좀 다르'));assert(global.LunaRemixExperience.lastEpisode.debug);
g=create();waitOrder(g);g.openRecipes();g.selectCocktail('gin_fizz');g.debugCraft('excellent');tick(g,1.5);g.offer();g.serve('L','drag');tick(g,15);assert(g.finished);assert.equal(g.transactions[0].sewage,'order_mismatch');assert(g.remix.episodeReaction.includes('원한 건 다른'));
g.reset(99,'general',7,true,{variant:'original'});assert.equal(g.remix,null);assert.equal(g.bark({...g.seats.L,slot:{},personality:{id:'gentle'},actor:'gentle'},'call').id.startsWith('rx_episode_'),false);
assert.deepEqual(Object.values(R.PROFILES).map(p=>[p.shake,p.stir]),[[15,8],[15,8],[15,8]]);assert.equal(JSON.stringify(D),original);console.log('STORYFIRST_CORE_OK: actual pours, one complete episode, poor response, patience, zero bonus/upkeep, no source mutations, 15/8 counts');
