const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const dir=path.resolve(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(dir+'/data.js','utf8'),ctx);
const D=ctx.window.LUNA_DATA,C=require(dir+'/core'),R=require(dir+'/remix'),M=require(dir+'/minigames'),original=JSON.stringify(D);
let count=0;function test(name,fn){fn();count++;console.log('PASS',name);}
function game(){const g=new C.Game(D);R.attach(g);M.attach(g);return g;}
function tick(g,s){for(let t=0;t<s;t+=.01)g.tick(.01);assert.equal(g.error,null);}
const pour=require('./pour-test-driver.cjs');
function finish(g){let guard=0;while(g.screen==='gimmick'&&guard++<2000){const s=g.gimmick;if(g.remix?.hold){tick(g,1);continue;}if(!s.started)g.gimmickInput(s.type==='stir'?'KeyW':'Space');if(['pour','fill_up'].includes(s.type)){pour(g);}else if(s.type==='open'){s.beatTime=1.6;g.gimmickInput('Space');}else if(s.type==='shake'){while(!C.MIX.nearest(s))g.tick(.005);g.gimmickInput('Space');g.tick(.06);}else if(s.type==='stir'){for(const key of ['KeyD','KeyS','KeyA','KeyW']){tick(g,.12);g.gimmickInput(key);}}if(s.completed&&g.variant==='original')g.endGimmick();tick(g,.01);}assert.equal(g.screen,'minigame_result');}
for(const variant of ['original','gpt'])for(const kind of M.KINDS)test(variant+' '+kind+': one stage, correct single-skill score, no bar effects',()=>{const g=game();let records=0;g.onRemixRecord=()=>records++;g.read.add('preserved');g.startMinigame(kind,variant);const money=g.progress.money;assert.equal(g.craft.queue.length,1);assert.equal(g.gimmick.type,kind);assert.equal(g.screen,'gimmick');assert.equal(g.story,null);assert.equal(g.currentOrder,null);finish(g);assert.equal(g.minigame.result.score,100);assert.equal(g.craft.results.length,1);assert.equal(records,0);assert.equal(g.progress.money,money);assert.equal(g.transactions.length,0);assert.equal(g.dailySettlement,null);assert.equal(g.result,null);assert(g.read.has('preserved'));assert.equal(g.remix?.crafts||0,0);assert.equal(g.remix?.goalBonus||0,0);});
test('data supplies quantity examples; no invented recipe targets',()=>{const g=game();for(const kind of ['pour','fill_up']){const e=M.example(g,kind),line=g.t.recipes.find(r=>r.context===e.selected.id&&r.action===kind);assert.equal(e.step.target,Number(line.qty));assert.equal(e.step.unit,line.unit);}});
test('quantity misses score the chosen skill, not missing full-recipe steps',()=>{const g=game();g.startMinigame('pour','original');pour(g,1.5);assert.equal(g.minigame.result.score,C.band(g.t.score_bands,'quantity',Math.abs(g.minigame.result.value/g.minigame.result.target-1)));assert(g.minigame.result.score<100);});
test('opening misses and failed mix attempts lower standalone scores',()=>{const g=game();g.startMinigame('open','gpt');g.gimmickInput('Space');g.gimmickInput('Space');finish(g);assert.equal(g.minigame.result.score,85);g.startMinigame('stir','gpt','cozy');g.gimmickInput('KeyW');g.gimmickInput('KeyA');finish(g);assert(g.minigame.result.score<100);});
test('pause, early-end guard, retry reset and repeated completion are safe',()=>{const g=game();g.startMinigame('stir','gpt','cozy');assert.equal(g.endGimmick(),false);g.gimmickInput('KeyW');tick(g,.3);g.overlay='settings';const elapsed=g.craft.elapsed;tick(g,2);assert.equal(g.craft.elapsed,elapsed);g.overlay=null;finish(g);const id=g.minigame.result.id;g.endGimmick();assert.equal(g.craft.results.length,1);g.retryMinigame();assert.notEqual(g.craft.id,id);assert.equal(g.gimmick.targetStacks,6);assert.equal(g.gimmick.started,false);assert.equal(g.craft.results.length,0);assert.equal(g.craft.elapsed,0);assert.equal(g.minigame.result,null);});
test('leaving a feedback hold cannot finish a later session',()=>{const g=game();g.startMinigame('open','gpt');g.gimmickInput('Space');g.gimmick.beatTime=1.6;g.gimmickInput('Space');tick(g,.01);assert(g.remix.hold);g.reset(1,'general',1,true,{variant:'original'});tick(g,2);assert.equal(g.minigame,null);assert.equal(g.remix,null);assert.equal(g.phase,'general');assert.equal(g.queue.length,4);assert.equal(g.craft,null);});
test('normal recipe still has all steps after minigame practice',()=>{const g=game();g.startMinigame('shake','gpt');g.reset(99,'practice',1,true,{variant:'gpt'});g.selectCocktail('gin_fizz');g.debugFill();g.startCraft();assert(g.craft.queue.length>1);assert.equal(g.minigame,null);assert.equal(g.gimmick.type,'pour');});
test('invalid kind is rejected without resetting an active game',()=>{const g=game();g.reset(1,'general');const phase=g.phase;assert.throws(()=>g.startMinigame('missing'));assert.equal(g.phase,phase);});
test('original data stays unchanged',()=>assert.equal(JSON.stringify(D),original));
console.log('MINIGAMES_CORE_OK',count,'groups');
