const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1600,height:1000}}),errors=[],missing=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)missing.push([r.status(),r.url()]);});await p.goto('http://127.0.0.1:8123/bar-playtest/resource-review.html');await p.waitForFunction(()=>resourceReview.ready);const list=await p.evaluate(()=>resourceReview.rows.filter(r=>r.launch&&['bar-ui','out-ui','bar-serve'].includes(r.group)).map(r=>({id:r.id,title:r.title,d:r.launch,note:r.note})));const fail=[];
for(const r of list){await p.evaluate(r=>resourceReview.launch(r.d,r.title,r.note),r);await p.waitForTimeout(70);const status=await p.evaluate(()=>({error:document.querySelector('#lab-note').classList.contains('error')?document.querySelector('#lab-note').textContent:null,game:document.querySelector('iframe').contentWindow.barGame.error}));if(status.error||status.game)fail.push([r.id,status]);await p.evaluate(()=>resourceReview.close());}
console.log('SMOKE',list.length,'FAILURES',fail,'ERRORS',errors,'MISSING',missing);assert.deepEqual(fail,[]);assert.deepEqual(errors,[]);assert.deepEqual(missing,[]);
await p.evaluate(()=>resourceReview.select('actor:chris:Chris_idle_talk'));await p.waitForTimeout(350);await p.screenshot({path:'/private/tmp/resource-review-animation.png'});
await p.evaluate(()=>resourceReview.launch({type:'pair'},'단골 2명 / 루나 말풍선'));await p.waitForTimeout(1300);await p.screenshot({path:'/private/tmp/resource-review-live.png'});await p.evaluate(()=>resourceReview.close());
await p.click('[data-group="out-characters"]');await p.evaluate(()=>resourceReview.select('cinema:luna_v2-run_Sheet'));await p.waitForTimeout(300);await p.screenshot({path:'/private/tmp/resource-review-outside.png'});
await p.setViewportSize({width:390,height:844});await p.screenshot({path:'/private/tmp/resource-review-mobile.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));console.log('SCREENSHOTS_OK');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
