const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{
const p=await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/resource-review.html');await p.waitForFunction(()=>resourceReview.ready&&resourceReview.missing);
const entries=await p.evaluate(()=>resourceReview.missing.entries);assert(entries.length>10);assert.equal(new Set(entries.map(e=>e.id)).size,entries.length);
const passers=await p.evaluate(()=>resourceReview.rows.filter(r=>r.group==='out-characters'&&(/^outside:(M1|M2|W1)$/.test(r.id)||r.id.startsWith('outside-role:')&&/^행인(?:\s*\d+)?$/.test(r.title||''))).map(r=>r.id));
assert(passers.length>=7,'Passerby assets remain in the normal catalog');
assert(!entries.some(e=>e.rows.some(x=>passers.includes(x.row.id))),'Passerby excluded from missing list');
for(const id of ['bd-vendor','thug','resident-left','trade-smuggler'])assert(entries.some(e=>e.rows.some(x=>x.row.id==='outside-role:'+id)),id+' remains');
assert(!entries.some(e=>e.rows.some(x=>/^item:gin:/.test(x.row.id))));assert(entries.some(e=>e.rows.some(x=>x.row.id==='item:milk:shelf')));assert(!entries.some(e=>e.rows.some(x=>x.row.id==='bg:street:residence-building')));
console.log('GAPS',Object.fromEntries(['cocktail','item','character','background','ui','effect'].map(c=>[c,entries.filter(e=>e.category===c).length])));
await p.click('#missing-resources');assert(await p.locator('#missing-dialog').isVisible());assert.equal(await p.locator('[data-missing-category]').count(),7);assert.equal(await p.locator('#missing-list .missing-entry').count(),entries.length);assert.equal(await p.evaluate(()=>document.activeElement.id),'missing-search');
await p.waitForTimeout(350);await p.screenshot({path:'/private/tmp/resource-missing-all.png'});
for(const cat of ['cocktail','item','character','background','ui','effect']){await p.click('[data-missing-category="'+cat+'"]');assert.equal(await p.locator('#missing-list .missing-entry').count(),entries.filter(e=>e.category===cat).length);}
await p.click('[data-missing-category="item"]');await p.fill('#missing-search','우유');assert.equal(await p.locator('#missing-list .missing-entry').count(),1);assert((await p.locator('#missing-list').innerText()).includes('공용 더미 사용'));await p.locator('#missing-list summary').click();assert.equal(await p.locator('#missing-list .missing-detail').count(),3);await p.screenshot({path:'/private/tmp/resource-missing-item.png'});
const download=p.waitForEvent('download');await p.click('#missing-export');assert.equal((await download).suggestedFilename(),'unknown-missing-resources.csv');
await p.click('.missing-inspect');assert(!await p.locator('#missing-dialog').isVisible());assert.equal(await p.evaluate(()=>resourceReview.selected.id),'item:milk:shelf');assert.equal(await p.locator('[data-group="bar-items"]').getAttribute('aria-current'),'true');
await p.click('#missing-resources');await p.click('#missing-reset');await p.selectOption('#missing-area','외부');await p.selectOption('#missing-reason','sharedDummy');assert(await p.locator('#missing-list .missing-entry').count()>0);assert((await p.locator('#missing-list').innerText()).includes('BD 칩'));
await p.fill('#missing-search','없는리소스검색');assert.equal(await p.locator('#missing-list .missing-entry').count(),0);assert(await p.locator('.missing-empty').isVisible());await p.click('#missing-reset');
await p.keyboard.press('Escape');assert(!await p.locator('#missing-dialog').isVisible());assert.equal(await p.evaluate(()=>document.activeElement.id),'missing-resources');
await p.setViewportSize({width:390,height:844});await p.click('#missing-resources');await p.click('[data-missing-category="character"]');await p.screenshot({path:'/private/tmp/resource-missing-mobile.png'});assert(await p.locator('#missing-dialog').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.click('#missing-close');assert(!await p.locator('#missing-dialog').isVisible());assert.deepEqual(errors,[]);
console.log('RESOURCE_MISSING_UI_OK',entries.length,'grouped gaps, category/search/reason/area filters, details, CSV, inspect navigation, Escape/focus, mobile');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
