const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
const id='outside_day0_store_passers';
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
for(const [main,variant]of [[false,'original'],[false,'gpt'],[true,'original']]){
 await p.evaluate(async({main,variant})=>{const c=lunaCampaign,a=outsidePlaytest;a.exit(true);c.session.uninstall();c.session.install({developer:!main});barGame.reset(0,'full',1,false);c.session.day=0;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(a.config,{day:0,flow:'out',place:'bar',variant});await a.start();c.screen(c.playView);a.model.x=-3.9;a.model.updateNear();a.snapCamera();a.tick(.05);},{main,variant});
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech),null);
 await p.evaluate(()=>{const a=outsidePlaytest;a.model.x=-4.35;a.snapCamera();a.tick(.05);a.model.backgroundStory.speech.elapsed=1;a.refreshHUD();});
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.id),id);
 if(!main&&variant==='original')await p.screenshot({path:'/private/tmp/store-passers.png'});
 const result=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,lines=new Set();let hidden=0;for(let i=0;i<1000;i++){const s=m.backgroundStory.speech;if(s){lines.add(s.index);if(document.querySelector('.outside-background-speech').hidden)hidden++;}a.tick(.05);}const before=m.x;m.tick(.05,{move:-1});return{lines:lines.size,hidden,complete:m.backgroundStory.done.has('outside_day0_store_passers'),blocked:m.story.blocking,movable:m.x<before,replay:!!m.backgroundStory.speech,faces:LunaOutsideAmbient.placements.filter(p=>p.id.startsWith('store-')).map(p=>LunaOutsideAmbient.faceTarget(p.x,LunaOutsideEncounters.actor(p.faces).x))};});
 assert.deepEqual(result,{lines:8,hidden:0,complete:true,blocked:false,movable:true,replay:false,faces:[true,false]});
}
const guards=await p.evaluate(()=>{const out=[];for(const day of [0,1,2,3])for(const flow of ['in','out']){const m=new LunaOutside.Model({day,flow});m.x=-5.4;m.tick(.05);out.push((m.backgroundStory.speech?.id==='outside_day0_store_passers')===(day===0&&flow==='out'));}const q=new LunaOutside.Model({day:99,qaCase:'outside_day0_store_passers'});q.x=0;q.tick(.05);out.push(q.story.speech?.rows.length===8&&q.story.speech.auto&&q.qa.people.length===2);return out;});assert(guards.every(Boolean));assert.deepEqual(errors,[]);console.log('STORE_PASSERS_OK main/original/GPT automatic 8 lines, no E/no names, facing each other, movement unblocked, day0 out only, QA case');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
