const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await p.goto('http://127.0.0.1:8123/bar-playtest/?mode=outside');await p.locator('.updates-confirm').click();await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);
 const npc=await p.evaluate(()=>{const d=LUNA_OUTSIDE_DATA,n=d.scenes.street.nodes.filter(n=>n.ambient),before=n.length;LunaOutsideAmbient.apply(d);const order=LunaOutside.streetDrawOrder(d.scenes.street.nodes);return{count:before,idempotent:d.scenes.street.nodes.filter(n=>n.ambient).length,behind:n.every(n=>order.indexOf(n)<order.findIndex(n=>n.name==='Luna')),frames:n.map(n=>[0,1,2,3,4,5].map(i=>LunaOutsideAmbient.frame(n,i/n.ambient.fps+.00001).x)),feet:n.map(n=>n.sprite.h*(1-n.sprite.pivot.y)),conditions:[0,1,2,3].flatMap(day=>['in','out'].map(flow=>LunaOutsideAmbient.visible({scene:'street',config:{day,flow}})))};});assert.equal(npc.count,5);assert.equal(npc.idempotent,5);assert(npc.behind);assert(npc.feet.every(y=>y===114));assert(npc.frames.every(f=>new Set(f).size===6));assert.deepEqual(npc.conditions,[false,true,false,false,false,false,false,false]);
 await p.evaluate(()=>{outsidePlaytest.model.x=-.9;for(let i=0;i<120;i++)outsidePlaytest.tick(.016);});await p.screenshot({path:'/private/tmp/outside-npc-pair.jpg',type:'jpeg',quality:85});
 const actual=await p.evaluate(()=>{const c=document.querySelector('#outside-root canvas').getContext('2d'),original=c.drawImage,frames=[];c.drawImage=function(im,...args){if(im.src.includes('NPC_idle_'))frames.push([im.src,args[0]]);return original.call(this,im,...args);};outsidePlaytest.tick(0);const initial=frames.slice();frames.length=0;for(let i=0;i<25;i++)outsidePlaytest.tick(.02);const later=frames.slice();frames.length=0;outsidePlaytest.model.config.flow='in';outsidePlaytest.tick(0);const other=frames.slice();c.drawImage=original;outsidePlaytest.model.config.flow='out';return{initial,later,other};});assert(actual.initial.length>=2);assert(actual.later.some(f=>!actual.initial.some(a=>a[0]===f[0]&&a[1]===f[1])));assert.equal(actual.other.length,0);
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-7.495;m.updateNear();});await p.keyboard.press('KeyE');for(let i=0;i<4;i++){await p.keyboard.press('KeyE');assert(await p.locator('.outside-speech').evaluate(e=>{const s=getComputedStyle(e);return s.outlineStyle==='none'&&s.borderTopWidth==='1px';}));}await p.screenshot({path:'/private/tmp/outside-single-outline.jpg',type:'jpeg',quality:85});
 const bounds=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,stats={bottom:Infinity,width:0,samples:0};function sample(){const c=a.camera;stats.bottom=Math.min(stats.bottom,c.y-c.w*720/1280/2);stats.width=Math.max(stats.width,c.w);stats.samples++;}function ticks(n){for(let i=0;i<n;i++){a.tick(1/60);sample();}}m.start({place:'bar',day:0,flow:'out'});m.x=LunaResidence.layout.elevatorX;ticks(120);m.updateNear();m.interact();ticks(150);return stats;});assert(bounds.bottom>=-1.48-1e-6,JSON.stringify(bounds));assert(bounds.width>8);await p.screenshot({path:'/private/tmp/outside-lift-floor-safe.jpg',type:'jpeg',quality:85});
 const ride=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model;let min=Infinity;function ticks(n){for(let i=0;i<n;i++){a.tick(1/60);const c=a.camera;min=Math.min(min,c.y-c.w*720/1280/2);}}ticks(900);const top=m.level;m.updateNear();m.interact();ticks(900);return{min,top,bottom:m.level,ride:!!m.ride};});assert(ride.min>=-1.48-1e-6);assert.equal(ride.top,1);assert.equal(ride.bottom,0);assert(!ride.ride);
 await p.keyboard.press('KeyY');await p.waitForFunction(()=>outsidePlaytest.camera.w>28);assert(await p.evaluate(()=>{const c=outsidePlaytest.camera;return c.y-c.w*720/1280/2>=-1.48-1e-6;}));await p.keyboard.press('KeyY');await p.waitForFunction(()=>outsidePlaytest.camera.w<5);assert(await p.evaluate(()=>{const c=outsidePlaytest.camera;return c.y-c.w*720/1280/2>=-1.48-1e-6;}));assert.deepEqual(errors,[]);console.log('PASS 5 ambient NPCs/6 frames/feet/conditions/draw order, actual animation, one focus border, ascent/descent/panorama camera floor bounds');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

