const assert=require('assert/strict'),{chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&update=shelf-settled');await p.locator('.updates-confirm').click();
for(const seconds of [.45,1.1,0]){
 await p.evaluate(()=>{const g=barGame;g.reset(0,'practice',7,true,{variant:'original'});g.tutorial=null;g.screen='recipe';});await p.locator('[data-act="selectRecipe"][data-id="gin_tonic"]').click();await p.waitForTimeout(150);
 await p.addStyleTag({content:'.shelf-track{transition-duration:'+seconds+'s!important}'});
 await p.evaluate(()=>{barGame.tutorial={kind:'prepNavigate'};window.shelfSamples=[];window.shelfWatching=true;const record=()=>{if(!window.shelfWatching)return;const t=document.querySelector('.shelf-track'),guide=document.querySelector('.day0-guide');if(t){const moving=t.getAnimations().some(a=>a.transitionProperty==='transform'&&a.playState==='running');window.shelfSamples.push({moving,kind:barGame.tutorial?.kind,outline:!!guide?.querySelector('[data-guide-ring="source"]'),tab:document.querySelector('.shelf-slide[data-current="true"] .shelf-scene')?.dataset.category});}requestAnimationFrame(record);};requestAnimationFrame(record);});await p.waitForTimeout(100);
 await p.keyboard.press('KeyD');if(seconds){await p.waitForTimeout(70);await p.keyboard.press('KeyA');await p.waitForTimeout(40);await p.keyboard.press('KeyD');await p.waitForTimeout(seconds*1000+150);}await p.keyboard.press('KeyD');
 if(seconds){await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>barGame.tutorial.kind),'prepNavigate');assert.equal(await p.locator('.day0-guide [data-guide-ring]').count(),0);await p.evaluate(()=>document.querySelector('.shelf-slide[data-current="true"] [data-id="gin"]').dispatchEvent(new PointerEvent('pointerover',{bubbles:true})));assert.equal(await p.evaluate(()=>barGame.tutorial.kind),'prepNavigate');}
 await p.waitForFunction(()=>barGame.tutorial?.kind==='prepHover');await p.locator('.day0-guide [data-guide-ring="source"]').waitFor();
 const gin=p.locator('.shelf-slide[data-current="true"] [data-id="gin"]');await gin.hover();await gin.click();await p.locator('.prep-inventory [data-id="gin"]').click();await gin.click();assert.equal(await p.evaluate(()=>barGame.tutorial.kind),'prepSodaNavigate');await p.locator('.shelf-arrow.next').click();
 if(seconds){await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>barGame.tutorial.kind),'prepSodaNavigate');assert.equal(await p.locator('.day0-guide [data-guide-ring]').count(),0);}
 await p.waitForFunction(()=>barGame.tutorial?.kind==='prepSodaHover');await p.locator('.day0-guide [data-guide-ring="source"]').waitFor();await p.waitForTimeout(100);
 const samples=await p.evaluate(()=>{window.shelfWatching=false;return window.shelfSamples});assert(!samples.some(x=>x.moving&&x.outline),JSON.stringify(samples.filter(x=>x.moving&&x.outline)));if(seconds)assert(samples.some(x=>x.moving));console.log('SHELF_SETTLED_OK',seconds,'seconds, rapid reversal, Gin + Soda, no moving outlines');
}assert.deepEqual(errors,[]);}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
