const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
async function start(cfg){await p.evaluate(async cfg=>{const a=outsidePlaytest;a.exit(true);lunaCampaign.screen('developer');Object.assign(a.config,{day:0,flow:'out',place:'bar',variant:'original',...cfg});await a.start();},cfg);}
async function capture(x){return p.evaluate(x=>{const a=outsidePlaytest,m=a.model,c=document.querySelector('#outside-root canvas').getContext('2d'),original=c.drawImage,records=[];m.x=x;a.snapCamera();c.drawImage=function(im,...args){const kind=im.src.match(/NPC_idle_(M1|M2|W1)/)?.[1];if(kind)records.push({kind,sign:Math.sign(this.getTransform().a),frame:args[0]});return original.call(this,im,...args);};try{a.tick(0);}finally{c.drawImage=original;}return records;},x);}
for(const variant of ['original','gpt']){await start({variant});for(const x of [-1.9,0]){const r=await capture(x);assert.equal(r.find(n=>n.kind==='M2').sign,-1);assert.equal(r.find(n=>n.kind==='W1').sign,1);}await capture(-1.65);await p.waitForTimeout(300);await p.screenshot({path:'/private/tmp/npc-pair-facing-'+variant+'.png'});}
// Vendor must turn toward Luna from either side, independent of the static node flag.
await start({day:1});for(const [x,expected]of [[5.3,1],[6,-1]]){assert.equal((await capture(x)).find(n=>n.kind==='M1').sign,expected);}await capture(5.3);await p.evaluate(()=>outsidePlaytest.model.interact());await p.waitForTimeout(300);await p.screenshot({path:'/private/tmp/npc-vendor-facing.png'});
// Virtual QA pair faces each other too; solo NPCs of every idle type face Luna.
await start({day:99,qaCase:'outside_day0_port_pair'});for(const x of [-1.3,1.4]){const r=await capture(x);assert.equal(r.find(n=>n.kind==='M2').sign,-1);assert.equal(r.find(n=>n.kind==='W1').sign,1);}await capture(-1.3);await p.screenshot({path:'/private/tmp/npc-qa-pair-facing.png'});
await start({day:99,qaCase:'runtime:night1'});for(const kind of ['M1','M2','W1']){await p.evaluate(kind=>{outsidePlaytest.model.qa.people=[{id:'solo-test',name:'QA',x:0,y:-.7,kind}];},kind);for(const [x,expected]of [[-1,1],[1,-1]]){assert.equal((await capture(x)).find(n=>n.kind===kind).sign,expected);}}
assert.deepEqual(errors,[]);console.log('ALL_NPC_FACING_OK actual rendered transforms: original/GPT pairs face each other from both approach sides; BD vendor faces Luna both sides; QA pairs/solo M1 M2 W1');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
