const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();await p.evaluate(async()=>{const c=lunaCampaign;c.session.uninstall();c.session.install();c.session.beginCommute(1);await c.street('in','bar');const m=outsidePlaytest.model;m.x=1.0086;m.updateNear();});
const begin=Date.now();await p.keyboard.press('KeyE');await p.locator('.bar-door-scene').waitFor();assert.equal(await p.locator('.bar-door-sign span').innerText(),'언노운');await p.waitForTimeout(650);await p.screenshot({path:'/private/tmp/bar-door-closed.png'});await p.keyboard.press('Space');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'bar-door');await p.waitForTimeout(1700);assert.equal(await p.locator('.bar-door-scene').getAttribute('data-phase'),'loading');assert.equal(await p.locator('.bar-door-scene').getAttribute('data-open'),'0');
await p.waitForFunction(()=>lunaCampaign.doorTransition?.motionAt!=null);assert(Date.now()-begin>=3000);assert(await p.evaluate(()=>lunaCampaign.doorTransition.ready));await p.waitForTimeout(600);await p.screenshot({path:'/private/tmp/bar-door-opening.png'});const open=await p.locator('.bar-door-scene').getAttribute('data-open');assert(+open>0&&+open<1);assert((await p.locator('.bar-door-leaf').evaluate(e=>new DOMMatrix(getComputedStyle(e).transform).m41))<0);await p.waitForTimeout(860);await p.screenshot({path:'/private/tmp/bar-door-open.png'});await p.waitForFunction(()=>lunaCampaign.view==='game'&&!lunaCampaign.doorTransition);assert.equal(await p.evaluate(()=>barGame.day),1);assert.equal(await p.evaluate(()=>barGame.overlay),'dailyUnlocks');assert.equal(await p.evaluate(()=>outsidePlaytest.active),false);
// The real settlement action enters the reverse (closing) transition once.
await p.evaluate(()=>{barGame.overlay=null;barGame.pendingDailyUnlocks=false;barGame.finishDay();lunaCampaign.render(true);});await p.locator('[data-act="confirmSettlement"]').click();await p.locator('.bar-door-scene[data-direction="out"]').waitFor();assert.equal(await p.locator('.bar-door-scene').getAttribute('data-open'),'1');const balance=await p.evaluate(()=>barGame.progress.money);await p.waitForFunction(()=>lunaCampaign.doorTransition?.motionAt!=null);await p.waitForTimeout(700);await p.screenshot({path:'/private/tmp/bar-door-closing.png'});assert(+(await p.locator('.bar-door-scene').getAttribute('data-open'))<1);await p.waitForFunction(()=>lunaCampaign.view==='game'&&!lunaCampaign.doorTransition);assert.equal(await p.evaluate(()=>outsidePlaytest.config.flow),'out');assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'street');assert.equal(await p.evaluate(()=>barGame.progress.money),balance);
// Long real loading holds a closed door past 3 seconds; cancellation cannot enter the bar later.
await p.evaluate(()=>{const c=lunaCampaign;c.outside.exit(true);window.commits=0;c.runDoorTransition('in',()=>new Promise(r=>window.releaseDoorLoad=r),()=>window.commits++);});await p.waitForTimeout(3300);assert.equal(await p.locator('.bar-door-scene').getAttribute('data-open'),'0');assert.equal(await p.evaluate(()=>lunaCampaign.doorTransition.motionAt),null);await p.evaluate(()=>{lunaCampaign.toPicker();window.releaseDoorLoad();});await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>window.commits),0);assert.equal(await p.evaluate(()=>lunaCampaign.view),'picker');assert.equal(await p.locator('#campaign-root').evaluate(e=>e.style.opacity),'');
// Retry performs only the load/transition, and the commit runs once after success.
await p.evaluate(()=>{window.attempts=0;lunaCampaign.runDoorTransition('in',()=>{if(!window.attempts++)throw Error('test failure');},()=>window.commits++);});await p.waitForFunction(()=>lunaCampaign.view==='load-error');await p.locator('[data-campaign="retry-load"]').click();await p.waitForFunction(()=>!lunaCampaign.doorTransition&&lunaCampaign.view==='game');assert.equal(await p.evaluate(()=>window.commits),1);
assert.deepEqual(errors,[]);console.log('BAR_DOOR_UI_OK entry/exit, >=3s hold, real loading gate, left slide/warm light, no skip, unlocks, settlement once, cancellation/retry');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
