const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
async function setup(day,version='A',main=false,variant='original'){await p.evaluate(({day,version,main,variant})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main,serviceVersion:version});barGame.reset(day,'regular',1,true,{serviceVersion:version,variant});c.session.day=day;c.screen(c.playView);},{day,version,main,variant});}
async function advanceToCraft(){return p.evaluate(()=>{const g=barGame,c=lunaCampaign;for(let i=0;i<30000&&!g.finished;i++){g.cameraMoving=false;if(g.transition||g.cameraLeft){g.tick(.2);continue;}if(c.view==='menu'){c.action('drink:gin_tonic');continue;}if(c.view==='response'){c.action('response:B');continue;}if(c.view==='scene'){c.dialog.chars=1e6;c.next();continue;}if(c.view==='observation'){document.querySelector('#observation-base').value='rye';document.querySelector('#observation-order').value='right';c.action('confirm-observation');continue;}if(g.tutorial&&g.tutorial.kind!=='recipe'){const t=g.tutorial;if(t.kind==='coaster')g.coaster(t.seat,'keyboard');else{g.tutorial=null;g.stepDone(t.step);}continue;}if(g.dialogue){g.advance();g.advance();continue;}if(g.choice){g.choose(2);continue;}if(g.currentOrder&&g.story?.steps[g.story.index]?.type==='craft'){c.render(true);return {...g.currentOrder};}g.tick(.2);}c.render(true);return null;});}
for(const [day,version,variant]of [[0,'A','original'],[1,'A','original'],[1,'B','original'],[1,'A','gpt'],[2,'A','original'],[3,'A','original']]){await setup(day,version,false,variant);let n=0;for(;;){const order=await advanceToCraft();if(!order)break;try{await p.locator('[data-act="skipStoryCraft"]').waitFor({state:'visible',timeout:5000});}catch(e){console.log(await p.evaluate(()=>({view:lunaCampaign.view,active:lunaCampaign.active,phase:barGame.phase,screen:barGame.screen,tutorial:barGame.tutorial,overlay:barGame.overlay,cameraMoving:barGame.cameraMoving,cameraLeft:barGame.cameraLeft,transition:barGame.transition,order:barGame.currentOrder,dialogue:barGame.dialogue?.text,error:barGame.error})));throw e;}if(day===1&&n===0&&variant==='original')await p.screenshot({path:'/private/tmp/dev-skip-craft.png'});const before=await p.evaluate(()=>barGame.transactions.length);await p.locator('[data-act="skipStoryCraft"]').click();const result=await p.evaluate(()=>({error:barGame.error,order:barGame.currentOrder,transactions:barGame.transactions.length,last:barGame.transactions.at(-1),tutorial:barGame.tutorial}));assert.equal(result.error,null);assert.equal(result.order,null);assert.equal(result.transactions,before+1);assert.equal(result.last.grade,'good');assert(result.last.match);assert.equal(result.last.orderId,order.id);if(order.payment==='none')assert.equal(result.last.net,0);assert.equal(result.tutorial,null);assert.equal(await p.locator('[data-act="skipStoryCraft"]').count(),0);n++;}assert(n>0);}
// Main game: no button, and a forged action cannot bypass the main-mode guard.
await setup(1,'A',true);const order=await advanceToCraft();assert.equal(await p.locator('[data-act="skipStoryCraft"]').count(),0);await p.evaluate(()=>{const b=document.createElement('button');b.dataset.act='skipStoryCraft';document.querySelector('#app').append(b);b.click();b.remove();});assert.equal(await p.evaluate(()=>barGame.currentOrder.id),order.id);assert.equal(await p.evaluate(()=>barGame.transactions.length),0);
await setup(1);await p.evaluate(()=>{barGame.startGeneral();lunaCampaign.render(true);});assert.equal(await p.locator('[data-act="skipStoryCraft"]').count(),0);
assert.deepEqual(errors,[]);console.log('DEV_SKIP_CRAFT_OK days0-3, A/B, GPT regular, tutorial, free/unpaid order, good settlement once, story continuation; main forged-action and general guest guards');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
