const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{
 const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto('http://127.0.0.1:8123/bar-playtest/?mode=outside');await p.locator('.updates-confirm').click();await p.selectOption('#outside-place','home');await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);
 assert(!await p.evaluate(()=>!!outsidePlaytest.model.backgroundStory.speech));await p.keyboard.down('KeyD');await p.waitForFunction(()=>!!outsidePlaytest.model.backgroundStory.speech);await p.keyboard.up('KeyD');
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.id),'np_tv_1');assert(await p.locator('.outside-background-speech').isVisible());assert.equal(await p.locator('.outside-background-speech strong').innerText(),'TV');assert(await p.locator('.outside-interact').isHidden());assert(await p.locator('.outside-speech').isHidden());
 assert(await p.evaluate(()=>!outsidePlaytest.model.story.blocking&&!outsidePlaytest.model.encounter&&outsidePlaytest.camera.w===4.8&&!outsidePlaytest.model.targets().some(t=>t.id==='tv')));
 const index=await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.index);await p.keyboard.press('KeyE');await p.keyboard.press('Space');await p.locator('.outside-background-speech').click();assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.index),index);
 await p.keyboard.press('Escape');const elapsed=await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.elapsed);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.elapsed),elapsed);await p.keyboard.press('Escape');
 const x=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyD');await p.waitForTimeout(150);await p.keyboard.up('KeyD');assert(await p.evaluate(x=>outsidePlaytest.model.x>x,x));await p.waitForTimeout(500);await p.screenshot({path:'/private/tmp/outside-auto-tv.jpg',type:'jpeg',quality:85});
 for(const viewport of [{width:600,height:800},{width:960,height:540}]){await p.setViewportSize(viewport);await p.waitForTimeout(150);assert(await p.locator('.outside-background-speech').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));}
 const result=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,seen=[];m.x=1.22;for(let i=0;i<1800;i++){if(m.backgroundStory.speech)seen.push(m.backgroundStory.speech.line.actor);a.tick(1/60);}const stopped=!m.backgroundStory.speech&&m.backgroundStory.flags.tv_seen1;m.x=-.1;a.tick(.02);m.x=1.22;a.tick(.02);const second=m.backgroundStory.speech.id;for(let i=0;i<1800;i++){if(m.backgroundStory.speech)seen.push(m.backgroundStory.speech.line.actor);a.tick(1/60);}m.x=-.1;a.tick(.02);m.x=1.22;a.tick(.02);return{seen:[...new Set(seen)],stopped,second,replay:m.backgroundStory.speech?.id,sourcePreserved:LUNA_OUTSIDE_DIALOGUES.np_tv_1.some(r=>r.actor==='luna')};});assert.deepEqual(result,{seen:['radio'],stopped:true,second:'np_tv_2',replay:'np_tv_1',sourcePreserved:true});
 assert(await p.evaluate(()=>{for(const day of [0,1,2,3])for(const flow of ['in','out']){const m=new LunaOutside.Model({place:'home',day,flow});m.x=1.22;m.tick(.02);if(m.backgroundStory.speech?.id!=='np_tv_1')return false;}return true;}));
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.start({place:'home'});m.x=1.22;m.tick(.02);m.transition={time:0,to:'street',swapped:false};m.tick(.02);});assert(!await p.evaluate(()=>!!outsidePlaytest.model.backgroundStory.speech));assert(!await p.evaluate(()=>!!outsidePlaytest.model.backgroundStory.flags.tv_seen1));assert.deepEqual(errors,[]);
 console.log('PASS TV real-walk proximity, TV-only speakers/source preserved, no E/lock/zoom, automatic progress, pause, responsive bubble, second broadcast, replay on re-entry, all day/flow and transition cleanup');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
