const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
for(const [main,variant]of [[false,'original'],[false,'gpt'],[true,'original']]){
 await p.evaluate(async({main,variant})=>{const c=lunaCampaign,a=outsidePlaytest;a.exit(true);c.session.uninstall();c.session.install({developer:!main});barGame.reset(0,'full',1,false);c.session.day=0;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(a.config,{day:0,flow:'out',place:'home',variant});await a.start();c.screen(c.playView);},{main,variant});
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech),null);
 await p.evaluate(()=>{outsidePlaytest.model.x=1.22;outsidePlaytest.snapCamera();outsidePlaytest.tick(.05);});
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.id),'outside_day0_tv_news1');assert.equal(await p.locator('.outside-background-speech strong').count(),0);assert.equal(await p.locator('.outside-interact').isVisible(),false);
 const index=await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.index);await p.keyboard.press('e');await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.index),index);
 await p.keyboard.press('Escape');const elapsed=await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.elapsed);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.elapsed),elapsed);await p.keyboard.press('Escape');
 const result=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,seen=new Set(),actors=new Set();let hidden=0;for(let i=0;i<1100;i++){const s=m.backgroundStory.speech;if(s){seen.add(s.index);actors.add(s.line.actor);if(document.querySelector('.outside-background-speech').hidden)hidden++;}a.tick(.05);}const ended=!m.backgroundStory.speech;const x=m.x;m.tick(.05,{move:1});const moved=m.x>x;m.x=-.1;a.tick(.05);m.x=1.22;a.tick(.05);return {count:seen.size,actors:[...actors],hidden,ended,moved,replay:m.backgroundStory.speech?.id,block:m.story.blocking,targets:m.targets().map(t=>t.id)};});
 assert.equal(result.count,5);assert.deepEqual(result.actors,['tv']);assert.equal(result.hidden,0);assert(result.ended&&result.moved&&!result.block);assert.equal(result.replay,'outside_day0_tv_news1');assert(!result.targets.includes('tv'));
 if(!main&&variant==='original'){await p.evaluate(()=>{const s=outsidePlaytest.model.backgroundStory.channels.get("outside_day0_tv_news1");s.speech.index=1;s.seek();s.speech.elapsed=2;outsidePlaytest.tick(0);});await p.screenshot({path:'/private/tmp/tv-news1.png'});}
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.transition={time:0,to:'street',swapped:false};m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech),null);
}
const guards=await p.evaluate(()=>{const results=[];for(const day of [0,1,2,3])for(const flow of ['in','out'])for(const place of ['bar','home']){const m=new LunaOutside.Model({day,flow,place});m.x=1.22;m.tick(.05);results.push(!!m.backgroundStory.speech===(day===0&&flow==='out'&&place==='home'));}const m=new LunaOutside.Model({day:99,qaCase:'outside_day0_tv_news1'});m.x=0;m.tick(.05);results.push(m.qa.people.length===0&&m.story.speech?.rows.length===5&&m.story.speech.auto);return results;});assert(guards.every(Boolean));assert.deepEqual(errors,[]);console.log('TV_NEWS1_OK main/original/GPT: day0 out home only, 5 TV-only lines, proximity/no E/no lock, replay after range re-entry, pause and scene cleanup, world bubble, QA');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
