const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/');await p.locator('[data-campaign="title"]').click();await p.locator('[data-campaign="new"]').click();await p.waitForFunction(()=>lunaCampaign.view==='prologue');await p.keyboard.down('Space');await p.waitForTimeout(3200);await p.keyboard.up('Space');await p.waitForFunction(()=>lunaCampaign.view==='game'&&barGame.day===0,null,{timeout:60000});
 // Scripted bar completion still uses the real game core; navigation uses E/click handlers.
 async function completeBar(){return p.evaluate(()=>{const g=barGame,c=lunaCampaign,seen=[];const tick=()=>{g.cameraMoving=false;g.tick(.1);};for(let i=0;i<40000&&!g.finished;i++){if(g.error)throw Error(g.error);if(c.view==='menu'){c.action('drink:gin_tonic');continue;}if(c.view==='response'){c.action('response:B');continue;}if(c.view==='scene'){c.dialog.chars=1e6;c.next();continue;}if(c.view==='observation'){document.querySelector('#observation-base').value='rye';document.querySelector('#observation-order').value='right';c.action('confirm-observation');continue;}if(g.pendingDailyUnlocks){g.confirmDailyUnlocks();continue;}if(g.transition||g.cameraLeft){tick();continue;}g.cameraMoving=false;if(g.choice){g.choose(2);continue;}if(g.dialogue){g.advance();g.advance();continue;}if(g.phase==='general'){const w=Object.entries(g.seats).find(([k,v])=>v&&['WAIT_COASTER','WAIT_SERVE'].includes(v.state));if(w){const[k,v]=w;if(g.focus!==k){g.focusSeat(k);tick();continue;}if(v.state==='WAIT_COASTER'){g.coaster(k);tick();continue;}if(v.order&&g.screen==='bar'){g.openRecipes();g.selectCocktail(v.order.cocktail);g.debugCraft('good');g.offer();g.serve(k);continue;}}tick();continue;}if(g.currentOrder&&g.story?.steps[g.story.index]?.type==='craft'){const o=g.currentOrder;seen.push(o.cocktail);g.openRecipes();g.selectCocktail(o.cocktail);g.debugCraft('good');if(c.session.problems(g.result).length)throw Error('drink mismatch');g.offer();g.serve(o.seat,'drag');continue;}tick();}if(!g.finished)throw Error('bar stalled');c.render(true);return{day:g.day,seen,money:g.progress.money};});}
 for(let day=0;day<4;day++){const r=await completeBar();assert.equal(r.day,day);await p.locator('[data-act="confirmSettlement"]').click();await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading&&lunaCampaign.view==='game');assert.equal(await p.evaluate(()=>outsidePlaytest.config.flow),'out');
  if(day===0){await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-12.51;m.story.cancel();m.backgroundStory.cancel();m.updateNear();});await p.keyboard.press('KeyE');assert(await p.evaluate(()=>!!outsidePlaytest.model.ride));assert(!await p.evaluate(()=>!!outsidePlaytest.model.story.speech));await p.evaluate(()=>{for(let i=0;i<240;i++)outsidePlaytest.tick(.02);lunaCampaign.tick(.02);});assert(await p.locator('#campaign-lift-logo').isVisible());await p.screenshot({path:'/private/tmp/luna-main-lift.png'});await p.evaluate(()=>{for(let i=0;i<500;i++)outsidePlaytest.tick(.02);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.level),1);}
  // Reach the authored apartment door, enter, and select sleep at the sofa.
  await p.evaluate(()=>{const m=outsidePlaytest.model,R=LunaResidence.layout;m.level=1;m.x=R.homeX;m.y=R.upperY;m.elevatorY=R.elevatorTop;m.story.cancel();m.backgroundStory.cancel();m.updateNear();});await p.keyboard.press('KeyE');await p.evaluate(()=>{for(let i=0;i<60;i++)outsidePlaytest.tick(.02);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'home');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=2.557;m.updateNear();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'sleep');await p.locator('[data-campaign="sleep-confirm"]').click();await p.evaluate(()=>{let n=0;while(lunaCampaign.view==='scene'&&n++<150){lunaCampaign.dialog.chars=1e6;lunaCampaign.next();}});
  if(day===3){assert.equal(await p.evaluate(()=>lunaCampaign.view),'ending');break;}
  await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading&&lunaCampaign.view==='game');assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'home');assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.day),day+1);assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.flow),'in');
  await p.evaluate(()=>{const m=outsidePlaytest.model;m.scene='street';m.level=0;m.x=-6.5;m.y=-.7;m.updateNear();lunaCampaign.tick(.01);});if(day+1>=2){assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');await p.evaluate(()=>{let n=0;while(lunaCampaign.view==='scene'&&n++<60){lunaCampaign.dialog.chars=1e6;lunaCampaign.next();}});}await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=1.0086;m.story.cancel();m.backgroundStory.cancel();m.updateNear();});await p.keyboard.press('KeyE');await p.waitForFunction(d=>barGame.day===d&&lunaCampaign.view==='game',day+1);assert.equal(await p.evaluate(()=>barGame.progress.money),await p.evaluate(()=>lunaCampaign.session.carry.money));
 }
 assert.deepEqual(await p.evaluate(()=>lunaCampaign.session.completed),[0,1,2,3]);assert.deepEqual(errors,[]);await p.screenshot({path:'/private/tmp/luna-main-ending.png'});await p.locator('[data-campaign="exit-run"]').click();assert.equal(await p.evaluate(()=>lunaCampaign.view),'title');assert(!await p.evaluate(()=>lunaCampaign.active));console.log('CAMPAIGN_FLOW_UI_OK full four days, settle, lift, house entry, sofa, night stories, both mandatory Samho meetings, observation, ending, teardown');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
