const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 const drain=()=>p.evaluate(()=>{const s=outsidePlaytest.model.story,seen=[];for(let i=0;s.speech&&!s.speech.choice&&i<100;i++){seen.push(s.speech.line.text);s.speech.elapsed=99;s.advance();}outsidePlaytest.tick(0);return seen;});
 const click=id=>p.locator('[data-choice="'+id+'"]').click();
 const menu=async()=>{await p.keyboard.press('KeyE');await click('shop-yes');await drain();};
 for(const [main,version,first,second]of [[true,'A','wild_dog','bitters'],[true,'B','bitters','wild_dog'],[false,'A','wild_dog','bitters']]){
 await p.evaluate(async({main,version})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main,serviceVersion:version});barGame.reset(2,'full',10,false,{serviceVersion:version});Object.assign(barGame.progress,{money:1000,inventory:{},flags:{shiba_shop_met:true}});c.session.day=2;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:2,flow:'out',place:'bar'});await outsidePlaytest.start();c.screen(c.playView);const a=outsidePlaytest,m=a.model;m.x=-2.87;m.updateNear();a.snapCamera();a.tick(0);},{main,version});
 await menu();await click('shop-buy-'+first);assert.deepEqual(await drain(),['너 그거 어디 가서 나한테 샀다고 하면 죽어.','…네.']);const balance=first==='wild_dog'?400:700;
 await menu();await p.evaluate(second=>{barGame.progress.money=LunaOutsideShop.items.find(i=>i.id===second).price-1;outsidePlaytest.tick(0);},second);assert(await p.locator('[data-choice="shop-buy-'+second+'"]').isDisabled());assert.equal(await p.evaluate(second=>outsidePlaytest.model.story.choose('shop-buy-'+second),second),false);await p.evaluate(balance=>{barGame.progress.money=balance;outsidePlaytest.tick(0);},balance);
 await click('shop-buy-'+second);assert.equal(await p.evaluate(()=>barGame.progress.money),balance);assert.equal(await p.evaluate(second=>barGame.progress.inventory[second]||0,second),0);const teaching=await drain();assert.equal(teaching[0],'…너 혹시 올드 패션드 만드냐?');assert(teaching.includes('올드 패션드가 왜 올드 패션드인지 알아?'));assert.equal(await p.locator('.outside-choices button').count(),3);assert.equal(await p.locator('.outside-speech strong').count(),0);
 if(main&&version==='A')await p.screenshot({path:'/private/tmp/shiba-old-fashioned-quiz.png'});
 for(const answer of ['shop-answer-2','shop-answer-3']){await click(answer);const retry=await drain();assert.equal(retry[0],'…다시 설명하지.');assert.equal(retry[1],'올드 패션드가 왜 올드 패션드인지 알아?');assert(!retry.includes('…너 혹시 올드 패션드 만드냐?'));assert.equal(await p.evaluate(()=>barGame.progress.money),balance);}
 await click('shop-answer-1');assert.deepEqual(await drain(),['정답이다, 바텐더. 자, 가져가도록.','…? 감사해요.']);assert.deepEqual(await p.evaluate(()=>({money:barGame.progress.money,inv:barGame.progress.inventory,taught:barGame.progress.flags.shiba_old_fashioned_taught,carry:lunaCampaign.session.carry.money})),{money:100,inv:{[first]:1,[second]:1},taught:true,carry:100});assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.choose('shop-answer-1')),false);
 // A later purchase does not repeat the completed lesson; coupons remain ordinary goods.
 await menu();await click('shop-buy-arcade_coupon');assert.equal((await drain())[0],'너 그거 어디 가서 나한테 샀다고 하면 죽어.');assert.equal(await p.evaluate(()=>barGame.progress.money),50);
 console.log('PASS',main?'main '+version:'developer',first+' -> '+second);
 }
 const qa=await p.evaluate(()=>{const m=outsidePlaytest.model,g=barGame,before=JSON.stringify(g.progress),results=[];for(const [qaCase,item]of [['shop:quiz-bitters','bitters'],['shop:quiz-wild-dog','wild_dog']]){m.start({day:99,flow:'out',qaCase});m.x=0;m.updateNear();m.interact();m.qa.shopProgress.money=1000;const drain=()=>{for(let i=0;m.story.speech&&!m.story.speech.choice&&i<100;i++){m.story.speech.elapsed=99;m.story.advance();}};m.story.choose('shop-yes');drain();m.story.choose('shop-buy-'+item);drain();const stage=m.story.speech.line.stage;m.story.cancel();const canceledBalance=m.qa.shopProgress.money;LunaOutsideShop.begin(m,{x:0,y:-.7},false);m.story.choose('shop-yes');drain();m.story.choose('shop-buy-'+item);drain();m.story.choose('shop-answer-1');drain();results.push({stage,canceledBalance,inventory:m.qa.shopProgress.inventory,money:m.qa.shopProgress.money});}return{results,isolated:before===JSON.stringify(g.progress)};});assert(qa.isolated);for(const r of qa.results){assert.equal(r.stage,'quiz');assert.equal(r.canceledBalance,1000);assert.deepEqual(r.inventory,{wild_dog:1,bitters:1});}assert.deepEqual(qa.results.map(r=>r.money),[700,400]);assert.deepEqual(errors,[]);console.log('SHIBA_QUIZ_OK both orders, wrong answers retry, deferred single charge, insufficient funds, carry, coupon, QA cancellation/isolation');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
