const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const dir=path.resolve(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(dir+'/data.js','utf8'),ctx);const D=ctx.window.LUNA_DATA,C=require(dir+'/core.js'),R=require(dir+'/remix.js');
const original=JSON.stringify(D);let count=0;
function test(name,fn){fn();count++;console.log('PASS',name);}
function create(day=99,mode='challenge',settings={}){const g=new C.Game(D);R.attach(g);g.reset(day,mode,7,true,{variant:'gpt',...settings});g.dialogSpeed=20;return g;}
function tick(g,sec){for(let t=0;t<sec;t+=.1)g.tick(.1);assert.equal(g.error,null);}
function prep(g,id){if(g.screen==='bar')g.openRecipes();assert.equal(g.screen,'recipe');g.selectCocktail(id);const c=g.cocktail(id);g.prep.glass=c.glass;g.prep.tool=c.mix==='shake'?'shaker':c.mix==='stir'?'mixing_glass':null;g.prep.ingredients=g.t.recipes.filter(r=>r.context===id&&!r.auto_apply).map(r=>r.ingredient);g.startCraft();}
function craft(g){let guard=0;while(g.screen==='gimmick'&&guard++<2000){const s=g.gimmick;if(g.remix?.hold){tick(g,1);continue;}if(['pour','fill_up'].includes(s.type)){g.gimmickInput('Space');s.value=s.target;g.holdPour(false);g.endGimmick();}else if(s.type==='open'){if(!s.started)g.gimmickInput('Space');s.beatTime=g.c('open_approach_sec',1.6);g.gimmickInput('Space');tick(g,.1);}else if(s.type==='shake'){if(!s.started)g.gimmickInput('Space');while(!C.MIX.nearest(s))g.tick(.005);g.gimmickInput('Space');g.tick(.06);}else if(s.type==='stir'){if(!s.started)g.gimmickInput('KeyW');for(const key of ['KeyD','KeyS','KeyA','KeyW']){tick(g,.12);g.gimmickInput(key);}tick(g,.1);}}
 assert.equal(g.screen,'result');tick(g,1.3);assert.equal(g.result.grade,'excellent');
}
function run(g){const visited=new Map();for(let i=0;i<10000&&!g.finished;i++){
 if(g.screen==='recipe'){prep(g,g.currentOrder?.cocktail);craft(g);g.offer();g.serve(g.currentOrder.seat);continue;}
 if(g.phase==='general'){
  const entries=Object.entries(g.seats).filter(([,v])=>v),entry=entries.find(([,x])=>['REACTION','ORDER_DIALOGUE'].includes(x.state))||entries.find(([,x])=>['WAIT_COASTER','WAIT_SERVE'].includes(x.state))||entries[0];
  if(entry){const[seat,x]=entry;if(g.focus!==seat){g.focusSeat(seat);tick(g,.6);}if(x.state==='WAIT_COASTER')g.coaster();else if(x.state==='WAIT_SERVE'){prep(g,x.order.cocktail);craft(g);g.offer();g.serve(seat);}}
 }else if(g.dialogue){g.advance();g.advance();}else if(g.choice){const id=g.choice.step.arg,n=visited.get(id)||0;visited.set(id,n+1);const max={ch_t99_main:4,ch_t99_branch:4,ch_t99_stage:3,ch_t99_bar:4}[id];g.choose(max?Math.min(n+1,max):1);}
 tick(g,.2);
 }assert.equal(g.finished,true,'flow stalled '+g.phase+' '+g.screen);assert.equal(g.error,null);}
test('challenge exposes eight parties, deterministic graduated orders, disclosed upkeep',()=>{for(const difficulty of Object.keys(R.PROFILES)){const g=create(99,'challenge',{difficulty});assert.equal(g.queue.length,8);assert.equal(g.upkeepOverride,R.challengeUpkeep(g,99,difficulty));tick(g,2.2);g.coaster();assert(R.complexity(g,g.cocktail(g.seats.L.nextCocktail))<=2);}});
test('shake counts only inputs, judges node distance and supports partial completion',()=>{const g=create(99,'practice');prep(g,'gin_fizz');g.craft.index=g.craft.queue.findIndex(q=>q.type==='shake');g.nextGimmick();g.gimmickInput('Space');tick(g,4);assert.equal(g.gimmick.attempts,0);while(!C.MIX.nearest(g.gimmick))g.tick(.005);g.gimmickInput('Space');assert.equal(g.gimmick.success,1);const index=g.craft.index;g.endGimmick();assert(g.remix.hold);tick(g,1);assert.equal(g.craft.index,index+1);assert.equal(g.craft.results.at(-1).completion,1/16);});
test('all 29 recipes finish with actual inputs and automatic transitions',()=>{for(const c of D.tables.cocktails){const g=create(99,'practice');prep(g,c.id);craft(g);assert.equal(g.result.score,100,c.id);}});
test('automatic completion holds freeze in menus and exclude transition time',()=>{const g=create(99,'practice');prep(g,'bottle_beer');g.gimmickInput('Space');g.gimmick.beatTime=1.6;g.gimmickInput('Space');tick(g,.1);assert(g.remix.hold);const time=g.craft.elapsed,remaining=g.remix.hold.remaining;g.overlay='settings';tick(g,2);assert.equal(g.remix.hold.remaining,remaining);assert.equal(g.craft.elapsed,time);g.overlay=null;tick(g,1);assert.equal(g.craft.elapsed,time);});
test('empty representative score is zero in remix only',()=>{const g=create(99,'practice');g.selectCocktail('gin_tonic');g.prep={selected:'gin_tonic',glass:g.cocktail('gin_tonic').glass,tool:null,ingredients:['vodka']};g.startCraft();while(g.screen==='gimmick'){g.gimmickInput('Space');g.endGimmick();tick(g,1);}assert.equal(g.result.score,0);assert.equal(g.result.grade,'sewage');});
test('result lock, retry new attempt ID and assist choices remain independent',()=>{const g=create(99,'practice',{assist:false});prep(g,'gin_tonic');craft(g);const id=g.result.id;g.remix.resultLock=1;assert.equal(g.offer(),false);assert.equal(g.remixRetry(),false);tick(g,1.2);assert.equal(g.remixRetry(),true);assert.notEqual(g.craft.id,id);assert.equal(g.remix.assist,false);});
test('full eight-party challenge pays goals once and settles real drinks',()=>{const g=create();run(g);assert.equal(g.remix.served,8);assert.equal(g.lost,0);assert.equal(g.remix.good,8);assert.equal(g.remix.maxCombo,8);assert(g.remix.bonus>0);assert.equal(g.remix.goalBonus,70);const balance=g.progress.money;g.finishDay();assert.equal(g.progress.money,balance);assert(g.progress.money>=g.dailySettlement.upkeep);g.confirmDailySettlement();assert.equal(g.dailySettlement.status,'paid');const paid=g.progress.money;g.confirmDailySettlement();assert.equal(g.progress.money,paid);});
test('ignored challenge finishes as game over without manufacturing rewards',()=>{const g=create();for(let i=0;i<2500&&!g.finished;i++)g.tick(.2);assert(g.finished);assert.equal(g.remix.served,0);assert.equal(g.remix.goalBonus,0);g.confirmDailySettlement();assert.equal(g.screen,'gameover');});
test('original Day 0 and QA story still complete with remix features',()=>{for(const day of [0,99]){const g=create(day,'full');run(g);assert(g.transactions.length>=2);}});
test('version switching resets goals, economy and keeps original queue',()=>{const g=create();g.remix.combo=9;g.progress.money=99999;g.reset(1,'general',7,true,{variant:'original'});assert.equal(g.remix,null);assert.equal(g.upkeepOverride,null);assert.equal(g.queue.length,4);assert.equal(g.progress.money,g.c('gold_start',300));const bare=new C.Game(D);bare.reset(1,'general',7);for(let i=0;i<50;i++){g.tick(.1);bare.tick(.1);}assert.deepEqual(g.logs,bare.logs);assert.deepEqual(g.progress,bare.progress);});
test('test-generated drinks never pay streak or goal rewards',()=>{const g=create();g.remix.debug=true;for(let i=0;i<5;i++)g.settle({orderId:'test_'+i,served:'gin_tonic',grade:'excellent',match:true,experimentalDebug:true});g.finishDay();assert.equal(g.remix.bonus,0);assert.equal(g.remix.goalBonus,0);});
test('recipe autofill is marked as testing and excludes result records',()=>{const g=create(99,'practice');g.selectCocktail('gin_tonic');g.debugFill();assert.equal(g.remix.debug,true);g.startCraft();craft(g);assert.equal(g.result.debug,true);});
test('source data stays byte-for-byte unchanged',()=>assert.equal(JSON.stringify(D),original));
console.log('REMIX_CORE_OK',count,'groups');
