const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();const id='outside_day1_samho_smuggler';
async function start(variant){await p.evaluate(async variant=>{outsidePlaytest.exit(true);lunaCampaign.screen('developer');Object.assign(outsidePlaytest.config,{day:1,flow:'out',place:'bar',variant});await outsidePlaytest.start();const a=outsidePlaytest,m=a.model;m.x=2.76;m.updateNear();a.snapCamera();a.tick(0);},variant);}
async function renderSigns(){return p.evaluate(()=>{const a=outsidePlaytest,m=a.model,ctx=document.querySelector('#outside-root canvas').getContext('2d'),old=ctx.drawImage,records=[];ctx.drawImage=function(im,...v){const kind=im.src.includes('4bdaf8a66fd58d')?'samho':im.src.includes('NPC_idle_M1')?'smuggler':null;if(kind)records.push({kind,sign:Math.sign(this.getTransform().a)});return old.call(this,im,...v);};try{a.tick(0);}finally{ctx.drawImage=old;}return records;});}
for(const variant of ['original','gpt']){await start(variant);await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech),null);assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech),null);assert(await p.locator('.outside-interact').isVisible());const signs=await renderSigns();assert.equal(signs.find(r=>r.kind==='samho').sign,1);assert.equal(signs.find(r=>r.kind==='smuggler').sign,1);
await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),id);await p.evaluate(()=>{outsidePlaytest.model.story.speech.elapsed=10;outsidePlaytest.refreshHUD();});assert.equal(await p.locator('.outside-speech strong').count(),0);assert.equal(await p.locator('.outside-speech-text').getAttribute('aria-label'),'…그 정도 스펙이면 웬만한 놈들은 상대도 안 될걸.');await p.screenshot({path:'/private/tmp/samho-smuggler-'+variant+'.png'});
const seen=await p.evaluate(()=>{const s=outsidePlaytest.model.story,text=[];for(let i=0;s.speech&&i<20;i++){s.speech.elapsed=99;text.push(s.speech.line.text);s.advance();}return text;});assert.equal(seen.length,8);assert(seen[3].includes('대금을 치를'));assert(seen[6].includes('떼먹을 일'));await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),id);}
const gates=await p.evaluate(id=>{const m=outsidePlaytest.model,result=[];for(const day of [0,1,2,3])for(const flow of ['in','out']){m.start({day,flow});result.push({day,flow,visible:LunaOutsideEncounters.tradeVisible(m),target:m.targets().some(t=>t.id===id)});}m.start({day:1,flow:'out',place:'homeDoor'});result.push({day:1,flow:'upper',visible:LunaOutsideEncounters.tradeVisible(m),target:m.targets().some(t=>t.id===id)});return result;},id);for(const r of gates){assert.equal(r.visible,r.day===1&&r.flow==='out');assert.equal(r.target,r.visible);}
await p.evaluate(id=>{const a=outsidePlaytest,m=a.model;m.start({day:99,qaCase:id});m.x=0;m.updateNear();m.interact();for(let i=0;i<40;i++)a.tick(.025);a.snapCamera();a.tick(0);},id);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),id);const people=await p.evaluate(()=>outsidePlaytest.model.qa.people.map(p=>p.id));assert.deepEqual(people,['trade-samho','trade-smuggler']);const qaSigns=await renderSigns();assert.equal(qaSigns.find(r=>r.kind==='samho').sign,1);assert.equal(qaSigns.find(r=>r.kind==='smuggler').sign,1);
// Main uses the same manual event, and does not substitute a mandatory commute scene.
await p.evaluate(async()=>{outsidePlaytest.exit(true);lunaCampaign.session.developer=false;lunaCampaign.session.day=1;await lunaCampaign.street('out','bar');});await p.waitForFunction(()=>lunaCampaign.view==='game'&&!lunaCampaign.doorTransition);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=2.76;m.updateNear();outsidePlaytest.snapCamera();outsidePlaytest.tick(0);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech),null);await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),id);
assert.deepEqual(errors,[]);console.log('SAMHO_SMUGGLER_OK day1-out only, manual/repeatable 8 lines, original/GPT/main/QA, real facing transforms, speakerless balloons');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
