const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=minigames');await p.locator('.updates-confirm').click();await p.locator('[data-act="miniStart"][data-id="shake"]').click();await p.waitForTimeout(400);await p.keyboard.press('Space');
await p.evaluate(()=>{window.normalTick=barGame.tick;barGame.tick=()=>{};});
for(const [target,tier,speed] of [[4,0,1],[5,1,1.25],[9,1,1.25],[10,2,1.5],[15,2,1.5],[19,2,1.5]]){
 const state=await p.evaluate(target=>{const g=barGame,s=g.gimmick,r=s.rhythm;while(r.combo<target){const n=r.notes.find(n=>!n.status);s.rhythm.trackTime=n.time;g.gimmickInput(n.lane?'KeyD':'KeyA');}const elapsed=s.elapsed,track=r.trackTime,clock=r.clock,notes=JSON.stringify(r.notes);LunaCore.MIX.visual(s,.1);return {tier:r.tier,speed:(r.clock-clock)/.1,unchanged:s.elapsed===elapsed&&r.trackTime===track&&JSON.stringify(r.notes)===notes,completed:s.completed,count:r.notes.length};},target);
 assert.equal(state.tier,tier);assert(Math.abs(state.speed-speed)<1e-6);assert(state.unchanged);assert(!state.completed);assert.equal(state.count,20);await p.waitForTimeout(80);assert.equal(await p.locator('.rhythm-board').getAttribute('data-combo-tier'),String(tier));assert.equal(await p.locator('.combo-flame').count(),tier===2?7:tier===1?4:0);assert.equal(await p.locator('.rhythm-speed-lines path').count(),tier===2?8:tier===1?4:0);assert.equal(await p.locator('.rhythm-note-tail').count()>0,tier>0);
 if(target===5||target===10){await p.screenshot({path:'/private/tmp/shake-heat-'+target+'.png'});}
}
// A miss clears both heat and motion; the next hit resumes at normal speed.
await p.evaluate(()=>{const s=barGame.gimmick;s.rhythm.trackTime=s.rhythm.notes[19].time-.3;barGame.gimmickInput('KeyA');});await p.waitForTimeout(80);assert.equal(await p.locator('.combo-flame').count(),0);assert.equal(await p.locator('.rhythm-board').getAttribute('data-combo-tier'),'0');assert(!(await p.evaluate(()=>barGame.gimmick.rhythm.playing)));
await p.evaluate(()=>{const s=barGame.gimmick;s.rhythm.trackTime=s.rhythm.notes[19].time;barGame.gimmickInput(s.rhythm.notes[19].lane?'KeyD':'KeyA');});assert.equal(await p.evaluate(()=>barGame.gimmick.rhythm.combo),1);assert(await p.evaluate(()=>barGame.gimmick.completed));await p.evaluate(()=>barGame.tick=window.normalTick);await p.locator('.minigame-result').waitFor();assert.equal(await p.evaluate(()=>barGame.minigame.result.targetStacks),20);
await p.locator('[data-act="miniRetry"]').click();await p.keyboard.press('Space');await p.evaluate(()=>{window.normalTick=barGame.tick;barGame.tick=()=>{};const s=barGame.gimmick;for(const n of s.rhythm.notes.slice(0,10)){s.rhythm.trackTime=n.time;barGame.gimmickInput(n.lane?'KeyD':'KeyA');}});await p.waitForTimeout(100);await p.keyboard.press('Escape');const frozen=await p.evaluate(()=>JSON.stringify(barGame.gimmick));await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>JSON.stringify(barGame.gimmick)),frozen);await p.keyboard.press('Escape');await p.setViewportSize({width:960,height:540});await p.waitForTimeout(100);await p.screenshot({path:'/private/tmp/shake-heat-small.png'});await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.rhythm-speed-lines').evaluate(e=>getComputedStyle(e).display),'none');assert.equal(await p.locator('.rhythm-combo-fire').evaluate(e=>getComputedStyle(e).display),'none');assert.deepEqual(errors,[]);console.log('COMBO_TIERS_OK: 4/5/9/10 thresholds, 1/1.25/1.5 speeds, unchanged timing, 20 notes, miss reset, resume, finish, pause, small viewport and reduced motion');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
