const assert=require('assert/strict');
const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const BASE=process.env.LUNA_TEST_URL||'http://127.0.0.1:8123/bar-playtest/';
(async()=>{let browser;try{
 browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[],bad=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)bad.push(r.url());});
 await p.goto(BASE);await p.locator('[data-act="version"][data-id="original"]').waitFor();assert.equal(await p.evaluate(()=>barGame.variant),'original');
 await p.locator('[data-act="version"][data-id="gpt"]').click();await p.locator('.remix-start').waitFor();await p.screenshot({path:'/tmp/luna-remix-start.png'});
 await p.locator('[data-act="remixDifficulty"][data-id="cozy"]').click();await p.locator('#start-mode').selectOption('practice');await p.locator('[data-act="start"]').click();await p.locator('.remix-recipe-detail').waitFor();
 await p.locator('[data-act="remixFilter"][data-id="build"]').click();assert(await p.locator('.remix-recipe-row').count()>0);
 await p.locator('[data-act="remixFavorite"][data-id="gin_tonic"]').click();await p.locator('[data-act="remixFilter"][data-id="favorite"]').click();assert.equal(await p.locator('.remix-recipe-row').count(),1);
 await p.locator('[data-act="remixPreview"][data-id="gin_tonic"]').click();await p.screenshot({path:'/tmp/luna-remix-recipes.png'});await p.locator('[data-act="selectRecipe"]').click();assert.equal(await p.locator('.prep-recipe').count(),0);assert.equal(await p.locator('.remix-prep-check').count(),1);assert(await p.evaluate(()=>Number(getComputedStyle(document.querySelector('.remix-prep-check')).zIndex)>Number(getComputedStyle(document.querySelector('.craft-screen')).zIndex)));
 await p.evaluate(()=>{const g=barGame,c=g.cocktail('gin_tonic');g.pickItem(c.glass);for(const r of g.t.recipes.filter(r=>r.context===c.id&&!r.auto_apply))g.pickItem(r.ingredient);});await p.waitForTimeout(200);await p.screenshot({path:'/tmp/luna-remix-prep.png'});await p.locator('[data-act="craft"]').click();
 const id=await p.evaluate(()=>barGame.craft.id);
 for(let step=0;step<2;step++){
  await p.waitForFunction(()=>barGame.screen==='gimmick'&&!barGame.remix.hold);await p.keyboard.down('Space');await p.waitForFunction(()=>barGame.gimmick.predicted>=barGame.gimmick.target,undefined,{timeout:10000,polling:16});await p.keyboard.up('Space');await p.waitForTimeout(650);
  if(step===0)await p.screenshot({path:'/tmp/luna-remix-pour.png'});await p.locator('[data-act="endGimmick"]').click();
  if(step===0){await p.locator('.remix-step-feedback').waitFor();await p.keyboard.press('Escape');const hold=await p.evaluate(()=>barGame.remix.hold.remaining);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>barGame.remix.hold.remaining),hold);await p.keyboard.press('Escape');await p.waitForFunction(()=>barGame.craft.index===1);}
 }
 await p.waitForFunction(()=>barGame.screen==='result');assert(await p.locator('[data-act="offer"]').isDisabled());await p.waitForTimeout(1200);assert.equal(await p.locator('[data-act="offer"]').isDisabled(),false);await p.screenshot({path:'/tmp/luna-remix-result.png'});assert(await p.evaluate(()=>JSON.parse(localStorage.getItem('luna.bar.gpt.v1')).best.gin_tonic>=0));
 await p.locator('[data-act="remixRetry"]').click();assert.notEqual(await p.evaluate(()=>barGame.craft.id),id);assert.equal(await p.evaluate(()=>barGame.screen),'gimmick');
 // Actual key events, automatic transitions, no missing-beat penalties.
 await p.evaluate(()=>{const g=barGame;g.reset(99,'practice',1,true,{variant:'gpt',difficulty:'cozy'});g.selectCocktail('gin_fizz');g.debugFill();g.startCraft();g.craft.index=g.craft.queue.findIndex(s=>s.type==='shake');g.nextGimmick();});await p.waitForTimeout(200);await p.keyboard.press('Space');await p.waitForTimeout(1200);assert.equal(await p.evaluate(()=>barGame.gimmick.attempts),0);await p.screenshot({path:'/tmp/luna-remix-shake.png'});
 const startIndex=await p.evaluate(()=>barGame.craft.index);await p.evaluate(()=>{barGame.endGimmick();});assert.equal(await p.evaluate(()=>barGame.craft.index),startIndex);
 for(let i=0;i<12;i++){await p.evaluate(()=>{barGame.gimmick.beatTime=.75;barGame.gimmick.beatIndex++;});await p.keyboard.press('Space');}
 await p.waitForFunction(i=>barGame.remix.hold!==null||barGame.craft.index>i,startIndex);await p.waitForFunction(i=>barGame.craft.index>i,startIndex);assert.equal(await p.evaluate(()=>barGame.error),null);
 // A second person in story mode still waits for camera staging.
 await p.evaluate(()=>barGame.reset(99,'regular',3,true,{variant:'gpt'}));await p.waitForFunction(()=>barGame.choice&&!barGame.cameraMoving&&barGame.transition===0);await p.locator('.choices [data-id="3"]').click();assert.equal(await p.locator('.dialogue-wrap').count(),0);await p.waitForFunction(()=>barGame.dialogue&&!barGame.cameraMoving&&barGame.transition===0);assert.equal(await p.evaluate(()=>Object.values(barGame.seats).filter(Boolean).length),2);
 // Back to original via the actual options path, then both tabs work again.
 await p.evaluate(()=>{barGame.read.add('gpt_only_probe');localStorage.setItem('luna.bar.playtest.read.v1',JSON.stringify(['original_only_probe']));});
 await p.keyboard.press('Escape');await p.locator('[data-act="restart"]').click();await p.locator('[data-act="setup"]').click();await p.locator('[data-act="version"][data-id="original"]').click();assert.equal(await p.locator('.remix-start').count(),0);assert.equal(await p.evaluate(()=>barGame.remix),null);assert.equal(await p.evaluate(()=>barGame.read.has('gpt_only_probe')),false);assert.equal(await p.evaluate(()=>barGame.read.has('original_only_probe')),true);assert.equal(await p.locator('#start-mode option[value="challenge"]').count(),0);await p.screenshot({path:'/tmp/luna-original-with-tabs.png'});
 await p.locator('[data-act="version"][data-id="gpt"]').click();await p.locator('[data-act="start"]').click();await p.waitForTimeout(2500);await p.screenshot({path:'/tmp/luna-remix-bar.png'});
 await p.locator('[data-act="remixGoals"]').click();const time=await p.evaluate(()=>barGame.barTime);await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>barGame.barTime),time);await p.keyboard.press('Escape');
 // Summary appears before the ledger; debug-assisted runs cannot create official records.
 await p.evaluate(()=>{const g=barGame;g.remix.served=8;g.remix.good=6;g.remix.maxCombo=4;g.remix.variety=new Set(['a','b','c']);g.progress.money=1800;g.finishDay();});await p.locator('.remix-summary').waitFor();assert.equal(await p.locator('.remix-summary-goals>div').count(),3);const report=await p.locator('.remix-summary').boundingBox();assert(report.y>=0&&report.y+report.height<650);await p.screenshot({path:'/tmp/luna-remix-settlement.png'});await p.locator('[data-act="confirmSettlement"]').click();assert.equal(await p.evaluate(()=>JSON.parse(localStorage.getItem('luna.bar.gpt.v1')).runs.length),1);await p.locator('[data-act="retryDay"]').click();await p.waitForFunction(()=>barGame.phase==='general'&&!barGame.finished);assert.equal(await p.evaluate(()=>barGame.remix.served),0);assert.equal(await p.evaluate(()=>barGame.remix.difficulty),'cozy');
 await p.setViewportSize({width:960,height:540});await p.waitForTimeout(200);const box=await p.locator('.app-shell').boundingBox();assert(box.width<=961&&box.height<=541);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);assert.deepEqual(bad,[]);console.log('REMIX_UI_OK: both tabs, recipe filters/favorites, prep, real pours, pause/transition guards, retry, shake inputs, two-person story, version isolation, 16:9, zero JS/resource errors.');
 }finally{await browser?.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
