const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
for(const [main,variant] of [[false,'original'],[false,'gpt'],[true,'original']]){
 await p.evaluate(async({main,variant})=>{const c=lunaCampaign,a=outsidePlaytest;a.exit(true);c.session.uninstall();c.session.install({developer:!main});barGame.reset(0,'full',1,false);c.session.day=0;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(a.config,{day:0,flow:'out',place:'bar',variant});await a.start();c.screen(c.playView);},{main,variant});
 const result=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model;let start=null;for(let i=0;i<160;i++){m.tick(.05,{move:-1,run:true});if(m.backgroundStory.channels.has('outside_day0_store_passers')){start={x:m.x,t:m.time,ids:[...m.backgroundStory.channels.keys()]};break;}}a.snapCamera();a.tick(0);const bubbles=[...document.querySelectorAll('.outside-background-speech')].map(el=>({id:el.dataset.storyId,hidden:el.hidden,world:el.dataset.worldSpeech,text:el.textContent}));const before=[...m.backgroundStory.channels.values()].map(s=>s.speech.elapsed);m.paused=true;m.tick(.05);const paused=[...m.backgroundStory.channels.values()].map(s=>s.speech.elapsed);m.paused=false;m.tick(.05);const after=[...m.backgroundStory.channels.values()].map(s=>s.speech.elapsed);return{start,bubbles,before,paused,after,blocked:m.story.blocking};});
 assert(result.start&&result.start.t<5);assert.deepEqual(result.start.ids,['outside_day0_port_pair','outside_day0_store_passers']);assert.equal(result.bubbles.length,2);assert(result.bubbles.every(e=>!e.hidden&&e.world==='true'));assert.deepEqual(result.before,result.paused);assert(result.after.every((t,i)=>t>result.before[i]));assert(!result.blocked);
 await p.evaluate(()=>{const a=outsidePlaytest,m=a.model;for(let i=0;i<30;i++)m.tick(.05);a.snapCamera();a.tick(0);});if(!main&&variant==='original')await p.screenshot({path:'/private/tmp/store-parallel.png'});
 const end=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model;for(let i=0;i<1000;i++)m.tick(.05);a.tick(0);return{done:[...m.backgroundStory.done].sort(),channels:m.backgroundStory.channels.size,bubbles:document.querySelectorAll('.outside-background-speech').length,hidden:document.querySelector('.outside-background-speech').hidden};});assert.deepEqual(end,{done:['outside_day0_port_pair','outside_day0_store_passers'],channels:0,bubbles:1,hidden:true});
 const cleanup=await p.evaluate(()=>{const m=outsidePlaytest.model;for(const id of ['outside_day0_port_pair','outside_day0_store_passers'])m.backgroundStory.begin(id,{id},true);m.backgroundStory.cancel();const cancelled=m.backgroundStory.channels.size;for(const id of ['outside_day0_port_pair','outside_day0_store_passers'])m.backgroundStory.begin(id,{id},true);m.transition={to:'home',time:0};m.tick(.05);return{cancelled,transition:m.backgroundStory.channels.size};});assert.deepEqual(cleanup,{cancelled:0,transition:0});
}
assert.deepEqual(errors,[]);console.log('PARALLEL_AMBIENT_OK main/original/GPT actual run from bar, immediate independent conversations and world bubbles, clocks/pause, completion/no duplicate, cancel/scene cleanup');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
