const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');if(await p.locator('.updates-confirm').count())await p.locator('.updates-confirm').click();
// Use the actual day/phase controls before any scripted progression.
await p.locator('[data-act="day"][data-id="3"]').click();await p.selectOption('#start-mode','regular');await p.locator('[data-act="start"]').click();await p.waitForFunction(()=>barGame.phase==='regular');assert.equal(await p.evaluate(()=>barGame.story.steps.filter(s=>s.type==='say').length),146);assert(!await p.evaluate(()=>lunaCampaign.active));await p.evaluate(()=>{const g=barGame;for(let i=0;i<1500&&g.story?.steps[g.story.index]?.type!=='craft';i++){g.cameraMoving=false;if(g.dialogue){g.advance();g.advance();}else g.tick(.1);}lunaCampaign.render(true);});await p.waitForTimeout(350);await p.screenshot({path:'/private/tmp/luna-day3-regular.png'});await p.evaluate(()=>lunaCampaign.developer());if(await p.locator('.updates-confirm').isVisible())await p.locator('.updates-confirm').click();await p.locator('[data-act="version"][data-id="outside"]').click();await p.screenshot({path:'/private/tmp/luna-developer-tabs.png'});
async function finishScene(){return p.evaluate(()=>{const rows=[];for(let i=0;i<160&&lunaCampaign.view==='scene';i++){rows.push(lunaCampaign.dialog.rows[lunaCampaign.dialog.index].text);lunaCampaign.dialog.chars=1e6;lunaCampaign.next();}return rows;});}
for(const day of [2,3]){
await p.selectOption('#outside-place','bar');await p.selectOption('#outside-flow','in');await p.selectOption('#outside-day',String(day));await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-6.3;m.story.cancel();m.backgroundStory.cancel();m.updateNear();lunaCampaign.tick(.01);});assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');assert(await p.evaluate(()=>lunaCampaign.streetBackdrop.startsWith('data:image/')));await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'options');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');const expected=await p.evaluate(d=>LUNA_CAMPAIGN_DATA.scenes['commute'+d].map(r=>r.text),day);assert.deepEqual(await finishScene(),expected);await p.evaluate(()=>{outsidePlaytest.model.x=-5.99;outsidePlaytest.model.updateNear();lunaCampaign.tick(.02);});assert.equal(await p.evaluate(()=>lunaCampaign.view),'developer');await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');assert.deepEqual(await finishScene(),expected);await p.evaluate(()=>outsidePlaytest.exit());
await p.selectOption('#outside-place','home');await p.selectOption('#outside-flow','out');await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading);const balance=await p.evaluate(()=>barGame.progress.money);await p.evaluate(()=>{outsidePlaytest.model.x=2.557;outsidePlaytest.model.updateNear();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');const night=await p.evaluate(d=>[...LUNA_CAMPAIGN_DATA.scenes['night'+d],...(d===3?LUNA_CAMPAIGN_DATA.scenes.ending:[])].map(r=>r.text),day);assert.deepEqual(await finishScene(),night);assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.day),day);assert.equal(await p.evaluate(()=>barGame.progress.money),balance);assert(await p.evaluate(()=>outsidePlaytest.active));await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');await finishScene();await p.evaluate(()=>outsidePlaytest.exit());console.log('PASS developer outside day '+day+' auto commute / ESC / E replay / night preview / unchanged day and money');}
assert.deepEqual(errors,[]);console.log('DAYS23_OUTSIDE_UI_OK real lobby start + story data + both commute/night previews');}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
