const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
async function start(day=1,flow='in',money=800,main=false){await p.evaluate(async o=>{const c=lunaCampaign;c.outside.exit(true);c.session.uninstall();c.session.install({developer:!o.main});barGame.reset(o.day,'full',1,false);barGame.progress.money=o.money;c.session.day=o.day;c.session.route=o.flow;c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:o.day,flow:o.flow,place:'homeDoor',variant:'original'});await outsidePlaytest.start();c.screen(c.playView);},{day,flow,money,main});}
async function trigger(){await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.encounter?.kind==='thug');await p.keyboard.up('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.id===LunaOutsideThug.id);}
async function choice(){await p.evaluate(()=>{const m=outsidePlaytest.model;for(let i=0;i<30&&!m.story.speech.choice;i++){m.story.speech.elapsed=99;m.story.advance();}outsidePlaytest.refreshHUD();});}
async function finish(){await p.evaluate(()=>{const m=outsidePlaytest.model;for(let i=0;i<500;i++){if(m.encounter)m.encounter.cameraReady=true;if(m.story.speech?.line&&!m.story.speech.choice){m.story.speech.elapsed=99;m.story.advance();}m.tick(.05,{move:1});if(!m.encounter)break;}outsidePlaytest.refreshHUD();});}
// Other days/routes never trigger.
for(const [day,flow] of [[0,'in'],[1,'out'],[2,'in'],[3,'in']]){await start(day,flow);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.homeX+.3;m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);}
for(const main of [false,true]){
await start(1,'in',800,main);assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);await trigger();const x=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyD');await p.waitForTimeout(160);await p.keyboard.up('KeyD');assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),x);await p.screenshot({path:'/private/tmp/day1-thug-intro.png'});await choice();assert.equal(await p.locator('[data-choice="thug-pay"]').isDisabled(),false);await p.locator('[data-choice="thug-pay"]').click();await p.evaluate(()=>outsidePlaytest.model.story.choose('thug-pay'));assert.equal(await p.evaluate(()=>barGame.progress.money),300);assert.equal(await p.evaluate(()=>lunaCampaign.session.carry.money),300);await finish();assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.homeX+.3;m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);
await start(1,'in',100,main);await trigger();await choice();assert(await p.locator('[data-choice="thug-pay"]').isVisible());assert(await p.locator('[data-choice="thug-pay"]').isDisabled());await p.screenshot({path:'/private/tmp/day1-thug-choice.png'});await p.locator('[data-choice="thug-refuse"]').focus();await p.keyboard.press('Space');await p.evaluate(()=>{const m=outsidePlaytest.model;for(let i=0;i<4;i++){m.story.speech.elapsed=99;m.story.advance();}outsidePlaytest.refreshHUD();});assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter.stage),'punch');const px=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.press('KeyE');await p.waitForTimeout(950);assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),px);await p.screenshot({path:'/private/tmp/day1-thug-punch.png'});await p.waitForTimeout(800);assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter.hurt),true);await finish();assert.equal(await p.evaluate(()=>barGame.progress.money),100);assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);
}
assert.deepEqual(errors,[]);console.log('THUG_OK main/developer auto approach, day/route guard, movement lock, both choices, insufficient funds, single charge/carry, punch/action lock, departure, no repeat');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
