const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/');await p.locator('[data-campaign="title"]').click();await p.locator('[data-campaign="new"]').click();await p.locator('[data-campaign="start-day:0"]').click();await p.waitForFunction(()=>lunaCampaign.view==='prologue');
await p.evaluate(()=>{lunaCampaign.cinema.time=lunaCampaign.cinema.scene.end-.001;});await p.waitForFunction(()=>lunaCampaign.view==='awakening');
assert.equal(await p.evaluate(()=>barGame.dialogue.chars),0);const chris=p.locator('.actor[data-actor="chris"]');assert.equal(await chris.evaluate(e=>e.style.opacity),'1');assert.equal(await chris.evaluate(e=>e.style.getPropertyValue('--arrival')),'0px');assert.equal(await p.locator('.dialogue-wrap').evaluate(e=>getComputedStyle(e).visibility),'hidden');assert.equal(await p.evaluate(()=>barGame.seats.R.seated),true);
await p.waitForTimeout(850);await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>barGame.dialogue.chars),0);await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'options');const paused=await p.evaluate(()=>lunaCampaign.awakening.time);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>lunaCampaign.awakening.time),paused);await p.keyboard.press('Escape');await p.waitForTimeout(1000);await p.screenshot({path:'/private/tmp/bar-wake-middle.png'});assert.equal(await chris.evaluate(e=>e.style.opacity),'1');assert.equal(await p.evaluate(()=>barGame.dialogue.chars),0);
await p.waitForFunction(()=>lunaCampaign.view==='game');assert.equal(await p.locator('.dialogue-wrap').evaluate(e=>getComputedStyle(e).visibility),'visible');assert.equal(await chris.evaluate(e=>e.style.opacity),'1');await p.screenshot({path:'/private/tmp/bar-wake-complete.png'});
// First seated state must not leak into subsequent entrants.
await p.evaluate(()=>{lunaCampaign.session.uninstall();lunaCampaign.view='developer';lunaQA.runSituation('arrival');});await p.waitForTimeout(50);assert.equal(await p.evaluate(()=>!!barGame.seats.L.seated),false);
await p.evaluate(()=>lunaCampaign.newGame());await p.waitForFunction(()=>lunaCampaign.view==='prologue');await p.keyboard.down('Space');await p.waitForFunction(()=>lunaCampaign.view==='awakening');await p.keyboard.up('Space');assert.equal(await p.evaluate(()=>lunaCampaign.awakening.fromWhite),false);assert.equal(await p.locator('.campaign-wake-white').evaluate(e=>e.style.opacity),'0');await p.waitForFunction(()=>lunaCampaign.view==='game');assert.equal(await p.evaluate(()=>barGame.day),0);
assert.deepEqual(errors,[]);console.log('PASS natural/skip smooth wake, seated Chris at full opacity, dialogue/input hold, pause/resume, later guests unchanged');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
