const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
const drain=()=>p.evaluate(()=>{const s=outsidePlaytest.model.story;for(let i=0;s.speech&&!s.speech.choice&&i<100;i++){s.speech.elapsed=99;s.advance();}outsidePlaytest.tick(0);});
const click=id=>p.locator('[data-choice="'+id+'"]').click();
const menu=async()=>{await p.keyboard.press('KeyE');await click('shop-yes');await drain();if(await p.locator('[data-choice="shop-allowance-no"]').count()){await click('shop-allowance-no');await drain();}};
for(const main of [false,true]){
 await p.evaluate(async main=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main});barGame.reset(2,'full',10,false);Object.assign(barGame.progress,{money:2000,inventory:{},flags:{shiba_shop_met:true}});c.session.day=2;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:2,flow:'out',place:'bar'});await outsidePlaytest.start();c.screen(c.playView);const a=outsidePlaytest,m=a.model;m.x=-2.87;m.updateNear();a.snapCamera();a.tick(0);},main);
 assert.equal(await p.locator('.outside-notices .currency-hud').count(),0);assert(await p.locator('.outside-item-notice').isHidden());await menu();await click('shop-buy-wild_dog');await p.locator('.outside-notices .currency-spending').waitFor();await p.waitForTimeout(350);assert.equal(await p.locator('.outside-notices .currency-delta').innerText(),'−600');assert.equal(await p.locator('.outside-item-notice').innerText(),'와일드 독 추가');assert(await p.locator('.outside-item-notice img').evaluate(i=>i.complete&&i.naturalWidth>0));const box=await p.locator('.outside-item-notice').boundingBox();assert(box.x>=0&&box.x<30&&box.y<30&&box.width<=220&&box.height<=60);const cash=await p.locator('.outside-notices .currency-hud').boundingBox();assert(cash.x>1000&&cash.y<30);const focus=await p.evaluate(()=>document.activeElement.className);assert(!focus.includes('notice'));if(main)await p.screenshot({path:'/private/tmp/outside-purchase-notices.png'});await drain();await p.waitForTimeout(3000);assert(await p.locator('.outside-item-notice').isHidden());assert.equal(await p.locator('.outside-notices .currency-hud').count(),0);
 await menu();await click('shop-buy-bitters');await drain();assert(await p.locator('.outside-item-notice').isHidden());assert.equal(await p.locator('.outside-notices .currency-hud').count(),0);await click('shop-answer-2');await drain();assert(await p.locator('.outside-item-notice').isHidden());await click('shop-answer-1');await p.waitForTimeout(350);assert.equal(await p.locator('.outside-item-notice').innerText(),'비터스 추가');assert.equal(await p.locator('.outside-notices .currency-delta').innerText(),'−300');await drain();await p.waitForTimeout(2900);
 await menu();assert.equal(await p.locator('[data-choice^="shop-buy-"]').count(),0);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.choose('shop-buy-arcade_coupon')),false);await click('shop-no');await drain();assert(await p.locator('.outside-item-notice').isHidden());
 // Insufficient funds and a cancelled purchase never enqueue material notifications.
 await p.evaluate(()=>{barGame.progress.money=10;barGame.progress.inventory={};delete barGame.progress.flags.shiba_bought_wild_dog;delete barGame.progress.flags.shiba_bought_bitters;outsidePlaytest.tick(0);});await p.waitForTimeout(2800);await menu();assert(await p.locator('[data-choice="shop-buy-wild_dog"]').isDisabled());assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.choose('shop-buy-wild_dog')),false);await click('shop-no');await drain();assert(await p.locator('.outside-item-notice').isHidden());assert.equal(await p.locator('.outside-notices .currency-hud').count(),0);
 // Rapid purchases queue their small cards rather than overlapping; currency aggregates.
 await p.evaluate(()=>{const m=outsidePlaytest.model;barGame.progress.money=2500;outsidePlaytest.tick(0);for(let i=0;i<30;i++)outsidePlaytest.tick(.1);const drain=()=>{for(let i=0;m.story.speech&&!m.story.speech.choice&&i<100;i++){m.story.speech.elapsed=99;m.story.advance();}};for(const id of ['wild_dog','bitters']){LunaOutsideShop.begin(m,{x:-2.68,y:-.596},false);m.story.choose('shop-yes');drain();m.story.choose('shop-buy-'+id);drain();}});await p.waitForTimeout(300);assert.equal(await p.locator('.outside-item-notice').innerText(),'와일드 독 추가');assert.equal(await p.locator('.outside-notices .currency-delta').innerText(),'−900');await p.waitForTimeout(2800);assert.equal(await p.locator('.outside-item-notice').innerText(),'비터스 추가');await p.waitForTimeout(2800);assert(await p.locator('.outside-item-notice').isHidden());
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.story.cancel();LunaBDVendor.interact(m,{id:'bd-vendor',x:5.65,y:-.7});for(let i=0;m.story.speech&&!m.story.speech.choice&&i<100;i++){m.story.speech.elapsed=99;m.story.advance();}outsidePlaytest.tick(0);});await click('buy');await p.waitForTimeout(150);assert.equal(await p.locator('.outside-notices .currency-delta').innerText(),'−500');assert(await p.locator('.outside-item-notice').isHidden());
 await p.evaluate(()=>{outsidePlaytest.exit(true);barGame.phase='practice';barGame.screen='bar';lunaCampaign.screen(lunaCampaign.playView);lunaCampaign.render(true);});assert.equal(await p.locator('.currency-hud').count(),0,'No repeated outside deduction on bar return');console.log('PASS purchase HUD',main?'main':'developer');
}
 // Isolated QA wallet: never show or mutate the campaign wallet as a side effect.
 await p.evaluate(async()=>{lunaCampaign.toPicker();lunaCampaign.developer();Object.assign(outsidePlaytest.config,{day:99,flow:'out',place:'bar',qaCase:'shop:quiz-bitters'});await outsidePlaytest.start();const m=outsidePlaytest.model;m.x=0;m.updateNear();m.interact();m.qa.shopProgress.money=1000;outsidePlaytest.tick(0);});await menu().catch(()=>{});
 const qa=await p.evaluate(()=>{const m=outsidePlaytest.model,before=JSON.stringify(barGame.progress),drain=()=>{for(let i=0;m.story.speech&&!m.story.speech.choice&&i<100;i++){m.story.speech.elapsed=99;m.story.advance();}};m.story.cancel();LunaOutsideShop.begin(m,{x:0,y:-.7},false);m.story.choose('shop-yes');drain();outsidePlaytest.tick(0);for(let i=0;i<30;i++)outsidePlaytest.tick(.1);m.story.choose('shop-buy-bitters');drain();m.story.choose('shop-answer-1');outsidePlaytest.tick(0);return{isolated:before===JSON.stringify(barGame.progress),money:m.qa.shopProgress.money};});assert(qa.isolated);assert.equal(qa.money,700);await p.waitForTimeout(350);assert.equal(await p.locator('.outside-item-notice').innerText(),'비터스 추가');assert.equal(await p.locator('.outside-notices .currency-delta').innerText(),'−300');await p.emulateMedia({reducedMotion:'reduce'});await p.waitForTimeout(100);assert.equal(await p.locator('.outside-item-notice').evaluate(el=>getComputedStyle(el).transform),'none');await p.evaluate(()=>outsidePlaytest.exit(true));assert.equal(await p.locator('.outside-notices').count(),0);assert.deepEqual(errors,[]);console.log('OUTSIDE_PURCHASE_NOTICES_OK payment timing, quiz/cancel/no funds, compact images, queue, expiry, BD, no replay, QA wallet, reduced motion');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
