const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();await p.locator('[data-act="day"][data-id="1"]').click();await p.locator('[data-act="start"]').click();
await p.evaluate(()=>{const g=barGame;if(g.pendingDailyUnlocks)g.confirmDailyUnlocks();for(let i=0;i<3000&&!g.tutorial;i++){g.cameraMoving=false;g.cameraLeft=0;if(g.dialogue){g.advance();g.advance();}g.tick(.1);}if(g.error)throw Error(g.error);lunaCampaign.render(true);});
await p.waitForFunction(()=>barGame.tutorial?.kind==='recipe'&&!barGame.cameraMoving&&!barGame.cameraLeft);await p.locator('.service-handle').click();await p.locator('#service-panel [data-act="recipes"]').click();await p.locator('[data-act="selectRecipe"][data-id="bottle_beer"]').click();
async function stage(kind){await p.waitForFunction(k=>barGame.tutorial?.kind===k,kind);await p.locator('.day0-guide[data-guide="'+kind+'"]').waitFor();}
await stage('beerGlass');const glass=await p.evaluate(()=>barGame.cocktail('bottle_beer').glass);await p.locator('.shelf-slide[data-current="true"] [data-act="pick"][data-id="'+glass+'"]').click();await stage('beerToolNavigate');await p.keyboard.press('KeyD');await stage('beerOpener');await p.screenshot({path:'/private/tmp/day1-beer-opener.png'});await p.locator('.shelf-slide[data-current="true"] [data-act="pickOpener"]').click();await stage('beerFridgeNavigate');await p.keyboard.press('KeyD');await p.waitForTimeout(700);await p.keyboard.press('KeyD');await stage('beerAdd');await p.screenshot({path:'/private/tmp/day1-beer-fridge.png'});await p.locator('.shelf-slide[data-current="true"] [data-act="pick"][data-id="beer"]').click();await stage('beerStart');await p.locator('.craft-start').click();await p.locator('[data-open-lesson]').waitFor();assert.equal(await p.evaluate(()=>barGame.gimmick.type),'open');assert.equal(await p.evaluate(()=>barGame.gimmick.started),false);assert((await p.locator('.opening-lesson-copy').innerText()).includes('시작하세요'));
await p.keyboard.press('Space');await p.waitForTimeout(120);await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>barGame.gimmick.completed),false);assert((await p.locator('.opening-lesson-copy').innerText()).includes('괜찮아요'));
await p.screenshot({path:'/private/tmp/day1-beer-timing.png'});
await p.evaluate(()=>{const g=barGame;g.gimmick.beatTime=g.c('open_approach_sec',1.6);g.gimmickInput('Space');});await p.waitForFunction(()=>barGame.gimmick.completed);await p.waitForTimeout(900);await p.locator('[data-act="endGimmick"]').click();await p.waitForFunction(()=>barGame.gimmick?.type==='pour'||barGame.gimmick?.type==='fill_up');assert.equal(await p.locator('[data-open-lesson]').count(),0);assert.equal(await p.evaluate(()=>!!barGame.gimmick.pourTutorial),false);assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.tool),'none');
await p.evaluate(()=>{const g=barGame;g.debugCraft('good');g.offer();g.cameraMoving=false;g.cameraLeft=0;g.serve(g.currentOrder.seat,'drag');for(let i=0;i<30;i++)g.tick(.1);lunaCampaign.render(true);});assert((await p.evaluate(()=>barGame.dialogue.text)).includes('잘했어'));assert.equal(await p.evaluate(()=>barGame.phase),'opening');assert.equal(await p.evaluate(()=>barGame.transactions[0].net),0);
await p.evaluate(()=>{const g=barGame;for(let i=0;i<4000&&g.phase!=='general';i++){g.cameraMoving=false;g.cameraLeft=0;if(g.dialogue){g.advance();g.advance();}g.tick(.1);}lunaCampaign.render(true);});assert.equal(await p.evaluate(()=>barGame.phase),'general');assert.equal(await p.evaluate(()=>barGame.queue.length),2);assert((await p.evaluate(()=>barGame.spawnLeft))<=5);assert.deepEqual(errors,[]);console.log('DAY1_BEER_UI_OK recipe/glass/tools/opener/fridge/beer, real A-D slide completion, start/miss/success, no pour lesson, free Chris practice, opening before general');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
