const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
const prepare=async(id)=>{await p.evaluate(id=>{const g=barGame;g.reset(99,'practice',1,true,{variant:g.variant});g.selectCocktail(id);},id);await p.locator('.prep-recipe-brief').waitFor();await p.waitForTimeout(180);};
await prepare('gin_tonic');assert.equal(await p.locator('.prep-brief-amount').count(),0);assert.equal(await p.locator('.prep-brief-row').count(),2);assert.equal(await p.locator('.prep-controls [data-act="togglePrepRecipe"]').count(),0);assert.equal(await p.locator('[data-act="prepBack"]').count(),1);
const note=await p.locator('.prep-recipe-brief').boundingBox(),help=await p.locator('.help-corner').boundingBox(),back=await p.locator('.prep-back').boundingBox(),tray=await p.locator('.prep-inventory').boundingBox();assert(note.x<40&&note.y<40);assert(help.x>1200&&help.y<40);assert(back.x<40&&back.y>500&&back.y+back.height<tray.y);await p.screenshot({path:'/private/tmp/prep-brief-glass.png'});
await p.locator('.prep-recipe-brief').click();await p.locator('#prep-recipe-detail').waitFor();assert.equal(await p.locator('.prep-recipe-brief').getAttribute('aria-expanded'),'true');await p.locator('.prep-recipe-heading [data-act="togglePrepRecipe"]').click();await p.locator('#prep-recipe-detail').waitFor({state:'detached'});await p.locator('.help-corner').click();assert.equal(await p.evaluate(()=>barGame.overlay),'help');await p.keyboard.press('Escape');await p.locator('.shelf-slide[data-current="true"] [data-id="long_drink"]').click();await p.locator('.prep-back').click();assert.equal(await p.evaluate(()=>barGame.screen),'recipe');
await prepare('long_island');assert.equal(await p.locator('.prep-brief-row').count(),5);await p.locator('[data-act="tab"][data-id="fridge"]').click();await p.waitForTimeout(550);await p.screenshot({path:'/private/tmp/prep-brief-fridge.png'});assert.equal(await p.locator('.prep-brief-amount').count(),0);
// The same summary drives the original Day 0 recipe-open/read/close tutorial.
await prepare('gin_tonic');await p.evaluate(()=>{barGame.day=0;barGame.tutorial={kind:'prepRecipeOpen'};});await p.waitForTimeout(250);await p.locator('.prep-recipe-brief').click();assert.equal(await p.evaluate(()=>barGame.tutorial.kind),'prepRecipeRead');await p.locator('[data-act="tutorialContinue"]').click();await p.locator('.prep-recipe-heading [data-act="togglePrepRecipe"]').click();assert.equal(await p.evaluate(()=>barGame.tutorial.kind),'prepGlass');await p.evaluate(()=>{barGame.tutorial=null;barGame.reset(0,'full',1,false,{variant:'original'});});await p.waitForTimeout(150);await p.locator('[data-act="version"][data-id="gpt"]').click();await prepare('kahlua_milk');assert.equal(await p.locator('.prep-brief-amount').count(),0);assert.equal(await p.locator('.prep-brief-row').count(),2);const a=await p.locator('.prep-recipe-brief').boundingBox(),c=await p.locator('.remix-prep-check').boundingBox();assert(a.x+a.width<c.x||a.y+a.height<c.y);await p.screenshot({path:'/private/tmp/prep-brief-gpt.png'});await p.setViewportSize({width:960,height:540});await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);assert(await p.locator('.prep-recipe-brief').isVisible());await p.screenshot({path:'/private/tmp/prep-brief-small.png'});assert.deepEqual(errors,[]);console.log('PREP_BRIEF_OK: name-only summary, all shelf pages, single back, help, detail toggle, original tutorial, GPT no overlap, 960 layout');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
