const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');const root=path.resolve(__dirname,'..'),ctx={window:{}};vm.runInNewContext(fs.readFileSync(root+'/data.js','utf8'),ctx);const D=ctx.window.LUNA_DATA,C=require(root+'/core.js'),R=require(root+'/remix.js');
function tick(g,n=1){for(let t=0;t<n;t+=.1)g.tick(.1);assert.equal(g.error,null);}
function create(){const g=new C.Game(D);R.attach(g);g.reset(0,'full',4,true,{variant:'original'});for(let i=0;i<100&&!g.tutorial;i++){if(g.transition)tick(g);else if(g.choice)g.choose(1);else if(g.dialogue){g.advance();g.advance();}}assert.equal(g.tutorial.kind,'seatExplore');return g;}
const g=create(),index=g.story.index;assert.equal(g.focus,'R');assert.equal(g.advance(),false);assert.equal(g.focusSeat('L'),false);assert.equal(g.continueBarTutorial(),false);
for(const blocker of ['overlay','paused','hidden','cameraMoving','cameraLeft','transition']){g[blocker]=blocker==='overlay'?'settings':true;assert.equal(g.focusSeat('M'),false,blocker);g[blocker]=blocker==='overlay'?null:['cameraLeft','transition'].includes(blocker)?0:false;}
for(const seat of ['M','L','M','R']){assert.equal(g.focusSeat(seat),true);g.cameraMoving=true;tick(g,1);assert.equal(g.story.index,index);assert.equal(g.dialogue,null);g.cameraMoving=false;tick(g,.1);}
assert.equal(g.tutorial,null);assert.equal(g.dialogue.text,'총 3개로 보입니다.');
for(let i=0;i<20&&!g.tutorial;i++){g.advance();g.advance();}assert.equal(g.tutorial.kind,'seatIndicator');assert(g.continueBarTutorial());assert.equal(g.tutorial.kind,'seatLegend');const at=g.story.index;g.overlay='settings';assert.equal(g.continueBarTutorial(),false);g.overlay=null;tick(g,10);assert.equal(g.story.index,at);assert(g.continueBarTutorial());assert.equal(g.dialogue.text,'좋아, 이제 다음으로 넘어가자.');assert.equal(g.continueBarTutorial(),false);
// A matching first drink is taught once; wrong recipes and the skip path never get trapped.
function result(skip=false,wrong=false){const a=new C.Game(D);R.attach(a);a.reset(0,'practice',4,true,{variant:'original'});a.selectCocktail(wrong?'gin_fizz':'gin_tonic');a.debugCraft();a.phase='regular';a.progress.flags.day0_skip_tutorial=skip;a.seats.R={actor:'chris',coaster:true};a.currentOrder={id:'tutorial_order',actor:'chris',seat:'R',cocktail:'gin_tonic'};a.story={scene:{id:"test_serve_lesson"},index:0,steps:[{type:'craft'},{type:'serve',actor:'chris'},{type:'say',actor:'chris','text.ko':'음…','text.en':'Hmm…'}]};a.offer();return a;}
const drink=result();assert.equal(drink.tutorial.kind,'serveDrink');assert.equal(drink.serve('R'),false);assert.equal(drink.serve('L','drag'),false);assert.equal(drink.transactions.length,0);drink.overlay='settings';assert.equal(drink.serve('R','drag'),false);drink.overlay=null;assert.equal(drink.serve('R','drag'),true);assert.equal(drink.tutorial,null);assert.equal(drink.serve('R','drag'),false);assert.equal(drink.transactions.length,1);assert.equal(drink.progress.flags.day0_drink_taught,true);tick(drink,1.2);assert.equal(drink.dialogue.text,'음…');
assert.equal(result(true).tutorial,null);assert.equal(result(false,true).tutorial,null);
const keyboard=result();assert.equal(keyboard.serve('R','keyboard'),true);
for(const kind of ['seatExplore','seatIndicator','seatLegend','serveDrink']){const a=create();a.tutorial.kind=kind;a.reset(1,'general',3);assert.equal(a.tutorial,null);assert(!a.progress.flags.day0_seats_revealed);}
console.log('DAY0_SEAT_SERVING_CORE_OK: adjacent inputs, camera settlement, modal pause, skip, wrong recipe, drag-only gate, single settlement, keyboard fallback and reset');
