const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{
 const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));
 await p.goto('http://127.0.0.1:8123/bar-playtest/');await p.locator('[data-campaign="title"]').click();await p.locator('[data-campaign="service:B"]').click();await p.locator('[data-campaign="new"]').click();await p.locator('[data-campaign="start-day:1"]').click();await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading&&lunaCampaign.view==='game');
 const outsideAction=async a=>p.locator('[data-outside-action="'+a+'"]').click();
 const state=()=>p.evaluate(()=>{const m=outsidePlaytest.model;return{day:m.config.day,x:m.x,y:m.y,scene:m.scene,money:barGame.progress.money,flow:m.config.flow,route:lunaCampaign.session.route};});
 await p.keyboard.press('KeyP');const initial=await state();await outsideAction('dev-flow-out');assert.deepEqual(await state(),{...initial,flow:'out',route:'out'});assert.equal(await p.locator('[data-outside-action="dev-flow-out"]').getAttribute('aria-pressed'),'true');await outsideAction('dev-flow-in');assert.deepEqual(await state(),initial);
 await outsideAction('dev-bar');await p.keyboard.press('KeyP');await p.keyboard.press('KeyE');await p.waitForFunction(()=>!outsidePlaytest.active&&lunaCampaign.view==='game'&&!lunaCampaign.doorTransition);await p.evaluate(()=>barGame.confirmDailyUnlocks());
 await p.keyboard.down('KeyP');await p.keyboard.down('KeyP');await p.keyboard.up('KeyP');assert(await p.locator('.campaign-dev-console').isVisible());
 const frozen=await p.evaluate(()=>({time:barGame.barTime,chars:barGame.dialogue?.chars,screen:barGame.screen,phase:barGame.phase}));await p.keyboard.press('KeyD');await p.waitForTimeout(200);assert.deepEqual(await p.evaluate(()=>({time:barGame.barTime,chars:barGame.dialogue?.chars,screen:barGame.screen,phase:barGame.phase})),frozen);
 await p.locator('[data-campaign="dev-plus"]').focus();await p.keyboard.press('Space');assert.equal(await p.evaluate(()=>barGame.progress.money),initial.money+1000);assert.deepEqual(await p.evaluate(()=>({time:barGame.barTime,chars:barGame.dialogue?.chars,screen:barGame.screen,phase:barGame.phase})),frozen);await p.waitForTimeout(250);await p.screenshot({path:'/private/tmp/main-console-bar.png'});await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'game');assert.equal(await p.locator('#app').getAttribute('inert'),null);
 await p.keyboard.press('KeyP');await p.locator('[data-campaign="dev-home"]').click();await p.waitForFunction(()=>outsidePlaytest.devConsoleOpen&&lunaCampaign.view==='game');assert.equal((await state()).scene,'home');assert.equal((await state()).flow,'out');assert.equal((await state()).money,initial.money+1000);assert.equal(await p.evaluate(()=>lunaCampaign.session.serviceVersion),'B');
 await outsideAction('dev-flow-in');await p.keyboard.press('KeyP');await p.evaluate(()=>{const m=outsidePlaytest.model;m.wakeAtSofa();outsidePlaytest.snapCamera();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'notice');await p.locator('[data-campaign="resume"]').click();
 await p.keyboard.press('KeyP');await outsideAction('dev-flow-out');await p.waitForTimeout(250);await p.screenshot({path:'/private/tmp/main-console-flow.png'});await p.keyboard.press('KeyP');await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>lunaCampaign.view),'sleep');await p.locator('[data-campaign="sleep-confirm"]').click();await p.waitForFunction(()=>lunaCampaign.view==='scene'||!!lunaCampaign.dayTransition);await p.evaluate(()=>{for(let i=0;i<1000&&lunaCampaign.view==='scene';i++)lunaCampaign.next();});await p.waitForFunction(()=>outsidePlaytest.active&&lunaCampaign.view==='game'&&!lunaCampaign.dayTransition&&lunaCampaign.session.day===2,{},{timeout:20000});assert.equal((await state()).flow,'in');assert.equal((await state()).money,initial.money+1000);assert.equal(await p.evaluate(()=>outsidePlaytest.model.near.id),'sofa');
 // Switching routes resets the current route's events but never resets funds or day.
 await p.keyboard.press('KeyP');await p.evaluate(()=>{lunaCampaign.morningSeen.add(2);outsidePlaytest.model.notionCommuteSeen=true;outsidePlaytest.model.playedAmbient.add('old');});await outsideAction('dev-flow-out');await outsideAction('dev-flow-in');assert.equal(await p.evaluate(()=>lunaCampaign.morningSeen.has(2)||outsidePlaytest.model.notionCommuteSeen||outsidePlaytest.model.playedAmbient.size>0),false);
 await outsideAction('dev-bar');await p.keyboard.press('KeyP');await p.waitForFunction(()=>lunaCampaign.view==='scene');assert.equal(await p.evaluate(()=>lunaCampaign.morningSeen.has(2)),true);
 // Original developer exterior also changes flow, and restart retains the new setting.
 await p.evaluate(async()=>{const c=lunaCampaign;c.toPicker();c.developer();Object.assign(outsidePlaytest.config,{day:0,flow:'out',place:'bar'});await outsidePlaytest.start();});if(await p.locator('.updates-confirm').isVisible())await p.locator('.updates-confirm').click();await p.keyboard.press('KeyP');await outsideAction('dev-flow-in');assert.equal(await p.evaluate(()=>outsidePlaytest.config.flow),'in');assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.flow),'in');await outsideAction('dev-flow-out');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'developer');
 assert.deepEqual(errors,[]);console.log('MAIN_CONSOLE_FLOW_OK real B start, bar P/repeat/Esc freeze, money, teleport, route sync, commute vs sofa, workshop -> next day, event reset, developer exterior');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
