const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();await p.evaluate(async()=>{Object.assign(outsidePlaytest.config,{day:2,flow:'in',place:'bar'});await outsidePlaytest.start();});
const result=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,ctx=document.querySelector('#outside-root canvas').getContext('2d'),original=ctx.drawImage,observed=[];
function capture(label,time){m.time=time;a.snapCamera();const draws=[];ctx.drawImage=function(im,...args){if(im.src.includes('4bdaf8a66fd58d'))draws.push({frame:args[0]/84,sign:Math.sign(this.getTransform().a)});return original.call(this,im,...args);};try{a.tick(0);}finally{ctx.drawImage=original;}if(draws.length!==1)throw Error(label+' expected one Samho: '+draws.length);observed.push({label,...draws[0]});}
for(const qa of [false,true])for(const side of [-1,1]){m.start(qa?{day:99,qaCase:'runtime:commute2',qaActivation:'manual'}:{day:2,flow:'in'});const center=qa?.25:-5.99;m.x=center+side*.78;LunaOutsideSamhoCommute.start(m);for(const t of [.01,.11,.21,1.5])capture((qa?'qa':'street')+'-target-'+side,t);LunaOutsideSamhoCommute.action(m);capture((qa?'qa':'street')+'-depart-'+(-side),.11);}
m.start({day:1,flow:'out'});const pair=LunaOutsideEncounters.trading,target=LunaOutsideEncounters.targets(m)[0];for(const side of [-1,1]){m.x=target.x+side*.5;for(const t of [.01,.11,.21])capture('pair-approach-'+side,t);}return {observed,pair:pair.map(p=>p.x),target:target.x};});
assert.deepEqual(result.pair,[3.6,4.32]);assert(Math.abs(result.target-3.96)<1e-8);for(const r of result.observed){const direction=Number(r.label.match(/(?:target|depart)-(-?\d+)$/)?.[1]),sign=r.label.startsWith('pair')?-1:direction<0?1:-1;assert.equal(r.sign,sign,r.label+' frame '+r.frame);}
for(const side of [-1,1]){await p.evaluate(side=>{const a=outsidePlaytest,m=a.model;m.start({day:2,flow:'in'});m.x=-5.99+side*.78;a.snapCamera();LunaOutsideSamhoCommute.start(m);},side);await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line);await p.evaluate(()=>{outsidePlaytest.model.story.speech.elapsed=99;outsidePlaytest.refreshHUD();});await p.screenshot({path:'/private/tmp/samho-facing-luna-'+side+'.png'});}
assert.deepEqual(errors,[]);console.log('SAMHO_CORRECTED_OK all blink frames, both Luna sides, both departure directions, QA, partner-facing unaffected by Luna, pair moved +1.2');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
