const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=minigames');await p.locator('.updates-confirm').click();await p.locator('[data-act="miniStart"][data-id="shake"]').click();
for(const mode of ['fall','cross']){await p.evaluate(()=>barGame.startMinigame('shake','gpt'));await p.locator('.rhythm-board').waitFor();await p.locator('[data-act="shakeMode"][data-id="'+mode+'"]').click();await p.keyboard.press('Space');await p.evaluate(()=>{window.savedTick=barGame.tick;barGame.tick=()=>{};});
for(const [goal,rate] of [[5,1.25],[10,1.5]]){
 await p.evaluate(goal=>{const g=barGame,s=g.gimmick,r=s.rhythm;while(r.combo<goal-1){const n=r.notes.find(n=>!n.status);r.trackTime=n.time;g.gimmickInput(n.lane?'KeyD':'KeyA');}r.trackTime=r.notes[goal-1].time;},goal);await p.waitForTimeout(60);
 const before=await p.locator('[data-rhythm-note="'+goal+'"]').getAttribute('transform');await p.evaluate(goal=>{const s=barGame.gimmick;barGame.gimmickInput(s.rhythm.notes[goal-1].lane?'KeyD':'KeyA');},goal);await p.waitForTimeout(60);assert.equal(await p.locator('[data-rhythm-note="'+goal+'"]').getAttribute('transform'),before,'tier change must not teleport upcoming notes');assert.equal(Number(await p.locator('.rhythm-board').getAttribute('data-note-speed')),rate);
 const step=await p.evaluate(()=>{const g=barGame,s=g.gimmick,track=s.rhythm.trackTime,elapsed=s.elapsed,craft=g.craft.elapsed;g.tickGimmick(.1);return{travel:s.rhythm.trackTime-track,real:s.elapsed-elapsed,craft:g.craft.elapsed-craft};});assert(Math.abs(step.travel-.1*rate)<1e-9);assert(Math.abs(step.real-.1)<1e-9);assert(Math.abs(step.craft-.1)<1e-9);
}
// Late but still valid: keep a 150ms real-time offset at the fastest speed.
await p.evaluate(()=>{const g=barGame,s=g.gimmick,n=s.rhythm.notes[10];s.rhythm.trackTime=n.time+.15*1.5;g.gimmickInput(n.lane?'KeyD':'KeyA');});assert.equal(await p.evaluate(()=>barGame.gimmick.message),'GOOD');
await p.evaluate(()=>{const s=barGame.gimmick;s.rhythm.trackTime=s.rhythm.notes[11].time-.4;});await p.waitForTimeout(60);const beforeMiss=await p.locator('[data-rhythm-note="11"]').getAttribute('transform');await p.keyboard.press('a');await p.waitForTimeout(60);assert.equal(await p.locator('[data-rhythm-note="11"]').getAttribute('transform'),beforeMiss);assert.equal(await p.locator('.rhythm-board').getAttribute('data-note-speed'),'1');assert.equal(await p.locator('.combo-flame').count(),0);
const delta=await p.evaluate(()=>{const s=barGame.gimmick,t=s.rhythm.trackTime;barGame.tickGimmick(.1);return s.rhythm.trackTime-t;});assert(Math.abs(delta-.1)<1e-9);await p.evaluate(()=>{const g=barGame,s=g.gimmick;for(const n of s.rhythm.notes.filter(n=>!n.status)){s.rhythm.trackTime=n.time;g.gimmickInput(n.lane?'KeyD':'KeyA');}g.tick=window.savedTick;});await p.locator('.minigame-result').waitFor();assert.equal(await p.evaluate(()=>barGame.minigame.result.targetStacks),20);
}assert.deepEqual(errors,[]);console.log('NOTE_SPEED_OK: 2 chart views, 1.25x/1.5x rates, no position jump on tier up/reset, real-time judgement window and craft clock, failure reset, 20-note completion');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
