const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
async function start(day,flow,main=false){await p.evaluate(async({day,flow,main})=>{const c=lunaCampaign;c.outside.exit(true);c.session.uninstall();c.session.install({developer:!main});barGame.reset(day===99?0:day,'full',1,false);barGame.progress.money=300;c.session.day=day;c.session.route=flow;c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day,flow,place:'bar',variant:'original'});await outsidePlaytest.start();c.screen(c.playView);},{day,flow,main});}
for(const main of [false,true])for(const [day,flow]of [[0,'out'],[1,'in'],[2,'out'],[3,'in']]){
 await start(day,flow,main);assert.equal(await p.locator('.outside-dev-console').isVisible(),false);await p.keyboard.down('KeyP');await p.keyboard.down('KeyP');await p.keyboard.up('KeyP');assert(await p.locator('.outside-dev-console').isVisible());
 const x=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyA');await p.waitForTimeout(100);await p.keyboard.up('KeyA');assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),x);
 await p.locator('[data-outside-action="dev-plus"]').click();assert.equal(await p.evaluate(()=>barGame.progress.money),1300);assert.equal(await p.evaluate(()=>lunaCampaign.session.carry.money),1300);await p.locator('[data-outside-action="dev-minus"]').click();assert.equal(await p.evaluate(()=>barGame.progress.money),300);await p.locator('[data-outside-action="dev-minus"]').click();assert.equal(await p.evaluate(()=>barGame.progress.money),0);assert(await p.locator('[data-outside-action="dev-minus"]').isDisabled());await p.locator('[data-outside-action="dev-plus"]').click();
 for(const dest of ['home','elevator','bar']){await p.locator('[data-outside-action="dev-'+dest+'"]').click();const state=await p.evaluate(()=>{const m=outsidePlaytest.model;return {scene:m.scene,day:m.config.day,flow:m.config.flow,near:m.near?.id,level:m.level,ride:m.ride,transition:m.transition};});assert.deepEqual(state,{scene:dest==='home'?'home':'street',day,flow,near:dest==='home'?'exit':dest,level:dest==='home'?1:0,ride:null,transition:null});}
 if(main&&day===1)await p.screenshot({path:'/private/tmp/outside-dev-console.png'});await p.keyboard.press('Escape');assert.equal(await p.locator('.outside-dev-console').isVisible(),false);assert.equal(await p.evaluate(()=>outsidePlaytest.model.paused),false);assert.equal(await p.evaluate(()=>lunaCampaign.view),main?'game':'developer');await p.keyboard.press('KeyP');await p.keyboard.press('KeyP');assert.equal(await p.locator('.outside-dev-console').isVisible(),false);
}
// A money edit updates the existing disabled BD purchase; teleport cancels the conversation.
await start(1,'out',true);await p.evaluate(()=>{const a=outsidePlaytest;a.model.x=LunaBDVendor.x-.2;a.model.updateNear();a.snapCamera();a.model.interact();for(let i=0;i<8&&!a.model.story.speech.choice;i++)a.model.story.advance();a.refreshHUD();});assert(await p.locator('[data-choice="buy"]').isDisabled());await p.keyboard.press('KeyP');await p.locator('[data-outside-action="dev-plus"]').click();await p.keyboard.press('KeyP');assert.equal(await p.locator('[data-choice="buy"]').isDisabled(),false);await p.keyboard.press('KeyP');await p.locator('[data-outside-action="dev-home"]').click();assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech),null);await p.keyboard.press('KeyP');
// Teleport while riding cancels the ride without a stale camera/position update.
await p.keyboard.press('KeyP');await p.locator('[data-outside-action="dev-elevator"]').click();await p.keyboard.press('KeyP');await p.keyboard.press('KeyE');assert(await p.evaluate(()=>!!outsidePlaytest.model.ride));await p.keyboard.press('KeyP');await p.locator('[data-outside-action="dev-home"]').click();await p.keyboard.press('KeyP');await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'home');assert.equal(await p.evaluate(()=>outsidePlaytest.model.ride),null);
await start(99,'out');await p.keyboard.press('KeyP');await p.locator('[data-outside-action="dev-home"]').click();assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'home');assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.day),99);
assert.deepEqual(errors,[]);console.log('OUTSIDE_CONSOLE_OK main/developer, days0-3 both routes, P/repeat/Esc, freeze, 3 locations, +/-1000 floor0, carry, BD enable, ride/dialog cleanup, QA teleport');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
