const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');if(await p.locator('.updates-confirm').count())await p.locator('.updates-confirm').click();
async function prep(id,variant='original'){await p.evaluate(({id,variant})=>{const c=lunaCampaign;c.view='developer';c.host.hidden=true;c.app.inert=false;c.ui.variant=variant;c.ui.recipeOpen=false;c.ui.minigames=false;c.ui.tab='glass';barGame.reset(99,'practice',42,true,{variant});barGame.selectCocktail(id);c.render(true);},{id,variant});await p.locator('.prep-recipe-brief').waitFor();}
for(const variant of ['original','gpt']){
await prep('gin_fizz',variant);const recipe=await p.evaluate(()=>barGame.t.recipes.filter(r=>r.context==='gin_fizz'&&!r.auto_apply).map(r=>r.ingredient));for(const id of ['long_drink','shaker',...recipe])assert.equal(await p.locator('[data-required-item="'+id+'"]').getAttribute('data-packed'),'false',id);
await p.evaluate(()=>{barGame.pickItem('long_drink');barGame.pickItem('shaker');barGame.pickItem('gin');lunaCampaign.render(true);});
for(const id of ['long_drink','shaker','gin'])assert.equal(await p.locator('[data-required-item="'+id+'"]').getAttribute('data-packed'),'true');
await p.evaluate(()=>{barGame.pickItem('gin');barGame.pickItem('mixing_glass');barGame.pickItem('wine');lunaCampaign.render(true);});for(const id of ['gin','long_drink','shaker'])assert.equal(await p.locator('[data-required-item="'+id+'"]').getAttribute('data-packed'),'false');
await p.evaluate(()=>{barGame.pickItem('long_drink');barGame.pickItem('shaker');barGame.pickItem('gin');lunaCampaign.render(true);});await p.screenshot({path:'/private/tmp/prep-checklist-'+variant+'.png'});
assert(!(await p.locator('.prep-recipe-brief').textContent()).includes('ml'));await p.locator('.prep-recipe-brief').click();assert(await p.locator('#prep-recipe-detail').isVisible());
}
await prep('bottle_beer');assert.equal(await p.locator('[data-required-item="opener"]').getAttribute('data-packed'),'false');await p.evaluate(()=>{lunaCampaign.ui.tab='tool';lunaCampaign.render(true);});await p.locator('.shelf-item[data-act="pickOpener"]').click();assert.equal(await p.locator('[data-required-item="opener"]').getAttribute('data-packed'),'true');await p.locator('.inventory-slot[data-act="pickOpener"]').click();assert.equal(await p.locator('[data-required-item="opener"]').getAttribute('data-packed'),'false');
await prep('dry_martini');assert.equal(await p.locator('[data-required-item="mixing_glass"]').count(),1);assert.equal(await p.locator('[data-required-item="shaker"]').count(),0);await p.mouse.move(1000,600);await p.waitForTimeout(350);assert.equal(await p.locator('.prep-recipe-brief').evaluate(e=>getComputedStyle(e).backgroundColor),'rgba(12, 23, 35, 0.65)');
assert.deepEqual(errors,[]);console.log('PASS original/GPT glass/tools/ingredients, selection removal & replacement, opener UI toggle, recipe click, no quantities, translucent background, no browser errors');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
