const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{
 const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 async function start(main,version){await p.evaluate(async({main,version})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main,serviceVersion:version});barGame.reset(0,'full',10,false,{serviceVersion:version});barGame.progress.money=2300;c.session.day=0;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:0,flow:'out',place:'home',variant:'original'});await outsidePlaytest.start({wakeAtSofa:true});c.screen(c.playView);},{main,version});await p.keyboard.press('KeyE');if(main)await p.locator('[data-campaign="sleep-confirm"]').click();await p.locator('.terrace-scene').waitFor();await p.waitForFunction(()=>!lunaCampaign.memoryTransition);}
 async function beforeMemory(){const lines=await p.evaluate(()=>{const c=lunaCampaign,rows=[];while(c.view==='scene'&&!c.dayTransition){rows.push(c.dialog.rows[c.dialog.index].text);c.dialog.chars=1e6;c.next();}return rows;});assert.equal(lines.length,13);assert.equal(lines[11],'…사람과 감정을 이해하고 싶다는 마음은 여전한 거지?');await p.waitForFunction(()=>lunaCampaign.view==='prologue'&&!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.cinema.title),'유나와의 기억 · 폐기물 처리소');assert.deepEqual(await p.evaluate(()=>lunaCampaign.cinema.scene.lines.map(l=>l.text)),await p.evaluate(()=>LUNA_CAMPAIGN_DATA.scenes.terraceMemory.map(r=>r.text)));assert.deepEqual(await p.evaluate(()=>lunaCampaign.cinema.scene.order.map(a=>a.id).sort()),['luna','yuna']);}
 for(const [main,version,skip] of [[true,'A',false],[true,'B',true],[false,'A',false]]){
  await start(main,version);await beforeMemory();
  await p.keyboard.press('Escape');const time=await p.evaluate(()=>lunaCampaign.cinema.time);await p.waitForTimeout(150);assert.equal(await p.evaluate(()=>lunaCampaign.cinema.time),time);await p.keyboard.press('Escape');
  const lines=await p.evaluate(()=>lunaCampaign.cinema.scene.lines.map(l=>({t:l.t,dur:l.dur})));
  for(const [width,height] of [[1280,720],[960,540]]){await p.setViewportSize({width,height});await p.waitForTimeout(100);await p.evaluate(()=>{const c=lunaCampaign.cinema,l=c.scene.lines[2];c.time=l.t+l.dur-.1;c.player.render(c.time,null,false,0);});const box=await p.locator('.campaign-cinema-ui .bubble').boundingBox();assert(box&&box.x>=0&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1);assert.equal(await p.locator('.campaign-cinema-ui strong,.campaign-cinema-ui .speaker').count(),0);if(main&&version==='A'&&width===1280)await p.screenshot({path:'/private/tmp/terrace-memory.png'});}
  await p.setViewportSize({width:1280,height:720});
  if(skip){await p.evaluate(()=>{lunaCampaign.cinema.time=0;});await p.keyboard.down('Space');await p.waitForTimeout(600);await p.keyboard.up('Space');assert.equal(await p.evaluate(()=>lunaCampaign.view),'prologue');await p.keyboard.down('Space');await p.waitForTimeout(3200);await p.keyboard.up('Space');}
  else await p.evaluate(()=>{const c=lunaCampaign.cinema;c.time=c.scene.end-.01;lunaCampaign.tick(.05);});
  await p.waitForFunction(()=>lunaCampaign.view==='scene'&&!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),13);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows[lunaCampaign.dialog.index].text),'…');assert.equal(await p.evaluate(()=>barGame.progress.money),2300);assert.equal(await p.evaluate(()=>lunaCampaign.cinema),null);
  const after=await p.evaluate(()=>{const c=lunaCampaign,lines=[];while(c.view==='scene'&&!c.dayTransition){lines.push(c.dialog.rows[c.dialog.index].text);c.dialog.chars=1e6;c.next();}return lines;});assert.equal(after.length,5);assert.equal(after.at(-1),'그래. 오늘은 이만 자고, 내일 다시 해 보자고.');await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading&&!lunaCampaign.dayTransition&&['game','developer'].includes(lunaCampaign.view)&&outsidePlaytest.model.config.day===1,null,{timeout:20000});assert.equal(await p.evaluate(()=>outsidePlaytest.model.near.id),'sofa');assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.flow),'in');assert.equal(await p.evaluate(()=>barGame.progress.money),2300);
 }
 // Returning to the picker during a slow resource load must cancel the callback.
 await start(false,'A');await p.evaluate(()=>{const c=lunaCampaign,original=c.script.bind(c);c.script=name=>name==='terrace-memory'?new Promise(resolve=>window.resumeRecallLoad=()=>resolve(original(name))):original(name);while(c.view==='scene'){c.dialog.chars=1e6;c.next();}});await p.waitForFunction(()=>!!window.resumeRecallLoad);await p.evaluate(()=>{lunaCampaign.toPicker();window.resumeRecallLoad();});await p.waitForTimeout(250);assert.equal(await p.evaluate(()=>lunaCampaign.view),'picker');
 // QA retains its virtual stage and includes all five memory lines in script order.
 await p.evaluate(async()=>{lunaCampaign.developer();Object.assign(outsidePlaytest.config,{day:99,flow:'out',place:'bar',qaCase:'runtime:night0'});await outsidePlaytest.start();const m=outsidePlaytest.model;m.x=0;m.updateNear();m.interact();for(let i=0;i<20;i++)m.tick(.05);});const qa=await p.evaluate(()=>outsidePlaytest.model.story.speech.rows.map(r=>r.text));assert.equal(qa.length,23);assert.equal(qa[13],'루나, 내가 말했던 거 기억나지?');assert.equal(qa[18],'…');
 assert.deepEqual(errors,[]);console.log('TERRACE_MEMORY_OK main A/B + developer sofa, 18 terrace / 5 memory lines, disposal actors only, text-only bubbles, two viewport bounds, pause, short/3s skip, natural finish, exact resume, next morning sofa, money preserved, load cancellation, QA virtual dialogue');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
