const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=minigames');await p.locator('.updates-confirm').click();await p.locator('[data-act="miniStart"][data-id="shake"]').click();await p.waitForTimeout(600);assert(await p.locator('.rhythm-intro').isVisible());assert.equal(await p.locator('[data-rhythm-status]').count(),0);assert(!(await p.locator('.rhythm-board').innerText()).includes('BPM'));await p.screenshot({path:'/private/tmp/rhythm-glow-intro.png'});
const before=await p.locator('.rhythm-stage').boundingBox();await p.waitForTimeout(3600);assert(!(await p.locator('.rhythm-intro').isVisible()));const after=await p.locator('.rhythm-stage').boundingBox();assert.deepEqual(before,after);await p.locator('[data-act="shakeMode"][data-id="cross"]').click();assert(!(await p.locator('.rhythm-intro').isVisible()));await p.keyboard.press('Space');assert(await p.evaluate(()=>barGame.gimmick.started));await p.waitForTimeout(350);assert(await p.locator('[data-rhythm-count-in]').textContent());
for(const mode of ['fall','cross']){
 await p.evaluate(()=>barGame.startMinigame('shake','original'));await p.locator('.rhythm-board').waitFor();await p.locator('[data-act="shakeMode"][data-id="'+mode+'"]').click();await p.keyboard.press('Space');await p.waitForTimeout(500);await p.screenshot({path:'/private/tmp/rhythm-glow-'+mode+'.png'});
 await p.evaluate(()=>{window.savedTick=barGame.tick;barGame.tick=()=>{};const s=barGame.gimmick;s.rhythm.trackTime=1.8;barGame.gimmickInput('KeyA');s.shakeEffects.at(-1).age=.12;});await p.waitForTimeout(80);assert.equal(await p.locator('[data-rhythm-verdict]').textContent(),'PERFECT');await p.screenshot({path:'/private/tmp/rhythm-glow-hit-'+mode+'.png'});
 await p.evaluate(()=>{const s=barGame.gimmick;s.rhythm.trackTime=2.4;barGame.gimmickInput('KeyA');});await p.waitForTimeout(80);assert.equal(await p.evaluate(()=>barGame.gimmick.rhythm.playing),false);assert.equal(await p.locator('[data-rhythm-combo]').textContent(),'0');await p.evaluate(()=>{const s=barGame.gimmick;s.rhythm.trackTime=3;barGame.gimmickInput('KeyA');});assert(await p.evaluate(()=>barGame.gimmick.rhythm.playing));await p.evaluate(()=>barGame.tick=window.savedTick);
}
await p.setViewportSize({width:960,height:540});await p.waitForTimeout(120);await p.screenshot({path:'/private/tmp/rhythm-glow-small.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.emulateMedia({reducedMotion:'reduce'});assert.equal(await p.locator('.note-aura').first().evaluate(e=>getComputedStyle(e).display),'none');assert.deepEqual(errors,[]);console.log('RHYTHM_GLOW_OK: one-off fading intro, no reserved space, no BPM copy, post-fade start, two chart layouts, hit FX, miss/resume, small screen, reduced motion');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
