const BASE=(process.env.LUNA_TEST_URL||'http://127.0.0.1:8765/').replace(/\/?$/, '/');
const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('assert/strict');
(async()=>{let b;try{b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});const p=await b.newPage({viewport:{width:1440,height:900}});const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE);await p.waitForTimeout(400);await p.screenshot({path:'/private/tmp/bar-start.png'});
 await p.locator('[data-act="start"]').click();await p.waitForTimeout(1300);await p.screenshot({path:'/private/tmp/bar-story.png'});assert.equal(await p.evaluate(()=>barGame.phase),'regular');await p.keyboard.press('Enter');await p.keyboard.press('Enter');
 await p.evaluate(()=>{barGame.reset(99,'practice',2);});await p.waitForTimeout(150);await p.locator('[data-act="selectRecipe"][data-id="gin_tonic"]').click();await p.locator('[data-act="pick"][data-id="long_drink"]').click();await p.locator('[data-act="tab"][data-id="liquor"]').click();await p.locator('[data-act="pick"][data-id="gin"]').click();await p.locator('[data-act="tab"][data-id="fridge"]').click();await p.locator('[data-act="pick"][data-id="soda_water"]').click();await p.screenshot({path:'/private/tmp/bar-prep.png'});await p.locator('[data-act="craft"]').click();await p.keyboard.down('Space');await p.waitForTimeout(2100);await p.keyboard.up('Space');await p.waitForTimeout(650);assert((await p.evaluate(()=>barGame.gimmick.value))>0);await p.screenshot({path:'/private/tmp/bar-pour.png'});await p.locator('[data-act="endGimmick"]').click();await p.keyboard.down('Space');await p.waitForTimeout(2300);await p.keyboard.up('Space');await p.waitForTimeout(650);await p.locator('[data-act="endGimmick"]').click();assert.equal(await p.evaluate(()=>barGame.screen),'result');await p.screenshot({path:'/private/tmp/bar-result.png'});await p.locator('[data-act="offer"]').click();await p.locator('[data-act="serve"]').click();assert.equal(await p.evaluate(()=>barGame.transactions.length),1);
 await p.evaluate(()=>{barGame.reset(99,'general',7);barGame.dialogSpeed=20;for(let i=0;i<53;i++)barGame.tick(.1);});await p.waitForTimeout(700);await p.keyboard.press('Space');await p.evaluate(()=>{for(let i=0;i<50;i++)barGame.tick(.1)});assert.equal(await p.evaluate(()=>barGame.seats.L.state),'WAIT_SERVE');await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>barGame.seats.L.reasking),true);await p.screenshot({path:'/private/tmp/bar-general.png'});
 await p.locator('[data-act="sales"]').click();const timer=await p.evaluate(()=>barGame.seats.L.left);await p.waitForTimeout(500);assert.equal(await p.evaluate(()=>barGame.seats.L.left),timer);await p.locator('[data-act="closeOverlay"]').click();
 await p.evaluate(()=>{barGame.openRecipes();barGame.selectCocktail(barGame.seats.L.order.cocktail);barGame.debugCraft();barGame.offer();});await p.locator('[data-drag="drink"]').waitFor({state:'visible',timeout:5000});await p.locator('[data-drop="L"]').waitFor({state:'visible',timeout:5000});const from=await p.locator('[data-drag="drink"]').boundingBox(),to=await p.locator('[data-drop="L"]').boundingBox();assert(from&&to,'Serving source/target must be visible');await p.mouse.move(from.x+from.width/2,from.y+from.height/2);await p.mouse.down();await p.mouse.move(to.x+to.width/2,to.y+to.height/2,{steps:10});await p.mouse.up();assert.equal(await p.evaluate(()=>barGame.drink),null);
 await p.evaluate(()=>barGame.reset(99,'regular',9));await p.waitForTimeout(1000);await p.evaluate(()=>{barGame.advance();barGame.advance();});await p.waitForTimeout(150);await p.locator('[data-act="choice"][data-id="3"]').click();await p.waitForTimeout(1000);await p.screenshot({path:'/private/tmp/bar-two-guests.png'});assert.equal(await p.evaluate(()=>Object.values(barGame.seats).filter(Boolean).length),2);
 await p.setViewportSize({width:820,height:650});await p.screenshot({path:'/private/tmp/bar-compact.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.setViewportSize({width:600,height:800});await p.screenshot({path:'/private/tmp/bar-mobile.png'});assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
 assert.deepEqual(errors,[]);console.log('BROWSER_OK: real clicks, keyboard pour, preparation, serving drag, reask, paused menus, paired entrance, responsive layout.');console.log('Images',await p.evaluate(()=>[...document.images].filter(i=>!i.complete||!i.naturalWidth).map(i=>i.src)));
 await p.setViewportSize({width:1440,height:900});await p.goto(BASE);await p.locator('[data-act="day"][data-id="3"]').click();await p.locator('#upkeep-test').fill('100');await p.locator('[data-act="start"]').click();assert.equal(await p.evaluate(()=>barGame.dailySettlement.status),'pending');assert.equal(await p.evaluate(()=>barGame.progress.money),300);await p.screenshot({path:'/private/tmp/bar-upkeep-pending.png'});await p.locator('[data-act="confirmSettlement"]').click();assert.equal(await p.evaluate(()=>barGame.progress.money),200);assert.equal(await p.evaluate(()=>barGame.dailySettlement.status),'paid');await p.screenshot({path:'/private/tmp/bar-upkeep-paid.png'});assert.equal(await p.locator('[data-act="confirmSettlement"]').count(),0);
 await p.locator('[data-act="setup"]').click();await p.locator('#upkeep-test').fill('301');await p.locator('[data-act="start"]').click();await p.locator('[data-act="confirmSettlement"]').click();assert.equal(await p.evaluate(()=>barGame.screen),'gameover');assert.equal(await p.evaluate(()=>barGame.progress.money),300);assert.equal(await p.evaluate(()=>barGame.dailySettlement.shortfall),1);await p.screenshot({path:'/private/tmp/bar-upkeep-gameover.png'});await p.keyboard.press('KeyP');assert.equal(await p.evaluate(()=>barGame.paused),false);await p.locator('[data-act="retryDay"]').click();assert.equal(await p.evaluate(()=>barGame.dailySettlement.status),'pending');
 await p.evaluate(()=>{barGame.reset(99,'practice',1)});await p.keyboard.press('F2');await p.locator('[data-input="upkeep"]').fill('450');await p.locator('[data-act="applyUpkeep"]').click();await p.locator('[data-act="debugEndDay"]').click();assert.equal(await p.evaluate(()=>barGame.dailySettlement.upkeep),450);await p.setViewportSize({width:600,height:800});await p.screenshot({path:'/private/tmp/bar-upkeep-mobile.png'});await p.locator('[data-act="confirmSettlement"]').click();assert.equal(await p.evaluate(()=>barGame.screen),'gameover');await p.locator('[data-act="setup"]').click();await p.locator('#upkeep-test').fill('-5');await p.locator('[data-act="start"]').click();assert.equal(await p.evaluate(()=>barGame.phase),'ready');assert.equal(await p.evaluate(()=>barGame.error),null);assert.deepEqual(errors,[]);console.log('UPKEEP_BROWSER_OK: override input, settlement → payment/game over, retry, F2 early close, mobile, validation.');
 // Double-click entry point must work without a server, including the local Korean font.
 await p.goto(require('url').pathToFileURL(require('path').resolve(__dirname,'../index.html')).href);await p.waitForTimeout(400);assert.equal(await p.evaluate(()=>!!window.barGame),true);await p.evaluate(()=>document.fonts.ready);assert.equal(await p.evaluate(()=>document.fonts.check('16px LunaPixel')),true);console.log('FILE_ENTRY_OK');
 }finally{if(b)await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
