const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
const drain=()=>p.evaluate(()=>{const s=outsidePlaytest.model.story,lines=[];for(let i=0;s.speech&&!s.speech.choice&&i<100;i++){lines.push(s.speech.line.text);s.speech.elapsed=99;s.advance();}outsidePlaytest.tick(0);return lines;});
const click=id=>p.locator('[data-choice="'+id+'"]').click();
for(const [main,day,money,accept] of [[true,1,300,true],[true,2,0,true],[false,2,300,false],[false,2,301,false],[true,3,300,false]]){
await p.evaluate(async({main,day,money})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main});barGame.reset(day,'full',10,false);Object.assign(barGame.progress,{money,inventory:{},flags:{}});c.session.day=day;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day,flow:'out',place:'bar'});await outsidePlaytest.start();c.screen(c.playView);const m=outsidePlaytest.model;m.x=-2.87;m.updateNear();outsidePlaytest.snapCamera();outsidePlaytest.tick(0);},{main,day,money});
await p.keyboard.press('KeyE');const lines=await drain(),eligible=day<3&&money<=300;assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.line.stage),eligible?'allowance':'items');assert.equal(lines.includes('뭐야, 너 돈 없어?'),eligible);assert.equal(await p.evaluate(()=>barGame.progress.money),money);
if(eligible){assert.equal(await p.locator('.outside-choices button').count(),2);assert.equal(await p.locator('.outside-speech strong').count(),0);await click(accept?'shop-allowance-yes':'shop-allowance-no');if(accept){assert.equal(await p.evaluate(()=>barGame.progress.money),money,'Wait for Luna to shout');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.line.text),'박용석 바보!');await p.evaluate(()=>{const s=outsidePlaytest.model.story;s.speech.elapsed=99;s.advance();outsidePlaytest.tick(0);});assert.equal(await p.evaluate(()=>barGame.progress.money),money+500);assert.equal(await p.evaluate(()=>LunaOutsideShop.grantAllowance(outsidePlaytest.model)),false);await p.waitForTimeout(180);assert.equal(await p.locator('.outside-notices .currency-delta').innerText(),'+500');assert.equal(await p.evaluate(()=>lunaCampaign.session.carry.money),money+500);if(day===1)await p.screenshot({path:'/private/tmp/shiba-allowance.png'});}await drain();assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.line.stage),'items');assert.equal(await p.evaluate(()=>barGame.progress.money),money+(accept?500:0));}
assert.equal(await p.locator('[data-choice^="shop-buy-"]').count(),2);await click('shop-no');await drain();
// A new visit at low balance offers it again; aborting before the grant gives nothing.
if(eligible){await p.evaluate(()=>{barGame.progress.money=300;outsidePlaytest.tick(0);});await p.keyboard.press('KeyE');await drain();await click('shop-yes');await drain();assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.line.stage),'allowance');await click('shop-allowance-yes');await p.evaluate(()=>outsidePlaytest.model.story.cancel());assert.equal(await p.evaluate(()=>barGame.progress.money),300);}
console.log('PASS',main?'main':'developer',day,money,accept);}
await p.evaluate(async()=>{lunaCampaign.toPicker();lunaCampaign.developer();Object.assign(outsidePlaytest.config,{day:99,flow:'out',place:'bar',qaCase:'shop:allowance'});await outsidePlaytest.start();const m=outsidePlaytest.model;m.x=0;m.updateNear();m.interact();outsidePlaytest.snapCamera();outsidePlaytest.tick(0);});if(await p.locator('.updates-confirm').isVisible())await p.locator('.updates-confirm').click();const before=await p.evaluate(()=>JSON.stringify(barGame.progress));await drain();await click('shop-allowance-yes');await drain();assert.equal(await p.evaluate(()=>outsidePlaytest.model.qa.shopProgress.money),800);assert.equal(await p.evaluate(()=>JSON.stringify(barGame.progress)),before);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.line.stage),'items');assert.deepEqual(errors,[]);console.log('SHIBA_ALLOWANCE_OK boundary/day conditions, accept/refuse, timed single payment, return to stock, repeat visit, cancel, money HUD, QA isolation');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
