const assert=require('assert/strict'),M=require(process.env.LUNA_MISSING_MODULE||'../resource-missing.js');
const row=(id,group,status,layers=[],extra={})=>({id,group,status,layers,title:id,usage:'test',...extra}),real={key:'item_gin',source:'6. 칵테일-재료/진.png',src:'gin.png'},dummy={key:'item_dummy',source:'0. 더미(임시)/공용.png',src:'dummy.png'};
const samples=[row('item:gin:recipe','bar-items','shared',[real]),row('item:gin:inventory','bar-items','shared',[real]),row('item:milk:shelf','bar-items','shared',[dummy],{key:'item_dummy'}),row('item:milk:recipe','bar-items','shared',[dummy],{key:'item_dummy'}),row('item:milk:inventory','bar-items','shared',[dummy],{key:'item_dummy'}),row('outside-role:thug','out-characters','dummy',[{key:'ambient-M2'}]),row('bg:residence','out-backgrounds','registered',[{key:'residence-building',source:'User supplied residential building layers'}]),row('ui:choices','bar-ui','code'),row('fx:camera','bar-fx','code'),row('fx:placeholder','bar-fx','dummy'),row('bg:cinema-stage3','out-backgrounds','dummy'),row('ui-art:choice','bar-ui','dummy',[{key:'choice',source:'더미 UI'}]),row('drink:good:recipe','bar-drinks','shared',[real]),row('serve:good','bar-serve','shared',[real]),row('drink:missing:hero','bar-drinks','shared',[real],{key:'item_cocktail'}),row('actor:missing','bar-characters','missing')];
samples.push(row('actor:tom:idle','bar-characters','dummy'),row('actor:shiba:idle','bar-characters','dummy'));
const gaps=M.build(samples);assert.equal(gaps.length,8);assert.equal(gaps.find(e=>e.id==='item:item:milk').rows.length,3);assert.equal(gaps.find(e=>e.id==='item:item:milk').reasons[0],'sharedDummy');assert.equal(gaps.find(e=>e.id==='cocktail:cocktail:good').reasons[0],'animation');assert.deepEqual(new Set(gaps.map(e=>e.category)),new Set(M.categories.map(c=>c[0])));
const pending=M.build([row('ui:recipes','bar-ui','missing',[],{uiArtPending:true,preview:'screenshot.jpg'}),row('ui:choices','bar-ui','code')]);
assert.equal(M.reason(row('serve:absent','bar-serve','missing',[real])),'animation');
assert.equal(pending.length,1);assert.equal(pending[0].category,'ui');assert.deepEqual(pending[0].reasons,['uiArt']);
for(const id of ['item:gin:recipe','item:gin:inventory','bg:residence','ui:choices','fx:camera','drink:good:recipe'])assert(!gaps.some(e=>e.rows.some(x=>x.row.id===id)),id);
const passers=['M1','M2','W1'].map(kind=>row('outside:'+kind,'out-characters','dummy',[{key:'ambient-'+kind}]));
for(const [id,title] of [['store-pair-left','행인 1'],['bar-pair-right','행인 2'],['commute-pair-left','행인'],['reopening-pair-right','행인']])passers.push(row('outside-role:'+id,'out-characters','dummy',[{key:'ambient-M1'}],{title}));
assert.equal(M.build(passers).length,0);
assert.equal(M.build([...samples,...passers]).length,8);
for(const [id,title] of [['bd-vendor','BD 칩 판매상'],['thug','복도 불량배'],['resident-left','빌딩 주민 1'],['trade-smuggler','밀수업자']])assert.equal(M.build([row('outside-role:'+id,'out-characters','dummy',[{key:'ambient-M1'}],{title})]).length,0);
assert.deepEqual(gaps.filter(e=>e.category==='character').map(e=>e.id).sort(),['character:actor:shiba','character:actor:tom']);
const terrace=M.build([row('outside:terrace-chris','out-characters','missing'),row('actor:chris:idle','bar-characters','dummy'),row('outside:terrace','out-characters','shared')]);
assert.equal(terrace.length,1);assert.equal(terrace[0].id,'character:outside:terrace-chris');assert.equal(terrace[0].area,'외부');
console.log('RESOURCE_MISSING_UNIT_OK Tom, Shiba and terrace Chris only; other categories and grouping preserved');
