const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 await p.evaluate(()=>{const g=barGame;g.reset(3,'regular',11,true);for(let i=0;i<10000;i++){g.cameraMoving=false;if(g.transition||g.cameraLeft){g.tick(.1);continue;}if(g.dialogue){g.advance();g.advance();continue;}if(g.currentOrder&&g.story.steps[g.story.index].type==='craft')break;g.tick(.1);}g.openRecipes();g.selectCocktail('johnny_old_fashioned');lunaCampaign.ui.tab='liquor';lunaCampaign.render(true);});
 for(const id of ['wild_dog','bitters','sugar_cube']){let found=false;for(let page=0;page<4;page++){await p.evaluate(page=>{lunaCampaign.ui.tab='liquor';lunaCampaign.ui.shelfPage=page;lunaCampaign.render(true);},page);const el=p.locator('.shelf-item[data-id="'+id+'"]');if(await el.count()){await p.waitForTimeout(500);await el.click();found=true;break;}}assert(found,'shelf '+id);assert.equal(await p.locator('[data-required-item="'+id+'"]').getAttribute('data-packed'),'true');}
 await p.evaluate(()=>{barGame.pickItem('old_fashioned');barGame.pickItem('mixing_glass');lunaCampaign.render(true);});await p.screenshot({path:'/private/tmp/day3-recipe-prep.png'});
 const queue=await p.evaluate(()=>{const g=barGame;g.startCraft();const q=structuredClone(g.craft.queue);g.craft.index=2;g.nextGimmick();return{q,now:g.gimmick.type,add:g.craft.results.at(-1)};});assert.deepEqual(queue.q.map(r=>r.type),['pour','pour','add','stir']);assert.equal(queue.now,'stir');assert.equal(queue.add.ingredient,'sugar_cube');assert.equal(queue.add.value,1);
 for(const activation of ['source','manual','proximity']){await p.evaluate(async activation=>{lunaCampaign.toPicker();lunaCampaign.developer();Object.assign(outsidePlaytest.config,{day:99,flow:'in',place:'bar',qaCase:'runtime:commute3',qaActivation:activation});await outsidePlaytest.start();const m=outsidePlaytest.model;m.x=0;m.updateNear();outsidePlaytest.snapCamera();if(activation==='manual')m.interact();outsidePlaytest.tick(.05);},activation);await p.waitForTimeout(2000);await p.waitForFunction(()=>outsidePlaytest.model.story.speech?.line?.text==='어, 루나. 출근해?',{},{timeout:5000});assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.rows.length),7);await p.evaluate(()=>{const s=outsidePlaytest.model.story;for(let i=0;i<15&&s.speech;i++){s.speech.elapsed=99;s.advance();}});await p.waitForFunction(()=>outsidePlaytest.model.qa.done);}
 await p.goto('http://127.0.0.1:8123/bar-playtest/story-guide.html#day-3');await p.locator('#event-detail').waitFor();assert.equal(await p.locator('[data-event]').count(),6);await p.locator('.dialogue-reader summary').click();for(const key of ['opening','bar','commute3','ending','terraceMemory3']){await p.selectOption('#script-section',key);assert(await p.locator('#dialogue-lines p').count()>0,key);}assert.deepEqual(errors,[]);console.log('DAY3_RECIPE_QA_GUIDE_OK real shelf clicks + checkbox + no sugar pour minigame; QA source/manual/proximity; all guide day3 sections');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
