const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
for(const day of [0,1,2,3,99]){
 const layouts=await p.evaluate(day=>{const g=barGame;g.reset(day,'regular',1,false);g.phase='regular';g.screen='bar';g.paused=true;g.focus='R';const out=[];for(const seats of [{L:{id:'port',actor:'port',state:'STORY'},M:null,R:null},{L:null,M:null,R:{id:'chris',actor:'chris',state:'STORY'}},{L:{id:'aili',actor:'aili',state:'STORY'},M:null,R:{id:'chris',actor:'chris',state:'STORY'}},{L:null,M:null,R:null}]){g.seats=seats;lunaCampaign.render(true);out.push(document.querySelector('.counter-plane').dataset.cameraKey);}return out;},day);
 assert.deepEqual(layouts.map(k=>+k.split(':')[0]),[960,960,1280,960]);assert.equal(layouts[0].split(':')[1],'270');assert.equal(layouts[1].split(':')[1],'810');assert.equal(layouts[2].split(':')[1],'380');assert.equal(layouts[3],layouts[1],'empty stage keeps the focused seat rather than recentering');
}
await p.evaluate(()=>{const g=barGame;g.reset(1,'regular',1,false);g.phase='regular';g.screen='bar';g.paused=true;g.seats={L:null,M:null,R:{id:'chris',actor:'chris',state:'STORY'}};lunaCampaign.render(true);});await p.waitForTimeout(1100);
for(const two of [true,false]){
 const frames=await p.evaluate(async two=>{const plane=document.querySelector('.counter-plane');barGame.seats.L=two?{id:'aili',actor:'aili',state:'STORY'}:null;lunaCampaign.render(true);const scales=[];for(let i=0;i<65;i++){await new Promise(requestAnimationFrame);scales.push(new DOMMatrixReadOnly(getComputedStyle(plane).transform).a);}return {scales,same:plane===document.querySelector('.counter-plane'),duration:getComputedStyle(plane).transitionDuration,width:document.querySelector('.bar-stage').dataset.cameraWidth};},two);
 assert(frames.same);assert.equal(frames.duration,'0.95s');assert.equal(frames.width,two?'1280':'960');assert(frames.scales.some(s=>s>1.01&&s<1.32));for(let i=1;i<frames.scales.length;i++)assert((frames.scales[i]-frames.scales[i-1])*(two?-1:1)>=-.001);
 await p.screenshot({path:'/private/tmp/regular-camera-'+(two?'two':'one')+'.png'});
}
assert.deepEqual(errors,[]);console.log('REGULAR_CAMERA_OK days0/1/2/3/QA: one=960 focused, two=1280 centered, empty holds focus; real .95s easing both ways, same DOM');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
