const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1600,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/resource-review.html');await p.waitForFunction(()=>resourceReview.ready);const f=()=>p.frames().find(f=>f.url().includes('resourceReview=1'));
async function run(type,id){await p.evaluate(({type,id})=>resourceReview.launch({type,id},type+' '+(id||'')),{type,id});await p.waitForTimeout(350);assert(!await p.locator('#lab-note').evaluate(e=>e.classList.contains('error')));}
await run('choices');await f().locator('.choices').waitFor({state:'visible'});await run('tutorial');assert.equal(await f().evaluate(()=>barGame.day),0);assert(await f().evaluate(()=>!!barGame.story));
await run('exterior','settings');assert(await f().locator('.outside-dialog').isVisible());assert(await f().evaluate(()=>outsidePlaytest.model.paused));
await run('exterior','console');assert(await f().evaluate(()=>outsidePlaytest.devConsoleOpen));
await run('exterior','poor');console.log('POOR',await f().evaluate(()=>({line:outsidePlaytest.model.story.speech?.line,choice:outsidePlaytest.model.story.speech?.choice})));assert.equal(await f().locator('[data-choice^="shop-buy-"]:disabled').count(),2);
await run('exterior','panorama');assert(await f().locator('.outside-viewpoint').isVisible());await f().locator('.outside-viewpoint').click();await p.waitForTimeout(1000);assert(await f().evaluate(()=>outsidePlaytest.camera.w>5));
await run('exterior','purchase');assert(await f().locator('.outside-item-notice').isVisible());assert(await f().locator('.currency-spending').isVisible());
await run('updates');assert(await f().locator('#luna-updates').isVisible());await f().locator('.updates-confirm').click();
await run('prep','milk');await p.waitForTimeout(800);assert(await f().locator('[data-current="true"] [data-hover-item="milk"]').isVisible());await f().locator('[data-current="true"] [data-hover-item="milk"]').hover();await p.screenshot({path:'/private/tmp/resource-review-prep.png'});
await run('serve','gin_tonic');await p.waitForTimeout(1800);assert(await f().locator('[data-act="offer"]').isEnabled());await f().locator('[data-act="serveDetails"]').click();assert(await f().locator('.serve-score-detail').isVisible());
await p.evaluate(()=>resourceReview.close());await p.click('[data-group="bar-items"]');await p.selectOption('#status','attention');assert(await p.locator('.card').count()>0);await p.fill('#search','우유');assert.equal(await p.locator('.card').count(),3);await p.locator('[data-id="item:milk:shelf"]').click();assert((await p.locator('#inspector').innerText()).includes('item_dummy'));await p.screenshot({path:'/private/tmp/resource-review-missing.png'});
const bottle=await p.locator('#preview-canvas').boundingBox(),preview=await p.locator('.preview').boundingBox();assert(bottle.height<=preview.height+.1&&bottle.width<=preview.width+.1,'Tall bottles must fit the preview, not overlap controls');
await p.evaluate(()=>resourceReview.select('actor:chris:Chris_idle_talk'));await p.waitForTimeout(100);await p.click('[data-action="next"]');const before=await p.locator('#frame-slider').inputValue();await p.waitForTimeout(300);assert.equal(await p.locator('#frame-slider').inputValue(),before);assert(await p.locator('[data-layer]').count()>1);await p.locator('[data-layer]').first().uncheck();await p.click('[data-action="play"]');await p.waitForTimeout(100);assert(await p.locator('#preview-canvas').evaluate(c=>c.width===551));
const download=p.waitForEvent('download');await p.click('#export');assert.equal((await download).suggestedFilename(),'unknown-resource-review.csv');assert.deepEqual(errors,[]);console.log('INTERACTIVE_OK choices, tutorial, outside settings/console, disabled purchase, Y overview, notices, updates, shelf hover, serving/detail, filters, frame/layers, export');
await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');assert(await p.locator('a[href="resource-review.html"]').isVisible());console.log('TAB_OK');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
