const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 for(const [main,version]of [[true,'A'],[true,'B'],[false,'A']]){
  await p.evaluate(async({main,version})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main,serviceVersion:version});barGame.reset(1,'full',10,false,{serviceVersion:version});barGame.progress.money=2300;c.session.day=1;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:1,flow:'out',place:'home',variant:'original'});await outsidePlaytest.start({wakeAtSofa:true});c.screen(c.playView);},{main,version});await p.keyboard.press('KeyE');if(main)await p.locator('[data-campaign="sleep-confirm"]').click();assert.equal(await p.evaluate(()=>lunaCampaign.dialog.background),'black');assert.equal(await p.locator('.campaign-speech strong').innerText(),'포트');
  const workshop=await p.evaluate(()=>{const c=lunaCampaign,seen=[];while(c.view==='scene'&&c.dialog.background==='black'){seen.push(c.dialog.rows[c.dialog.index].text);c.dialog.chars=1e5;c.next();}return seen;});assert.equal(workshop.length,12);await p.waitForFunction(()=>!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.background),'terrace');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows.length),19);assert.equal(await p.locator('.terrace-speech strong').count(),0);
  await p.evaluate(()=>{const c=lunaCampaign;while(c.dialog.index<11){c.dialog.chars=1e5;c.next();}c.dialog.chars=c.dialog.rows[11].text.indexOf('와일드 독')+2;c.paintLine();});assert.equal(await p.locator('.campaign-ink .terrace-ingredient').textContent(),'와일');
  await p.evaluate(()=>{lunaCampaign.dialog.chars=1e5;lunaCampaign.paintLine();});assert.deepEqual(await p.locator('.campaign-ink .terrace-ingredient').allTextContents(),['와일드 독','비터스','각설탕']);assert.equal(await p.locator('.campaign-ink .terrace-ingredient').first().evaluate(el=>getComputedStyle(el).color),'rgb(255, 173, 104)');assert(!/[\[\]\\]/.test(await p.locator('.campaign-ink').textContent()));assert(!(await p.locator('.terrace-speech').innerText()).includes('대괄호'));if(main&&version==='A')await p.screenshot({path:'/private/tmp/day1-terrace-orange.png'});
  await p.keyboard.press('Escape');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),11);assert.equal(await p.locator('.campaign-ink .terrace-ingredient').count(),3);
  await p.evaluate(()=>{const c=lunaCampaign;while(c.view==='scene'&&!c.dayTransition){c.dialog.chars=1e5;c.next();}});await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading&&!lunaCampaign.dayTransition&&['game','developer'].includes(lunaCampaign.view)&&outsidePlaytest.model.config.day===2,null,{timeout:20000});assert.equal(await p.evaluate(()=>outsidePlaytest.model.near.id),'sofa');assert.equal(await p.evaluate(()=>barGame.progress.money),2300);assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.flow),'in');
 }
 assert(await p.evaluate(()=>LunaOutsideQA.catalog().some(c=>c.id==='runtime:night1')));assert.deepEqual(errors,[]);console.log('DAY1_TERRACE_UI_OK A/B + external day test: workshop12 -> terrace19 -> Day2 sofa; orange names/no brackets; partial typing, ESC resume, money preservation, QA catalog');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
