const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
// Every day and route shares the left doorway, including re-entry/exit transitions.
const doors=await p.evaluate(()=>{const results=[];for(let day=0;day<4;day++)for(const flow of ['in','out']){const m=new LunaOutside.Model({day,flow,place:'homeDoor'});results.push(m.x);m.x=-14.62;m.updateNear();if(m.near?.id==='home')throw Error('right door still interactable');m.x=LunaResidence.layout.homeX;m.updateNear();if(m.near?.id!=='home')throw Error('left door not interactable');m.interact();for(let i=0;i<20;i++)m.tick(.05);if(m.scene!=='home')throw Error('entry failed');m.interact();for(let i=0;i<20;i++)m.tick(.05);results.push(m.x);}return results;});assert(doors.every(x=>x===-16.36));
await p.evaluate(async()=>{const c=lunaCampaign;c.session.install({developer:true});Object.assign(outsidePlaytest.config,{day:1,flow:'in',place:'homeDoor',variant:'original'});await outsidePlaytest.start();c.screen('developer');});await p.screenshot({path:'/private/tmp/home-left-door.png'});await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.encounter?.kind==='thug');await p.keyboard.up('KeyD');await p.waitForFunction(()=>!!outsidePlaytest.model.story.speech);await p.screenshot({path:'/private/tmp/thug-facing-luna.png'});
const flips=await p.evaluate(()=>{const m=outsidePlaytest.model,ctx=document.querySelector('#outside-root canvas').getContext('2d'),position=(x,y)=>({x,y}),out=[];for(const side of [-1,1]){m.x=m.encounter.npcX+side*.5;LunaOutsideThug.draw(m,(...args)=>out.push(args[5]),ctx,position);}m.encounter.stage='depart';LunaOutsideThug.draw(m,(...args)=>out.push(args[5]),ctx,position);return out;});assert.deepEqual(flips,[false,true,true]);
// Inspect the actual canvas transform used by Samho's draw call from both sides.
for(const day of [2,3]){await p.evaluate(async day=>{const a=outsidePlaytest;a.exit(true);Object.assign(a.config,{day,flow:'in',place:'bar'});await a.start();lunaCampaign.screen('developer');},day);const signs=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,c=document.querySelector('#outside-root canvas').getContext('2d'),original=c.drawImage,out=[];c.drawImage=function(im,...args){if(im.src.includes('outside_4bdaf8a66fd58d'))out.push(Math.sign(this.getTransform().a));return original.call(this,im,...args);};try{for(const x of [-6.5,-5.4]){m.x=x;m.notionCommuteSeen=true;a.snapCamera();a.tick(0);}}finally{c.drawImage=original;}return out;});assert.deepEqual(signs,[1,-1]);await p.evaluate(()=>{outsidePlaytest.model.x=-6.5;outsidePlaytest.snapCamera();outsidePlaytest.tick(0);lunaCampaign.previewCommute(outsidePlaytest.model);});await p.screenshot({path:'/private/tmp/samho-facing-luna-day'+day+'.png'});await p.evaluate(()=>lunaCampaign.screen('developer'));}
assert.deepEqual(errors,[]);console.log('HOME_FACING_OK all 0-3 day/route entry+exit at left door only; thug faces Luna both sides and forward on departure; Samho day2/3 actual canvas direction');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
