const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
for(const seat of ['L','M','R']){
 await p.evaluate(seat=>{const g=barGame;g.reset(1,'general',1,true,{variant:'original'});g.queueIndex=g.queue.length;g.focus=seat;g.seats={L:null,M:null,R:null};g.seats[seat]={id:'test',actor:'gentle',state:'EXITING',exitLeft:999,lines:[],appearance:null};lunaCampaign.render(true);g.paused=true;},seat);await p.waitForTimeout(650);
 const frames=await p.evaluate(async()=>{const g=barGame,plane=document.querySelector('.counter-plane'),before=new DOMMatrixReadOnly(getComputedStyle(plane).transform);g.seats={L:null,M:null,R:null};g.finishGeneralService();lunaCampaign.render(true);const frames=[];for(let i=0;i<65;i++){await new Promise(requestAnimationFrame);const m=new DOMMatrixReadOnly(getComputedStyle(plane).transform);frames.push([m.a,m.e]);}return{before:[before.a,before.e],frames,same:plane===document.querySelector('.counter-plane'),width:document.querySelector('.bar-stage').dataset.cameraWidth,duration:getComputedStyle(plane).transitionDuration};});
 assert(frames.same);assert.equal(frames.width,'1280');assert.equal(frames.duration,'0.95s');assert(frames.frames.some(f=>f[0]>1.01&&f[0]<1.32));for(let i=1;i<frames.frames.length;i++){assert(frames.frames[i][0]<=frames.frames[i-1][0]+.001);const dir=Math.sign(-380-frames.before[1]);assert((frames.frames[i][1]-frames.frames[i-1][1])*dir>=-.01);}
}
await p.evaluate(()=>barGame.paused=false);
for(const day of [1,2,3]){
 const keys=await p.evaluate(day=>{const g=barGame;g.reset(day,'regular',1,false);g.phase='regular';g.screen='bar';g.paused=true;const keys=[];for(const seats of [{L:{id:'port',actor:'port',state:'STORY'},M:null,R:null},{L:null,M:null,R:null},{L:null,M:null,R:{id:'chris',actor:'chris',state:'STORY'}},{L:{id:'aili',actor:'aili',state:'STORY'},M:null,R:{id:'chris',actor:'chris',state:'STORY'}}]){g.seats=seats;lunaCampaign.render(true);keys.push(document.querySelector('.counter-plane').dataset.cameraKey);}return keys;},day);assert.equal(new Set(keys).size,1);
}
await p.evaluate(()=>{barGame.paused=false;lunaCampaign.render(true);});await p.waitForTimeout(1050);await p.screenshot({path:'/private/tmp/regular-stable-camera.png'});
await p.evaluate(()=>{const g=barGame;g.reset(0,'regular',1,false);g.phase='regular';g.seats={L:null,M:null,R:{id:'chris',actor:'chris',state:'STORY'}};g.paused=true;lunaCampaign.render(true);});assert.equal(await p.locator('.bar-stage').getAttribute('data-camera-width'),'960');assert.deepEqual(errors,[]);console.log('REGULAR_CAMERA_OK L/M/R continuous one-way .95s handoff, persistent DOM, day1–3 fixed frame across empty/one/two guests, day0 framing preserved');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
