const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/');await p.locator('[data-campaign="title"]').click();await p.locator('[data-campaign="new"]').click();
assert.equal(await p.locator('.campaign-day').count(),4);assert.equal(await p.evaluate(()=>document.activeElement.dataset.campaign),'start-day:0');await p.keyboard.press('ArrowRight');assert.equal(await p.evaluate(()=>document.activeElement.dataset.campaign),'start-day:1');await p.keyboard.press('ArrowDown');assert.equal(await p.evaluate(()=>document.activeElement.dataset.campaign),'start-day:3');await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.view),'title');await p.locator('[data-campaign="new"]').click();await p.screenshot({path:'/private/tmp/campaign-start-day-picker.png'});
for(const day of [1,2,3,1]){
 await p.locator('[data-campaign="start-day:'+day+'"]').click();await p.waitForFunction(()=>lunaCampaign.view==='game'&&outsidePlaytest.active&&!outsidePlaytest.loading,null,{timeout:60000});
 const state=await p.evaluate(()=>{const c=lunaCampaign,g=barGame,m=outsidePlaytest.model;return{day:c.session.day,gameDay:g.day,scene:m.scene,x:m.x,flow:m.config.flow,outsideDay:m.config.day,route:c.session.route,cinema:c.cinema,completed:c.session.completed,carry:c.session.carry.money,money:g.progress.money,flags:g.progress.flags,dialog:g.dialogue};});
 assert.equal(state.day,day);assert.equal(state.gameDay,day);assert.equal(state.outsideDay,day);assert.equal(state.scene,'home');assert.equal(state.x,2.557);assert.equal(state.flow,'in');assert.equal(state.route,'in');assert.equal(state.cinema,null);assert.equal(state.dialog,null);assert.deepEqual(state.completed,[]);assert.equal(state.money,state.carry);assert.equal(state.flags.leaked,undefined);assert.equal(state.flags.tom_name_known,day>=2?true:undefined);assert.equal(state.flags.campaign_observation,day>=3?true:undefined);
 // Actually leave the home, then exercise the mandatory commute trigger before entering the bar.
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-1.581;m.updateNear();});await p.keyboard.press('KeyE');await p.evaluate(()=>{for(let i=0;i<80;i++)outsidePlaytest.tick(.02);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'street');
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.level=0;m.x=-6.5;m.y=-.7;m.story.cancel();m.backgroundStory.cancel();m.updateNear();lunaCampaign.tick(.01);});
 if(day>=2){assert.equal(await p.evaluate(()=>lunaCampaign.view),'scene');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows[0].text),await p.evaluate(d=>lunaCampaign.data.scenes['commute'+d][0].text,day));await p.evaluate(()=>{let n=0;while(lunaCampaign.view==='scene'&&n++<100){lunaCampaign.dialog.chars=1e6;lunaCampaign.next();}});assert.equal(await p.evaluate(()=>lunaCampaign.session.carry.flags.samho_met),true);}else assert.equal(await p.evaluate(()=>lunaCampaign.view),'game');
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=1.0086;m.updateNear();});await p.keyboard.press('KeyE');await p.waitForFunction(d=>lunaCampaign.view==='game'&&lunaCampaign.session.route==='bar'&&barGame.day===d,day,{timeout:60000});assert.equal(await p.evaluate(()=>outsidePlaytest.active),false);assert.equal(await p.evaluate(()=>barGame.pendingDailyUnlocks),true);await p.evaluate(()=>barGame.confirmDailyUnlocks());assert.equal(await p.evaluate(()=>barGame.phase),'opening');
 await p.evaluate(()=>{barGame.progress.flags.leaked=true;barGame.progress.money=99999;lunaCampaign.toPicker();lunaCampaign.action('title');});await p.locator('[data-campaign="new"]').click();console.log('START_DAY_OK',day,state.money);
}
await p.locator('[data-campaign="start-day:0"]').click();await p.waitForFunction(()=>lunaCampaign.view==='prologue',null,{timeout:60000});assert.equal(await p.evaluate(()=>lunaCampaign.cinema.scenes.length),1);await p.keyboard.down('Space');await p.waitForTimeout(3200);await p.keyboard.up('Space');await p.waitForFunction(()=>lunaCampaign.view==='game',null,{timeout:60000});assert.equal(await p.evaluate(()=>barGame.day),0);assert.equal(await p.evaluate(()=>barGame.progress.flags.leaked),undefined);assert.equal(await p.evaluate(()=>outsidePlaytest.active),false);assert.equal(await p.evaluate(()=>lunaCampaign.session.route),'bar');assert.deepEqual(errors,[]);console.log('START_DAY_UI_OK picker / keyboard / 1–3 morning home + events + unlocks / clean restart / unchanged day 0');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
