const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await p.goto('http://127.0.0.1:8123/bar-playtest/?mode=outside');await p.locator('.updates-confirm').click();await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);
 const before=await p.evaluate(()=>JSON.stringify({progress:barGame.progress,day:barGame.day,phase:barGame.phase}));
 const definitions=await p.evaluate(()=>LunaOutsideEncounters.cases);assert.equal(definitions.filter(c=>c.kind==='pair').length,2);assert.equal(definitions.filter(c=>c.kind==='direct').length,2);
 assert(await p.evaluate(()=>{const m=new LunaOutside.Model();for(let day=0;day<=3;day++)for(const flow of ['in','out'])for(const place of ['bar','homeDoor','home']){m.start({day,flow,place});if(m.targets().filter(t=>t.encounter).length!==(day===0&&flow==='out'&&place==='bar'?4:0))return false;}return true;}));
 for(const c of definitions.filter(c=>c.activation!=='proximity'))for(const member of c.members){await p.evaluate(id=>{const a=outsidePlaytest,m=a.model;m.start({day:0,flow:'out'});const t=m.targets().find(t=>t.actor===id);m.x=t.x+.04;m.updateNear();for(let i=0;i<120;i++)a.tick(.016);},member);assert.equal(await p.locator('.outside-interact').innerText(),'E');assert(!await p.evaluate(()=>!!outsidePlaytest.model.story.speech));await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter.stage),'entering');assert(await p.locator('.outside-speech').isHidden());await p.keyboard.press('KeyE');await p.keyboard.press('Space');await p.keyboard.press('KeyY');assert(!await p.evaluate(()=>!!outsidePlaytest.model.story.speech));
  if(member===c.members[0]){await p.keyboard.press('Escape');const elapsed=await p.evaluate(()=>outsidePlaytest.model.encounter.elapsed);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter.elapsed),elapsed);await p.keyboard.press('Escape');}
  await p.waitForFunction(()=>outsidePlaytest.model.encounter?.stage==='active');const state=await p.evaluate(()=>({x:outsidePlaytest.model.x,to:outsidePlaytest.model.encounter.to,id:outsidePlaytest.model.story.speech.id,w:outsidePlaytest.camera.w,target:outsidePlaytest.model.encounter.camera.w}));assert.equal(state.id,c.id);assert.equal(state.x,state.to);assert(Math.abs(state.w-state.target)<.015);assert(await p.locator('.outside-speech').isVisible());await p.keyboard.down('KeyA');await p.waitForTimeout(60);await p.keyboard.up('KeyA');assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),state.x);
  const seen=[];for(let i=0;i<c.lines.length;i++){await p.keyboard.press('KeyE');const v=await p.evaluate(()=>({actor:outsidePlaytest.model.story.speech.line.actor,view:outsidePlaytest.model.story.view(),x:outsidePlaytest.model.x}));assert.equal(v.actor,c.lines[i][0]);assert.equal(v.view.full,c.lines[i][1]);seen.push(v.actor);if(v.actor==='luna')assert.equal(v.view.anchor.x,v.x);else assert.equal(v.view.anchor.x,await p.evaluate(id=>LunaOutsideEncounters.actor(id).x,v.actor));if(i===1&&member===c.members[0])await p.screenshot({path:'/private/tmp/'+c.id+'.jpg',type:'jpeg',quality:85});await p.keyboard.press('KeyE');}
  if(c.kind==='pair')assert(!seen.includes('luna'));else assert(seen.includes('luna'));await p.waitForFunction(()=>outsidePlaytest.model.encounter?.stage==='leaving');assert(await p.locator('.outside-speech').isHidden());await p.keyboard.press('KeyE');assert(!await p.evaluate(()=>!!outsidePlaytest.model.story.speech));await p.waitForFunction(()=>!outsidePlaytest.model.encounter);assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),state.x);assert(Math.abs(await p.evaluate(()=>outsidePlaytest.camera.w)-4.8)<.02);await p.keyboard.down('KeyD');await p.waitForTimeout(80);await p.keyboard.up('KeyD');assert(await p.evaluate(x=>outsidePlaytest.model.x>x,state.x));
 }
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.start({day:0,flow:'out'});m.x=LunaResidence.layout.elevatorX;m.updateNear();});await p.keyboard.press('KeyE');await p.waitForTimeout(150);assert(await p.evaluate(()=>!!outsidePlaytest.model.ride));assert.equal(await p.locator('.outside-elevator-status,.outside-lift-progress').count(),0);assert(!(await p.locator('#outside-root').innerText()).match(/올라가는 중|내려가는 중|엘리베이터를 부르는 중/));assert.deepEqual(errors,[]);assert.equal(await p.evaluate(()=>JSON.stringify({progress:barGame.progress,day:barGame.day,phase:barGame.phase})),before);console.log('PASS 3 manual cases/4 entry points, gates, no auto-start, transition input guard, pause, zoom/position completion, alternating speakers, return control, no lift HUD, bar isolation');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
