const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
for(const main of [false,true]){
 await p.evaluate(main=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main});c.session.day=3;c.session.route='bar';barGame.reset(3,'regular',11,true,{storyPrerequisites:true});c.screen(c.playView);for(let i=0;i<1000&&barGame.overlay!=='johnnyUnlock';i++){barGame.cameraMoving=false;if(barGame.transition||barGame.cameraLeft){barGame.tick(.1);continue;}if(barGame.dialogue){barGame.advance();barGame.advance();}else barGame.tick(.1);}c.render(true);},main);
 await p.locator('.johnny-unlock').waitFor();assert.equal(await p.locator('.johnny-unlock [data-unlock-id]').count(),3);await p.waitForFunction(()=>[...document.querySelectorAll('.johnny-unlock img')].every(i=>i.complete&&i.naturalWidth));await p.keyboard.press('Escape');assert(await p.locator('.johnny-unlock').isVisible());await p.keyboard.press('Tab');assert.equal(await p.evaluate(()=>document.activeElement.dataset.act),'confirmJohnnyUnlock');await p.waitForTimeout(400);assert.equal(await p.locator('.johnny-unlock').evaluate(el=>getComputedStyle(el).opacity),'1');if(main)await p.screenshot({path:'/private/tmp/johnny-unlock-popup.png'});await p.locator('[data-act="confirmJohnnyUnlock"]').click();assert.equal(await p.evaluate(()=>barGame.overlay),null);
 await p.evaluate(()=>{const g=barGame;for(let i=0;i<10000;i++){g.cameraMoving=false;if(g.transition||g.cameraLeft){g.tick(.1);continue;}if(g.dialogue){g.advance();g.advance();continue;}if(g.currentOrder&&g.story.steps[g.story.index].type==='craft')break;g.tick(.1);}g.openRecipes();lunaCampaign.render(true);});await p.locator('.recipe-card[data-id="johnny_old_fashioned"]').click();await p.evaluate(()=>{lunaCampaign.ui.tab='liquor';lunaCampaign.render(true);});await p.waitForTimeout(600);
 const shelf=await p.evaluate(()=>[...document.querySelectorAll('.shelf-scene[data-category="liquor"] .shelf-item')].map(e=>({id:e.dataset.id,y:Number(e.dataset.baseline),x:e.getBoundingClientRect().x})));const cube=shelf.find(i=>i.id==='sugar_cube');assert(cube);assert.equal(cube.x,Math.max(...shelf.filter(i=>i.y===cube.y).map(i=>i.x)));
 for(const id of ['wild_dog','bitters','sugar_cube'])await p.locator('.shelf-item[data-id="'+id+'"]').click();await p.evaluate(()=>{barGame.pickItem('old_fashioned');barGame.pickItem('mixing_glass');lunaCampaign.render(true);});if(main)await p.screenshot({path:'/private/tmp/johnny-unlock-shelf.png'});
 assert.deepEqual(await p.evaluate(()=>barGame.prep.ingredients),['wild_dog','bitters','sugar_cube']);const crafted=await p.evaluate(()=>{const g=barGame;g.startCraft();const queue=g.craft.queue.map(r=>[r.type,r.ingredient,r.target]);g.craft.index=2;g.nextGimmick();return{queue,current:g.gimmick.type,result:g.craft.results.at(-1)};});assert.deepEqual(crafted.queue.slice(0,3),[['pour','wild_dog',45],['pour','bitters',5],['add','sugar_cube',1]]);assert.equal(crafted.current,'stir');assert.equal(crafted.result.value,1);
}
for(const main of [false,true]){
 await p.evaluate(async main=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main});barGame.reset(2,'full',1,false);barGame.progress.inventory={wild_dog:1};c.session.day=2;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:2,flow:'out',place:'bar'});await outsidePlaytest.start();c.screen(c.playView);const m=outsidePlaytest.model;m.x=LunaResidence.layout.elevatorX;m.elevatorY=LunaResidence.layout.elevatorBottom;m.updateNear();outsidePlaytest.snapCamera();outsidePlaytest.tick(0);},main);
 await p.keyboard.press('KeyE');await p.waitForFunction(()=>lunaCampaign.view==='notice');assert((await p.locator('#campaign-root').innerText()).includes('비터스'));assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.day),2);assert.equal(await p.evaluate(()=>outsidePlaytest.active),true);if(main)await p.screenshot({path:'/private/tmp/johnny-lift-required.png'});await p.locator('[data-campaign="resume"]').click();assert.equal(await p.evaluate(()=>lunaCampaign.view),main?'game':'developer');assert.equal(await p.evaluate(()=>outsidePlaytest.model.paused),false);
 const cases=await p.evaluate(()=>{const c=lunaCampaign,a=outsidePlaytest,m=a.model,r=LunaResidence.layout,rows=[];for(const spec of [{name:'missing-both',day:2,flow:'out',level:0,inv:{}},{name:'missing-wild-dog',day:2,flow:'out',level:0,inv:{bitters:1}},{name:'ready-without-memory',day:2,flow:'out',level:0,inv:{wild_dog:1,bitters:1}},{name:'commute-in',day:2,flow:'in',level:0,inv:{}},{name:'downward',day:2,flow:'out',level:1,inv:{}},{name:'call-lift',day:2,flow:'out',level:0,call:true,inv:{}},{name:'day0',day:0,flow:'out',level:0,inv:{}},{name:'day1',day:1,flow:'out',level:0,inv:{}},{name:'day3',day:3,flow:'out',level:0,inv:{}}]){c.screen(c.playView);barGame.progress.inventory=spec.inv;delete barGame.progress.flags.campaign_observation;m.start({day:spec.day,flow:spec.flow,place:'bar'});m.scene='street';m.level=spec.level;m.y=spec.level?r.upperY:-.7;m.x=r.elevatorX;m.elevatorY=spec.level||spec.call?r.elevatorTop:r.elevatorBottom;m.notionCommuteSeen=true;m.updateNear();m.interact();rows.push({name:spec.name,notice:c.view==='notice',ride:!!m.ride,call:!!m.ride?.call,text:c.view==='notice'?c.noticeText:''});}return rows;});
 for(const row of cases){const blocked=row.name.startsWith('missing-');assert.equal(row.notice,blocked,row.name);assert.equal(row.ride,!blocked,row.name);if(row.name==='call-lift')assert(row.call);if(row.name==='missing-wild-dog'){assert(row.text.includes('와일드 독'));assert(!row.text.includes('비터스'));}}

}
assert.deepEqual(errors,[]);console.log('JOHNNY_UNLOCK_UI_OK main + developer popup, keyboard trap, shelf end, real item selection, sugar auto-add, blocked homeward lift and safe return');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
