const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
for(const size of [{width:1280,height:720},{width:960,height:540}]){await p.setViewportSize(size);await p.waitForTimeout(150);for(const id of ['gin_tonic','long_island','kahlua_milk']){
 await p.evaluate(id=>{const g=barGame;g.reset(99,'practice',1,true,{variant:'original'});g.selectCocktail(id);g.debugFill();},id);await p.locator('.prep-recipe-brief').waitFor({state:'visible'});await p.waitForFunction(id=>document.querySelector('.prep-brief-heading strong')?.textContent===barGame.name(id),id);await p.waitForTimeout(250);const texts=await p.locator('.prep-brief-row').allTextContents();assert(texts.length>=2);assert.equal(await p.locator('.prep-brief-amount').count(),0);assert(!texts.some(t=>/\d|\bml\b/.test(t)));
 const rows=await p.locator('.prep-brief-row').evaluateAll(ns=>ns.map(n=>{const r=n.getBoundingClientRect();return{x:r.x,y:r.y,b:r.bottom};}));for(let i=1;i<rows.length;i++){assert(Math.abs(rows[i].x-rows[0].x)<1);assert(rows[i].y>=rows[i-1].b);}
 if(id==='long_island'&&size.width===1280)await p.screenshot({path:'/private/tmp/prep-one-column.png'});
 const trayBefore=await p.locator('.inventory-slot').first().boundingBox();await p.locator('.prep-recipe-brief').click();await p.locator('#prep-recipe-detail').waitFor();const box=await p.locator('#prep-recipe-detail').boundingBox(),tray=await p.locator('.prep-inventory').boundingBox(),controls=await p.locator('.prep-controls').boundingBox();assert(box.y<size.height*.05);assert(box.y+box.height<controls.y);assert(box.y+box.height<tray.y);const trayAfter=await p.locator('.inventory-slot').first().boundingBox();assert.equal(trayAfter.x,trayBefore.x);
 const scroll=p.locator('#prep-recipe-detail .prep-recipe-scroll');await scroll.evaluate(el=>el.scrollTop=el.scrollHeight);assert(await scroll.evaluate(el=>el.scrollTop>0));assert((await p.locator('#prep-recipe-detail').innerText()).includes('ml'));if(id==='long_island'&&size.width===1280){await scroll.evaluate(el=>el.scrollTop=0);await p.screenshot({path:'/private/tmp/prep-detail-raised.png'});}await p.locator('#prep-recipe-detail [data-act="togglePrepRecipe"]').click();
 }}assert.deepEqual(errors,[]);console.log('PREP_CLEARANCE_OK: single-column names, no summary amounts, raised detail, accessible scrolling, controls/tray clear, no tray shift, desktop/small');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
