const assert=require('assert/strict'),root=require('path').resolve(__dirname,'..');
for(const file of ['outside-residence','outside-dialogue-data','outside-story','outside'])require(root+'/'+file+'.js');
const {Model}=global.LunaOutside;
const step=(m,n)=>{for(let i=0;i<n*60;i++)m.tick(1/60);};
function approach(m,id){const t=m.targets().find(t=>t.id===id);assert(t,id+' target missing');m.x=t.x;m.updateNear();assert.equal(m.near.id,id);assert(m.interact());}
function finish(m){for(let i=0;m.story.speech&&i<100;i++){if(m.story.speech.choice)m.story.choose('leave');else m.story.advance();}assert(!m.story.speech);}
let m=new Model({day:0});assert(!m.targets().some(t=>t.id==='poster'||t.id==='shiba'));approach(m,'experiment');assert.equal(m.story.view().title,'임상시험 전단');const x=m.x;m.tick(.05,{move:1,run:true});assert.equal(m.x,x);m.story.cancel();assert(!m.story.flags.seen_coratech_ad);approach(m,'experiment');finish(m);assert(m.story.flags.seen_coratech_ad);assert(!m.targets().some(t=>t.id==='experiment'));
m=new Model({day:1,flow:'in'});assert(!m.targets().some(t=>t.id==='experiment'));approach(m,'poster');assert(m.story.view().full.includes('Bc25'));finish(m);approach(m,'poster');finish(m);
approach(m,'shiba');assert.equal(m.story.speech.id,'np_shiba_1');m.story.cancel();assert(!m.story.flags.shiba_met);approach(m,'shiba');finish(m);approach(m,'shiba');assert.equal(m.story.speech.id,'np_shiba_2');finish(m);
m=new Model({day:2});approach(m,'shiba');finish(m);approach(m,'shiba');assert.equal(m.story.speech.id,'np_shiba_3');for(let i=0;!m.story.speech.choice&&i<20;i++)m.story.advance();assert(m.story.speech.choice);assert.equal(m.story.choose('treat'),false);m.story.flags.has_snack=true;assert(m.story.choose('treat'));assert(m.story.flags.shiba_fed);assert(!m.story.flags.has_snack);assert.equal(m.story.speech.id,'np_shiba_treat');finish(m);approach(m,'shiba');assert.equal(m.story.speech.id,'np_shiba_2');finish(m);
m=new Model({place:'home'});approach(m,'tv');assert.equal(m.story.speech.id,'np_tv_1');finish(m);approach(m,'tv');assert.equal(m.story.speech.id,'np_tv_2');finish(m);approach(m,'exit');step(m,1);approach(m,'home');step(m,1);approach(m,'tv');assert.equal(m.story.speech.id,'np_tv_2');m.start({place:'home'});assert(!m.story.flags.tv_seen1);
for(const day of [0,1,2,3])for(const flow of ['in','out'])for(const place of ['bar','homeDoor']){m=new Model({day,flow,place});approach(m,'elevator');assert.equal(m.story.speech?.id,'d1_elevator');step(m,1);m.paused=true;const frozen=JSON.stringify(m);step(m,2);assert.equal(JSON.stringify(m),frozen);m.paused=false;step(m,13);assert(!m.ride);assert(m.story.speech,'Do not cut news off at arrival');step(m,60);assert(!m.story.speech);approach(m,'elevator');assert.equal(m.story.speech?.id,'d1_elevator','Every actual preview ride broadcasts');}
m=new Model({place:'homeDoor',day:0});m.elevatorY=global.LunaResidence.layout.elevatorBottom;approach(m,'elevator');assert(m.ride.call);assert(!m.story.speech);
m=new Model();approach(m,'elevator');step(m,14);assert(m.story.speech);m.x-=1;assert.equal(m.story.view().anchor.x,global.LunaResidence.layout.elevatorX);approach(m,'home');assert(!m.story.speech);step(m,1);assert.equal(m.scene,'home');
console.log('PASS outside story: conditions, repeat/once, cancel, choices, TV, session reset, radio timing and pause');
