const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict'),fs=require('fs'),path=require('path');
const stage=process.env.NOTION_STAGE,staged=!!stage;
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{
const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));
if(staged)await p.route('http://127.0.0.1:8123/**',async route=>{const u=new URL(route.request().url());let f=path.join(stage,decodeURIComponent(u.pathname));if(f.endsWith('/'))f+='index.html';if(fs.existsSync(f)&&fs.statSync(f).isFile())await route.fulfill({path:f});else await route.continue();});
await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
async function boot(day,flow,place='bar',main=false,qaCase){await p.evaluate(async v=>{lunaCampaign.toPicker();lunaCampaign.session.install({developer:!v.main});barGame.reset(v.day===99?2:v.day,'full',10,false);Object.assign(barGame.progress,{money:1000,flags:{},inventory:{}});lunaCampaign.session.day=v.day;lunaCampaign.session.route=v.flow;lunaCampaign.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:v.day,flow:v.flow,place:v.place,qaCase:v.qaCase});await outsidePlaytest.start();lunaCampaign.screen(lunaCampaign.playView);outsidePlaytest.snapCamera();outsidePlaytest.tick(0);},{day,flow,place,main,qaCase});}
async function settle(){await p.waitForFunction(()=>!outsidePlaytest.model.encounter||outsidePlaytest.model.encounter.stage==='active',null,{timeout:10000});await p.evaluate(()=>outsidePlaytest.tick(0));}
async function finish(){return p.evaluate(()=>{const m=outsidePlaytest.model,lines=[],stages=[];for(let i=0;i<2200;i++){if(m.story.speech?.line){if(m.story.speech.choice)break;lines.push(m.story.speech.line.text);m.story.speech.elapsed=999;m.story.advance();}if(m.encounter){stages.push(m.encounter.stage);m.encounter.cameraReady=true;m.tick(.05);}if(!m.story.speech&&!m.encounter)break;}outsidePlaytest.tick(0);return{lines,stages};});}
// Latest text + source branching preservation.
assert.deepEqual(await p.evaluate(()=>[LUNA_CAMPAIGN_DATA.scenes.night0.length,LUNA_CAMPAIGN_DATA.scenes.terraceMemory.length,LUNA_CAMPAIGN_DATA.scenes.commute2.filter(r=>r.type==='say').length]),[22,8,29]);
assert.equal(await p.evaluate(()=>LUNA_CAMPAIGN_DATA.scenes.ending.at(-1).text),'네. 보스.');
for(const [day,flow,expected] of [[0,'out','outside_day0_tv_news1'],[1,'in','outside_day1_tv_news2'],[1,'out',null],[2,'in',null]]){await boot(day,flow,'home');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=1.22;m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech?.id||null),expected);}
await boot(1,'in');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.elevatorX+1.45;m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.id),'outside_day1_commute_passers2');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.blocking),false);
// Parallel ambient remains supported; event day/flow is exact.
assert.equal(await p.evaluate(()=>{const m=outsidePlaytest.model;m.config.flow='out';return LunaOutsideContent.active(m,LunaOutsideContent.events.find(e=>e.id===LunaOutsideNotion.passers));}),false);
for(const main of [false,true]){
 await boot(2,'in','door',main);await p.evaluate(()=>{const m=outsidePlaytest.model;m.scene='street';m.level=1;m.y=LunaResidence.layout.upperY;m.x=LunaResidence.layout.homeX+.2;m.tick(.05);});await settle();assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),'day2-corridor-thug');const result=await finish();assert.equal(result.lines.length,6);await settle();assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.homeX+.7;m.updateNear();m.interact();outsidePlaytest.tick(0);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.line.stage),'topic');
 for(const topic of ['gang','coratech','chris']){if(topic!=='gang')await p.evaluate(()=>outsidePlaytest.model.interact());await p.evaluate(topic=>{outsidePlaytest.model.story.choose('info-'+topic);outsidePlaytest.tick(0);},topic);
 if(topic==='gang'){await p.evaluate(()=>{barGame.progress.money=49;outsidePlaytest.tick(0);});assert.equal(await p.locator('[data-choice="info-pay"]').isDisabled(),true);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.choose('info-pay')),false);await p.evaluate(()=>{barGame.progress.money=1000;outsidePlaytest.tick(0);});}
 const before=await p.evaluate(()=>barGame.progress.money);await p.locator('[data-choice="info-pay"]').click();assert.equal(await p.evaluate(()=>barGame.progress.money),before-50);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.choose('info-pay')),false);const out=await finish();assert.equal(out.lines.length,8);if(main)assert.equal(await p.evaluate(()=>lunaCampaign.session.carry.money),before-50);
 }
 await p.evaluate(()=>{outsidePlaytest.model.interact();outsidePlaytest.model.story.choose('info-gang');});const money=await p.evaluate(()=>barGame.progress.money);await p.evaluate(()=>outsidePlaytest.model.story.choose('info-cancel'));assert.equal(await p.evaluate(()=>barGame.progress.money),money);
 console.log('PASS day2 thug intro, three topics, money boundaries, one-shot payment, decline',main?'main':'developer');
 await boot(3,'out','bar',main);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.elevatorX+3.05;m.tick(.05);});await settle();assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),'day3-samho-contract');
 await p.screenshot({path:'/private/tmp/notion-contract-start.png'});
 const contract=await finish();assert.equal(contract.lines.length,20);for(const action of ['dealer-exit','approach','samho-exit'])assert(contract.stages.includes(action));await settle();assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.elevatorX+3.05;m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.encounter),null);console.log('PASS day3 contract talk, departures, approach, once',main?'main':'developer');
}
for(const qaCase of ['runtime:thug2','runtime:thug-info','runtime:samho-contract']){await boot(99,'out','bar',false,qaCase);const before=await p.evaluate(()=>JSON.stringify(barGame.progress));await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=0;m.tick(.05);m.updateNear();if(!m.encounter&&!m.story.speech)m.interact();});await settle();if(qaCase==='runtime:thug-info'){await p.evaluate(()=>{const s=outsidePlaytest.model.story;s.choose('info-chris');s.choose('info-pay');});assert.equal(await p.evaluate(()=>outsidePlaytest.model.qa.shopProgress.money),950);}await finish();assert.equal(await p.evaluate(()=>JSON.stringify(barGame.progress)),before);console.log('PASS QA isolated',qaCase);}
assert.deepEqual(errors,[]);console.log('NOTION_SYNC_UI_OK');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
