const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{
const p=await b.newPage({viewport:{width:1500,height:1000}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/resource-review.html');await p.waitForFunction(()=>resourceReview.ready&&resourceReview.missing);
const entries=await p.evaluate(()=>resourceReview.missing.entries);assert(entries.length>10);assert.equal(new Set(entries.map(e=>e.id)).size,entries.length);
const pendingIds=['recipes','dossier','overlay:service','overlay:settings','overlay:history','overlay:johnnyUnlock','unlock','mini:shake','mini:stir','mini:pour','result'].map(id=>'ui:'+id);
const catalog=await p.evaluate(()=>resourceReview.rows);
const missingItems=['cointreau','cranberry_juice','triple_sec','kahlua','milk','amaretto','wild_dog','bitters','sugar_cube'];
for(const id of missingItems){const rows=catalog.filter(r=>r.id.startsWith('item:'+id+':'));assert.equal(rows.length,3,id);for(const r of rows){assert.equal(r.status,'missing',r.id);assert(r.layers.length>0,r.id+' keeps placeholder preview');}const entry=entries.find(e=>e.id==='item:item:'+id);assert(entry,id+' in production checklist');assert.equal(entry.rows.length,3);assert.deepEqual(entry.reasons,['missing']);}
for(const id of ['gin','tequila']){assert(catalog.filter(r=>r.id.startsWith('item:'+id+':')).every(r=>r.status!=='missing'));assert(!entries.some(e=>e.id==='item:item:'+id));}
await p.click('[data-group="bar-items"]');await p.click('[data-status="missing"]');for(const id of missingItems)for(const kind of ['shelf','recipe','inventory'])assert.equal(await p.locator('[data-id="item:'+id+':'+kind+'"] .badge').innerText(),'미등록');await p.click('[data-status="all"]');
const registeredServe=['cosmopolitan','dry_martini','gin_fizz','gin_tonic','kahlua_milk'],serve=catalog.filter(r=>r.group==='bar-serve');
assert.deepEqual(serve.filter(r=>r.status==='registered').map(r=>r.id.slice(6)).sort(),registeredServe);
for(const r of serve.filter(r=>!registeredServe.includes(r.id.slice(6)))){assert.equal(r.status,'missing');assert(entries.some(e=>e.rows.some(x=>x.row.id===r.id&&x.reason==='animation')));}
await p.click('[data-group="bar-serve"]');await p.click('[data-status="missing"]');assert.equal(await p.locator('#grid .card').count(),serve.length-5);for(const badge of await p.locator('#grid .badge').allTextContents())assert.equal(badge,'미등록');await p.click('[data-status="all"]');
assert.equal(catalog.filter(r=>r.uiArtPending).length,pendingIds.length);
for(const id of pendingIds){const r=catalog.find(r=>r.id===id);assert(r&&r.uiArtPending&&r.status==='missing'&&r.preview&&r.launch,id);assert(entries.some(e=>e.category==='ui'&&e.reasons.includes('uiArt')&&e.rows.some(x=>x.row.id===id)),id);}
for(const id of ['ui:updates','ui:qa-panel'])assert(!catalog.some(r=>r.id===id));
assert.equal(catalog.find(r=>r.id==='ui:choices').status,'code');
const passers=await p.evaluate(()=>resourceReview.rows.filter(r=>r.group==='out-characters'&&(/^outside:(M1|M2|W1)$/.test(r.id)||r.id.startsWith('outside-role:')&&/^행인(?:\s*\d+)?$/.test(r.title||''))).map(r=>r.id));
assert(passers.length>=7,'Passerby assets remain in the normal catalog');
assert(!entries.some(e=>e.rows.some(x=>passers.includes(x.row.id))),'Passerby excluded from missing list');
for(const id of ['bd-vendor','thug','resident-left','trade-smuggler']){assert(catalog.some(r=>r.id==='outside-role:'+id),id+' remains in full catalog');assert(!entries.some(e=>e.rows.some(x=>x.row.id==='outside-role:'+id)),id+' excluded from checklist');}
assert.deepEqual(entries.filter(e=>e.category==='character').map(e=>e.id).sort(),['character:actor:shiba','character:actor:tom','character:outside:terrace-chris']);
const terrace=catalog.find(r=>r.id==='outside:terrace-chris');assert(terrace.preview&&terrace.launch.type==='terrace'&&terrace.status==='missing');assert.equal(entries.find(e=>e.id==='character:outside:terrace-chris').area,'외부');assert(!entries.some(e=>e.rows.some(x=>x.row.id.startsWith('actor:chris:'))));
assert(!entries.some(e=>e.rows.some(x=>/^item:gin:/.test(x.row.id))));assert(entries.some(e=>e.rows.some(x=>x.row.id==='item:milk:shelf')));assert(!entries.some(e=>e.rows.some(x=>x.row.id==='bg:street:residence-building')));
console.log('GAPS',Object.fromEntries(['cocktail','item','character','background','ui','effect'].map(c=>[c,entries.filter(e=>e.category===c).length])));
assert.equal(await p.locator('.top #missing-resources').count(),0);assert.equal(await p.locator('#missing-dialog').count(),0);assert.equal(await p.locator('#nav > button').first().getAttribute('id'),'missing-resources');
await p.click('#missing-resources');assert(await p.locator('#missing-view').isVisible());assert.equal(await p.locator('#missing-resources').getAttribute('aria-current'),'true');assert(!await p.locator('#catalog-view').isVisible());assert(!await p.locator('#inspector').isVisible());assert.equal(await p.locator('[data-missing-category]').count(),7);assert.equal(await p.locator('#missing-list .missing-entry').count(),entries.length);assert.equal(await p.evaluate(()=>document.activeElement.id),'missing-resources');
await p.waitForTimeout(350);await p.screenshot({path:'/private/tmp/resource-missing-all.png'});
await p.selectOption('#missing-reason','uiArt');assert.equal(await p.locator('#missing-list .missing-entry').count(),pendingIds.length);await p.screenshot({path:'/private/tmp/resource-ui-art-missing.png'});await p.click('#missing-reset');
for(const cat of ['cocktail','item','character','background','ui','effect']){await p.click('[data-missing-category="'+cat+'"]');assert.equal(await p.locator('#missing-list .missing-entry').count(),entries.filter(e=>e.category===cat).length);}
await p.click('[data-missing-category="item"]');await p.fill('#missing-search','우유');assert.equal(await p.locator('#missing-list .missing-entry').count(),1);assert((await p.locator('#missing-list').innerText()).includes('전용 리소스 미등록'));await p.locator('#missing-list summary').click();assert.equal(await p.locator('#missing-list .missing-detail').count(),3);await p.screenshot({path:'/private/tmp/resource-missing-item.png'});
const download=p.waitForEvent('download');await p.click('#missing-export');assert.equal((await download).suggestedFilename(),'unknown-missing-resources.csv');
await p.click('.missing-inspect');assert(!await p.locator('#missing-view').isVisible());assert(await p.locator('#catalog-view').isVisible());assert(await p.locator('#inspector').isVisible());assert.equal(await p.evaluate(()=>resourceReview.selected.id),'item:milk:shelf');assert.equal(await p.locator('[data-group="bar-items"]').getAttribute('aria-current'),'true');
await p.click('#missing-resources');assert.equal(await p.locator('#missing-search').inputValue(),'우유');assert.equal(await p.locator('[data-missing-category="item"]').getAttribute('aria-pressed'),'true');assert.equal(await p.locator('#missing-list .missing-entry').count(),1);
await p.click('#missing-resources');await p.click('#missing-reset');await p.selectOption('#missing-area','외부');await p.selectOption('#missing-reason','sharedDummy');assert.equal(await p.locator('#missing-list .missing-entry').count(),0);assert(!(await p.locator('#missing-list').innerText()).includes('BD 칩'));
await p.fill('#missing-search','없는리소스검색');assert.equal(await p.locator('#missing-list .missing-entry').count(),0);assert(await p.locator('.missing-empty').isVisible());await p.click('#missing-reset');
await p.keyboard.press('Escape');assert(await p.locator('#missing-view').isVisible(),'Not a dismissible popup');
await p.click('[data-group="bar-items"]');await p.fill('#search','진');await p.click('#missing-resources');await p.click('[data-group="bar-items"]');assert.equal(await p.locator('#search').inputValue(),'진');await p.fill('#search','');
await p.setViewportSize({width:390,height:844});await p.locator('#missing-resources').focus();await p.keyboard.press('Enter');await p.click('[data-missing-category="character"]');await p.screenshot({path:'/private/tmp/resource-missing-mobile.png'});assert(await p.locator('#missing-view').evaluate(e=>e.scrollWidth<=e.clientWidth+1));assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));await p.click('[data-group="bar-characters"]');assert(!await p.locator('#missing-view').isVisible());assert.deepEqual(errors,[]);
console.log('RESOURCE_MISSING_UI_OK',entries.length,'top sidebar category, inline grouped gaps, filters, CSV, inspect navigation, filter retention, keyboard, mobile');
await p.setViewportSize({width:1500,height:1000});await p.click('[data-group="bar-ui"]');await p.click('[data-status="missing"]');
for(const id of pendingIds){const card=p.locator('#grid [data-id="'+id+'"]');assert(await card.isVisible());assert.equal(await card.locator('.badge').innerText(),'UI 아트 미제작');}
await p.locator('#grid [data-id="ui:recipes"]').click();assert((await p.locator('.ui-preview figcaption').innerText()).includes('미제작'));await p.screenshot({path:'/private/tmp/resource-ui-art-catalog.png'});
await p.locator('#inspector [data-action="launch"]').click();await p.waitForFunction(()=>!document.querySelector('#lab').classList.contains('parked')&&document.querySelector('#game').contentWindow.barGame.screen==='recipe');await p.click('#close-lab');assert.deepEqual(errors,[]);
console.log('RESOURCE_UI_ART_OK',pendingIds.length,'confirmed UI art gaps, previews and recipe test retained, two catalog-only removals');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
