const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?version=gpt');await p.locator('.updates-confirm').click();await p.locator('.remix-start').waitFor();assert.equal(await p.inputValue('#start-mode'),'episode');await p.screenshot({path:'/private/tmp/rx-lobby.png'});await p.locator('[data-act="start"]').click();await p.waitForFunction(()=>barGame.seats.L?.state==='WAIT_COASTER');await p.keyboard.press('Space');await p.waitForFunction(()=>barGame.seats.L?.state==='WAIT_SERVE',null,{timeout:20000});assert.equal(await p.locator('.remix-run-hud').count(),0);
await p.evaluate(()=>{barGame.openRecipes();barGame.selectCocktail('gin_tonic');});await p.waitForTimeout(250);await p.screenshot({path:'/private/tmp/rx-prep.png'});
await p.evaluate(()=>{const g=barGame;g.debugFill();g.startCraft();g.craft.index=g.craft.queue.findIndex(s=>s.ingredient==='soda_water');g.nextGimmick();g.gimmickInput('Space');});await p.keyboard.down('Space');await p.waitForTimeout(1900);await p.keyboard.up('Space');await p.waitForTimeout(800);await p.screenshot({path:'/private/tmp/rx-carbonation.png'});assert.equal(await p.locator('[data-fluid-stage]').getAttribute('data-carbonation'),'true');
await p.evaluate(()=>{const g=barGame;g.debugCraft('good');g.remix.resultLock=0;g.offer();g.serve('L','drag');});await p.waitForFunction(()=>barGame.finished,null,{timeout:25000});await p.locator('.rx-episode-report').waitFor();await p.screenshot({path:'/private/tmp/rx-report.png'});await p.locator('[data-act="remixOutside"]').click();await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading);assert(await p.evaluate(()=>!!outsidePlaytest.model.remixX));
async function finishSpeech(){await p.evaluate(()=>{const m=outsidePlaytest.model;for(let i=0;i<30&&m.story.speech&&!m.story.speech.auto;i++){m.story.speech.elapsed=999;m.story.advance();}m.tick(.02);});}
await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-4.15;m.story.cancel();m.backgroundStory.cancel();m.updateNear();outsidePlaytest.snapCamera();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),'rx_shift_intro');await finishSpeech();await p.locator('[data-outside-action="rx-wait"]').waitFor();await p.screenshot({path:'/private/tmp/rx-choice.png'});await p.locator('[data-outside-action="rx-wait"]').click();await finishSpeech();assert.equal(await p.evaluate(()=>outsidePlaytest.model.remixX.choice),'wait');assert.equal(await p.evaluate(()=>outsidePlaytest.model.remixX.entries.filter(e=>e.id==='rx-choice').length),1);
await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-4.15;m.updateNear();});await p.keyboard.press('KeyE');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),'rx_shift_repeat');await finishSpeech();
await p.evaluate(()=>{const m=outsidePlaytest.model;m.scene='home';m.level=1;m.x=2.557;m.y=-.7;m.updateNear();outsidePlaytest.snapCamera();});await p.keyboard.press('KeyE');await p.locator('.rx-reflection').waitFor();assert((await p.locator('.rx-reflection').innerText()).includes('시원하네요'));assert((await p.locator('.rx-reflection').innerText()).includes('잠깐의 침묵'));await p.screenshot({path:'/private/tmp/rx-home.png'});await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>outsidePlaytest.model.paused),false);await p.keyboard.press('Escape');await p.locator('[data-outside-action="rx-notebook"]').click();await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>outsidePlaytest.model.paused),false);
await p.evaluate(()=>{outsidePlaytest.exit(true);barGame.reset(0,'full',1,false,{variant:'original'});});await p.waitForTimeout(200);await p.locator('[data-act="version"][data-id="outside-gpt"]').click();await p.screenshot({path:'/private/tmp/rx-out-lobby.png'});await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-4.15;m.updateNear();});await p.keyboard.press('KeyE');await finishSpeech();await p.locator('[data-outside-action="rx-speak"]').click();await finishSpeech();assert.equal(await p.evaluate(()=>outsidePlaytest.model.remixX.choice),'speak');await p.keyboard.press('Escape');await p.locator('[data-outside-action="exit"]').click();await p.locator('[data-act="version"][data-id="outside"]').click();await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);assert.equal(await p.evaluate(()=>outsidePlaytest.model.remixX),null);
await p.keyboard.press('Escape');await p.locator('[data-outside-action="exit"]').click();await p.locator('[data-act="version"][data-id="outside-gpt"]').click();await p.selectOption('#outside-day','2');await p.selectOption('#outside-flow','in');await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-5.99;m.updateNear();});await p.waitForTimeout(300);assert.equal(await p.evaluate(()=>lunaCampaign.view),'developer');
await p.evaluate(()=>{outsidePlaytest.exit(true);outsidePlaytest.config.day=99;outsidePlaytest.start();});await p.waitForFunction(()=>!outsidePlaytest.loading);assert.equal(await p.evaluate(()=>outsidePlaytest.model.remixX),null);assert(await p.evaluate(()=>!!outsidePlaytest.model.qa));
await p.evaluate(()=>{outsidePlaytest.exit(true);barGame.reset(0,'full',1,false,{variant:'original'});});await p.waitForTimeout(250);await p.locator('[data-act="version"][data-id="gpt"]').click();await p.setViewportSize({width:960,height:540});await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);await p.screenshot({path:'/private/tmp/rx-small.png'});
assert.deepEqual(errors,[]);console.log('STORYFIRST_UI_OK: episode, craft cue/carbonation, result-to-street, both choices, replay, home recap, Escape, explicit tabs, day2 isolation, QA exclusion, 960 layout, no JS errors');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
