const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/');
async function noSelect(sel){const el=p.locator(sel).first();assert.equal(await el.evaluate(e=>getComputedStyle(e).userSelect),'none');const box=await el.boundingBox();await p.mouse.move(box.x+4,box.y+box.height/2);await p.mouse.down();await p.mouse.move(box.x+box.width-4,box.y+box.height/2+5,{steps:15});await p.mouse.up();assert.equal(await p.evaluate(()=>getSelection().toString()),'');assert.equal(await el.evaluate(e=>{const event=new Event('selectstart',{bubbles:true,cancelable:true});e.dispatchEvent(event);return event.defaultPrevented;}),true);}
await noSelect('.campaign-picker h1');await p.locator('[data-campaign="title"]').click();assert.equal(await p.locator('.title-logo').evaluate(e=>getComputedStyle(e).webkitUserDrag),'none');assert(await p.locator('.title-logo').evaluate(e=>{const d=new DragEvent('dragstart',{bubbles:true,cancelable:true});e.dispatchEvent(d);return d.defaultPrevented;}));
await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
await p.evaluate(()=>{const g=barGame;g.reset(1,'general',1,true);g.spawn();g.cameraMoving=false;g.cameraLeft=0;g.transition=0;g.changed();});await p.waitForTimeout(700);
async function gameDrag(source,target){const a=await p.locator(source).boundingBox(),z=await p.locator(target).boundingBox();await p.mouse.move(a.x+a.width/2,a.y+a.height/2);await p.mouse.down();assert(await p.locator('#drag-ghost').isVisible());await p.mouse.move(z.x+z.width/2,z.y+z.height*.8,{steps:15});await p.mouse.up();assert.equal(await p.evaluate(()=>getSelection().toString()),'');}
await gameDrag('[data-drag="coaster"]','[data-drop="L"]');assert.equal(await p.evaluate(()=>barGame.seats.L.coaster),true);
await p.evaluate(()=>{const g=barGame,guest=g.seats.L;guest.lineDone();g.openRecipes();g.selectCocktail(guest.order.cocktail);g.debugCraft('excellent');g.offer();g.cameraMoving=false;g.cameraLeft=0;g.transition=0;g.changed();});await p.waitForTimeout(700);await gameDrag('[data-drag="drink"]','[data-drop="L"]');assert.equal(await p.evaluate(()=>barGame.drink),null);assert.equal(await p.evaluate(()=>barGame.seats.L.state),'REACTION');
await p.evaluate(async()=>{lunaCampaign.screen('developer');Object.assign(outsidePlaytest.config,{day:1,flow:'out',place:'bar'});await outsidePlaytest.start();});await p.keyboard.press('KeyP');await noSelect('.outside-dev-note');
// Dynamically inserted text editors must retain real mouse selection and editing.
await p.evaluate(()=>{const fixture=document.createElement('div');fixture.id='selection-fixture';fixture.style='position:fixed;left:20px;top:20px;z-index:999999;background:black;padding:20px;display:grid';fixture.innerHTML='<input value="select editable text"><textarea>textarea selection</textarea><div contenteditable="true">Editable <span>nested text</span></div>';document.body.append(fixture);});
for(const sel of ['input','textarea','[contenteditable] span']){const el=p.locator('#selection-fixture '+sel);assert.equal(await el.evaluate(e=>getComputedStyle(e).userSelect),'text');assert.equal(await el.evaluate(e=>{const event=new Event('selectstart',{bubbles:true,cancelable:true});e.dispatchEvent(event);return event.defaultPrevented;}),false);}
const field=p.locator('#selection-fixture input');await field.fill('editable preserved');await field.evaluate(e=>e.select());assert.equal(await field.evaluate(e=>e.value.slice(e.selectionStart,e.selectionEnd)),'editable preserved');await p.keyboard.insertText('edited');assert.equal(await field.inputValue(),'edited');assert.deepEqual(errors,[]);console.log('GAME_SELECTION_OK title/exterior text, native image drag blocked, dynamic editable exceptions, actual coaster and cocktail mouse delivery retained');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
