const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 await p.evaluate(()=>lunaCampaign.scene('night0','테라스','terrace',()=>lunaCampaign.screen('developer')));await p.waitForFunction(()=>!lunaCampaign.memoryTransition);await p.evaluate(()=>{const c=lunaCampaign;window.memoryIndex=c.data.scenes.night0.findIndex(r=>r.cinemaAfter==='terrace-memory');if(window.memoryIndex<0)throw Error('Missing terrace memory cue');c.dialog.index=window.memoryIndex;c.dialog.chars=1e5;c.draw();window.swaps=[];const screen=c.screen.bind(c);c.screen=view=>{window.swaps.push({view,alpha:c.memoryTransition?Number(c.memoryTransition.host.style.opacity):null});screen(view);};const script=c.script.bind(c);c.script=async name=>{if(name==='terrace-memory')await new Promise(resolve=>window.releaseMemory=resolve);return script(name);};window.fadeTrace=[];const tick=c.tick.bind(c);c.tick=dt=>{const result=tick(dt),d=c.memoryTransition;if(d)window.fadeTrace.push({phase:d.phase,alpha:Number(d.host.style.opacity),gain:c.bgm.transitionGain});return result;};});
 await p.keyboard.press('KeyE');await p.waitForFunction(()=>lunaCampaign.memoryTransition?.phase==='out'&&lunaCampaign.memoryTransition.time>.2);const initial=await p.evaluate(()=>lunaCampaign.dialog.index);await p.keyboard.press('Space');await p.keyboard.press('ControlLeft');await p.mouse.click(400,340);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),initial);await p.waitForFunction(()=>lunaCampaign.memoryTransition?.phase==='hold'&&!!window.releaseMemory);await p.waitForTimeout(350);assert.equal(await p.evaluate(()=>lunaCampaign.view),'memory-transition');assert.equal(await p.locator('.campaign-loading').count(),0);assert.equal(await p.locator('.campaign-memory-transition').evaluate(el=>getComputedStyle(el).opacity),'1');assert.equal(await p.locator('.terrace-scene').count(),1);
 await p.evaluate(()=>window.releaseMemory());await p.waitForFunction(()=>lunaCampaign.memoryTransition?.phase==='in');assert.equal(await p.evaluate(()=>lunaCampaign.cinema.time),0);await p.keyboard.press('Space');await p.mouse.click(400,340);assert.equal(await p.evaluate(()=>lunaCampaign.cinema.time),0);await p.waitForFunction(()=>!lunaCampaign.memoryTransition&&lunaCampaign.view==='prologue');
 const noise=await p.evaluate(()=>{const c=lunaCampaign.cinema,t=c.scene.lines[2].t+1,fx=c.scene.fx;c.time=t;c.player.render(t,null,false,0);const canvas=document.querySelector('.campaign-prologue'),withNoise=canvas.toDataURL();c.scene.fx=fx.filter(f=>f.type!=='tvnoise');c.player.render(t,null,false,0);const without=canvas.toDataURL();c.scene.fx=fx;c.player.render(t,null,false,0);return {different:withNoise!==without,noise:fx.filter(f=>f.type==='tvnoise').length,fade:fx.filter(f=>f.type==='fade').length};});assert(noise.different);assert.equal(noise.fade,0);assert.equal(noise.noise,3);await p.screenshot({path:'/private/tmp/terrace-memory-noise.png'});
 await p.evaluate(()=>{const c=lunaCampaign.cinema;c.time=c.scene.end-.01;lunaCampaign.tick(.05);});await p.waitForFunction(()=>lunaCampaign.memoryTransition?.phase==='in'&&lunaCampaign.view==='scene');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.chars),0);await p.keyboard.press('KeyE');await p.keyboard.press('Space');await p.mouse.click(400,340);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),await p.evaluate(()=>window.memoryIndex+1));assert.equal(await p.evaluate(()=>lunaCampaign.dialog.chars),0);await p.waitForFunction(()=>!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),await p.evaluate(()=>window.memoryIndex+1));assert.equal(await p.locator('.memory-return').count(),0);assert.equal(await p.evaluate(()=>lunaCampaign.bgm.transitionGain),1);assert.equal(await p.evaluate(()=>lunaCampaign.bgm.audio.muted),false);assert.equal(await p.locator('#campaign-root').getAttribute('inert'),null);
 const swaps=await p.evaluate(()=>window.swaps);assert(swaps.filter(s=>['prologue','scene'].includes(s.view)).every(s=>s.alpha===1));const trace=await p.evaluate(()=>window.fadeTrace);for(let i=1;i<trace.length;i++){const a=trace[i-1],b=trace[i];if(a.phase===b.phase&&b.phase==='out')assert(b.alpha>=a.alpha);if(a.phase===b.phase&&b.phase==='in')assert(b.alpha<=a.alpha);}assert(!swaps.some(s=>s.view==='loading'));
 // Cancellation clears the persistent overlay and all input locks.
 await p.evaluate(()=>{const c=lunaCampaign;c.scene('night0','테라스','terrace',()=>{});c.dialog.index=window.memoryIndex;c.dialog.chars=1e6;c.next();c.toPicker();});await p.waitForTimeout(200);assert.equal(await p.locator('.campaign-memory-transition').count(),0);assert.equal(await p.locator('#campaign-root').getAttribute('inert'),null);assert.equal(await p.evaluate(()=>lunaCampaign.view),'picker');assert.deepEqual(errors,[]);console.log('MEMORY_TRANSITION_OK blackout-only swaps; slow loading hold/no loading card; monotonic fades; input/typing/playback locks; actual dream noise; natural return + BGM ramp; cancellation');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
