const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await p.goto('http://127.0.0.1:8123/bar-playtest/?mode=outside');await p.locator('.updates-confirm').click();await p.selectOption('#outside-day','2');await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);
 const order=await p.evaluate(()=>{const n=LunaOutside.streetDrawOrder(LUNA_OUTSIDE_DATA.scenes.street.nodes);return n.map(n=>n.name);});
 const before=(a,b)=>assert(order.indexOf(a)<order.indexOf(b),a+' must precede '+b);
 for(const name of ['1 experiment_recruit','3 poster_help_wanted','10 real_estate_posting','7 poster_human_trafficking','2 toilet_bin','6 vending_machine','5 poster_shiba_wanted_day1']){before('B_Obects',name);before(name,'Luna');}
 before('shiba','Luna');for(const name of ['Elevator Fore','B_ForeFore_Object_1','residence-railing'])before('Luna',name);
 assert(await p.evaluate(()=>{const n=LUNA_OUTSIDE_DATA.scenes.street.nodes,a=LunaOutside.streetDrawOrder(n).map(n=>n.id).join(),b=LunaOutside.streetDrawOrder(n.slice().reverse()).map(n=>n.id).join();return a===b;}));
 // Inspect actual draw calls, not only the sort helper.
 const draw=await p.evaluate(()=>{const c=document.querySelector('#outside-root canvas').getContext('2d'),original=c.drawImage,seen=[];c.drawImage=function(im,...args){seen.push(im.src);return original.call(this,im,...args);};outsidePlaytest.model.x=-2.68;for(let i=0;i<120;i++)outsidePlaytest.tick(.016);seen.length=0;outsidePlaytest.tick(0);c.drawImage=original;const a=LUNA_OUTSIDE_DATA.assets,shiba=seen.findIndex(s=>s.endsWith(a[LUNA_OUTSIDE_DATA.animations.shiba.frames[0].asset].src)),luna=seen.findIndex(s=>LUNA_OUTSIDE_DATA.animations.idle.frames.some(f=>s.endsWith(a[f.asset].src)));return {shiba,luna};});assert(draw.shiba>=0&&draw.luna>draw.shiba,JSON.stringify(draw));
 await p.waitForTimeout(300);await p.screenshot({path:'/private/tmp/outside-layer-shiba-fixed.jpg',type:'jpeg',quality:85});
 for(const [name,x]of [['poster',-5.93],['experiment',-7.8]]){await p.evaluate(x=>{outsidePlaytest.model.x=x;outsidePlaytest.model.updateNear();},x);await p.waitForTimeout(1000);await p.screenshot({path:'/private/tmp/outside-layer-'+name+'-fixed.jpg',type:'jpeg',quality:85});}
 // Visible broadcast for all 4 days, both directions, and both lower/upper starts.
 for(const day of [0,1,2,3])for(const flow of ['in','out'])for(const place of ['bar','homeDoor']){await p.evaluate(c=>{const m=outsidePlaytest.model;m.start(c);m.x=LunaResidence.layout.elevatorX;m.updateNear();},{day,flow,place});await p.keyboard.press('KeyE');await p.waitForTimeout(100);assert(await p.locator('.outside-speech').isVisible(),JSON.stringify({day,flow,place}));assert.equal(await p.locator('.outside-speech strong').innerText(),'라디오');assert(await p.locator('.outside-speech-text').getAttribute('aria-label'));}
 await p.waitForTimeout(1500);await p.screenshot({path:'/private/tmp/outside-radio-all-days-fixed.jpg',type:'jpeg',quality:85});
 await p.evaluate(()=>{const m=outsidePlaytest.model;m.start({place:'homeDoor',day:2,flow:'in'});m.x=LunaResidence.layout.elevatorX;m.elevatorY=LunaResidence.layout.elevatorBottom;m.updateNear();});await p.keyboard.press('KeyE');await p.waitForTimeout(100);assert(await p.locator('.outside-speech').isHidden());assert(await p.evaluate(()=>outsidePlaytest.model.ride.call));
 assert.deepEqual(errors,[]);console.log('PASS layer ordering, shuffled manifest, actual draw calls, 16 visible radio configurations, silent remote call; no browser/asset errors');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});

