const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path'),root=path.resolve(__dirname,'..');
const box={window:{}};for(const f of ['data.js','campaign-data.js','campaign-engine.js'])vm.runInNewContext(fs.readFileSync(root+'/'+f,'utf8'),box);
const C=require(root+'/core.js'),source=box.window.LUNA_DATA,drink='johnny_old_fashioned',ids=['wild_dog','bitters','sugar_cube'];
const data=()=>C.millilitreData(structuredClone(source));
for(const adapter of [false,true])for(let mask=0;mask<16;mask++){
 const D=data(),g=new C.Game(D);if(adapter)new box.window.LunaCampaignEngine.Session(g,D,box.window.LUNA_CAMPAIGN_DATA).install();g.reset(3,'regular',1,false);g.progress.inventory={wild_dog:mask&1?1:0,bitters:mask&2?1:0};g.progress.flags.campaign_observation=!!(mask&4);g.progress.flags.day3_sugar_received=!!(mask&8);
 assert(!g.cocktailsAvailable().some(c=>c.id===drink));g.currentOrder={cocktail:drink};assert(!g.cocktailsAvailable().some(c=>c.id===drink),'orders cannot bypass lock');assert(!g.itemsAvailable().some(i=>ids.includes(i.id)));
 const unlocked=g.checkJohnnyUnlock();assert.equal(unlocked,mask===15);assert.equal(g.overlay,mask===15?'johnnyUnlock':null);if(unlocked){assert(g.isPaused());assert(ids.every(id=>g.itemsAvailable().some(i=>i.id===id)));assert(g.cocktailsAvailable().some(c=>c.id===drink));assert(!g.dailyUnlocks().cocktails.some(c=>c.id===drink));assert.equal(g.progress.inventory.sugar_cube,1);assert(!g.checkJohnnyUnlock());g.confirmJohnnyUnlock();assert.equal(g.overlay,null);assert(!g.checkJohnnyUnlock());assert.equal(g.logs.filter(l=>l.event==='recipe_unlocked').length,1);}
}
const D=data(),g=new C.Game(D),s=new box.window.LunaCampaignEngine.Session(g,D,box.window.LUNA_CAMPAIGN_DATA);s.install();s.beginCommute(3);assert.deepEqual(g.johnnyMissing(),[]);assert(!g.progress.flags.johnny_recipe_unlocked);assert(!g.progress.flags.day3_sugar_received);assert(!g.available(g.cocktail(drink)));
g.reset(2,'full',1,false);s.day=2;s.route='out';s.carry=structuredClone(g.progress);assert(!s.endDay());assert.equal(s.day,2);g.progress.inventory={wild_dog:1,bitters:1};assert(!s.endDay());g.progress.flags.campaign_observation=true;assert(s.endDay());assert.equal(s.day,3);
g.reset(3,'regular',1,true,{storyPrerequisites:true});let delivered=false;for(let i=0;i<1000&&!delivered;i++){g.cameraMoving=false;if(g.transition||g.cameraLeft){g.tick(.1);continue;}if(g.dialogue){const line=g.dialogue.text;g.advance();g.advance();if(g.overlay==='johnnyUnlock'){assert(line.includes('각설탕'));delivered=true;const at=g.story.index;g.tick(10);g.advance();assert.equal(g.story.index,at);assert.equal(g.dialogue,null);assert(g.confirmJohnnyUnlock());assert(g.dialogue);assert(!g.dialogue.text.includes('필요하다던 각설탕'));}}else g.tick(.1);}assert(delivered);
g.reset(99,'practice',1,true);assert(g.cocktailsAvailable().some(c=>c.id===drink));assert(ids.every(id=>g.itemsAvailable().some(i=>i.id===id)));
for(const id of ids.concat(drink)){const key=(id===drink?'cocktail_':'item_')+id,a=D.assets[key];assert(a.src.includes('assets/campaign/johnny-'));assert(fs.existsSync(root+'/'+a.src));assert(a.w<=200&&a.h<=200);}
console.log('JOHNNY_UNLOCK_OK 32 prerequisite combinations, no order bypass, exact Aili delivery pause/resume, one-shot unlock, sleep deadline and QA isolation');
