const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
 for(const [main,variant]of [[false,'original'],[false,'gpt'],[true,'original']]){
 await p.evaluate(async({main,variant})=>{const c=lunaCampaign,a=outsidePlaytest;a.exit(true);c.session.uninstall();c.session.install({developer:!main});barGame.reset(0,'full',1,false);c.session.day=0;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(a.config,{day:0,flow:'out',place:'bar',variant});await a.start();c.screen(c.playView);const m=a.model;m.x=LunaResidence.layout.elevatorX;m.updateNear();a.snapCamera();m.interact();for(let i=0;i<300;i++)a.tick(.05);},{main,variant});
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech),null,'old lift trigger removed');
 await p.evaluate(()=>{const a=outsidePlaytest,m=a.model;m.x=-17.15;m.level=1;m.y=LunaResidence.layout.upperY;m.updateNear();a.snapCamera();a.tick(.05);m.backgroundStory.speech.elapsed=1;a.refreshHUD();});
 assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.id),'outside_day0_building_residents');
 if(!main&&variant==='original')await p.screenshot({path:'/private/tmp/residents-upstairs.png'});
 const result=await p.evaluate(()=>{const a=outsidePlaytest,m=a.model,seen=new Set();let hidden=0;for(let i=0;i<500;i++){const s=m.backgroundStory.speech;if(s){seen.add(s.index);if(document.querySelector('.outside-background-speech').hidden)hidden++;}a.tick(.05);}return{lines:seen.size,hidden,done:m.backgroundStory.done.has(LunaOutsideResidents.id),blocked:m.story.blocking,repeat:!!m.backgroundStory.speech,nodes:LUNA_OUTSIDE_DATA.scenes.street.nodes.filter(n=>n.resident).length,dummies:LunaOutsideResidents.dummies.map(p=>({x:p.x,y:p.y,actor:!!LunaOutsideResidents.actor(p.id)}))};});
 assert.equal(result.lines,4);assert.equal(result.hidden,0);assert(result.done);assert(!result.blocked&&!result.repeat);assert.equal(result.nodes,4);assert.deepEqual(result.dummies,[{x:-14.9,y:7.61,actor:false},{x:-14.22,y:7.61,actor:false}]);
 }
 const guards=await p.evaluate(()=>{const r=LunaOutsideResidents,results=[];for(const [day,flow]of [[0,'in'],[1,'out'],[2,'out'],[3,'out']]){const m=new LunaOutside.Model({day,flow,place:'homeDoor'});m.x=-17.15;r.tickView(m,{x:m.x,y:10.32,w:4.8});results.push(!r.visible(m)&&!m.backgroundStory.speech);}return results;});assert(guards.every(Boolean));
 await p.evaluate(()=>{const a=outsidePlaytest,m=a.model;m.x=-14.6;m.y=7.6;m.level=0;m.backgroundStory.cancel();m.playedAmbient.clear();a.snapCamera();a.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech),null);await p.screenshot({path:'/private/tmp/residents-silent-downstairs.png'});
 assert.deepEqual(errors,[]);console.log('RESIDENTS_RELOCATED_OK original/GPT/main, upper corridor proximity only, old lift silent, four actors with two silent dummies at original coordinates, day/route guards');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
