const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
for(const [main,version]of [[true,'A'],[true,'B'],[false,'A']]){
 await p.evaluate(async({main,version})=>{const c=lunaCampaign;c.toPicker();c.session.install({developer:!main,serviceVersion:version});barGame.reset(2,'full',10,false,{serviceVersion:version});barGame.progress.money=2300;c.session.day=2;c.session.route='out';c.session.carry=structuredClone(barGame.progress);Object.assign(outsidePlaytest.config,{day:2,flow:'out',place:'home',variant:'original'});await outsidePlaytest.start({wakeAtSofa:true});c.screen(c.playView);},{main,version});await p.keyboard.press('KeyE');if(main)await p.locator('[data-campaign="sleep-confirm"]').click();await p.waitForFunction(()=>!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.background),'terrace');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows.length),13);
 await p.evaluate(()=>{const c=lunaCampaign;while(!c.memoryTransition){c.dialog.chars=1e5;c.next();}});await p.waitForFunction(()=>lunaCampaign.dialog?.background==='johnny-memory'&&!lunaCampaign.memoryTransition);assert.equal(await p.locator('[data-memory-pov="johnny"]').count(),1);assert.equal(await p.locator('.johnny-memory strong,.campaign-memory-note,.campaign-menu').count(),0);
 assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows.length),26);await p.evaluate(()=>{lunaCampaign.dialog.chars=1e5;lunaCampaign.next();});await p.waitForTimeout(1200);await p.evaluate(()=>{lunaCampaign.dialog.chars=1e5;lunaCampaign.paintLine();});assert.equal(await p.evaluate(()=>lunaCampaign.dialog.johnnyView.g.seats.R.actor),'tom');assert.equal(await p.locator('.johnny-memory .bar-scene-layer').count()>0,true);
 if(main&&version==='A')await p.screenshot({path:'/private/tmp/day2-johnny-memory.png'});
 await p.keyboard.press('Escape');const index=await p.evaluate(()=>lunaCampaign.dialog.index);await p.keyboard.press('Escape');assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),index);
 const seen=await p.evaluate(()=>{const c=lunaCampaign,rows=[];while(c.dialog?.background==='johnny-memory'&&!c.memoryTransition){rows.push(c.dialog.rows[c.dialog.index].text);c.dialog.chars=1e5;c.next();}return rows;});assert(seen.some(t=>t.includes('45')));assert(seen.some(t=>t.includes('5ml')));assert(seen.some(t=>t.includes('각설탕')));
 await p.waitForFunction(()=>lunaCampaign.dialog?.background==='terrace'&&!lunaCampaign.memoryTransition);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.index),12);assert.equal(await p.evaluate(()=>lunaCampaign.dialog.rows[12].text),'…');assert.equal(await p.evaluate(()=>barGame.progress.money),2300);assert(await p.evaluate(()=>barGame.progress.flags.campaign_observation));
 await p.evaluate(()=>{lunaCampaign.dialog.chars=1e5;lunaCampaign.next();});await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading&&!lunaCampaign.dayTransition&&['game','developer'].includes(lunaCampaign.view)&&outsidePlaytest.model.config.day===3,null,{timeout:20000});assert.equal(await p.evaluate(()=>outsidePlaytest.model.near.id),'sofa');assert.equal(await p.evaluate(()=>barGame.progress.money),2300);assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.flow),'in');
}
assert(await p.evaluate(()=>LunaOutsideQA.catalog().some(c=>c.id==='runtime:night2')));assert.deepEqual(errors,[]);console.log('DAY2_TERRACE_MEMORY_OK A/B/developer: terrace -> Johnny POV bar memory26 -> terrace exact resume -> day3 sofa, money unchanged, QA catalog');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
