const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await p.goto('http://127.0.0.1:8123/bar-playtest/?mode=outside');await p.locator('.updates-confirm').click();await p.selectOption('#outside-day','2');await p.locator('[data-outside-action="start"]').click();await p.waitForFunction(()=>!outsidePlaytest.loading);
 const barBefore=await p.evaluate(()=>JSON.stringify({progress:barGame.progress,day:barGame.day,phase:barGame.phase}));
 async function at(id){await p.evaluate(id=>{const m=outsidePlaytest.model,t=m.targets().find(t=>t.id===id);if(!t)throw Error('No target '+id);m.x=t.x;m.updateNear();},id);await p.waitForTimeout(700);await p.keyboard.press('KeyE');}
 async function finish(){for(let i=0;i<100&&await p.evaluate(()=>outsidePlaytest.model.story.blocking);i++){if(await p.evaluate(()=>outsidePlaytest.model.story.speech.choice))await p.locator('[data-outside-action="choice-leave"]').click();else await p.keyboard.press('KeyE');}assert(!await p.evaluate(()=>outsidePlaytest.model.story.blocking));}
 // Reach Shiba using real walking, then ensure E reveals text and advances once.
 await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyA');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='shiba');await p.keyboard.up('KeyA');await p.keyboard.up('ShiftLeft');await p.keyboard.press('KeyE');await p.waitForTimeout(150);assert(await p.locator('.outside-speech').isVisible());await p.keyboard.press('KeyE');assert.equal(await p.locator('.outside-speech strong').innerText(),'시바');await p.keyboard.press('Space');await p.waitForTimeout(60);assert((await p.locator('.outside-speech-text').innerText()).includes('뭘 봐'));await p.screenshot({path:'/private/tmp/outside-story-shiba.jpg',type:'jpeg',quality:80});
 const x=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyD');await p.waitForTimeout(150);await p.keyboard.up('KeyD');assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),x);await p.evaluate(()=>outsidePlaytest.model.story.cancel());assert(!await p.evaluate(()=>outsidePlaytest.model.story.flags.shiba_met));await at('shiba');await finish();await at('shiba');for(let i=0;i<20&&!await p.evaluate(()=>outsidePlaytest.model.story.speech.choice);i++)await p.keyboard.press('KeyE');assert(await p.locator('[data-outside-action="choice-treat"]').isDisabled());await p.screenshot({path:'/private/tmp/outside-story-choice.jpg',type:'jpeg',quality:80});await p.locator('[data-outside-action="choice-leave"]').click();await finish();
 await at('poster');await p.keyboard.press('Space');await p.waitForTimeout(100);assert((await p.locator('.outside-speech-text').innerText()).includes('Bc25'));await p.screenshot({path:'/private/tmp/outside-story-poster.jpg',type:'jpeg',quality:80});await finish();await at('poster');await finish();await at('experiment');await p.keyboard.press('Space');await finish();assert(await p.evaluate(()=>outsidePlaytest.model.targets().some(t=>t.id==='experiment')));await at('experiment');assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.id),'ob_experiment_1');await finish();
 await p.evaluate(()=>outsidePlaytest.model.start({place:'home',day:0,flow:'out'}));await p.waitForTimeout(100);await p.evaluate(()=>{outsidePlaytest.model.x=1.22;});await p.waitForFunction(()=>!!outsidePlaytest.model.backgroundStory.speech);await p.waitForTimeout(600);assert((await p.locator('.outside-background-text').innerText()).includes('실종'));await p.screenshot({path:'/private/tmp/outside-story-tv.jpg',type:'jpeg',quality:80});
 for(const viewport of [{width:600,height:800},{width:960,height:540}]){await p.setViewportSize(viewport);await p.waitForTimeout(150);assert(await p.locator('.outside-background-speech').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));}await p.setViewportSize({width:1280,height:720});await p.evaluate(()=>{const m=outsidePlaytest.model;for(let i=0;i<1800;i++)m.tick(1/60);m.x=-.1;m.tick(.02);m.x=1.22;m.tick(.02);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.backgroundStory.speech.id),'np_tv_2');
 await p.evaluate(()=>outsidePlaytest.model.start({place:'bar',day:0,flow:'out'}));await at('elevator');await p.waitForTimeout(3300);assert(await p.locator('.outside-speech').isVisible());assert.equal(await p.locator('.outside-speech strong').innerText(),'라디오');await p.screenshot({path:'/private/tmp/outside-story-radio.jpg',type:'jpeg',quality:80});await p.keyboard.press('Escape');let time=await p.evaluate(()=>outsidePlaytest.model.story.speech.elapsed);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>outsidePlaytest.model.story.speech.elapsed),time);await p.keyboard.press('Escape');await p.waitForFunction(()=>!outsidePlaytest.model.ride,{},{timeout:18000});assert(await p.evaluate(()=>!!outsidePlaytest.model.story.speech));await at('home');await p.waitForFunction(()=>outsidePlaytest.model.scene==='home'&&!outsidePlaytest.model.transition);assert(!await p.evaluate(()=>outsidePlaytest.model.story.speech));assert(await p.locator('.outside-speech').isHidden());assert.deepEqual(errors,[]);assert.equal(await p.evaluate(()=>JSON.stringify({progress:barGame.progress,day:barGame.day,phase:barGame.phase})),barBefore);
 console.log('PASS browser story: real walk/E/Space, typing, movement lock, cancel, choices, posters, TV, responsive bubbles, radio ride/pause/cleanup and bar isolation');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
