const{chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));p.on('response',r=>{if(r.status()>=400)errors.push(r.status()+' '+r.url());});await p.goto(process.env.LUNA_TEST_URL||'http://127.0.0.1:8123/bar-playtest/');await p.locator('.updates-confirm').click();
const click=a=>p.locator('[data-outside-action="'+a+'"]:not([inert] *)').filter({visible:true}).first().click();
await p.locator('[data-act="version"][data-id="outside"]').click();await p.waitForTimeout(250);assert.equal(await p.locator('.version-tabs button.selected').count(),1);assert.equal(await p.locator('.version-tabs button.selected').getAttribute('data-id'),'outside');await p.screenshot({path:'/private/tmp/outside-lobby-final.jpg',type:'jpeg',quality:80});
const barBefore=await p.evaluate(()=>JSON.stringify({progress:barGame.progress,day:barGame.day,phase:barGame.phase}));
for(const place of ['bar','homeDoor','home'])for(const flow of ['in','out'])for(const day of [0,1,2,3]){await p.selectOption('#outside-place',place);await p.selectOption('#outside-flow',flow);await p.selectOption('#outside-day',String(day));await click('start');await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading);assert.deepEqual(await p.evaluate(()=>outsidePlaytest.model.config),{place,flow,day});assert(await p.locator('#app').isHidden());await p.keyboard.press('Escape');await click('exit');assert.equal(await p.locator('#outside-root').count(),0);}
console.log('PASS browser: all 24 lobby configurations and cleanup');
await p.selectOption('#outside-place','bar');await p.selectOption('#outside-flow','out');await p.selectOption('#outside-day','1');await click('start');await p.waitForFunction(()=>!outsidePlaytest.loading);
await p.keyboard.down('KeyA');await p.waitForTimeout(350);await p.keyboard.up('KeyA');assert((await p.evaluate(()=>outsidePlaytest.model.x))<.95);await p.waitForTimeout(60);assert.equal(await p.evaluate(()=>outsidePlaytest.model.anim),'idle');
// Walk to the elevator with real held keyboard input, not a teleported screenshot.
await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyA');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='elevator',{},{timeout:20000});await p.keyboard.up('KeyA');await p.keyboard.up('ShiftLeft');await p.keyboard.press('KeyE');assert(await p.evaluate(()=>!!outsidePlaytest.model.ride));
await p.waitForTimeout(1200);await p.keyboard.press('Escape');let y=await p.evaluate(()=>outsidePlaytest.model.elevatorY);await p.waitForTimeout(200);assert.equal(await p.evaluate(()=>outsidePlaytest.model.elevatorY),y);await p.keyboard.press('Escape');await p.waitForTimeout(4300);await p.screenshot({path:'/private/tmp/outside-elevator-final.jpg',type:'jpeg',quality:80});await p.waitForFunction(()=>!outsidePlaytest.model.ride,{},{timeout:15000});assert.equal(await p.evaluate(()=>outsidePlaytest.model.level),1);
await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyA');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='home',{},{timeout:8000});await p.keyboard.up('KeyA');await p.keyboard.up('ShiftLeft');await p.screenshot({path:'/private/tmp/outside-home-door-final.jpg',type:'jpeg',quality:80});await p.keyboard.press('KeyE');await p.waitForFunction(()=>outsidePlaytest.model.scene==='home'&&!outsidePlaytest.model.transition);await p.screenshot({path:'/private/tmp/outside-home-entry-final.jpg',type:'jpeg',quality:80});
await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='sofa',{},{timeout:6000});await p.keyboard.up('KeyD');await p.keyboard.up('ShiftLeft');await p.keyboard.press('KeyE');await p.getByRole('dialog',{name:'소파'}).waitFor();await p.keyboard.press('KeyE');await p.waitForTimeout(700);await p.screenshot({path:'/private/tmp/outside-home-final.jpg',type:'jpeg',quality:80});
await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyA');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='exit',{},{timeout:6000});await p.keyboard.up('KeyA');await p.keyboard.up('ShiftLeft');await p.keyboard.press('KeyE');await p.waitForFunction(()=>outsidePlaytest.model.scene==='street'&&!outsidePlaytest.model.transition);
await p.keyboard.down('ShiftLeft');await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='elevator',{},{timeout:8000});await p.keyboard.up('KeyD');await p.keyboard.up('ShiftLeft');await p.keyboard.press('KeyE');await p.waitForFunction(()=>!outsidePlaytest.model.ride,{},{timeout:18000});assert.equal(await p.evaluate(()=>outsidePlaytest.model.level),0);
console.log('PASS browser: real-input street → elevator → house → elevator round trip');
// Keyboard release and focus loss must not leave movement held.
const x0=await p.evaluate(()=>outsidePlaytest.model.x);await p.keyboard.down('KeyD');await p.waitForTimeout(1700);await p.keyboard.up('KeyD');assert((await p.evaluate(()=>outsidePlaytest.model.x))>x0+.8);await p.waitForTimeout(70);const x1=await p.evaluate(()=>outsidePlaytest.model.x);await p.waitForTimeout(100);assert.equal(await p.evaluate(()=>outsidePlaytest.model.x),x1);
await p.keyboard.down('KeyD');await p.evaluate(()=>window.dispatchEvent(new Event('blur')));await p.keyboard.up('KeyD');assert(await p.evaluate(()=>outsidePlaytest.model.paused));await click('menu');
for(const viewport of [{width:960,height:540},{width:600,height:800},{width:1600,height:900}]){await p.setViewportSize(viewport);await p.waitForTimeout(100);assert(await p.locator('.outside-stage').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=-1&&r.top>=-1&&r.right<=innerWidth+1&&r.bottom<=innerHeight+1;}));await p.keyboard.press('Escape');assert(await p.locator('.outside-dialog').evaluate(e=>{const r=e.getBoundingClientRect();return r.left>=0&&r.top>=0&&r.right<=innerWidth&&r.bottom<=innerHeight;}));await click('menu');}
await p.keyboard.press('Escape');await click('exit');assert.equal(await p.evaluate(()=>JSON.stringify({progress:barGame.progress,day:barGame.day,phase:barGame.phase})),barBefore);
for(const tab of ['gpt','minigames','original']){await p.locator('[data-act="version"][data-id="'+tab+'"]').click();assert.equal(await p.locator('.version-tabs button.selected').getAttribute('data-id'),tab);}
await p.locator('[data-act="start"]').click();await p.waitForFunction(()=>barGame.phase!=='ready');assert(!await p.evaluate(()=>outsidePlaytest.active));assert(!await p.locator('#app').isHidden());assert.deepEqual(errors,[]);
console.log('PASS browser: keyboard release, blur pause, responsive layout, bar isolation and original start; no errors');
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
