const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
for(const type of ['pour','fill_up'])for(const target of ['open-tests','closed-tests','sound','camera']){
 await p.evaluate(type=>{barGame.startMinigame(type,'original');lunaCampaign.render(true);},type);
 const tests=p.locator('.pour-tests-toggle');assert.equal(await p.locator('.pour-tools-toggle,[data-act="pourTool"]').count(),0);
 {await tests.click();if(target==='closed-tests')await tests.click();if(target==='sound')await p.locator('[data-act="pourSound"][data-id="2"]').click();if(target==='camera')await p.locator('[data-act="pourPresentation"][data-id="bottle"]').click();}
 const snapshot=()=>p.evaluate(()=>({tests:!!barGame.gimmick.pourTestsOpen,tool:barGame.gimmick.fluid.tool,sound:document.querySelector('[data-act="pourSound"][aria-pressed="true"]').dataset.id,camera:document.querySelector('[data-act="pourPresentation"][aria-pressed="true"]').dataset.id}));
 const before=await snapshot();await p.keyboard.down('Space');assert.equal(await p.evaluate(()=>barGame.gimmick.held),true,target);await p.keyboard.down('Space');await p.waitForFunction(()=>barGame.gimmick.fluid.emittedMl>0,null,{timeout:5000});await p.keyboard.up('Space');assert.equal(await p.evaluate(()=>barGame.gimmick.held),false,target);assert.deepEqual(await snapshot(),before,target+' must not activate or toggle controls');
}
await p.evaluate(()=>{barGame.startMinigame('pour','original');lunaCampaign.render(true);});await p.locator('.pour-tests-toggle').focus();await p.keyboard.press('Enter');assert.equal(await p.locator('.pour-tests-toggle').getAttribute('aria-expanded'),'true');assert.equal(await p.evaluate(()=>barGame.gimmick.started),false);
assert.deepEqual(errors,[]);console.log('POUR_SPACE_OK: pour/fill-up, four focus cases, hold/release/repeat, no settings activation, Enter retained');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
