const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
async function start(day=0,variant='original',skip=false){await p.evaluate(({day,variant,skip})=>{const g=barGame;g.reset(day,'practice',1,true,{variant});g.progress.flags.day0_skip_tutorial=skip;g.currentOrder={actor:'chris',cocktail:'gin_tonic',seat:'R'};g.selectCocktail('gin_tonic');g.debugFill();g.startCraft();lunaCampaign.render(true);},{day,variant,skip});}
async function step(name){await p.locator('.pour-tutorial[data-step="'+name+'"]:not([hidden])').waitFor();const box=await p.locator('.pour-tutorial-card').boundingBox();assert(box.x>=0&&box.y>=0&&box.x+box.width<=p.viewportSize().width+1&&box.y+box.height<=p.viewportSize().height+1,name+' card in viewport');}
await start();await step('target');assert((await p.locator('.pour-tutorial-card').innerText()).includes('±5 ml'));assert.equal(await p.evaluate(()=>barGame.gimmick.started),false);await p.screenshot({path:'/private/tmp/pour-tutorial-target.png'});
await p.locator('[data-act="pourTutorialNext"]').click();await step('open');await p.locator('.pour-tools-toggle').click();await step('remove');await p.screenshot({path:'/private/tmp/pour-tutorial-remove.png'});await p.locator('[data-act="pourTool"][data-id="none"]').click();await step('attachOpen');assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.tool),'none');assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.caughtMl),0);await p.locator('.pour-tools-toggle').click();await step('attach');await p.locator('[data-act="pourTool"][data-id="pourer"]').click();await step('pour');assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.tool),'pourer');assert.equal(await p.evaluate(()=>barGame.gimmick.started),false);await p.screenshot({path:'/private/tmp/pour-tutorial-pour.png'});
await p.keyboard.down('Space');await p.waitForFunction(()=>barGame.gimmick.fluid.caughtMl>5);await p.keyboard.up('Space');await step('finish');await p.screenshot({path:'/private/tmp/pour-tutorial-finish.png'});await p.keyboard.down('Space');await step('pour');await p.keyboard.up('Space');await step('finish');await p.locator('[data-act="endGimmick"]').click();await p.waitForFunction(()=>barGame.progress.flags.day0_pour_taught===true);assert.equal(await p.evaluate(()=>barGame.logs.filter(x=>x.event==='tutorial_complete'&&x.kind==='pour').length),1);assert.equal(await p.locator('.pour-tutorial:not([hidden])').count(),0);
for(const [day,variant,skip]of [[0,'gpt',false],[1,'original',false],[0,'original',true]]){await start(day,variant,skip);assert.equal(await p.evaluate(()=>!!barGame.gimmick.pourTutorial),false);}
await p.evaluate(()=>{barGame.startMinigame('pour','original');lunaCampaign.render(true);});assert.equal(await p.evaluate(()=>!!barGame.gimmick.pourTutorial),false);
// Space is never repurposed as the introduction's Continue action.
await start();await step('target');await p.locator('[data-act="pourTutorialNext"]').focus();await p.keyboard.down('Space');assert.equal(await p.evaluate(()=>barGame.gimmick.held),true);await p.keyboard.up('Space');await step('pour');assert.equal(await p.evaluate(()=>!!barGame.gimmick.pourToolsOpen),false);
await p.keyboard.press('Escape');assert.equal(await p.locator('.pour-tutorial:not([hidden])').count(),0);await p.keyboard.press('Escape');await step('pour');for(const vp of [{width:960,height:540},{width:600,height:800}]){await p.setViewportSize(vp);await start();await step('target');await p.locator('[data-act="pourTutorialNext"]').click();await step('open');await p.locator('.pour-tools-toggle').click();await step('remove');await p.locator('[data-act="pourTool"][data-id="none"]').click();await step('attachOpen');await p.locator('.pour-tools-toggle').click();await step('attach');await p.locator('[data-act="pourTool"][data-id="pourer"]').click();await step('pour');}assert.deepEqual(errors,[]);console.log('POUR_TUTORIAL_OK six steps, real detach/attach, zero volume during instructions, Space/release/topup/finish, one-time completion, GPT/day1/skip/minigame exclusions, pause');}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
