const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const assert=require('node:assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await browser.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();await p.locator('[data-act="day"][data-id="99"]').click();await p.locator('.qa-launch').click();await p.screenshot({path:'/private/tmp/luna-qa-bar.png'});
 for(const id of await p.evaluate(()=>LunaQALab.STATES.map(s=>s[0]))){await p.evaluate(id=>lunaQA.runSituation(id),id);await p.waitForTimeout(180);console.log('STATE',id,await p.evaluate(()=>({phase:barGame.phase,screen:barGame.screen,error:barGame.error,seats:Object.values(barGame.seats).filter(Boolean).map(s=>s.state)})));assert(!await p.evaluate(()=>barGame.error));}
 await p.evaluate(()=>lunaQA.open('animations'));for(const actor of await p.evaluate(()=>Object.keys(barData.characterLayers))){await p.selectOption('[data-qa-field="actor"]',actor);for(const pose of await p.locator('[data-qa-field="pose"] option').evaluateAll(ns=>ns.map(n=>n.value))){await p.selectOption('[data-qa-field="pose"]',pose);assert(await p.locator('.qa-actor-canvas .actor-layer').count()>0);}}
 await p.screenshot({path:'/private/tmp/luna-qa-animation.png'});await p.keyboard.press('Escape');
 await p.evaluate(()=>{outsidePlaytest.config.day=99;outsidePlaytest.start();});await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading);assert.equal(await p.evaluate(()=>outsidePlaytest.model.config.day),99);
 const ids=await p.evaluate(()=>LunaOutsideQA.catalog().map(c=>c.id));for(const id of ids){await p.evaluate(id=>{outsidePlaytest.model.start({day:99,qaCase:id});const m=outsidePlaytest.model,t=LunaOutsideQA.target(m);m.x=t.x-.25;m.updateNear();if(!LunaOutsideQA.catalog().find(c=>c.id===id).auto)m.interact();},id);await p.waitForTimeout(850);console.log('OUT',id,await p.evaluate(()=>({speech:outsidePlaytest.model.story.speech?.id,ride:!!outsidePlaytest.model.ride,transition:!!outsidePlaytest.model.transition,dialog:outsidePlaytest.model.dialog?.title,qa:outsidePlaytest.model.qa.caseId})));}
 await p.evaluate(()=>outsidePlaytest.model.start({day:99,qaCase:'runtime:commute2'}));await p.waitForTimeout(500);await p.screenshot({path:'/private/tmp/luna-qa-outside.png'});await p.locator('.qa-launch').click();await p.screenshot({path:'/private/tmp/luna-qa-outside-panel.png'});console.log('ERRORS',errors);assert.deepEqual(errors,[]);
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
