const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');const assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:800}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();
 const sceneErrors=await p.evaluate(()=>{const errors=[];for(const s of barData.tables.scenes){lunaQA.state.scene=s.id;lunaQA.state.step='0';try{lunaQA.runScene();if(barGame.error)errors.push([s.id,barGame.error]);}catch(e){errors.push([s.id,e.message]);}lunaCampaign.screen('developer');}return errors;});console.log('SCENE ENTRY ERRORS',sceneErrors);assert.deepEqual(sceneErrors,[]);
 const jumpErrors=await p.evaluate(()=>{const errors=[];for(const scene of barData.tables.scenes.filter(s=>s.id.startsWith('campaign_'))){const rows=barData.tables.steps.filter(r=>r.context===scene.id);for(let i=0;i<rows.length;i++){if(!['say','order','craft','serve','exit'].includes(rows[i].type))continue;lunaQA.state.scene=scene.id;lunaQA.state.step=String(i);try{lunaQA.runScene();if(barGame.error)errors.push([scene.id,i,rows[i].type,barGame.error]);}catch(e){errors.push([scene.id,i,rows[i].type,e.message]);}lunaCampaign.screen('developer');}}return errors;});console.log('STORY JUMP ERRORS',jumpErrors);assert.deepEqual(jumpErrors,[]);
 await p.evaluate(()=>{lunaQA.runSituation('serve');});assert(await p.evaluate(()=>!!barGame.drink&&barGame.seats.L.coaster));await p.waitForFunction(()=>!barGame.cameraMoving&&!barGame.cameraLeft);await p.locator('[data-act="serve"]').click();assert.equal(await p.evaluate(()=>barGame.seats.L.state),'REACTION');await p.evaluate(()=>{for(let i=0;i<400;i++)barGame.tick(.1);});assert(await p.evaluate(()=>barGame.transactions.length)>0);
 await p.evaluate(()=>lunaQA.runSituation('income'));await p.waitForTimeout(100);assert(await p.locator('.currency-hud').count());await p.evaluate(()=>lunaQA.runSituation('expense'));await p.waitForTimeout(100);assert(await p.locator('.currency-spending').count());
 await p.evaluate(()=>lunaQA.open('barks'));await p.selectOption('[data-qa-field="situation"]','call');await p.locator('[data-qa="bark"]').first().click();assert(await p.evaluate(()=>barGame.seats.L.lines[0].id));await p.evaluate(()=>{lunaQA.state.scene='t99_dialogue';lunaQA.state.step='0';lunaQA.runScene();});await p.waitForFunction(()=>!!barGame.dialogue&&!barGame.cameraMoving&&!barGame.cameraLeft&&!barGame.transition);await p.locator('.dialogue-box').hover();await p.locator('.dialogue-box').focus();assert.deepEqual(await p.locator('.dialogue-box').evaluate(e=>[getComputedStyle(e).outlineStyle,getComputedStyle(e).borderColor]),['none','rgba(0, 0, 0, 0)']);
 await p.evaluate(()=>lunaQA.open('animations'));await p.selectOption('[data-qa-field="actor"]','outside:luna');await p.selectOption('[data-qa-field="pose"]','walk');await p.waitForTimeout(350);assert.equal(await p.locator('.qa-preview canvas').count(),1);await p.locator('[data-qa="next"]').click();const n=await p.locator('[data-qa-field="frame"]').inputValue();await p.waitForTimeout(180);assert.equal(await p.locator('[data-qa-field="frame"]').inputValue(),n);await p.selectOption('[data-qa-field="actor"]','haru');assert(await p.locator('.qa-empty').count());await p.keyboard.press('Escape');
 await p.evaluate(()=>{outsidePlaytest.config.day=99;outsidePlaytest.start();});await p.waitForFunction(()=>outsidePlaytest.active&&!outsidePlaytest.loading);const progress=await p.evaluate(()=>JSON.stringify(barGame.progress));
 async function set(id,more={}){await p.evaluate(({id,more})=>{outsidePlaytest.model.start({day:99,qaCase:id,...more});outsidePlaytest.snapCamera();}, {id,more});}
 await set('np_shiba_3',{qaSnack:true});await p.keyboard.down('KeyD');await p.waitForFunction(()=>outsidePlaytest.model.near?.id==='qa-event');await p.keyboard.up('KeyD');await p.keyboard.press('KeyE');await p.waitForFunction(()=>outsidePlaytest.model.story.speech);for(let i=0;i<20&&!await p.evaluate(()=>outsidePlaytest.model.story.speech?.choice);i++)await p.keyboard.press('KeyE');assert(await p.locator('[data-outside-action="choice-treat"]').isEnabled());await p.locator('[data-outside-action="choice-treat"]').click();assert(await p.evaluate(()=>outsidePlaytest.model.story.flags.shiba_fed));
 await set('np_tv_1');await p.keyboard.down('KeyD');await p.waitForFunction(()=>!!outsidePlaytest.model.story.speech);await p.keyboard.up('KeyD');assert(await p.evaluate(()=>outsidePlaytest.model.story.speech.auto));assert(await p.evaluate(()=>outsidePlaytest.model.story.speech.rows.every(r=>r.actor==='radio')));
 await set('demo_out_pair_neon');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-.4;m.tick(.02);for(let i=0;i<2000;i++)m.tick(.05);});assert(!await p.evaluate(()=>outsidePlaytest.model.story.speech));await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=-2;m.tick(.02);m.x=-.5;m.tick(.02);});assert(await p.evaluate(()=>outsidePlaytest.model.story.speech));
 await set('lift-up');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.elevatorX;m.updateNear();m.interact();for(let i=0;i<280;i++)m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.level),1);assert(!await p.evaluate(()=>outsidePlaytest.model.ride));
 await set('home-in');await p.evaluate(()=>{const m=outsidePlaytest.model;m.x=LunaResidence.layout.homeX;m.updateNear();m.interact();for(let i=0;i<30;i++)m.tick(.05);});assert.equal(await p.evaluate(()=>outsidePlaytest.model.scene),'home');
 assert.equal(await p.evaluate(()=>JSON.stringify(barGame.progress)),progress);await p.locator('.qa-launch').click();await p.setViewportSize({width:390,height:844});await p.waitForTimeout(100);assert(await p.locator('.qa-panel').evaluate(el=>{const r=el.getBoundingClientRect();return r.left>=0&&r.right<=innerWidth&&r.top>=0&&r.bottom<=innerHeight;}));await p.screenshot({path:'/private/tmp/luna-qa-mobile.png'});console.log('PASS scene entries, intermediate jumps, serve/reaction, money, single focus outline, outside animations, shiba choices, TV, proximity replay, elevator, doors, isolation, mobile',errors);assert.deepEqual(errors,[]);
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
