const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('node:assert/strict');
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');if(await p.locator('.updates-confirm').count())await p.locator('.updates-confirm').click();
for(const mode of ['original','gpt','campaign']){
 await p.evaluate(mode=>{const c=lunaCampaign;c.session.uninstall();c.view=mode==='campaign'?'game':'developer';c.host.hidden=true;c.app.inert=false;c.ui.variant=mode==='gpt'?'gpt':'original';c.session.install({developer:mode!=='campaign'});barGame.reset(1,'regular',42,true,{variant:c.ui.variant});},mode);
 async function reach(target){await p.evaluate(target=>{const g=barGame;for(let n=0;n<5000;n++){g.cameraMoving=false;if(lunaCampaign.view==='menu'){lunaCampaign.action('drink:gin_tonic');continue;}if(g.error)throw Error(g.error);if(g.transition||g.cameraLeft){g.tick(.1);continue;}if(g.dialogue){if(g.dialogue.actor==='tom'&&(target==='first'||target==='intro'&&g.dialogue.text==='톰이야.'||target==='known'&&g.progress.flags.tom_name_known))return;g.advance();g.advance();continue;}if(g.currentOrder&&g.story.steps[g.story.index].type==='craft'){const o=g.currentOrder;g.openRecipes();g.selectCocktail(o.cocktail);g.debugCraft('good');g.offer();g.serve(o.seat,'drag');continue;}g.tick(.1);}throw Error('Target not reached: '+target);},target);await p.waitForTimeout(100);}
 await reach('first');assert.equal(await p.locator('.dialogue-box .speaker').textContent(),'???');
 await reach('intro');assert.equal(await p.locator('.dialogue-box .speaker').textContent(),'???');await p.evaluate(()=>{barGame.dialogue.chars=barGame.dialogue.text.length;barGame.advance();});
 await reach('known');assert.equal(await p.locator('.dialogue-box .speaker').textContent(),await p.evaluate(()=>barGame.name('tom')));await p.screenshot({path:'/private/tmp/tom-name-'+mode+'.png'});
}
assert.deepEqual(errors,[]);console.log('PASS original/GPT/main: Tom is ??? through introduction, then revealed in actual dialogue UI');
}finally{await b.close()}})().catch(e=>{console.error(e);process.exitCode=1});
