const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
(async()=>{const browser=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true,args:['--mute-audio']});try{for(const renderer of ['webgl','canvas2d']){const p=await browser.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.stack));if(renderer==='canvas2d')await p.addInitScript(()=>{const old=HTMLCanvasElement.prototype.getContext;HTMLCanvasElement.prototype.getContext=function(type,...args){return type==='webgl'?null:old.call(this,type,...args);};});await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1');await p.locator('.updates-confirm').click();await p.evaluate(()=>{barGame.startMinigame('pour','original');lunaCampaign.render(true);});await p.locator('[data-fluid-stage]').waitFor();await p.waitForTimeout(250);
assert.equal(await p.locator('[data-act="pourPresentation"]').first().isVisible(),false);assert.equal(await p.locator('.pour-tests-toggle').innerText(),'테스트 변경');assert.equal(await p.locator('[data-fluid-stage]').getAttribute('data-pour-tool'),'pourer');await p.evaluate(()=>window.pourCanvas=document.querySelector('.pour-front'));
await p.locator('.pour-tools-toggle').click();await p.waitForTimeout(350);assert.equal(await p.locator('.pour-tools-toggle').getAttribute('aria-expanded'),'true');for(const preview of await p.locator('.pour-tool-preview').all()){const r=await preview.boundingBox();assert(Math.abs(r.width-r.height)<1);}assert.equal(await p.locator('[data-act="pourTool"][data-id="none"] svg').count(),0);assert.equal(await p.locator('[data-act="pourTool"][data-id="pourer"] svg').count(),1);await p.screenshot({path:'/private/tmp/pour-tool-drawer-'+renderer+'.png'});
await p.locator('[data-act="pourTool"][data-id="none"]').focus();await p.keyboard.press('Enter');assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.tool),'none');assert.equal(await p.evaluate(()=>barGame.gimmick.started),false);assert.equal(await p.locator('.pour-tools-toggle').getAttribute('aria-expanded'),'false');
await p.locator('.pour-tests-toggle').click();await p.locator('[data-act="pourSound"][data-id="2"]').click();assert.equal(await p.locator('[data-act="pourSound"][data-id="2"]').getAttribute('aria-pressed'),'true');await p.screenshot({path:'/private/tmp/pour-test-settings-'+renderer+'.png'});
for(const mode of ['classic','clean','bottle']){await p.locator('[data-act="pourPresentation"][data-id="'+mode+'"]').click();await p.waitForFunction(mode=>document.querySelector('[data-fluid-stage]')?.dataset.presentation===mode,mode);}
await p.keyboard.press('Escape');assert.equal(await p.locator('.pour-test-panel').isVisible(),false);assert.equal(await p.evaluate(()=>barGame.overlay),null);assert(await p.evaluate(()=>window.pourCanvas===document.querySelector('.pour-front')));
// Keyboard pouring is available again after leaving the panel; mid-pour swaps are disabled.
await p.keyboard.press('Tab');await p.locator('.pour-hold').focus();await p.keyboard.down('Space');await p.waitForTimeout(1900);await p.keyboard.up('Space');assert((await p.evaluate(()=>barGame.gimmick.fluid.emittedMl))>20);await p.locator('.pour-tools-toggle').click();assert(await p.locator('[data-act="pourTool"][data-id="pourer"]').isDisabled());await p.waitForFunction(()=>barGame.gimmick.angle===0);await p.waitForFunction(()=>!document.querySelector('[data-act="pourTool"][data-id="pourer"]').disabled);await p.locator('[data-act="pourTool"][data-id="pourer"]').click();assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.tool),'pourer');
for(const tool of ['pourer','none']){await p.evaluate(tool=>{const g=barGame;g.gimmick.angle=0;g.gimmick.held=false;g.setPourTool(tool);g.gimmick.started=true;g.gimmick.held=true;for(let i=0;i<180;i++)g.tick(1/120);g.gimmick.held=false;window.savedTick=g.tick;g.tick=()=>{};g.changed();},tool);await p.waitForTimeout(150);const state=await p.evaluate(()=>{const s=barGame.gimmick,stage=document.querySelector('[data-fluid-stage]'),cam=JSON.parse(stage.dataset.camera),n=LunaPour.nozzle(s.angle,s.fluid.tool);return{x:n.x*cam.scale+cam.x,y:n.y*cam.scale+cam.y,renderer:stage.dataset.renderer,rate:s.fluid.rate,error:s.fluid.audit().error,width:Math.max(...s.fluid.particles.filter(p=>p.stream===s.fluid.streamSerial).map(p=>p.emissionWidth||1))};});assert.equal(state.renderer,renderer);assert(Math.abs(state.x-500)<1e-8&&Math.abs(state.y-270)<1e-8);assert(Math.abs(state.error)<1e-6);assert.equal(state.width,tool==='none'?2:1);await p.screenshot({path:'/private/tmp/pour-tool-'+tool+'-'+renderer+'.png'});await p.evaluate(()=>{barGame.tick=window.savedTick;barGame.gimmick.held=false;for(let i=0;i<240;i++)barGame.tick(1/120);});}
// Reopening settings and changing tools preserve measured volume, including fill-up.
await p.evaluate(()=>{barGame.startMinigame('fill_up','gpt');lunaCampaign.render(true);});assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.tool),'pourer');assert.equal(await p.locator('.pour-tests-toggle').getAttribute('aria-expanded'),'false');await p.locator('.pour-tools-toggle').click();await p.locator('[data-act="pourTool"][data-id="none"]').click();assert.equal(await p.evaluate(()=>barGame.gimmick.fluid.rate/barGame.gimmick.fluid.baseRate),4);
for(const [width,height]of [[960,540],[600,800],[1920,1080]]){await p.setViewportSize({width,height});await p.locator('.pour-tools-toggle').click();await p.waitForTimeout(350);const box=await p.locator('.pour-tools-panel').boundingBox();assert(box.x>=-1&&box.y>=0&&box.x+box.width<=width+1&&box.y+box.height<=height+1);await p.keyboard.press('Escape');await p.locator('.pour-tests-toggle').click();const t=await p.locator('.pour-test-panel').boundingBox();assert(t.x>=0&&t.y>=0&&t.x+t.width<=width&&t.y+t.height<=height);await p.keyboard.press('Escape');}
assert.deepEqual(errors,[]);console.log('POUR_TOOLS_UI_OK',renderer,'panels, keyboard, 1:1 previews, 4x flow, camera mouth, fill-up, responsive');await p.close();}}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
