const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const root=require('path').resolve(__dirname,'..'),C=require(root+'/core.js'),R=require(root+'/remix.js');
function setup(version,day,mode='full'){const box={window:{}};for(const f of ['data.js','campaign-data.js','campaign-engine.js'])vm.runInNewContext(fs.readFileSync(root+'/'+f,'utf8'),box);const D=C.millilitreData(box.window.LUNA_DATA),g=new C.Game(D);R.attach(g);const s=new box.window.LunaCampaignEngine.Session(g,D,box.window.LUNA_CAMPAIGN_DATA);s.install({serviceVersion:version});s.onStep=step=>{if(step.type==='campaign_menu')g.progress.flags.campaign_selected_drink='gin_tonic';if(step.type==='campaign_memory')g.progress.flags.campaign_observation=true;s.finishStep();};s.beginDay(day);if(mode!=='full')g.reset(day,mode,1,true,{variant:'original',serviceVersion:version});return {g,s,D};}
function run(version,day,{timeouts=false,mode='full'}={}){const {g,s,D}=setup(version,day,mode),before=JSON.stringify(D.tables),drinks=[],lines=[];let last=null;
 const tick=()=>{g.cameraMoving=false;g.tick(.1);assert.equal(g.error,null);};
 for(let i=0;i<40000&&!g.finished;i++){
  if(g.pendingDailyUnlocks){g.confirmDailyUnlocks();continue;}if(g.transition||g.cameraLeft){tick();continue;}g.cameraMoving=false;
  if(g.choice){g.choose(2);continue;}if(g.dialogue){if(last!==g.dialogue&&g.phase==='regular')lines.push([g.dialogue.actor,g.dialogue.text]);last=g.dialogue;g.advance();g.advance();continue;}
  if(g.phase==='general'){if(!timeouts){const w=Object.entries(g.seats).find(([k,v])=>v&&['WAIT_COASTER','WAIT_SERVE'].includes(v.state));if(w){const [seat,v]=w;if(g.focus!==seat){g.focusSeat(seat);tick();continue;}if(v.state==='WAIT_COASTER'){g.coaster(seat);tick();continue;}if(v.order&&g.screen==='bar'){drinks.push('general');g.openRecipes();g.selectCocktail(v.order.cocktail);g.debugCraft('good');g.offer();assert(g.serve(seat));continue;}}}tick();continue;}
  if(g.currentOrder&&g.story?.steps[g.story.index]?.type==='craft'){const o=g.currentOrder;drinks.push(o.actor);g.openRecipes();g.selectCocktail(o.cocktail);g.debugCraft('good');g.offer();assert(g.serve(o.seat,'drag'));continue;}tick();
 }
 assert(g.finished,'stalled '+JSON.stringify({day,version,phase:g.phase,step:g.story?.steps[g.story.index],resume:g.mixedResume}));assert.equal(g.error,null);assert.equal(JSON.stringify(D.tables),before,'author data mutated');assert.equal(g.transactions.find(t=>t.payment==='none')?.net,day===1?0:undefined);
 return {g,s,lines,drinks};
}
const a=run('A',1),b=run('B',1);assert.deepEqual(a.drinks,['general','general','general','general','shiba','tom','aili']);assert.deepEqual(b.drinks,['general','general','shiba','general','tom','aili']);assert.deepEqual(b.lines,a.lines);assert.equal(b.g.logs.filter(x=>x.event==='guest_enter').length,3);assert.deepEqual(b.g.logs.filter(x=>x.event==='mixed_service_block').map(x=>x.block),['general-2','shiba','general-1','tom-aili-chris']);assert.equal(b.g.transactions.length,6);assert.equal(b.g.progress.money,b.g.openingBalance+b.g.transactions.reduce((n,t)=>n+t.net,0));assert(b.s.settle());const cash=b.g.progress.money;assert.equal(b.s.settle(),false);assert.equal(b.g.progress.money,cash);assert(b.s.endDay());b.s.beginDay(2,b.s.carry);assert.equal(b.g.serviceVersion,'B');assert.equal(b.g.mixedService(),false);
for(const day of [0,2,3]){const x=run('A',day),y=run('B',day);assert.deepEqual(y.drinks,x.drinks);assert.deepEqual(y.lines,x.lines);assert.equal(y.g.progress.money,x.g.progress.money);assert.equal(y.g.logs.some(l=>l.event==='mixed_service_block'),false);}
const timeout=run('B',1,{timeouts:true});assert.deepEqual(timeout.drinks,['shiba','tom','aili']);assert.equal(timeout.g.lost,3);assert.equal(timeout.g.mixedResume,null);
assert.deepEqual(run('B',1,{mode:'general'}).drinks,b.drinks);assert.deepEqual(run('B',1,{mode:'regular'}).drinks,['shiba','general','tom','aili']);
const retry=setup('B',1);retry.s.retry();assert.equal(retry.g.serviceVersion,'B');assert.equal(retry.g.mixedResume,null);console.log('SERVICE_AB_CORE_OK A unchanged / B 2-Shiba-1-Tom-Aili / identical dialogue / no data mutation / funds+one settlement / day0,2,3 unchanged / timeouts / entry modes / retry / next day');
