const {chromium}=require('/Users/lee/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright'),assert=require('assert/strict');
const near=(a,b,msg)=>assert(Math.abs(a-b)<.04,`${msg}: ${a} != ${b}`);
(async()=>{const b=await chromium.launch({executablePath:'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});try{
const p=await b.newPage({viewport:{width:1280,height:720}}),errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto('http://127.0.0.1:8123/bar-playtest/?dev=1&mode=outside');await p.locator('.updates-confirm').click();
await p.evaluate(async()=>{await outsidePlaytest.start();const a=outsidePlaytest,m=a.model;m.x=LunaOutside.viewpoint.x;m.updateNear();a.snapCamera();m.backgroundStory.beginRows('world-test',{id:'world-test',x:-8.55,y:-.7},[{type:'say',actor:'sign',text:'카메라가 움직여도 같은 월드 위치와 크기입니다.'}],true);a.tick(0);});
const outside=()=>p.evaluate(()=>{const a=outsidePlaytest,el=document.querySelector('.outside-background-speech'),r=el.getBoundingClientRect(),s=4.8/a.camera.w,anchor=a.model.backgroundStory.view().anchor;return {x:a.camera.x+(r.x+r.width/2-640)*a.camera.w/1280,y:a.camera.y-(r.bottom+22*s-360)*a.camera.w/1280,w:r.width*a.camera.w/1280,h:r.height*a.camera.w/1280,layout:el.offsetWidth,anchor,hidden:el.hidden};});
const before=await outside();await p.keyboard.press('y');await p.evaluate(()=>{for(let i=0;i<100;i++)outsidePlaytest.tick(.01);});const zoom=await outside();near(before.w,zoom.w,'outside world width');near(before.h,zoom.h,'outside world height');near(zoom.x,zoom.anchor.x,'outside anchor x');near(zoom.y,zoom.anchor.y,'outside anchor y');assert.equal(before.layout,zoom.layout);
await p.evaluate(()=>{const a=outsidePlaytest;a.model.x=-3;a.snapCamera();a.tick(0);});const off=await outside();near(off.x,before.x,'offscreen anchor');near(off.w,before.w,'offscreen width');assert(!off.hidden);await p.screenshot({path:'/private/tmp/world-speech-offscreen.png'});
await p.evaluate(()=>{outsidePlaytest.exit(true);barGame.reset(99,'practice',1,true);const g=barGame;g.screen='bar';g.phase='regular';g.dialogSpeed=.00001;g.seats={L:{actor:'port',state:'STORY'},M:null,R:null};g.dialogue=g.makeLine('port','월드에 고정된 바 말풍선입니다. 긴 대사도 카메라와 함께 움직입니다.');});
await p.waitForFunction(()=>document.querySelector('.dialogue-wrap')&&!barGame.cameraMoving);
const bar=()=>p.evaluate(()=>{const el=document.querySelector('.dialogue-wrap'),r=el.getBoundingClientRect(),m=new DOMMatrixReadOnly(getComputedStyle(document.querySelector('.counter-plane')).transform);return {worldW:r.width/m.a,x:(r.x+r.width/2-m.e)/m.a,y:(r.bottom-m.f)/m.d,anchor:Number(el.dataset.worldX),layout:el.offsetWidth};});
const close=await bar();await p.evaluate(()=>barGame.seats.R={actor:'aili',state:'STORY'});await p.waitForTimeout(800);const wide=await bar();near(close.worldW,wide.worldW,'bar world width');near(close.x,wide.x,'bar world x');near(close.y,wide.y,'bar world y');near(wide.x,wide.anchor,'bar seat anchor');assert.equal(close.layout,wide.layout);await p.screenshot({path:'/private/tmp/world-speech-bar-wide.png'});
// A same-line camera change in the dream cannot resize its authored layout or clamp it.
await p.evaluate(()=>lunaCampaign.newGame());await p.waitForFunction(()=>lunaCampaign.view==='prologue');
const cinema=await p.evaluate(()=>{lunaCampaign.tick=()=>true;const c=lunaCampaign.cinema,sc=c.scene,time=sc.lines[0].t+1,rd=c.player.renderer,original=rd.camera;const measure=()=>{const el=document.querySelector('.campaign-cinema-ui .bubble'),r=el.getBoundingClientRect();return{w:r.width,h:r.height,x:r.x,y:r.y,layout:el.offsetWidth,scale:new DOMMatrixReadOnly(getComputedStyle(el).transform).a};};c.player.render(time,null,false,0);const cam=rd.camera(time);rd.camera=()=>cam;c.player.render(time,null,false,0);const a=measure();rd.camera=()=>({...cam,z:cam.z*.5});c.player.render(time,null,false,0);const z=measure();rd.camera=()=>({...cam,x:cam.x+1000});c.player.render(time,null,false,0);const off=measure();rd.camera=original;return{a,z,off};});near(cinema.a.w*.5,cinema.z.w,'cinema world scale');assert.equal(cinema.a.layout,cinema.z.layout);assert(cinema.off.x<0);assert.deepEqual(errors,[]);console.log('WORLD_SPEECH_OK outside + bar + cinema: world dimensions invariant, camera scaling, no edge clamp, stable line layout');
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
