/* Current Notion main story. Generated by tools/build_campaign_data.cjs. Other is not a dialogue source. */
(function(root){root.LUNA_CAMPAIGN_DATA={
  "source": "https://app.notion.com/p/3d81612298dc80fbb176cbd6acd05651",
  "revision": "2026-09-30",
  "actors": {
    "루나": "luna",
    "크리스": "chris",
    "톰": "tom",
    "아일리": "aili",
    "포트": "port",
    "삼호": "samho",
    "조니": "johnny",
    "과거의 톰": "tom",
    "기억 속 루나": "luna",
    "연구원": "researcher",
    "주거층 주민": "resident",
    "의뢰 연락 메시지": "message",
    "삼호가 보내는 메시지": "samho",
    "보안부 3팀 팀장": "captain",
    "진입조｜무전": "radio",
    "보안부 대원 A": "soldier",
    "경계조 A｜무전": "radio"
  },
  "prologue": [
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "진입조, 진행 상황은?"
    },
    {
      "type": "say",
      "actor": "radio",
      "who": "진입조｜무전",
      "text": "지하 3층까지 정리했습니다. 하지만.. 마지막 층에서 연구원들이 저항 중입니다."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "…겨우 연구원한테 막혔다고?"
    },
    {
      "type": "say",
      "actor": "radio",
      "who": "진입조｜무전",
      "text": "한 실험체가 계속 방해를.."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "병신 같은 놈들.. 직접 내려간다. 대치 상황만 유지해."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "들었지? 경계조만 남기고 다 내려간다."
    },
    {
      "type": "say",
      "actor": "soldier",
      "who": "보안부 대원 A",
      "text": "모두 진입 준비!"
    },
    {
      "type": "say",
      "actor": "radio",
      "who": "경계조 A｜무전",
      "text": "팀장님, 현재 정문에 접근하는 차량들이 있습니다."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "뭐? 자세히 말해봐."
    },
    {
      "type": "say",
      "actor": "radio",
      "who": "경계조 A｜무전",
      "text": "지금 검정색으로 도색된 장갑차 여러 대가.."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "시발 아군 아니잖아 당장 격벽 올리고 쏴!!"
    },
    {
      "type": "say",
      "actor": "radio",
      "who": "경계조 A｜무전",
      "text": "벼..벽이 안 올라갑니다. 인트라넷 권한이…"
    },
    {
      "type": "say",
      "actor": "radio",
      "who": "경계조 A｜무전",
      "text": "야.. 저 사람 설마.. 그.."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "경계조? 경계조? 응답해라."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "…시발 좆된 거 같은데"
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "다들 준비해. 손님이 온 거 같다."
    },
    {
      "type": "say",
      "actor": "captain",
      "who": "보안부 3팀 팀장",
      "text": "..ㅆ..쏴!!"
    }
  ],
  "opening": {
    "1": [
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "오늘 새로 가져온 재료로 만들 수 있는 칵테일은 레시피 DB에 새로 업데이트했으니까 보면 될 거야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "확인했습니다."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "좋아 그럼 부탁할게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(시작해 보자.)"
      }
    ],
    "2": [
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "오늘도 새로 가져온 재료로 만들 수 있는 칵테일은 레시피 DB에 새로 업데이트했으니까 보면 될 거야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "확인했습니다."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "좋아 그럼 부탁할게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(시작해 보자.)"
      }
    ],
    "3": [
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "왔나. 어제 네가 부탁한 건 여기 뒀어.\n새로 가져온 재료로 만들 수 있는 칵테일은 레시피 DB에도 업데이트했으니까 보면 될 거야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "확인했습니다. 부탁드린 것도 모두 있네요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "기억은 볼 만했어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 조니가 만드는 과정도 확인했어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그럼 오늘은 만들 수 있겠군."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "만드는 방법은 알 것 같아요.\n톰이 왜 그때를 계속 생각하는지는, 직접 더 들어봐야겠지만요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그 녀석 말 시작하면 길어지니까 각오는 해두고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "오늘은 길어져도 괜찮을 것 같아요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "좋아. 그럼 부탁할게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(시작해 보자.)"
      }
    ]
  },
  "bar": {
    "1": [
      {
        "type": "enter",
        "actor": "chris",
        "arg": "R"
      },
      {
        "type": "coaster",
        "actor": "chris",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "어때 할 만한 것 같아?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "제가 잘하고 있는 건진 모르겠지만\n아직까지는 크게 어렵진 않은 것 같아요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "첫날치곤 잘하고 있다 생각해."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "평균적으로 봤을 땐 그리 잘하진 않는 건가 보네요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "너무 그렇게 생각할 필요 없다고."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "좀만 더 있으면 교대니까 힘내줘"
      },
      {
        "type": "exit",
        "actor": "chris",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(..퇴근하면 뭘 해야 하지.)"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(아까 본 그 이상해 보이는 가게나 가볼까)"
      },
      {
        "type": "enter",
        "actor": "tom",
        "arg": "L"
      },
      {
        "type": "coaster",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어서 오세요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "..어 그래 반가워."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "혹시 여기 전에 있던 분위기 잡는 무서운 아저씨는 어디 갔는지 알아?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "크리스를 말하시는 거라면 바 창고 쪽에서 다른 일을 하고 있습니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래? 그렇구만.. 다시 시작했으면서 말도 안 해주다니 망할 놈 같으니."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "크리스를 불러드릴까요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "어? 아니야 그럴 필욘 없어."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "혹시 올드 패션드 한 잔 가능한가?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "현재 레시피 DB에 올드 패션드가 없어요. 필요한 재료가 무엇인지부터 확인해야 해서, 지금 바로 만들어드리기는 어렵습니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…하긴 오래 쉬었으니 그럴 만도 한가."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그럼 지금 되는 건 어떤 것들이야?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "진피즈, 진토닉, 드라이 마티니가 가능합니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "음… 그러면 드라이 마티니로 한 잔 부탁할게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 주문 받았습니다."
      },
      {
        "type": "order",
        "actor": "tom",
        "arg": "exact:dry_martini"
      },
      {
        "type": "craft",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "serve",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "음… 괜찮네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "원하던 게 맞는 건가요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "이 정도면 꽤 괜찮다고 생각해 근데 예전에 있던\n영감이 만들어주던 것들이 나한텐 더 괜찮게 느껴지더라고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "특히 그 처음 마신 올드 패션드 맛은…\n잊지 못하지.."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "맛있었나 보네요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "뭐? 반응이 참.. 신선하네"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "맛도 맛인데. 그때 영감이 하던 말이랑 그 칵테일의 맛은..\n지금 생각해 보면 내 인생에 대해서 돌아보게 된 순간이었던 것 같네."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "어떻게 보면 내 인생을 바꾼 한 잔이라고 해야 하나."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그 정도로 칵테일이 사람에게 큰 영향을 주는지는 처음 알았네요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "하하. 뭐 말이 그렇다는 거지."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "아무튼 그 영감이 만들던 칵테일. 한번 만들어 볼 수 있겠어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "크리스가 만드는 건 별로인가요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그 아저씨가 만드는 건 영.. 내 취향은 아니거든.\n물론 요즘엔 그마저도 그립긴 하지만 말이야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그러면 한번 방법을 찾을 수 있는지 물어보겠습니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 부탁하지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "기억나는 맛을 조금 더 말씀해 주실 수 있나요?\n같은 이름의 술이면 되는 건가요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그냥 올드 패션드면 되는 건 아니야.\n영감이 처음 내줬던 그 한 잔. 다른 데서 마셔도 그 맛은 안 나더라고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그때 사용한 재료는 기억하시나요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "거기까지 봐둘 생각은 못 했지.\n…그날은 잔 앞에 앉아 있는 것만으로도 정신이 없었거든."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그렇군요. 만드는 기록이 남아 있는지 찾아볼게요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "모레쯤 다시 올게. 못 찾았으면 못 찾았다고 말해도 돼.\n그때는 다른 거 마시면 되니까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 그때까지 확인해 보겠습니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 오늘은 잘 마셨어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "안녕히 가세요."
      },
      {
        "type": "exit",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(지금 DB에는 없지만, 크리스가 따로 아는 방법이 있을까?)"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(이따 한번 물어봐야겠네.)"
      },
      {
        "type": "enter",
        "actor": "aili",
        "arg": "L"
      },
      {
        "type": "coaster",
        "actor": "aili",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "여!!! 이쁜이!!!"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어서 오세요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "딱딱한 건 여전하구나 루나!"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아쉽게도 지금은 그런 상태라서요 나중엔 변할 수도 있다고 하네요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "음… 지금 모습도 좋긴 한데. 표현이 풍부해진 루나도 보고 싶긴 한걸."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그래서 무슨 일로 오셨나요. 아일리?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "전에 고쳐주셨던 건 이미 끝난 걸로 알고 있었는데 혹시 아직 이상이 있는 부분이 있는 건가요?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "아냐 오늘은 루나 네가 일한다고 포트한테 들어서 안구정화 좀 할 겸\n한 잔하러 왔어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럼 주문은 어떤 걸로 하시겠나요?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "음.. 혹시 진피즈 돼? 예전부터 좋아하던 건데."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 가능해요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "오호. 다행히 이건 지금 되는구나 그럼 한 잔 부탁할게."
      },
      {
        "type": "order",
        "actor": "aili",
        "arg": "exact:gin_fizz"
      },
      {
        "type": "craft",
        "actor": "aili",
        "arg": ""
      },
      {
        "type": "serve",
        "actor": "aili",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "나왔습니다."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "오.. 좋은데? 보통 다른 술집들에서 얼굴이 볼 만하면 술맛이 형편없던데"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "루나 넌 둘 다 괜찮나 보네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "다행이네요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "만드는 걸 보니 일은 적응은 됐나 봐?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "대부분 이해가 끝난 것 같다고 생각해요. 하지만.."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "하지만?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "손님 중에 제가 모르는 레시피로 만든 칵테일에 대해\n만들어 달라고 부탁을 받아서 어떻게 해야 할지 고민 중이었어요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "어떤 레시피길래? 웬만한 건 크리스가 알고 있을 텐데"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "예전에 있던 조니라는 분이 만든 칵테일은\n약간 변형된 칵테일의 레시피로 추측이 됩니다."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "아하.. 그 할배가 만든 거라면 그럴 만하네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어떤 이유가 있나요?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "그 할배는 자기가 정한 기본 레시피를 고수하긴 하는데.\n가끔 특정 상황에 맞춰서 레시피를 바꿔서 주기도 하거든."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럴 상황이랄 게 있나요?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "음…"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "만약 술에 만취한 손님이 술을 달라고 하면 루나 넌 어떡할래?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "술을 줄 거 같습니다."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "그걸 마신 그 손님이 테이블에 토를 하거나 난동을 부린다면?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "음.. 그러면 주지 않는 게 맞다고 생각해요"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "그 손님이 술을 왜 안 주냐고 화를 내거나 따진다면?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "이해했습니다. 이 상황에서는 정답이 없는 거군요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "보통 난감하겠지. 그 할배는 일단 손님이 왜 더 마시려는지부터 듣더라고"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "지금은 물부터 마시자고 권하기도 하고, 덜 취한 손님한테는 약하게 만들어도 괜찮겠냐고 묻기도 하고.\n무조건 술부터 내주는 건 아니었어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…생각지 못한 사고방식인 것 같네요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "그치? 나도 어떻게 그렇게 행동하는지 믿을 수 없다니까"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "그래도.. 그걸 해주는 사람이다 보니까 이 가게가 유명했어"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "저기 저 높은 빌딩에 살고 있는 메가코프 임원들도 찾아올 정도로 말이야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "아 루나 너도 저쪽 놈들한테는 그리 좋은 감정은 없지?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그런 건 아니지만 저에게 위협이 되는 세력이라 조심하고 있습니다."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "걱정 마. 그 할배를 죽게 만들고 다시 이곳을 찾아올 일은 없으니까 말이야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그건 다행이네요."
      },
      {
        "type": "enter",
        "actor": "chris",
        "arg": "R"
      },
      {
        "type": "coaster",
        "actor": "chris",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "루나. 슬슬 교대해도 될 것 같은데."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "뭐야 너였냐."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "반갑다 음침한 아저씨."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "…왜 음침하단 말을 항상 하는 거지?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "너네 집엔 거울이 없어?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "거울이 전에 망가지긴 했지."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "음.. 이게 진짜네. 아무튼"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "한번 거울을 봐 항상 그렇게 -_- 이런 표정으로 다니면서\n잘 웃지도 않는데 그게 음침이지 상큼이겠냐?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "…."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "음침이랑 상큼이란 단어가 이렇게도 쓰이는군요.\n하나 더 배운 거 같습니다."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "저런 건 안 배워도 돼."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "킥킥 루나도 있어서 열 좀 받나 보군."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "이 이상한 꼬맹이 말고 별일은 없었나?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 별일은 없었는데 예전에 조니가 만든 칵테일에 대해 알아봐 달라고 부탁한 일이 있었습니다."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "음? 누가 그런 말을 했지?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "이름은 잘 모르지만 코트에 늑대 엠블럼이 박힌 옷을 입고 있었습니다."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "…톰인가 보군."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "걔가 원하는 레시피는 내가 가지고 있진 않아 전에 있던 영감이 변형해서 만들던 레시피라."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그걸 다시 만드는 건.. 힘들 것 같군."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그렇군요. 어쩔 수 없나 보네요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "음… 좀 조심스럽긴 한데 근데 그거 조니 기억 칩을 보면 되는 거 아니야?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "…."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "조니 유골캡슐이랑 같이 보관하고 있다고 들었는데."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "지금 그걸 보는 건.. 너한테는 무리긴 하겠지만.\n루나는 괜찮을 거라고 생각하지 않아?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "….확실히. 그 영감도 이대로 잊혀지는 건 원하지 않겠지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그 칩에 담긴 걸 보면 그 사람이 주문한 칵테일에 대해서도 알 수 있는 건가요?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "아마 그럴 거야 하지만 사고 때문에 손상되기도 했고 워낙 데이터가 많기 때문에 조정도 해야 해.\n그러려면…"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "그런 거라면 위 작업장 쪽에 처박혀서 기계랑 짝짜꿍하고 있는 포트 전문이긴 하지."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "한번 시도는 해 볼 만하겠군. 오늘 영업 끝나면 포트한테 맡겨보지.\n조니의 칩이랑 복원에 필요한 건 내가 챙길게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 알겠어요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "흐음.. 뭔가 기대되는걸?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어떤 게요?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "뭔가 느낌이 조니의 뒤를 네가 이을 것 같아서."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "뒤를 잇는다는 게 어떤 건지 모르겠네요."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "우리 이쁜이가 점점 성장하다 보면 알게 될 거야."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "일단 이 이상은 나중에 얘기하는 걸로 하고"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "루나 더 늦기 전에 먼저 들어가."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "알겠습니다."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "잘 가 이쁜이 나중에 또 보자구."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 나중에 봐요 아일리."
      }
    ],
    "2": [
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(흠.. 더 이상 안 들어오네 슬슬 정리해야 하나.)"
      },
      {
        "type": "enter",
        "actor": "port",
        "arg": "L"
      },
      {
        "type": "coaster",
        "actor": "port",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "여어-"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어서 오세요 포트."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "반가워 아가씨"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "일단.. 한 잔 먼저 시키지 드라이 마티니로 한 잔 부탁해."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 주문받았습니다."
      },
      {
        "type": "order",
        "actor": "port",
        "arg": "exact:dry_martini"
      },
      {
        "type": "craft",
        "actor": "port",
        "arg": ""
      },
      {
        "type": "serve",
        "actor": "port",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "이제 얼추 바텐더 태가 나는구만 아가씨"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "제가 바텐더처럼 보인다는 건가요?"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "제법 손님을 맞이하는 게 자연스러워 보인다 이거야.\n그전에는 영 뻣뻣해 보였거든."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "안 맞는 옷을 입은 것처럼 말이지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "지금 제 옷은 저에게 딱 맞는다고 생각됩니다."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "큭큭 아직 이런 센스는 부족하구만."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "자 받아 어제 부탁받은 물건이야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "이게 뭐죠?"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "벌써 까먹었나? 어제 아일리랑 크리스 이 자식들이\n새벽 3시에 대뜸 이걸 들고 오더니 고치라고 하더라니까?"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "그냥 고치는 것도 아니고 복원에다가 원하는 부분을 편집해서 추출까지\n내 고객이 이랬으면 난 벌써 대가리에 시원한 바람구멍 하나 내줬을 건데."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "암튼 그놈들 요청 사항 다 들어줘서 따로 뽑은 거니까 이따가 확인해 봐."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "감사합니다. 포트."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "뭘 대신 나중에 내 부탁 한 번만 들어줘."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어떤 걸 말씀하시는 거죠?"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "아직 확정은 아니라 지금 말하긴 좀 그렇고\n일단 너만 할 수 있는 거라고 말해둘게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "상당히 저에게 불리한 상황이 연출될 것 같습니다."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "날 뭘로 보는 거야? 암만 내가 못났어도 너한테 사기 칠 쓰레기는 아니지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럼 다행이네요."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "그래. 그럼 난 분명 건네준 거다? 나중에 딴소리하기 없기야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 하지만 추후에 부탁을 듣고 불합리하다 판단되면 거절할게요."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "큭큭 철저하구만 아가씨 누구한테 배운 건지 원."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "암튼 이만 가보지 수고하라고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네 안녕히 가세요."
      },
      {
        "type": "exit",
        "actor": "port",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "음.. 이건 언제 봐야 하는 거지? 퇴근하고 확인해야 하나."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "내일 온다고 했으니 오늘 교대할 때 보면 되겠다."
      },
      {
        "type": "enter",
        "actor": "samho",
        "arg": "L"
      },
      {
        "type": "coaster",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "뭐야. 진짜 여기 있었잖아?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "안녕하세요 손님."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래 반가워. 진짜 여기서 일하고 있네"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아까 밖에서 뵀죠. 삼호."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래 맞아. 근데 진짜 너 말투 특이하다."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "제 말투요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래 나 이 동네에서 평생을 살았는데.\n너처럼 존댓말 쓰는 사람을 거의 처음 봤어"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…원래 존댓말은 사용하지 않는 건가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "너.. 어디 살다가 왔길래…\n씁 그래 이런 걸 물어볼 만큼 좋은 동네는 아니지."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "암튼 그래 여기선 사람들 존댓말 안 써."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "생각해 보니 대부분 그랬던 거 같습니다."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "너 진짜 여기 온 지 얼마 안 되었나 보구나?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "맞습니다. 사정이 있어서"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "다 저마다의 사정이 있지. 알았어 더는 캐묻지 않을게."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래서 여기는 뭘 파는 곳이야?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "칵테일이라는 음료를 팔고 있습니다."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "오호.. 그럼 여기가 보스가 자주 오던 곳인가 보구나."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "주문하시겠습니까?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래. 아무거나 자신 있는 걸로 부탁해."
      },
      {
        "type": "campaign_menu",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럼 이걸로 만들어드릴게요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "좋아. 부탁해."
      },
      {
        "type": "order",
        "actor": "samho",
        "arg": "exact:@selected"
      },
      {
        "type": "craft",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "serve",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "오.. 괜찮은데?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "네가 실력이 좋은 건지 여기서 쓰는 재료가 좋은 건지"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "레시피대로만 만들면 됩니다."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "흠 내가 그 레시피를 안다고 해도 이렇겐 못 만들 것 같은데."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아무튼 둘 다 괜찮은 걸로 하자고.\n여기가 유명했었던 이유가 있는 것 같네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "여기가 유명했었나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "주변에 이렇게 술을 만들어 파는 곳은 저기 기업 구역에 있는 높은 라운지 빼곤 없다고 보스한테 들었어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이런 동네에 이렇게 술을 파는 곳이 있으면 유명할 수밖에 없지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그렇군요. 그런데 혹시 어딘가에서 일하고 계신 건가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "왜? 내가 그냥 할 일 없는 백수로 보여?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아니요, 보스라는 말을 하시길래 무슨 보스인지 궁금했습니다."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래 넌 이런 동네가 처음이니까 그럴 수 있겠네."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이 동네에서 보스란 건 대부분 갱단의 리더를 말하는 거야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럼 당신도 갱단원인 건가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "날 보고도 그런 걸 물어봐? 딱 보면 강해 보이지 않나?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아직 그런 기준은 잘 모르겠습니다."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…애니멀 갱 소속이라고 생각해. 아직 정식은 아니지만 뭐 곧 될 거니까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "이름이 왜 애니멀인가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "우리 갱은 짐승 같은 강함과 유대를 추구하거든. 또한 인간성에 대한 경멸도 있고."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "솔직히 사람들이 하는 짓을 보면 내가 사람이라는 게 싫어질 정도로 진절머리가 난다니까.\n동물들은 그래도 서로 챙겨주고 지킬 건 지킨다고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "생각보다 철학적인 뜻을 가진 조직이네요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그렇지? 다른 인간말종 쓰레기들이 모인 갱이랑은 다르다니까?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "내 보스만 봐도 딱 알 수 있지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어떤 사람인가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "음… 자기 갱 멤버를 가족처럼 여기고 헌신하고, 약자를 돕고 강자에게 맞서는 영웅 같은 사람이지."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그리고 늑대를 좋아해서 이 동네에선 다이어 울프라고 불려."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "왜? 내가 거짓말하는 것 같아?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "혹시 송곳니 목걸이를 하고 머리색이 빨간가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…이 동네에서 그러고 다닐 사람은 보스밖에 없는데."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그리고 이름이 톰인가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "음 백 프로 보스네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아무래도 어제 오신 손님이셨던 것 같네요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래? 보스도 여길 오는구나.\n앞으로 자주 와야 하는 이유가 생겼네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그분이랑 자주 보는 사이는 아닌가 보네요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "전에는 자주 와서 도와주거나 얘기도 하고 그랬는데.\n최근에는 날 피하는 느낌이 들어서."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "오래 알고 지내신 건가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "어릴 때부터. 거리에서 잘 데 없을 때 보스가 거처를 구해줬어.\n먹고살 것도 몇 번이나 챙겨주고. 나 같은 애들이 좀 있었거든."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그래서 그분과 같이 일하고 싶으신 거군요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "응. 근데 막상 들어가겠다고 하니까 자격부터 갖추래.\n이제 나도 스무 살인데, 언제까지 기다려야 하는지 모르겠어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이 정도 준비했으면 보스도 다시 생각해주겠지 싶었는데.\n요즘은 말 붙일 틈도 안 줘."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "무슨 잘못을 저지르셨나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아니? 잘못한 건 없는데…"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "피한다고 꼭 내가 뭘 잘못한 거야?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…그렇게 말씀하신 건 아니었죠."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "모르겠어. 언제부터 이랬는지도.\n이제 생각해 보니 자꾸 날 밀어내는 것 같기도 하고…"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "모르겠네. 나중에 보면 제대로 물어봐야겠어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "진실된 대화는 좋은 법이라고 배웠죠."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그게 말처럼 되면 좋겠네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "톰은 내일 다시 오기로 하셨어요. 부탁하신 술 때문에요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그럼 내일 와서 물어보면 되겠다.\n너도 그때 여기 있지?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "알았어. 오늘 잘 마셨어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "경호 일에 대한 연락인가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "응. 자세한 조건은 내일 보내준다네.\n일단 들어봐야지. 나중에 봐."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "안녕히 가세요."
      },
      {
        "type": "exit",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "enter",
        "actor": "chris",
        "arg": "R"
      },
      {
        "type": "coaster",
        "actor": "chris",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "루나, 슬슬 교대할까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 포트가 가져다준 기록을 확인하고 가도 될까요?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그래. 손님은 내가 볼게. 안쪽에서 보고 와."
      },
      {
        "type": "campaign_memory",
        "actor": "",
        "arg": ""
      }
    ],
    "3": [
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어서 오세요, 톰."
      },
      {
        "type": "enter",
        "actor": "tom",
        "arg": "L"
      },
      {
        "type": "coaster",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "오. 오늘은 날 보자마자 깔아주네.\n여기 내 자리도 생긴 거야?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "다른 손님이 먼저 오시면 그분께 드립니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "하하, 아주 공평하구만.\n그래서, 내 부탁은 좀 어때?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "조니가 남긴 기록에서 만드는 방법을 찾았어요.\n재료도 준비했고요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "정말? 크리스가 도와줬어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 아일리와 포트도요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "내가 한 잔 부탁했다가 사람 여럿 부려먹었네.\n나중에 다 한 잔씩 사야겠어."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "네 계산부터 밀리지 않으면 돼."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "이야, 저런 말은 또 잘 듣는다니까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "올드 패션드 한 잔, 맞으시죠?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 부탁할게."
      },
      {
        "type": "enter",
        "actor": "samho",
        "arg": "R"
      },
      {
        "type": "coaster",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "보스. 여기 있었네."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "뭐야. 너도 여기까지 소문 듣고 왔냐?\n루나, 벌써 단골 하나 잡았네."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "오늘 온다길래 기다렸어. 할 말 있어서."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "삼호도 주문하시겠어요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "조금 있다가. 먼저 얘기 좀 할게."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "보스. 요즘 왜 나 피해?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "피하긴 누가 피해. 지금 네 앞에 있잖아."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "일 얘기만 꺼내면 바쁘다며 가버리잖아."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그 얘기는 했을 텐데."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "안 된다는 말만 했지. 왜 안 되는지는 말 안 했잖아."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래서 나도 준비했어. 이거 군용이야.\n이제 끼워달라고 말만 하는 거 아니라고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…너 그거 언제 달았어?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "얼마 안 됐어. 작동도 확인했고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "돈은?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "빌렸어. 갚을 방법도 찾았고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "빌려서까지 이걸 달았다고?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "보스가 자격을 갖추라며.\n맨몸으로는 아무것도 못 한다는 건 나도 알아."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "내가 말한 건 이런 게 아니야."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그럼 뭔데? 이번에도 아니라고만 할 거야?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "일도 구했어. 물건 회수하는 데 경호가 필요하대.\n이번 거 하면 빌린 돈도 꽤 갚아."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "누구랑 붙는 일인데?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "다른 놈들이 올 수도 있대. 아직 누군지는…"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "누가 오는지도 모르고 받겠다고?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아직 대답 안 했어. 지금 확인하고 있잖아."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "연락은 어떻게 닿았는데. 그쪽이 널 뭘 보고 믿고?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "내가 애니멀 쪽이라고 했어."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "삼호."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그렇게라도 해야 일을 주니까. 어차피 곧 들어갈 거였고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "나랑 얘기도 없이 우리 이름을 팔았어?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "들어주지도 않으면서 언제 얘기하라는 건데!"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…미안하다, 루나. 술 한 잔 하러 와서 이러고 있네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "주문하신 술, 지금 만들어도 될까요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 부탁하지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "삼호, 물을 드릴까요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…응."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(재료는 준비됐어. 조니가 만들던 순서를 다시 확인하자.)"
      },
      {
        "type": "order",
        "actor": "tom",
        "arg": "exact:johnny_old_fashioned"
      },
      {
        "type": "craft",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "serve",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "주문하신 올드 패션드입니다."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…이거네."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "허. 진짜 이 맛이야.\n영감이 여기서 툭 튀어나올 것 같네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "찾으시던 맛인가요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 맞아.\n이거, 다시 마실 수 있을 줄 몰랐는데."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "기록에서, 그날 톰이 한참 동안 말을 하지 않으셨어요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "술 만드는 것 말고 그것도 남아 있었어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 조니가 잔을 만들던 때의 기록이라서요.\n계속 말씀드려도 괜찮을까요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…그래. 그랬지.\n그때는 잘난 소리 하러 온 날이 아니었으니까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "조니는 톰이 무슨 일을 해냈는지 먼저 묻지 않으셨어요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "뭐라도 해내야 얼굴 들고 올 수 있을 줄 알았거든.\n막상 와서는 아무 말도 못 했지."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "근데 영감은 평소처럼 잔부터 꺼내더라.\n내가 무슨 꼴을 하고 왔든, 여기 앉을 자리는 있다는 것처럼."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그래서 그 술을 다시 마시고 싶으셨나요?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그런 것도 있겠지.\n맛만 따라가면 그때 기분도 좀 돌아올 줄 알았나 봐."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "한동안 그 생각을 하고 살았어.\n나도 누가 찾아왔을 때 앉을 자리 정도는 만들어주자고.\n…요새는 통 여유가 없네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "삼호에게도 하실 말씀이 있는 것 같아요."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그리고 삼호도, 아직 이야기가 끝나지 않은 것 같고요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "…그래. 말해 봐."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "말하면 끝까지 들어줄 거야?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "응. 들어볼게."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "처음 잘 곳 구해준 거 기억해?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "기억하지."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그 뒤로도 몇 번이나 도와줬잖아.\n먹을 게 없든, 어디서 쫓겨나든. 나만 그런 것도 아니었고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그때 너희는…"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "응. 어렸지.\n근데 지금은 스무 살이야. 계속 그때처럼 살 수는 없잖아."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "나도 옆에서 뭔가 해주고 싶었어.\n맨날 보스가 와주기만 기다리는 거 말고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래서 이걸 단 거야?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그러면 적어도 짐은 안 될 줄 알았어.\n근데 이것도 아니라고 하면… 뭘 해야 하는데."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어제는 톰에게 무슨 잘못을 하셨냐고 물었어요.\n아직 이유도 모르면서요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…그랬지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "삼호는 도와드리고 싶었던 거군요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "응. 나도 도움이 된다는 말, 한 번쯤은 듣고 싶었어."
      },
      {
        "type": "say",
        "actor": "message",
        "who": "의뢰 연락 메시지",
        "text": "배정 마감한다. 조건 확인했으면 지금 답 줘.\n오늘 투입 가능한 거지? 애니멀 쪽 인원은 너 하나로 알면 되나?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그쪽이야?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…응. 지금 대답해 달래."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "무슨 일을 하겠다고 얘기했는지부터 말해 봐."
      },
      {
        "type": "campaign_response",
        "actor": "",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "거기서 네가 애니멀이라고 하고 누구 하나 건드리면, 그다음은?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그건 내가…"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…우리 쪽에서 시킨 줄 알겠지.\n아니, 애니멀에서."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 그놈들이 너한테만 따지러 온다는 보장도 없어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "나 혼자 할 수 있다고 생각했는데.\n일 얻을 때부터 보스 이름을 빌린 거네."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "돈은 진짜 많이 주는데.\n…빌린 건 또 어떻게 갚냐."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "근데 내가 뭘 끌고 가는지도 모르면서 하겠다고 할 순 없잖아."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호가 보내는 메시지",
        "text": "이번 일은 안 하겠습니다.\n그리고 앞에서 애니멀 쪽이라고 한 건 정정할게요. 저는 정식 소속이 아닙니다.\n그쪽에서 맡긴 일도 아니고요. 제가 잘못 말했습니다."
      },
      {
        "type": "say",
        "actor": "message",
        "who": "의뢰 연락 메시지",
        "text": "그럼 처음부터 그렇게 말했어야지. 다른 사람 구한다."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…끝났네."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "자격 얘기. 내가 제대로 말했어야 했어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그럼 무슨 뜻이었는데?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "힘을 쓸 수 있냐고 물은 게 아니야.\n쓰고 나면 누구한테 무슨 일이 생기는지, 거기까지 볼 수 있어야 한다는 뜻이었어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그럼 그렇게 말해주지."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 그랬어야 했지.\n안 된다고만 하면 네가 포기할 줄 알았어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…나한테는 더 세져서 오라는 말로 들렸어."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "너한테서 이런 팔을 보게 될 줄은 몰랐어.\n내 말 때문에 빚까지 냈다고 하니까, 겁부터 나더라."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "보스도 겁나는 게 있어?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "야. 많아.\n너 하나 못 알아들을 말 해놓고, 잘못되면 어떡하나 싶기도 하고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "우리가 네가 생각하는 만큼 좋은 놈들인 것도 아니야.\n돈 때문에 남을 다치게 하는 일도 하고, 약 만지는 일에도 손대.\n시키는 일 하다가 죽는 놈도 있고."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그래도 나한테 해준 건 진짜잖아."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그것도 진짜지.\n그러니까 네가 다칠 데로 들어오는 걸 보고만 있기가 싫은 거야."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…알았어.\n근데 내가 계속 아무것도 모르는 애로 있진 않을 거야."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "알아. 나도 오늘 들었어."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "들어가고 싶은 마음까지 없어진 건 아니고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그럴 거라 생각했어.\n그렇다고 오늘 받아주겠다는 말도 아니야."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그건 알겠다고.\n대신 앞으로 얘기하려고 하면 도망가지 마."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 바쁘면 언제 얘기할지라도 말할게.\n너도 혼자 결정해놓고 완성품처럼 들이밀지 말고."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…응."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이건 내가 단 거니까. 돈도 내가 방법을 찾아볼게."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "방법 찾으면 조건부터 같이 보자.\n이번에는 나도 제대로 들을 테니까."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…알았어."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "벌써 가게?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "할 얘기는 끝났잖아."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "얘기 끝나면 꼭 가야 하냐?\n나 아직 마시고 있는데."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…그 술이 그렇게 맛있어?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "내가 찾아달라고까지 했으면 궁금할 만하지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "한 잔 만들어드릴까요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "오늘은 이걸로 됐어. 다음에."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "그래. 다음에 또 오면 되지."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "루나. 잘 마셨어.\n다음에도 이걸로 부탁하지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 준비해 둘게요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "나 먼저 간다. 물 고마워."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "안녕히 가세요."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "톰",
        "text": "야, 같이 가. 그렇게 먼저 나갈 거면 왜 날 찾아왔냐."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그럼 빨리 와, 보스."
      },
      {
        "type": "exit",
        "actor": "tom",
        "arg": ""
      },
      {
        "type": "exit",
        "actor": "samho",
        "arg": ""
      },
      {
        "type": "enter",
        "actor": "chris",
        "arg": "R"
      },
      {
        "type": "coaster",
        "actor": "chris",
        "arg": ""
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "갔나?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 같이 가셨어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "술은 어땠대?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "찾던 맛이라고 하셨어요. 다음에도 부탁한다고요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그럼 됐네. 고생했어."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "왜?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어제는 레시피대로 만들면 된다고 했어요.\n삼호에게요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "틀린 말은 아니지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "오늘도 만드는 방법은 같았는데, 언제 말을 꺼내야 할지는 적혀 있지 않았어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그래서?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "조금 기다려 봤어요.\n아직 하려던 말이 남아 있는 것 같아서요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "…그랬군."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "어때. 아직도 일하기로 한 게 잘못된 선택 같아?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…조금 더 해보고 싶어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그래. 그럼 내일도 부탁하지.\n오늘은 이쯤 하고 들어가자."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네."
      }
    ]
  },
  "scenes": {
    "resident": [
      {
        "type": "say",
        "actor": "resident",
        "who": "주거층 주민",
        "text": "위층 가려고? 승강기는 저쪽이야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "감사합니다."
      },
      {
        "type": "say",
        "actor": "resident",
        "who": "주거층 주민",
        "text": "처음 들으면 놀라지. 위에서 물 쓰면 저래."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "고장 난 건 아닌가요?"
      },
      {
        "type": "say",
        "actor": "resident",
        "who": "주거층 주민",
        "text": "손볼 데야 많지. 그래도 저 소리 나면 오늘은 물이 나온다는 거니까.\n안 들리면 그게 더 걱정이야."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…그렇게도 알 수 있군요."
      },
      {
        "type": "say",
        "actor": "resident",
        "who": "주거층 주민",
        "text": "며칠 살다 보면 다 알아. 조심히 올라가."
      }
    ],
    "night0": [
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "많이 기다렸어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아니요. 집을 좀 둘러보고 있었어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "수납장 아래 칸은 비워뒀어. 네 물건 두면 돼."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 고마워요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "치킨 사 왔어. 밖에서 먹을까?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "제가 들고 갈게요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "뭘 좋아하는지 몰라서 반반으로 샀어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "먹어보고 말씀드릴게요."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "혼자 계실 때도 여기서 드세요?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "가끔. 오늘은 바람이 덜 불어서 괜찮네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "저도 종종 나와도 돼요?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그럼. 의자는 그대로 두자."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "오늘 해보니까 어땠어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "만드는 순서보다 무슨 말을 해야 할지 생각하는 데 시간이 더 걸렸어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "포트 말 다 받아주느라 피곤했겠네."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "질문에 대답하면 새로운 이야기가 시작되더라고요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그 영감은 원래 그래."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "앞으로는 어떻게 하고 싶어?\n바 말고 다른 걸 해보고 싶으면 말해도 돼."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아직 모르겠어요. 정해진 일 말고 제가 무엇을 하고 싶은지는요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "오늘 다 정할 필요는 없지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럼 며칠 더 해볼게요.\n여기 오는 사람들이 왜 그런 말을 하고, 무엇을 원하는지 알아보고 싶어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그래. 해보고 생각하자.\n그만두고 싶다고 여기서까지 나가야 하는 건 아니니까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…알겠어요."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "내일은 처음 보는 손님도 오겠죠."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "오겠지. 막히면 불러. 나도 옆에 있을 테니까."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "제가 바로 대답을 못 해도 조금만 기다려주세요. 제가 먼저 생각해 볼게요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "알았어."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "지금도 무슨 말을 해야 할지 생각하고 있었어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "나도 누구랑 여기 앉아 있는 게 오랜만이라."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그럼 그냥 먹을까요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그래. 식겠다."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "전 이쪽이 더 좋아요. 바삭한 쪽."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "다음엔 그걸로 사 오지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "반반으로 해요. 크리스는 양념부터 드셨잖아요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "……그럼 반반."
      }
    ],
    "workshop": [
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "지금 몇 시인지는 보고 온 거냐?"
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "불 켜져 있길래."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "불 켜져 있다고 다 영업 중은 아니거든?"
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "…그 영감 거야?"
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "손상된 부분을 봐줬으면 해.\n톰한테 올드 패션드를 처음 만들어줬던 기록을 찾고 있어."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "만드는 과정이 남아 있으면 루나가 보고 따라 해볼 수 있잖아."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "전부 멀쩡하게 살려내란 소리는 하지 마.\n남아 있는 것부터 봐야 하니까."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "알아. 제조 과정이랑 그때 나눈 대화만 찾을 수 있어도 돼."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "해보지. 정리되면 내가 내려갈 테니까 재촉하지 말고."
      },
      {
        "type": "say",
        "actor": "aili",
        "who": "아일리",
        "text": "부탁해, 영감."
      },
      {
        "type": "say",
        "actor": "port",
        "who": "포트",
        "text": "부탁할 때만 말이 곱지, 아주."
      }
    ],
    "night1": [
      {
        "type": "say",
        "actor": "researcher",
        "who": "연구원",
        "text": "늦었네. 어디 있었어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "기억 속 루나",
        "text": "돌아오는 데 예상보다 시간이 걸렸어요.\n이유를 설명해 드릴까요?"
      }
    ],
    "commute2": [
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "왜? 신기해?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "손을 계속 보고 계셔서요. 문제가 있나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아니. 새로 달아서 익숙해지는 중이야.\n군용이거든. 이런 거 흔하게 못 봐."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "힘이 많이 필요한 일을 하시나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이제 하려고. 경호 같은 거.\n계속 말로만 할 수 있다고 해봤자 아무도 안 믿어주니까."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "뭐, 싼 물건은 아니지.\n빨리 일부터 구해야 해."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "일은 이미 정해졌나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "연락 넣어둔 데는 있어. 물건 가져오는 사람 옆에서 경호해주는 일이래.\n조건은 더 들어봐야 하지만."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "근데 너, 이쪽 사람은 아닌 것 같은데. 길 찾는 중이야?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "일하러 가는 중이에요. 저쪽 바에서요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "거기 다시 열었어? 지나갈 때마다 닫혀 있던데."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 아직 만들 수 있는 건 많지 않지만요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이따 시간 나면 들러볼게. 이름이 뭐야?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "루나예요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "난 삼호. 이따 보자, 루나."
      }
    ],
    "johnny": [
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "왔냐."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "…영감. 오늘은 별로 해줄 얘기가 없는데."
      },
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "그래? 그럼 뭘 마실지는 말해봐."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "아무거나. 머리 좀 식힐 만한 걸로."
      },
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "올드 패션드로 한 잔 줄까?"
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "…그래."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "다른 놈들은 벌써 제 몫을 하는데.\n난 오늘도 빈손으로 왔네."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "뭐라도 해놓고 와야 할 것 같아서, 안 오려다가…"
      },
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "그걸 왜 나한테 검사받으려고 해."
      },
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "앉았으면 한숨 돌려.\n얘기는 하고 싶을 때 하고."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "…오늘은 그냥 좀 앉아 있다 가도 돼?"
      },
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "영업 끝날 때까지는.\n의자 들고 도망만 가지 마라."
      },
      {
        "type": "say",
        "actor": "tom",
        "who": "과거의 톰",
        "text": "다음에 와도 이걸로 줘."
      },
      {
        "type": "say",
        "actor": "johnny",
        "who": "조니",
        "text": "그래."
      }
    ],
    "prepare": [
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "찾았어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 톰에게 처음 올드 패션드를 내줬던 기록이 있었어요.\n사용한 병이랑 계량 과정도 확인했습니다."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "재료는?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "라이 위스키가 필요해요. 지금 재고에는 없는 종류예요.\n나머지도 목록으로 정리했어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "알았어. 내일 열기 전에 준비해 둘게."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "고마워요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "또 필요한 거 있어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아니요. 조니는 톰이 말을 하지 않을 때 계속 기다렸어요.\n물어보면 더 빨리 알 수 있었을 텐데요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "왜 말이 없었는지 네가 알아?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "…아니요. 기록에 나온 말만 알고 있어요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "그럼 톰이 왔을 때 들어봐.\n영감이 기다린 것도 그런 이유였을지 모르고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 내일 물어볼게요."
      },
      {
        "type": "say",
        "actor": "chris",
        "who": "크리스",
        "text": "오늘은 들어가서 쉬어. 나머지는 내가 정리할게."
      }
    ],
    "night2": [
      {
        "type": "say",
        "actor": "researcher",
        "who": "연구원",
        "text": "잠깐. 어디 다친 데는 없고?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "기억 속 루나",
        "text": "네. 이상 없습니다."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "(돌아온 이유보다, 다친 곳이 있는지 먼저 물었어.)"
      }
    ],
    "commute3": [
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "어, 루나. 출근해?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 삼호는 어제 말한 일을 하러 가시나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아직. 조건 좀 더 들어보는 중이야.\n오늘 보스 온다고 했지?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 부탁하신 술을 마시러 오실 거예요."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "그럼 나도 들러야겠네. 어제 말한 거 물어보려고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "조건이 달라졌나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "물건 가져오는 동안 옆에 서 있기만 하면 된다더니.\n다른 놈들도 그 물건을 가지러 올 수 있대."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "같이 일하는 사람들인가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아니. 무장하고 올 수도 있으니까, 오면 막으라는 거지.\n대신 돈은 더 준대."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "어떻게 막아야 하는지는 들으셨나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "…지금 물어보려고."
      },
      {
        "type": "say",
        "actor": "message",
        "who": "의뢰 연락 메시지",
        "text": "회수 끝날 때까지 접근 차단. 상대가 무력 쓰면 대응 가능.\n그쪽 전력 믿고 맡기는 거니까. 오늘 안에 확답 줘."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "뭐, 처음부터 순한 일일 거라고 생각한 건 아니니까.\n이 정도는 해야 돈도 되지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그만큼 돈이 필요한 건가요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "이거 공짜로 단 거 아니거든."
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "장비값에 수술비까지 빌렸어. 이번 거 하면 꽤 갚을 수 있어.\n보스도 이제 내가 뭘 할 수 있는지 알겠지."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "톰에게도 이 일을 말씀하셨나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "아직. 말부터 꺼내면 또 하지 말라고 할 게 뻔해서.\n…그래도 오늘은 이유나 들어보려고."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "아직 수락한 건 아니고요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "응. 일단 더 알아보고.\n너 늦겠다. 이따 보자."
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "네. 바에서 뵐게요."
      }
    ],
    "night3": [
      {
        "type": "say",
        "actor": "researcher",
        "who": "연구원",
        "text": "늦었네. 어디 있었어?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "기억 속 루나",
        "text": "돌아오는 데 예상보다 시간이 걸렸어요.\n이유를 설명해 드릴까요?"
      },
      {
        "type": "say",
        "actor": "researcher",
        "who": "연구원",
        "text": "잠깐. 어디 다친 데는 없고?"
      },
      {
        "type": "say",
        "actor": "luna",
        "who": "기억 속 루나",
        "text": "네. 이상 없습니다."
      },
      {
        "type": "say",
        "actor": "researcher",
        "who": "연구원",
        "text": "됐어. 일단 여기 앉아."
      }
    ],
    "ending": [
      {
        "actor": "narrator",
        "who": "",
        "text": "루나는 기억을 돌아보는 곳에서 벗어나 다시금 눈을 떴다. 테라스 너머 높은 빌딩들과 화려한 야경이 보였다."
      },
      {
        "actor": "chris",
        "who": "크리스",
        "text": "왜, 무슨 생각이라도 났어?"
      },
      {
        "actor": "luna",
        "who": "루나",
        "text": "…기뻤던 것 같아서요.\n지금 생각해 본 거지만."
      },
      {
        "actor": "narrator",
        "who": "",
        "text": "크리스는 잠시 허공을 보며 생각하다 말을 이었다."
      },
      {
        "actor": "chris",
        "who": "크리스",
        "text": "…그렇게 생각한다면 그런 거겠지."
      },
      {
        "actor": "narrator",
        "who": "",
        "text": "루나가 떠올린 일들이 정확히 무엇인지 크리스는 알지 못했다.\n문득 한 여자가 했던 말이 떠올랐다."
      },
      {
        "actor": "woman",
        "who": "기억 속 목소리",
        "text": "이 아이들을 그저 인공지능이라고 생각하지 마.\n너 같은 놈이랑은 달라. 얘들은… 가능성을 품고 있다고."
      },
      {
        "actor": "narrator",
        "who": "",
        "text": "화를 내듯 자신에게 쏘아붙이던 목소리였다.\n그 시절 자신은 이해하지 못한 말이었다."
      },
      {
        "actor": "narrator",
        "who": "",
        "text": "크리스는 잠시 하늘을 바라보다가 다시 도심 쪽으로 시선을 돌렸다.\n마침 어렸을 적 좋아하던 열차가 지나가고 있었다."
      },
      {
        "actor": "narrator",
        "who": "",
        "text": "크리스는 젊은 시절 품었다가 잊고 지냈던 자신의 꿈이 문득 떠올랐다.\n두 사람은 한동안 말없이 앉아 있었다."
      }
    ],
    "responseA": [
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "삼호가 확인한 조건부터 들어볼까요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "물건 가져오는 동안 다른 놈들이 못 오게 막는 거.\n상대가 먼저 무력을 쓰면 나도 써도 된대."
      }
    ],
    "responseB": [
      {
        "type": "say",
        "actor": "luna",
        "who": "루나",
        "text": "그쪽에서는 애니멀이 맡는 일이라고 생각하고 있나요?"
      },
      {
        "type": "say",
        "actor": "samho",
        "who": "삼호",
        "text": "응. 우리 쪽 전력을 믿고 맡긴다고 했어.\n다른 놈들이랑 붙을 수도 있으니까."
      }
    ]
  }
};})(typeof window==='undefined'?globalThis:window);
