/* Developer-only catalog. Source tables are read, never rewritten by QA controls. */
(function(W){
'use strict';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opt=(rows,value)=>rows.map(([id,label])=>`<option value="${esc(id)}" ${String(value)===String(id)?'selected':''}>${esc(label)}</option>`).join('');
const field=(key,label,rows,value)=>`<label>${label}<select data-qa-field="${key}">${opt(rows,value)}</select></label>`;
const btn=(label,action,id='',cls='')=>`<button class="${cls}" data-qa="${action}" data-id="${esc(id)}">${esc(label)}</button>`;
const STATES=[['arrival','입장 / 코스터 대기'],['order','주문 대화'],['wait','제조·제공 대기'],['orange','인내심 절반 / 주황'],['red','퇴장 8초 전 / 빨강'],['exit','시간 초과 / 퇴장'],['drink','마시기'],['reorder','추가 주문'],['reask','주문 되묻기'],['full','3좌석 / 입장 대기'],['serve','완성 칵테일 드래그 제공'],['wrong','잘못된 칵테일 제공'],['missing','필수 재료 누락 제공'],['result','완성·등급·버리기'],['prep','재료 선택 / 병따개·10개 경고'],['settlement','정산 성공'],['bankrupt','유지비 부족 / 게임오버'],['income','재화 증가'],['expense','재화 차감'],['unlock','신규 재료·레시피 해금'],['dossier','단골 정보']];
function create({g,D,ui,outside,render,clearInput}){
 const host=document.createElement('section');host.id='qa-lab';host.hidden=true;document.body.append(host);
 const launch=document.createElement('button');launch.className='qa-launch';launch.textContent='QA 99 · 상황 선택';launch.hidden=true;launch.setAttribute('aria-controls','qa-lab');launch.setAttribute('aria-expanded','false');document.body.append(launch);
 const state={tab:'situations',personality:'gentle',cocktail:'gin_tonic',grade:'excellent',seat:'L',actor:'chris',pose:'',frame:0,fps:6,playing:true,loop:true,search:'',situation:'all',voice:'all',scene:'',step:'0',flags:'{}',result:'{}',sourceDay:'1',language:'ko',layers:new Set(),outsideCase:'',activation:'source',seed:'99'};
 let opened=false,restore=null,lastFocus=null,age=0,lastCase=null,seen=new Set();
 const actors=()=>[...new Set([...Object.keys(D.characterLayers),...D.tables.characters.map(a=>a.id),'guest_m','guest_f','outside:luna','outside:shiba','outside:M1','outside:M2','outside:W1'])];
 const actorName=id=>({'outside:luna':'외부 루나 · 대기/걷기/달리기','outside:shiba':'외부 시바 · 대기','outside:M1':'외부 NPC M1','outside:M2':'외부 NPC M2','outside:W1':'외부 NPC W1',guest_m:'일반 손님 · 남성 부위 전체',guest_f:'일반 손님 · 여성 부위 전체'}[id]||g.name(id));
 const originalPoseEntries=()=>state.actor==='outside:luna'?['idle','walk','run']:['idle'];
 const outsideFrames=()=>{const id=state.actor.split(':')[1],data=W.LUNA_OUTSIDE_DATA;if(id==='luna')return data.animations[state.pose||'idle']?.frames||[];if(id==='shiba')return data.animations.shiba.frames;return Array.from({length:6},(_,i)=>({asset:'ambient-'+id,x:i*129,y:0,w:129,h:138,pivot:{x:.5,y:24/138},ppu:100}));};
 function poseEntries(){if(state.actor.startsWith('outside:'))return originalPoseEntries().map(k=>[k,['outside-sprite']]);if(state.actor.startsWith('guest_'))return [['composite',Object.keys(D.assets).filter(k=>k.startsWith(state.actor+'_')&&/_(body|top_1|eyes_1|eyebrow_1|mouth_1|hair_1)$/.test(k))],...Object.keys(D.assets).filter(k=>k.startsWith(state.actor+'_')).map(k=>[k,[k]])];return Object.entries(D.characterLayers[state.actor]||{});}
 function selectedPose(){const entries=poseEntries();if(!entries.some(([k])=>k===state.pose))state.pose=entries[0]?.[0]||'';return entries.find(([k])=>k===state.pose)?.[1]||[];}
 const frames=()=>state.actor.startsWith('outside:')?(selectedPose(),outsideFrames().length):Math.max(1,...selectedPose().map(k=>D.assets[k]?.frames||1));
 function sceneRows(){const s=D.tables.scenes.find(s=>s.id===state.scene);return s?D.tables.steps.filter(r=>r.context===s.id).sort((a,b)=>Number(a.seq)-Number(b.seq)):[];}
 function open(tab){if(W.lunaCampaign?.active)return;if(opened){if(tab)state.tab=tab;draw();return;}opened=true;launch.setAttribute('aria-expanded','true');lastFocus=document.activeElement;state.tab=tab||state.tab;clearInput();outside.clearInput();restore={bar:g.paused,model:outside.active?outside.model:null,outside:outside.model?.paused};g.paused=true;if(restore.model)restore.model.paused=true;host.hidden=false;document.querySelector('#app').inert=true;document.querySelector('#outside-root')?.setAttribute('inert','');draw();host.querySelector('button')?.focus();}
 function close(){if(!opened)return;opened=false;launch.setAttribute('aria-expanded','false');host.hidden=true;g.paused=restore?.bar||false;if(restore?.model&&restore.model===outside.model)restore.model.paused=restore.outside;document.querySelector('#app').inert=!!W.lunaCampaign?.blocking;document.querySelector('#outside-root')?.removeAttribute('inert');outside.refreshHUD?.();render(true);launch.hidden=false;const focusTarget=lastFocus?.isConnected&&lastFocus.getClientRects().length?lastFocus:outside.active?document.querySelector('#outside-root'):launch;focusTarget?.focus({preventScroll:true});}
 function reset(){close();if(outside.active)outside.exit(true);ui.outside=false;ui.minigames=false;ui.day=99;ui.inspector=false;ui.auto=false;ui.peek=null;ui.tab='glass';ui.shelfPage=0;ui.hoverItem=null;ui.recipeOpen=false;g.speed=1;g.lang=state.language;g.reset(99,'practice',Number(state.seed)||99,false,{variant:ui.variant});g.phase='practice';g.screen='bar';g.story=null;g.craft=null;g.focus=state.seat;g.progress.money=1000;g.openingBalance=1000;}
 function general(){g.startGeneral();g.queue=[{personality:state.personality,order:state.cocktail,max_rounds:2,delay_sec:0}];g.queueIndex=0;g.spawn();const guest=g.seats.L;if(state.seat!=='L'){g.seats[state.seat]=guest;g.seats.L=null;guest.seat=state.seat;}g.focus=state.seat;g.queue=[];g.queueIndex=0;g.qaKeepGeneral=true;return guest;}
 function waiting(guest){guest.coaster=true;g.beginOrder(guest,false);guest.lineDone();guest.lineDone=null;guest.lines=[];guest.left=guest.limit;}
 function craft(grade){g.openRecipes();g.selectCocktail(state.cocktail);g.debugCraft(grade);}
 function runSituation(id){reset();g.qaKeepGeneral=false;let p;
  if(['arrival','order','wait','orange','red','exit','drink','reorder','reask','full','serve','wrong','missing'].includes(id)){p=general();if(id!=='arrival'&&id!=='full')waiting(p);}
  if(id==='order'){p.state='ORDER_DIALOGUE';g.beginOrder(p,false);}
  if(id==='orange')p.left=p.limit*.48;
  if(id==='red')p.left=8;
  if(id==='exit')g.leave(p,'leave_serve');
  if(id==='reask')g.reask();
  if(id==='full'){g.queue=[{personality:state.personality,order:state.cocktail,max_rounds:1},{personality:'gentle',order:state.cocktail,max_rounds:1},{personality:'gentle'}];g.queueIndex=0;g.spawn();g.spawn();g.spawn();}
  if(['serve','wrong','missing','drink','reorder'].includes(id)){craft(state.grade);if(id==='wrong')g.result.selected=g.t.cocktails.find(c=>c.id!==state.cocktail&&c.status==='confirmed').id;if(id==='missing')g.result.missingCore=[g.t.recipes.find(r=>r.context===state.cocktail).ingredient];g.offer();if(['drink','reorder'].includes(id)){g.serve(state.seat);if(id==='drink'){p.state='DRINKING';p.drinkLeft=8;p.lines=[];}else{p.state='ORDER_DIALOGUE';g.beginOrder(p,true);}}}
  if(id==='prep'){g.openRecipes();g.selectCocktail(state.cocktail);}
  if(id==='result')craft(state.grade);
  if(['settlement','bankrupt'].includes(id)){g.setUpkeepOverride(id==='bankrupt'?2000:100);g.finishDay();}
  if(['income','expense'].includes(id)){render(true);g.progress.money+=id==='income'?300:-300;}
  if(id==='unlock'){g.day=Number(state.sourceDay);g.pendingDailyUnlocks=true;g.phase='arrival';g.overlay='dailyUnlocks';}
  if(id==='dossier'){g.overlay='dossier';}
  finish('상황: '+STATES.find(x=>x[0]===id)?.[1]);
 }
 function finish(label){seen.add(label);lastCase={tab:state.tab,label};g.log('qa_case',{label,seed:state.seed});render(true);}
 function runBark(index){const row=D.tables.barks[index];reset();const p=general();waiting(p);if(D.characterLayers[row.voice_id]){p.actor=row.voice_id;p.appearance=null;}const actor=row.voice_id==='luna'?'luna':p.actor;p.lines=[g.makeLine(actor,g.text(row).replace(/\{cocktail\}/g,g.name(state.cocktail)),row.row_id,row.expression)];p.lineIndex=0;p.lineDone=null;p.idleLeft=9999;p.left=9999;p.limit=9999;finish('대사: '+row.row_id);}
 function runScene(){const source=D.tables.scenes.find(s=>s.id===state.scene);if(!source)throw Error('장면을 선택해 주세요.');const rows=sceneRows();let index=Number(state.step)||0;if(rows[index]?.type==='serve'&&rows[index-1]?.type==='craft')index--;const flags=JSON.parse(state.flags),result=JSON.parse(state.result);if(!flags||Array.isArray(flags)||typeof flags!=='object'||!result||Array.isArray(result)||typeof result!=='object')throw Error('조건은 JSON 객체로 입력해 주세요.');reset();g.progress.flags={campaign_selected_drink:state.cocktail,...flags};g.phase=source.phase==='bar_open'?'opening':'regular';g.story={phase:source.phase,autos:[],cursor:0,scene:source,index,steps:rows};
  // Prime stage/order context before a selected line without applying future effects.
  const seatActor=actor=>{if(!actor||actor==='luna'||Object.values(g.seats).some(p=>p?.actor===actor))return;const slot=['L','R','M'].find(k=>!g.seats[k]);if(slot)g.seats[slot]={id:actor,actor,state:'STORY',coaster:false,expression:'default'};};
  for(const r of rows.slice(0,index)){if(!W.LunaCore.condition(r.when,g.ctx()))continue;if(r.type==='enter')g.seats[r.arg]={id:r.actor,actor:r.actor,state:'STORY',coaster:false,expression:'default'};if(r.type==='exit'){const k=Object.keys(g.seats).find(k=>g.seats[k]?.actor===r.actor);if(k)g.seats[k]=null;}if(r.type==='coaster'){seatActor(r.actor);const p=Object.values(g.seats).find(p=>p?.actor===r.actor);if(p)p.coaster=true;}if(r.type==='order'){seatActor(r.actor);g.currentOrder=null;g.createStoryOrder(r);}if(r.type==='serve')g.currentOrder=null;}
  // QA sub-scenes can depend on actors already seated by a preceding hub scene.
  const mentioned=new Set();for(const r of rows.slice(index)){if(!r.actor||mentioned.has(r.actor)||r.actor==='luna')continue;mentioned.add(r.actor);if(r.type!=='enter')seatActor(r.actor);}
  g.resultContext={...g.resultContext,...result};const speaker=rows[index]?.actor,seat=Object.keys(g.seats).find(k=>g.seats[k]?.actor===speaker);if(seat)g.focus=seat;g.safe(()=>g.pump());finish('장면: '+source.id+' / '+(rows[index]?.seq||1));
 }
 function animationsHTML(){const keys=selectedPose();return `<div class="qa-fields">${field('actor','캐릭터 (리소스 미등록 인물 포함)',actors().map(id=>[id,actorName(id)]),state.actor)}${field('pose','등록된 표정 / 동작',poseEntries().map(([k])=>[k,k]),state.pose)}${field('playMode','재생 방식',[['loop','반복'],['once','한 번']],state.loop?'loop':'once')}</div><div class="qa-preview"><div class="qa-actor-canvas"></div>${!keys.length?'<p class="qa-empty">이 인물의 애니메이션 리소스는 아직 등록되지 않았습니다.<br>다른 캐릭터로 대체하지 않습니다.</p>':''}</div><div class="qa-actions">${btn(state.playing?'일시정지':'재생','play')}${btn('처음부터','rewind')}${btn('이전 프레임','prev')}${btn('다음 프레임','next')}</div><div class="qa-fields"><label>프레임<input data-qa-field="frame" type="range" min="0" max="${frames()-1}" value="${state.frame}" step="1"></label><label>속도 (FPS)<input data-qa-field="fps" type="number" min="1" max="30" value="${state.fps}"></label><div class="qa-status" data-frame-status></div></div><div class="qa-layer-list">${keys.map(k=>`<label><input type="checkbox" data-qa-layer="${esc(k)}" ${state.layers.has(k)?'':'checked'}>${esc(k)} · ${D.assets[k]?.frames||1}프레임</label>`).join('')}</div><p class="qa-note">원본 프레임을 직접 재생하는 검수 뷰입니다. 눈 깜빡임 간격을 둔 실제 대화 재생과는 다릅니다. 정적 이미지에는 움직임을 임의로 추가하지 않습니다.</p>`;}
 function draw(){if(!opened)return;const focusedField=host.contains(document.activeElement)?document.activeElement.dataset.qaField:null,scrollTop=host.querySelector('.qa-body')?.scrollTop||0;const external=outside.active&&outside.model.config.day===99;
  const tabs=external?[['outside','외부 사건 / 런타임'],['animations','표정·애니메이션']]:[['situations','영업 상황'],['barks','전체 일반 대사'],['scenes','장면·분기 데이터'],['animations','표정·애니메이션'],['gimmicks','제조 기믹']];if(!tabs.some(t=>t[0]===state.tab))state.tab=tabs[0][0];let body='';
  const commons=`<div class="qa-fields">${field('personality','손님 성격',D.tables.personalities.map(p=>[p.id,g.text(p,'name')]),state.personality)}${field('cocktail','주문 칵테일',g.t.cocktails.filter(c=>c.status==='confirmed').map(c=>[c.id,g.name(c.id)]),state.cocktail)}${field('seat','좌석',[['L','왼쪽'],['M','가운데'],['R','오른쪽']],state.seat)}${field('grade','제공 등급',D.tables.grade_cuts.map(r=>[r.grade,r.grade]),state.grade)}${field('sourceDay','해금 확인 일차',[1,2,3].map(n=>[n,n+'일차']),state.sourceDay)}${field('language','언어',[['ko','한국어'],['en','English']],state.language)}</div>`;
  if(state.tab==='situations')body=commons+'<p class="qa-note">선택하면 현재 QA 시도를 초기화합니다. 조건을 바꿔 같은 상황을 반복할 수 있습니다. 일반 손님 테스트는 손님이 퇴장해도 자동으로 단골 영업으로 넘어가지 않습니다.</p><div class="qa-list">'+STATES.map(([id,label])=>btn(label,'situation',id)).join('')+'</div>';
  if(state.tab==='barks'){const rows=D.tables.barks.map((r,i)=>({...r,index:i})).filter(r=>(state.situation==='all'||r.situation===state.situation)&&(state.voice==='all'||(r.voice_id||'common')===state.voice)&&(!state.search||JSON.stringify(r).toLowerCase().includes(state.search.toLowerCase())));body=commons+`<div class="qa-fields">${field('situation','상황',[['all','전체 상황'],...new Set(D.tables.barks.map(r=>r.situation))].map(v=>Array.isArray(v)?v:[v,v]),state.situation)}${field('voice','화자',[['all','전체'],...new Set(D.tables.barks.map(r=>r.voice_id||'common'))].map(v=>Array.isArray(v)?v:[v,g.name(v)]),state.voice)}<label>대사 / ID 검색<input data-qa-field="search" value="${esc(state.search)}"></label></div><p class="qa-note">${rows.length} / ${D.tables.barks.length}개 · 원본의 각 행을 직접 선택합니다. 자동 추첨하지 않습니다.</p><div class="qa-list">${rows.map(r=>`<button data-qa="bark" data-id="${r.index}"><span>${esc(g.text(r).replace(/\{cocktail\}/g,g.name(state.cocktail)))}</span><small>${esc(r.voice_id||'공통')} / ${esc(r.situation)} / ${esc(r.row_id)}</small></button>`).join('')}</div>`;}
  if(state.tab==='scenes'){if(!D.tables.scenes.some(s=>s.id===state.scene))state.scene=D.tables.scenes[0]?.id;const rows=sceneRows();body=`<div class="qa-fields">${field('scene','원본 일차 / 장면',D.tables.scenes.map(s=>[s.id,`${s.day}일차 · ${s.id}`]),state.scene)}${field('step','시작 스텝',rows.map((r,i)=>[i,`${r.seq} · ${r.type} · ${g.text(r).slice(0,38)||r.arg||r.actor||''}`]),state.step)}${field('language','언어',[['ko','한국어'],['en','English']],state.language)}</div><label>시작 플래그 JSON (예: {"chris_met":true})<textarea data-qa-field="flags">${esc(state.flags)}</textarea></label><label>판정·분기 조건 JSON (예: {"grade":"excellent"})<textarea data-qa-field="result">${esc(state.result)}</textarea></label><p class="qa-note">본편 0–3일차와 기존 99일차 장면을 실제 진행기로 실행합니다. 중간 시작은 이전 입장·코스터·주문 상태를 준비하며, 분기 조건은 입력한 값을 사용합니다. 원본 대사와 본편 저장 데이터는 수정하지 않습니다.</p>${btn('선택한 스텝부터 실행','scene','','qa-primary')}<div class="qa-list">${rows.map((r,i)=>`<button data-qa="step" data-id="${i}"><span>${r.seq} · ${esc(r.type)} · ${esc(g.text(r)||r.arg||'')}</span><small>화자 ${esc(r.actor||'—')} / 조건 ${esc(r.when||'없음')} / 효과 ${esc(r.effects||'없음')}</small></button>`).join('')}</div>`;}
  if(state.tab==='animations')body=animationsHTML();
  if(state.tab==='gimmicks')body='<p class="qa-note">현재 선택한 기존/GPT 규칙으로 실제 기믹을 실행합니다. 전체 칵테일 제조와 등급·버리기 검수는 영업 상황 탭에서 선택하세요.</p><div class="qa-list">'+[['open','병따기'],['pour','따르기'],['fill_up','필업'],['shake','쉐이킹'],['stir','스터']].map(([id,label])=>btn(label,'gimmick',id)).join('')+'</div>';
  if(state.tab==='outside'){const catalog=W.LunaOutsideQA.catalog();if(!state.outsideCase)state.outsideCase=outside.model.qa.caseId;body=`<p class="qa-note">99일차 전용 가상 공간 · 바닥과 검수 대상만 표시합니다. 연구소/사전 제작 영상은 제외합니다. 기존 데이터와 런타임 이동·대화·카메라를 사용하며 본편의 일차·재화·플래그에는 반영하지 않습니다.</p><div class="qa-fields">${field('outsideCase','외부 사건 / 데이터',catalog.map(c=>[c.id,c.label]),state.outsideCase)}${field('activation','시작 방식',[['source','기존 방식'],['manual','E 상호작용'],['proximity','범위 접근 자동']],state.activation)}${field('snack','시바에게 줄 간식',[['no','없음'],['yes','있음']],state.snack||'no')}</div>${btn('대상 앞에서 다시 시작','outside','','qa-primary')}<div class="qa-list">${catalog.map(c=>`<button data-qa="outside-pick" data-id="${esc(c.id)}"><span>${esc(c.label)}</span><small>${esc(c.note||'')} · ${esc(c.id)}</small></button>`).join('')}</div>`;}
  host.innerHTML=`<section class="qa-panel" role="dialog" aria-modal="true" aria-label="99일차 QA 실험실"><header><div><h2>${external?'외부':'바 내부'} · QA 99</h2><small>${external?'Tab · 열기/닫기 &nbsp; · &nbsp; Shift+Tab · 항목 이동':'데이터 선택 → 재현 → 반복 확인'}</small></div>${btn(external?'닫기 · Tab / Esc':'닫기 · Esc','close')}</header><nav class="qa-tabs">${tabs.map(([id,label])=>`<button data-qa="tab" data-id="${id}" aria-selected="${state.tab===id}">${label}</button>`).join('')}</nav><div class="qa-body"><div class="qa-coverage">${external?`<span>외부 QA ${W.LunaOutsideQA.catalog().length}</span><span>대화 ${W.LunaOutsideQA.catalog().filter(c=>c.source).length}</span><span>런타임 장면 ${W.LunaOutsideQA.catalog().filter(c=>c.scene).length}</span><span>이동·오브젝트 ${W.LunaOutsideQA.catalog().filter(c=>c.physical).length}</span>`:`<span>일반 대사 ${D.tables.barks.length}</span><span>장면 ${D.tables.scenes.length}</span><span>캐릭터 포즈 ${Object.values(D.characterLayers).reduce((n,p)=>n+Object.keys(p).length,0)}</span>`}<span>이번 방문 실행 ${seen.size}</span></div>${body}<p class="qa-error" role="alert"></p><div class="qa-actions">${btn('검수 상태·로그 다운로드','export')}</div></div></section>`;paintAnimation();if(focusedField){host.querySelector(`[data-qa-field="${focusedField}"]`)?.focus({preventScroll:true});host.querySelector(".qa-body").scrollTop=scrollTop;}}
 const imageCache=new Map();
 function paintAnimation(){if(!opened||state.tab!=='animations')return;const box=host.querySelector('.qa-actor-canvas');if(!box)return;const keys=selectedPose(),n=frames();state.frame=Math.min(n-1,state.frame);
  if(state.actor.startsWith('outside:')){if(!box.querySelector('canvas'))box.innerHTML='<canvas width="551" height="530" style="width:100%;height:100%;image-rendering:pixelated"></canvas>';const c=box.querySelector('canvas'),ctx=c.getContext('2d'),sp=outsideFrames()[state.frame];ctx.clearRect(0,0,551,530);if(sp&&!state.layers.has('outside-sprite')){const src=W.LUNA_OUTSIDE_DATA.assets[sp.asset].src;let im=imageCache.get(src);if(!im){im=new Image();imageCache.set(src,im);im.src=src;im.onload=paintAnimation;}if(im.complete&&im.naturalWidth){const scale=Math.min(4,500/sp.w,480/sp.h);ctx.imageSmoothingEnabled=false;ctx.drawImage(im,sp.x,sp.y,sp.w,sp.h,(551-sp.w*scale)/2,(530-sp.h*scale)/2,sp.w*scale,sp.h*scale);}}}
  else box.innerHTML=keys.filter(k=>!state.layers.has(k)).map(k=>{const a=D.assets[k];if(!a)return '';const count=a.frames||1,f=state.frame%count,fw=a.frameWidth||a.w/count,fh=a.frameHeight||a.h;const offset=D.webPoseOffsets?.[state.actor]?.[state.pose]||[0,0];return `<div class="actor-layer" data-layer="${esc(k)}" data-frame="${f}" style="width:${fw/551*100}%;height:${fh/530*100}%;left:${50+offset[0]/551*100}%;bottom:${-offset[1]/530*100}%;background-image:url('${esc(a.src)}');background-size:${count*100}% 100%;background-position:${count>1?f/(count-1)*100:0}% 0"></div>`;}).join('');const status=host.querySelector('[data-frame-status]');if(status)status.textContent=`${state.frame+1} / ${n} 프레임 · ${n===1?'정적 리소스':state.playing?'재생 중':'일시정지'} · ${state.fps} FPS`;const slider=host.querySelector('[data-qa-field="frame"]');if(slider)slider.value=state.frame;}
 function runOutside(){const id=state.outsideCase;close();outside.clearInput();outside.model.start({...outside.config,day:99,qaCase:id,qaActivation:state.activation,qaSnack:state.snack==='yes'});Object.assign(outside.config,{day:99,qaCase:id,qaActivation:state.activation,qaSnack:state.snack==='yes'});outside.model.paused=false;outside.snapCamera();seen.add(id);lastCase={tab:'outside',label:id};}
 host.addEventListener('click',e=>{const b=e.target.closest('[data-qa]');if(!b)return;const id=b.dataset.id;try{switch(b.dataset.qa){case'close':close();break;case'tab':state.tab=id;draw();break;case'situation':runSituation(id);break;case'bark':runBark(Number(id));break;case'scene':runScene();break;case'step':state.step=id;runScene();break;case'play':state.playing=!state.playing;draw();break;case'rewind':state.frame=0;age=0;paintAnimation();break;case'prev':case'next':state.playing=false;state.frame=(state.frame+(b.dataset.qa==='next'?1:-1)+frames())%frames();draw();break;case'gimmick':reset();g.startMinigame(id,ui.variant,'standard');ui.minigames=true;finish('기믹: '+id);break;case'outside-pick':state.outsideCase=id;runOutside();break;case'outside':runOutside();break;case'export':{const data={case:lastCase,settings:{...state,layers:[...state.layers]},coverage:[...seen],bar:{day:g.day,phase:g.phase,screen:g.screen,progress:g.progress,logs:g.logs},outside:outside.active?{config:outside.model.config,qa:outside.model.qa,flags:outside.model.story.flags}:null};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='luna-qa99.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);break;}}}catch(err){if(!opened)open();host.querySelector('.qa-error').textContent=err.message;}});
 host.addEventListener('change',e=>{const key=e.target.dataset.qaField;if(key){state[key]=e.target.value;if(key==='frame'){state.frame=Number(state.frame);state.playing=false;}if(key==='fps')state.fps=Math.max(1,Math.min(30,Number(state.fps)||6));if(key==='playMode')state.loop=e.target.value==='loop';if(['actor','pose'].includes(key)){state.frame=0;state.layers.clear();age=0;}if(key==='scene')state.step='0';draw();}const layer=e.target.dataset.qaLayer;if(layer){if(e.target.checked)state.layers.delete(layer);else state.layers.add(layer);paintAnimation();}});
 launch.onclick=()=>open(outside.active?'outside':undefined);
 const outsideShortcut=()=>W.lunaCampaign?.view==='developer'&&outside.active&&!outside.loading&&outside.model?.config.day===99;
 function tick(dt){const external=outside.active&&outside.model?.config.day===99;launch.classList.toggle('is-outside',external);const scope=external?'outside':'bar';if(launch.dataset.scope!==scope){launch.dataset.scope=scope;launch.innerHTML=external?'<kbd>Tab</kbd><span>외부 QA · 상황 선택</span>':'QA 99 · 상황 선택';if(external)launch.setAttribute('aria-keyshortcuts','Tab');else launch.removeAttribute('aria-keyshortcuts');}const eligible=W.lunaCampaign?.view==='developer'&&(outside.active?outside.model.config.day===99:ui.day===99||g.day===99);launch.hidden=!eligible||opened;if(!opened)return;if(state.playing&&state.tab==='animations'){age+=dt*state.fps;while(age>=1){age--;if(state.frame+1<frames())state.frame++;else if(state.loop)state.frame=0;else state.playing=false;}paintAnimation();}}
 return{open,close,tick,outsideShortcut,get opened(){return opened;},state,runSituation,runBark,runScene,host};
}
// Register before the game handlers so editing JSON or a selector never moves the player.
W.addEventListener('keydown',e=>{const lab=W.lunaQA;if(lab?.outsideShortcut()&&e.code==='Tab'&&!e.shiftKey&&!e.ctrlKey&&!e.metaKey&&!e.altKey){e.preventDefault();e.stopImmediatePropagation();if(!e.repeat){if(lab.opened)lab.close();else lab.open('outside');}return;}if(!lab?.opened)return;if(e.code==='Escape'){e.preventDefault();lab.close();}else if(e.code==='Tab'){const nodes=[...lab.host.querySelectorAll('button:not(:disabled),select,input,textarea')].filter(n=>n.getClientRects().length),i=nodes.indexOf(document.activeElement);e.preventDefault();nodes[(i+(e.shiftKey?-1:1)+nodes.length)%nodes.length]?.focus();}e.stopImmediatePropagation();},true);
W.LunaQALab={create,STATES};
})(window);
