(function(root){
'use strict';
root.LunaRemixUI=function({g,D,ui,L,esc,a,button,itemArt,drinkArt,recipeLines,remix}){
 const KEY='luna.bar.gpt.v1';let saved={favorites:[],best:{},runs:[]};
 try{const value=JSON.parse(localStorage.getItem(KEY)||'null');if(value&&Array.isArray(value.favorites)&&value.best&&Array.isArray(value.runs))saved=value;}catch{}
 const persist=()=>{try{localStorage.setItem(KEY,JSON.stringify(saved));}catch{}};
 const favorite=id=>saved.favorites.includes(id);
 g.onRemixRecord=r=>{if(r.debug)return;const previous=Number(saved.best[r.selected]??-1);r.personalBest=r.score>previous;if(r.personalBest){saved.best[r.selected]=r.score;persist();}};
 const tabsHTML=()=>`<nav class="version-tabs" aria-label="${L('플레이 버전','Game version')}">${button(L('기존 버전','Original'),'version','data-id="original" aria-pressed="'+(!ui.minigames&&ui.variant!=='gpt')+'"',!ui.minigames&&ui.variant!=='gpt'?'selected':'')}${button(L('GPT 개선버전','GPT Remix'),'version','data-id="gpt" aria-pressed="'+(!ui.minigames&&ui.variant==='gpt')+'"',!ui.minigames&&ui.variant==='gpt'?'selected':'')}${button(L('기믹 미니게임','Gimmick minigames'),'version','data-id="minigames" aria-pressed="'+!!ui.minigames+'"',ui.minigames?'selected':'')}</nav>`;
 function startHTML(){
  const diff=ui.difficulty||'standard',cost=remix.challengeUpkeep(ui.day,diff),mode=ui.mode;
  const profile={cozy:L('여유로운 인내심 · 짧은 기믹 · 낮은 유지비','More patience · shorter mixing · lower upkeep'),standard:L('적당한 압박 · 연속 보너스 · 균형 잡힌 영업','Balanced pressure · streak bonuses · a full shift'),challenge:L('빠른 손님 교체 · 긴 기믹 · 높은 유지비','Faster arrivals · longer mixing · higher upkeep')};
  return `<div class="start-screen remix-start">${tabsHTML()}<section class="intro"><div class="eyebrow">GPT REMIX / EXPERIMENTAL</div><h1>${L('한 잔 더.<br><span>조금 더 잘.</span>','One more drink.<br><span>A little better.</span>')}</h1><p class="lede">${L('좋은 한 잔을 연속으로 만들고,<br>여덟 팀의 밤을 무사히 마무리하세요.','Find your rhythm, build a streak,<br>and see eight parties through the night.')}</p><div class="remix-feature-grid"><div><b>01</b><strong>${L('쉬운 주문부터','Ease into service')}</strong><span>${L('처음은 단순하게, 뒤로 갈수록 다양하게','Simple orders first, more variety later')}</span></div><div><b>02</b><strong>${L('실패가 다음 잔의 힌트','Learn with each drink')}</strong><span>${L('따르기 예상량 · 단계 피드백 · 재도전','Pour prediction · feedback · retry')}</span></div><div><b>03</b><strong>${L('목표와 연속 보너스','Goals & streaks')}</strong><span>${L('좋은 평가 · 다양한 메뉴 · 나만의 최고점','Great reviews · variety · personal bests')}</span></div></div><p class="remix-disclaimer">${L('기존 버전·원본 CSV·단골 대사는 변경하지 않습니다.<br>이 탭의 난이도·보상·조작 보조는 비교용 실험 규칙입니다.','The original version, CSV and story dialogue are unchanged.<br>Difficulty, rewards and assists here are experimental.')}</p></section>
   <section class="start-card"><div class="eyebrow">MAKE TONIGHT YOURS</div><h2>${L('오늘의 영업','Tonight’s shift')}</h2><label for="start-mode">${L('플레이 방식','Play mode')}</label><select id="start-mode" data-change="mode"><option value="challenge" ${mode==='challenge'?'selected':''}>${L('추천 · 8팀 챌린지 영업','Recommended · eight-party shift')}</option>${[['full','기존 대본 전체 흐름','Original story flow'],['general','일반 손님 영업','General guest service'],['regular','단골 손님 대화','Regular guest story'],['practice','제조 연습','Craft practice']].map(([v,ko,en])=>`<option value="${v}" ${mode===v?'selected':''}>${L(ko,en)}</option>`).join('')}</select><label>${L('사용할 일차의 해금 목록','Recipe unlocks by day')}</label><div class="day-list">${[0,1,2,3,99].map(day=>button(day===99?L('전체 해금','All unlocked'):L(day+'일차','Day '+day),'day',`data-id="${day}"`,ui.day===day?'selected':'')).join('')}</div>
   <label>${L('난이도','Difficulty')}</label><div class="remix-difficulties">${[['cozy','편안하게','Cozy'],['standard','보통','Standard'],['challenge','도전','Challenge']].map(([id,ko,en])=>button(L(ko,en),'remixDifficulty',`data-id="${id}" aria-pressed="${diff===id}"`,diff===id?'selected':'')).join('')}</div><p class="remix-profile">${profile[diff]}</p><label class="remix-assist"><input type="checkbox" data-change="remixAssist" ${ui.assist!==false?'checked':''}>${L('주문 메모·재료 준비 가이드','Order notes & preparation guide')}</label>
   <div class="remix-economy"><span>${L('시작 소지금','Starting cash')}<b>${g.c('gold_start',300)} G</b></span><span>${mode==='challenge'?L('이번 챌린지 유지비','Challenge upkeep'):L('데이터 기준 유지비','Data upkeep')}<b>${mode==='challenge'?cost:Number(g.t.days.find(d=>Number(d.day)===ui.day)?.upkeep_gold||0)} G</b></span></div><small class="remix-budget-note">${mode==='challenge'?L('8팀 영업 후 보유금으로 지불합니다. 목표 달성 보상은 최대 70G.','Paid from your balance after eight parties. Goals award up to 70G.'):L('선택한 일차의 기존 흐름에 개선 기능을 적용합니다. 빈 대본은 원래대로 건너뜁니다.','Uses the selected day’s existing content; empty sections stay empty.')}</small>
   ${button(L('개선버전 시작 →','Play GPT Remix →'),'start','','primary remix-play')}<div class="remix-start-foot"><span>${saved.runs.length?L('챌린지 완료 기록 ','Completed shifts ')+saved.runs.length:L('기록은 이 브라우저의 개선버전에만 저장','Records stay in this browser’s Remix')}</span>${button(L('조작 안내','Controls'),'help','','subtle')}</div></section></div>`;
 }
 const goals=()=>[{name:L('Good 이상 4잔','4 Good-or-better drinks'),value:g.remix.good,target:4,reward:30},{name:L('서로 다른 메뉴 3종','3 different recipes'),value:g.remix.variety.size,target:3,reward:20},{name:L('Good 이상 3연속','3 great drinks in a row'),value:g.remix.maxCombo,target:3,reward:20}];
 function helpHTML(){const p=root.LunaRemix.PROFILES[g.phase==='ready'?(ui.difficulty||'standard'):g.remix.difficulty];return `<div class="help-grid"><section><h3>${L('영업','Service')}</h3><p>A / D · ${L('좌석 이동','Change seat')}</p><p>Space · ${L('코스터 전달','Give coaster')}</p><p>Tab · ${L('서비스 패널','Service panel')}</p><p>E · ${L('주문 되묻기 · 최초 제한시간의 10% 차감','Ask again · costs 10% of initial patience')}</p><p>Y · ${L('대사 기록','Dialogue history')}</p><p>ESC · ${L('메뉴 닫기 / 옵션·일시정지','Close menu / options & pause')}</p></section><section><h3>${L('제조','Crafting')}</h3><p>${L('따르기: Space를 누르고 놓기. 노란 선은 놓았을 때 예상량입니다.','Pour: hold/release Space. The gold mark predicts your final amount.')}</p><p>${L('병따기: 원이 맞을 때 Space. 성공하면 자동 진행.','Open: Space when rings align. Advances automatically.')}</p><p>${L('쉐이킹: 분홍 표시가 노드와 겹칠 때 클릭 또는 Space. 입력한 '+p.shake+'회만 판정합니다.','Shake: click or Space on node overlap. Only your '+p.shake+' inputs count.')}</p><p>${L('스터: W로 시작, D→S→A→W. '+p.stir+'바퀴. 입력한 순서대로 판정합니다.','Stir: start W, then D→S→A→W for '+p.stir+' rounds. Keys are judged in event order.')}</p></section></div><p class="recipe-note">${L('제조·메뉴 중에는 손님 시간이 멈춥니다. 원본 대사와 선택지는 그대로이며, 연속 보너스·목표·난이도는 개선버전만의 실험입니다.','Guest timers pause during crafting and menus. Story dialogue is unchanged. Streaks, goals and difficulty are Remix-only experiments.')}</p>`;}
 function goalsHTML(){return `<div class="remix-goal-list">${goals().map(x=>`<div class="${x.value>=x.target?'done':''}"><span>${x.value>=x.target?'✓':'○'} ${x.name}</span><b>${Math.min(x.value,x.target)} / ${x.target}</b><small>+${x.reward} G</small><progress value="${Math.min(x.value,x.target)}" max="${x.target}"></progress></div>`).join('')}</div><p class="recipe-note">${L('목표 보상은 영업 정산 직전에 한 번만 지급됩니다. 연속 보너스는 Good 이상 두 번째 잔부터 +3G, 최대 +12G입니다.','Goals pay once at settlement. From the second Good-or-better drink, streak bonuses grow by 3G up to 12G.')}<br>${L('주문 불일치·낮은 평가·손님 이탈은 연속 기록을 끊습니다. F2 테스트 제조는 정식 기록·목표 보상에서 제외됩니다.','Wrong orders, low grades or lost guests break the streak. F2-generated drinks do not qualify for records or goal rewards.')}</p><label class="remix-assist"><input type="checkbox" data-change="remixLiveAssist" ${g.remix.assist?'checked':''}>${L('주문 메모·재료 준비 가이드','Order notes & preparation guide')}</label><label class="remix-assist"><input type="checkbox" data-change="remixAudio" ${ui.remixAudio!==false?'checked':''}>${L('작은 판정·알림 효과음','Gentle judgement & notification sounds')}</label>`;}
 function seatClass(seat){const x=g.seats[seat];if(!x)return'remix-seat-empty';if(x.state==='EXITING')return'remix-seat-exit';if(['WAIT_COASTER','WAIT_SERVE'].includes(x.state)){const left=x.left/x.limit;return left<=.2?'remix-seat-danger':left<=.5?'remix-seat-warn':'remix-seat-occupied';}return'remix-seat-occupied';}
 function seatLabel(seat){const x=g.seats[seat],state=x?({WAIT_COASTER:L('코스터 대기','Needs coaster'),ORDER_DIALOGUE:L('주문 중','Ordering'),WAIT_SERVE:L('서빙 대기','Awaiting drink'),DRINKING:L('마시는 중','Drinking'),REACTION:L('반응 중','Responding'),EXITING:L('퇴장 중','Leaving'),REORDER_WAIT:L('추가 주문','Reordering')})[x.state]||L('손님 있음','Occupied'):L('빈 좌석','Empty');return`${seat} · ${state}${x&&['WAIT_COASTER','WAIT_SERVE'].includes(x.state)?' · '+Math.max(0,Math.ceil(x.left))+'s':''}`;}
 function hudHTML(){
  if(!remix.active()||g.finished||g.phase==='ready'||g.isPaused())return'';
  const r=g.remix,guest=g.seats[g.focus];let context='';
  if(g.screen==='bar'&&g.phase==='general'){
   if(guest?.state==='WAIT_COASTER')context=L('Space · 앞자리 손님에게 코스터를 주세요','Space · give this guest a coaster');
   else if(guest?.state==='ORDER_DIALOGUE')context=L('손님의 주문을 듣는 중','Listening to the order');
   else if(guest?.state==='WAIT_SERVE')context=g.drink?L('중앙 아래 잔을 이 손님의 코스터에 놓으세요','Drag the drink to this guest’s coaster'):r.assist?L('주문 메모: ','Order note: ')+g.name(guest.order.cocktail):L('Tab · 제조하기 / E · 주문 되묻기','Tab · craft / E · ask again');
  }
  return `${g.screen==='bar'?`<div class="remix-run-hud">${button(L('영업 목표','Shift goals'),'remixGoals','','remix-goal-button')}<span>${r.challenge?`${r.served+g.lost} / 8`:r.served+L('잔 제공',' served')}</span><span class="remix-combo">${r.combo>1?`${r.combo} COMBO`:L('새 연속 기록에 도전','Start a fresh streak')}</span></div>${context?`<div class="remix-context ${guest?.state==='WAIT_SERVE'&&r.assist?'has-order':''}"><span>${esc(context)}</span>${guest?.state==='WAIT_SERVE'&&!g.drink?button(L('레시피 열기','Open recipes'),'recipes','','subtle'):''}</div>`:''}`:''}
   ${r.notice&&g.realTime<r.notice.until&&!g.overlay?`<div class="remix-notice ${r.notice.kind}" role="status">${esc(L(r.notice.ko,r.notice.en))}</div>`:''}`;
 }
 function recipesHTML(){
  const unlocked=g.cocktailsAvailable(),query=(ui.search||'').trim().toLowerCase(),filter=ui.remixFilter||'all';
  const rows=g.t.cocktails.filter(c=>c.status==='confirmed').slice().sort((a,b)=>Number(a.unlock_day)-Number(b.unlock_day)||remix.complexity(a)-remix.complexity(b));
  const visible=rows.filter(c=>{const ok=unlocked.some(x=>x.id===c.id);if(!ok)return!query&&filter==='all';return g.name(c.id).toLowerCase().includes(query)&&(filter==='all'||filter==='favorite'&&favorite(c.id)||c.mix===filter);});
  const peek=unlocked.find(c=>c.id===ui.peek)||unlocked[0];
  return `<div class="remix-recipes"><aside class="side-panel"><div class="panel-header"><div class="row spread"><h2>${L('칵테일 레시피','Recipes')}</h2>${button('×','closeRecipe')}</div><input id="recipe-search" data-input="search" value="${esc(ui.search)}" placeholder="${L('칵테일 이름 검색','Find a cocktail')}" aria-label="${L('레시피 검색','Recipe search')}"><div class="remix-filters">${[['all','전체','All'],['build','빌드','Build'],['stir','스터','Stir'],['shake','쉐이킹','Shake'],['favorite','★ 즐겨찾기','★ Favorites']].map(([id,ko,en])=>button(L(ko,en),'remixFilter',`data-id="${id}" aria-pressed="${filter===id}"`,filter===id?'selected':'')).join('')}</div></div>
   <div class="recipe-list">${visible.map(c=>{const ok=unlocked.some(x=>x.id===c.id);return `<div class="remix-recipe-row"><button class="recipe-card ${!ok?'locked':peek?.id===c.id?'selected':''}" data-act="remixPreview" data-id="${c.id}" ${ok?'':'disabled'}>${drinkArt(c.id,'recipe')}<div><strong>${ok?esc(g.name(c.id)):'???'}</strong><small>${ok?`${c.mix.toUpperCase()} · ${L('난이도','Complexity')} ${'●'.repeat(Math.min(3,Math.ceil(remix.complexity(c)/2)))}`:L(c.unlock_day+'일차 해금','Unlocks day '+c.unlock_day)}</small>${ok&&saved.best[c.id]!=null?`<small class="remix-best">BEST ${Number(saved.best[c.id]).toFixed(0)}</small>`:''}</div></button>${ok?button(favorite(c.id)?'★':'☆','remixFavorite',`data-id="${c.id}" aria-label="${esc(g.name(c.id))} ${L('즐겨찾기','favorite')}" aria-pressed="${favorite(c.id)}"`,'remix-star'):''}</div>`;}).join('')||`<p class="empty">${L('조건에 맞는 레시피가 없습니다.','No matching recipes.')}</p>`}</div></aside>
   ${peek?`<section class="remix-recipe-detail"><div class="eyebrow">RECIPE / ${peek.mix.toUpperCase()}</div><h2>${esc(g.name(peek.id))}</h2><div class="remix-detail-grid"><div>${drinkArt(peek.id,'recipe')}${saved.best[peek.id]!=null?`<p class="remix-best">PERSONAL BEST ${Number(saved.best[peek.id]).toFixed(0)}</p>`:''}</div><div>${recipeLines(peek)}</div></div><p>${esc(g.text(peek,'recipe_desc'))}</p><small>${L('레시피를 확인한 뒤 선택하세요. 주문과 다른 레시피도 선택할 수 있습니다.','Review before choosing. This does not check whether the recipe matches an order.')}</small>${button(L('이 레시피로 만들기 →','Prepare this recipe →'),'selectRecipe',`data-id="${peek.id}"`,'primary')}</section>`:''}</div>`;
 }
 function prepHTML(){if(!remix.active()||!g.remix.assist||!g.prep||ui.recipeOpen)return'';const c=g.cocktail(g.prep.selected),ids=g.t.recipes.filter(r=>r.context===c.id&&!r.auto_apply).map(r=>r.ingredient),missing=ids.filter(id=>!g.prep.ingredients.includes(id)),tool=c.mix==='shake'?'shaker':c.mix==='stir'?'mixing_glass':null;
  return `<div class="remix-prep-check"><b>${L('준비 가이드','Preparation guide')}</b><span class="${g.prep.glass===c.glass?'done':''}">${g.prep.glass===c.glass?'✓':'○'} ${esc(g.name(c.glass))}</span><span class="${(g.prep.tool||null)===tool?'done':''}">${(g.prep.tool||null)===tool?'✓':'○'} ${tool?esc(g.name(tool)):L('믹스 도구 없음','No mixing tool')}</span><span class="${!missing.length?'done':''}">${!missing.length?'✓':'○'} ${L('재료','Ingredients')} ${ids.length-missing.length}/${ids.length}</span>${missing.length?`<small>${L('남은 재료: ','Still needed: ')}${missing.map(id=>esc(g.name(id))).join(' · ')}</small>`:`<small>${L('정답 재료가 모였어요. 추가 재료는 감점될 수 있어요.','Required ingredients are ready. Extras may reduce the score.')}</small>`}</div>`;
 }
 function feedback(s){
  if(['pour','fill_up'].includes(s.type)){if(!s.inRecipe)return L('추가 재료 · 정답 수량이 없는 재료입니다.','Extra ingredient · no recipe target.');const pct=(s.value/s.target-1)*100;return Math.abs(pct)<5?L('정확한 한 번!','Right on target!'):pct>0?L(`${pct.toFixed(0)}% 많이 따랐어요. 다음엔 조금 일찍 놓아 보세요.`,`${pct.toFixed(0)}% over. Release a little earlier next time.`):L(`${Math.abs(pct).toFixed(0)}% 부족해요. 다음엔 조금 더 채워 보세요.`,`${Math.abs(pct).toFixed(0)}% short. Pour a little longer next time.`);}
  if(s.type==='open')return s.failures?L(`${s.failures}번 빗나갔지만 열었어요.`,`${s.failures} misses, but you opened it.`):L('한 번에 깔끔하게!','A clean first try!');
  return L(`${s.success}/${s.targetStacks} 성공 · ${s.success===s.targetStacks?'완벽한 리듬!':'다음 잔에서 더 정확하게!'}`,`${s.success}/${s.targetStacks} hits · ${s.success===s.targetStacks?'Perfect rhythm!':'Try for an even cleaner next drink!'}`);
 }
 function gimmickHTML(){if(!remix.active()||!g.gimmick||g.gimmick.fluid||['open','shake','stir'].includes(g.gimmick.type))return'';const s=g.gimmick;
  if(g.remix.hold)return`<div class="remix-step-feedback" role="status"><span>${['pour','fill_up'].includes(s.type)?'◌':'✓'}</span><h2>${feedback(s)}</h2><small>${L('잠시 후 다음 단계로 이어집니다.','Continuing to the next step…')}</small></div>`;
  return'';
 }
 function resultHTML(){const r=g.result,lock=g.remix.resultLock>0,labels={excellent:L('완벽한 한 잔','Excellent'),good:L('좋은 한 잔','Good'),decent:L('괜찮은 한 잔','Decent'),poor:L('연습이 더 필요해요','Needs practice'),sewage:L('다시 만들어 볼까요?','Try another batch?')};const hints=[];
  if(r.missing.length)hints.push(L('빠진 재료: ','Missing: ')+r.missing.map(id=>g.name(id)).join(', '));if(r.extra.length)hints.push(L('추가된 재료: ','Extra: ')+r.extra.map(id=>g.name(id)).join(', '));if(r.penalties.glass)hints.push(L('잔이 달라요. 필요한 잔: ','Wrong glass. Recipe uses ')+g.name(g.cocktail(r.selected).glass));if(r.penalties.tool)hints.push(L('믹스 도구를 레시피와 맞춰 보세요.','Match the mixing tool to the recipe.'));if(r.penalties.gimmick)hints.push(L('기믹 정확도를 높이면 더 좋은 등급을 받을 수 있어요.','More accurate inputs will improve the grade.'));if(r.penalties.overtime)hints.push(L('조작 시간을 조금 줄여 보세요.','Try reducing active crafting time.'));
  return `<div class="craft-screen remix-result"><div class="craft-top"><h2>${L('이번 한 잔의 기록','Your drink, reviewed')}</h2><span class="badge">${L('주문 일치 여부는 서빙할 때 판정','Order match is checked when serving')}</span></div><div class="remix-result-grid"><section class="remix-result-hero">${drinkArt(r.selected)}<div class="eyebrow">${r.personalBest?'NEW PERSONAL BEST':'CRAFT RESULT'}${r.debug?' · TEST':''}</div><h2>${labels[r.grade]}</h2><strong class="remix-score">${r.score.toFixed(0)}<small> / 100</small></strong><p>${esc(g.name(r.selected))}</p><small>${L('실제 선택한 잔: ','Selected glass: ')}${esc(g.name(r.actual.glass))}</small></section><section class="remix-result-notes"><h3>${hints.length?L('다음 잔은 이렇게','For your next drink'):L('준비와 제조가 모두 좋았어요','Well prepared, well crafted')}</h3><ul>${(hints.length?hints:[L('이 정확도를 유지해서 손님의 주문에 맞게 전달해 보세요.','Keep this accuracy and serve the correct order.')]).map(h=>`<li>${esc(h)}</li>`).join('')}</ul><div class="remix-step-results">${r.results.map(s=>`<div><span>${esc(s.ingredient?g.name(s.ingredient):s.type.toUpperCase())}</span><b>${['pour','fill_up'].includes(s.type)?Number(s.value).toFixed(2)+' '+(g.craft.queue.find(q=>q.type===s.type&&q.ingredient===s.ingredient)?.unit||''):s.type==='open'?L(s.failures+'회 실수',s.failures+' misses'):Math.round((s.completion||0)*100)+'%'}</b></div>`).join('')}</div><div class="remix-result-actions">${button(L('제공하기 →','Serve →'),'offer',lock?'disabled':'','primary')}${button(L('같은 구성으로 재도전','Retry this setup'),'remixRetry',lock?'disabled':'')}${button(L('버리고 다시 준비','Discard & prepare'),'discard',lock?'disabled':'','subtle')}</div><small>${lock?L('결과 확인 중…','Reviewing…'):L('재도전은 새로운 제조입니다. 이전 결과는 서빙하지 않습니다.','Retry starts a new attempt; the old result is not served.')}</small></section></div></div>`;
 }
 function summaryHTML(){if(!remix.active())return'';const r=g.remix,ratio=r.served?r.good/r.served:0,rank=r.served>=7&&ratio>=.85&&!g.lost?'S':r.served>=5&&ratio>=.7?'A':r.served>=3?'B':'C';return`<section class="remix-summary"><div class="remix-rank">${r.debug?'TEST':rank}</div><div><b>${L('오늘의 바텐더 리포트','Tonight’s bartender report')}</b><p>${L('좋은 평가','Great reviews')} ${r.good}/${r.served} · ${L('최고 연속','Best streak')} ${r.maxCombo} · ${L('이탈','Lost guests')} ${g.lost}</p><p>${L('연속 보너스','Streak bonus')} ${r.bonus}G + ${L('목표 보상','Goal rewards')} ${r.goalBonus}G</p></div></section><div class="remix-summary-goals">${goals().map(x=>`<div class="${x.value>=x.target?'done':''}"><span>${x.value>=x.target?'✓':'○'} ${x.name}</span><b>${Math.min(x.value,x.target)}/${x.target} · +${!r.debug&&x.value>=x.target?x.reward:0}G</b></div>`).join('')}</div>${r.debug?`<p class="recipe-note">${L('테스트 보조를 사용한 영업입니다. 정식 완료 기록과 목표 보상에서 제외됩니다.','Testing tools were used. This run is excluded from completion records and goal rewards.')}</p>`:''}`;}
 function recordRun(){if(!remix.active()||!g.dailySettlement||g.dailySettlement.status==='pending'||g.remix.recorded||g.remix.debug||!g.remix.challenge)return;g.remix.recorded=true;saved.runs.push({day:g.day,difficulty:g.remix.difficulty,served:g.remix.served,good:g.remix.good,maxCombo:g.remix.maxCombo,paid:g.dailySettlement.status==='paid',at:Date.now()});saved.runs=saved.runs.slice(-20);persist();}
 function act(name,id){
  if(name==='remixDifficulty'){ui.difficulty=id;return true;}if(name==='remixFilter'){ui.remixFilter=id;return true;}if(name==='remixPreview'){ui.peek=id;return true;}if(name==='remixFavorite'){if(favorite(id))saved.favorites=saved.favorites.filter(x=>x!==id);else saved.favorites.push(id);persist();return true;}if(name==='remixGoals'){g.overlay='remixGoals';return true;}if(name==='remixRetry'){g.remixRetry();return true;}return false;
 }
 let audio=null,lastCue=0,lastSession=null;
 function unlockAudio(){if(!remix.active()||ui.remixAudio===false)return;try{audio=audio||new(window.AudioContext||window.webkitAudioContext)();if(audio.state==='suspended')audio.resume().catch(()=>{});}catch{}}
 function soundTick(){if(!remix.active())return;if(lastSession!==g.remix){lastSession=g.remix;lastCue=0;}const cue=g.remix.cue;if(!cue||lastCue===cue.id)return;lastCue=cue.id;if(['open','shake','stir'].includes(g.gimmick?.type)&&['hit','miss','step'].includes(cue.kind))return;if(!audio||audio.state!=='running'||ui.remixAudio===false)return;try{const o=audio.createOscillator(),gain=audio.createGain(),freq={hit:660,miss:160,complete:880,arrival:440,order:520,start:330,step:740,low:220}[cue.kind]||440;o.type='sine';o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(freq*1.12,audio.currentTime+.09);gain.gain.setValueAtTime(.035,audio.currentTime);gain.gain.exponentialRampToValueAtTime(.0001,audio.currentTime+.13);o.connect(gain);gain.connect(audio.destination);o.start();o.stop(audio.currentTime+.14);o.onended=()=>{o.disconnect();gain.disconnect();};}catch{}}
 return{tabsHTML,startHTML,goalsHTML,hudHTML,helpHTML,seatClass,seatLabel,recipesHTML,prepHTML,gimmickHTML,resultHTML,summaryHTML,recordRun,act,unlockAudio,soundTick};
};
})(window);
