(function(){
'use strict';
const G=window.LUNA_STORY_GUIDE,D=window.LUNA_DATA,S=window.LUNA_CAMPAIGN_DATA;
const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let day=Math.max(0,Math.min(3,Number(location.hash.match(/^#day-([0-3])$/)?.[1]||0))),eventIndex=0,person='luna';
function portrait(id){const layers=D.characterLayers[id],key=layers&&Object.keys(layers).find(k=>k.endsWith('idle_default'));if(!key)return '<span class="portrait fallback" aria-hidden="true">'+(id==='johnny'?'J':'L')+'</span>';const arts=layers[key].map(k=>D.assets[k]).filter(Boolean);const staticArt=arts.length===1&&arts[0].static;const bounds=staticArt?arts[0].alphaBBox:(D.webActorBounds[id]||[55,80,490,465]),bw=bounds[2]-bounds[0],bh=bounds[3]-bounds[1];return '<span class="portrait" aria-hidden="true" style="aspect-ratio:'+bw+'/'+bh+'">'+arts.map(a=>'<i style="left:'+(-bounds[0]/bw*100)+'%;top:'+(-bounds[1]/bh*100)+'%;width:'+((a.frameWidth||a.w)/bw*100)+'%;height:'+((a.frameHeight||a.h)/bh*100)+'%;background-image:url('+esc(a.src)+');background-size:'+((a.frames||1)*100)+'% 100%"></i>').join('')+'</span>';}
function name(id){return G.people[id]?.name||S.actors&&Object.keys(S.actors).find(n=>S.actors[n]===id)||id;}
$('#hero-cast').innerHTML=['chris','tom','samho'].map(portrait).join('');
$('#overview').innerHTML=G.days.map(d=>'<button data-day="'+d.day+'" data-scroll="true" style="--day:'+d.color+'"><small>DAY 0'+d.day+'</small><strong>'+d.word+'</strong><p>'+d.after+'</p><span class="arrow" aria-hidden="true">↗</span></button>').join('');
$('#day-tabs').innerHTML=G.days.map(d=>'<button role="tab" id="tab-day-'+d.day+'" aria-controls="day-panel" data-day="'+d.day+'" style="--day:'+d.color+'">'+d.day+'일차 · '+d.word+'</button>').join('');
function setDay(n){day=n;eventIndex=0;const d=G.days[day];$('#day-panel').style.setProperty('--day',d.color);$('#day-panel').setAttribute('aria-labelledby','tab-day-'+day);document.querySelectorAll('[role=tab]').forEach((b,i)=>{b.setAttribute('aria-selected',i===day);b.tabIndex=i===day?0:-1;});
 $('#day-panel').innerHTML='<div class="day-intro"><div><h3>'+d.title+'</h3><p>'+d.question+'</p></div><div class="cast-chips">'+d.cast.map(id=>'<button data-person="'+id+'">'+name(id)+'</button>').join('')+'</div></div><div class="storyboard"><nav class="scene-list" aria-label="'+day+'일차 장면">'+d.events.map((e,i)=>'<button data-event="'+i+'" aria-controls="event-detail" aria-pressed="false"><span class="seq">'+String(i+1).padStart(2,'0')+'</span><small>'+e.place+'</small><b>'+e.title+'</b></button>').join('')+'</nav><article class="event-detail" id="event-detail" aria-live="polite"></article></div><div class="day-bottom"><div class="order-panel"><h4>오늘의 실제 주문</h4>'+d.orders.map(([who,drink,id])=>'<div class="order">'+(id?'<img loading="lazy" src="'+esc(D.assets['cocktail_'+id].src)+'" alt="">':'<i class="order-dot" aria-hidden="true">◇</i>')+'<div><b>'+who+'</b><br><span>'+drink+'</span></div></div>').join('')+'</div><div class="change-panel"><h4>루나의 변화 → 다음 날의 이유</h4><div class="change-line"><span>'+d.before+'</span><em>→</em><span>'+d.after+'</span></div><p>'+d.next+'</p></div></div><details class="dialogue-reader"><summary>실제 반영 대사 펼쳐 보기</summary><p class="reader-note">플레이에 쓰는 같은 대사 데이터를 읽습니다. 선택 분기는 각각 분리되어 있습니다.</p><label>확인할 구간<select id="script-section"></select></label><div class="dialogue-lines" id="dialogue-lines"></div></details>';
 const opts=day===0?[['day0','바 · 튜토리얼과 첫 손님'],['resident','주거층 주민'],['night0','집·테라스']]:[['opening','오픈 전'],['bar','단골 영업'],...(day===1?[['workshop','심야 작업장'],['night1','자기 기억']]:day===2?[['commute2','출근길'],['night2','테라스 대화'],['johnny','테라스 중 조니의 기억']]:[['commute3','출근길'],['ending','테라스 엔딩'],['terraceMemory3','테라스 중 유나 회상']])];$('#script-section').innerHTML=opts.map(([id,label])=>'<option value="'+id+'">'+label+'</option>').join('');$('#script-section').addEventListener('change',renderScript);renderScript();setEvent(0);
}
function setEvent(n){eventIndex=n;const d=G.days[day],e=d.events[n],type=e.place.includes('연구소')||e.place.includes('자기 기억')?'lab':e.place.includes('바')||e.id==='johnny-memory'?'bar':'city';document.querySelectorAll('[data-event]').forEach(b=>b.setAttribute('aria-pressed',+b.dataset.event===n));$('#event-detail').innerHTML='<div class="scene-image '+type+'"><span class="scene-number">DAY 0'+day+' / SCENE '+String(n+1).padStart(2,'0')+' · 구성 참고 이미지</span>'+(e.cast.length?e.cast.filter(id=>D.characterLayers[id]).slice(0,3).map(portrait).join(''):'<span class="scene-motif" aria-hidden="true">'+({lab:'◈',city:'◇',bar:'◌'}[type])+'</span>')+'</div><div class="event-copy"><span class="badge '+(e.scope==='optional'?'muted':'')+'">'+(e.scope==='optional'?'선택 탐색':'주 진행')+'</span><h3>'+e.title+'</h3><p>'+e.what+'</p><div class="event-fields"><div><h4>플레이어가 하는 일</h4><p>'+e.action+'</p></div><div><h4>이 장면이 남기는 것</h4><p>'+e.change+'</p></div></div><div class="stage-note"><b>연출·구현 기준</b><br>'+e.stage+'</div><div class="event-nav"><button data-event-prev '+(n===0?'disabled':'')+'>← 이전 장면</button><small>'+(n+1)+' / '+d.events.length+'</small><button data-event-next '+(n===d.events.length-1?'disabled':'')+'>다음 장면 →</button></div></div>';}
function renderScript(){const key=$('#script-section').value;let rows;if(key==='day0'){const ids=new Set(D.tables.scenes.filter(s=>Number(s.day)===0).map(s=>s.id));rows=D.tables.steps.filter(s=>ids.has(s.context));}else rows=key==='bar'?S.bar[day]:key==='opening'?S.opening[day]:S.scenes[key];$('#dialogue-lines').innerHTML=(rows||[]).map(r=>r.type==='say'||(!r.type&&r.text)?'<p><b>'+esc(r.who||name(r.actor))+'</b>'+esc(r.text||r['text.ko'])+'</p>':(['order','craft','serve','campaign_menu','campaign_memory','campaign_response','choice'].includes(r.type)?'<p class="checkpoint">'+esc({order:'주문 · '+(r.arg||''),craft:'제조 플레이',serve:'코스터에 제공',campaign_menu:'플레이어가 메뉴 선택',campaign_memory:'조니의 기억 → 관찰 메모',campaign_response:'응대 A / B 중 하나 선택',choice:'튜토리얼 선택 분기'}[r.type])+'</p>':'')).join('');}
const positions={luna:[50,48],chris:[17,20],port:[83,20],aili:[16,77],tom:[50,86],samho:[85,78],johnny:[50,9]};
$('#relationship-map').innerHTML='<svg viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true">'+G.relations.map(([a,b],i)=>'<line data-edge="'+i+'" x1="'+positions[a][0]+'" y1="'+positions[a][1]+'" x2="'+positions[b][0]+'" y2="'+positions[b][1]+'"/>').join('')+'</svg>'+Object.entries(positions).map(([id,[x,y]])=>'<button class="person-node" data-person="'+id+'" style="left:'+x+'%;top:'+y+'%" aria-pressed="false" aria-controls="person-detail"><strong>'+name(id)+'</strong><small>'+({luna:'BARTENDER',chris:'MENTOR',port:'MEMORY CHIP',aili:'CONNECTION',tom:'THE REQUEST',samho:'THE CHOICE',johnny:'THE MEMORY'}[id])+'</small></button>').join('');
function setPerson(id){person=id;const p=G.people[id],linked=new Set([id]);G.relations.forEach(([a,b])=>{if(a===id||b===id){linked.add(a);linked.add(b);}});document.querySelectorAll('.person-node').forEach(b=>{b.setAttribute('aria-pressed',b.dataset.person===id);b.classList.toggle('dim',!linked.has(b.dataset.person));});document.querySelectorAll('[data-edge]').forEach(l=>{const [a,b]=G.relations[l.dataset.edge],on=a===id||b===id;l.classList.toggle('active',on);l.classList.toggle('dim',!on);});$('#person-detail').innerHTML='<div class="person-title">'+portrait(id)+'<div><h3>'+p.name+'</h3><small>'+p.role+'</small></div></div><p>'+p.want+'</p><ol>'+p.arc.map((s,i)=>'<li><small>DAY 0'+i+'</small>'+s+'</li>').join('')+'</ol>';$('#relation-list').innerHTML=G.relations.filter(([a,b])=>a===id||b===id).map(([a,b,title,text])=>'<article class="relation"><strong>'+name(a)+' ↔ '+name(b)+'</strong><b>'+title+'</b><p>'+text+'</p></article>').join('');}
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.hasAttribute('data-day')){setDay(+b.dataset.day);history.replaceState(null,'','#day-'+day);if(b.dataset.scroll)$('#journey').scrollIntoView();}if(b.hasAttribute('data-event'))setEvent(+b.dataset.event);if(b.hasAttribute('data-event-prev'))setEvent(Math.max(0,eventIndex-1));if(b.hasAttribute('data-event-next'))setEvent(Math.min(G.days[day].events.length-1,eventIndex+1));if(b.hasAttribute('data-person')){setPerson(b.dataset.person);if(!b.classList.contains('person-node'))$('#people').scrollIntoView();}});
$('#day-tabs').addEventListener('keydown',e=>{let n=day;if(e.key==='ArrowRight')n=(day+1)%4;else if(e.key==='ArrowLeft')n=(day+3)%4;else if(e.key==='Home')n=0;else if(e.key==='End')n=3;else return;e.preventDefault();setDay(n);$('#tab-day-'+n).focus();history.replaceState(null,'','#day-'+n);});
window.addEventListener('hashchange',()=>{const m=location.hash.match(/^#day-([0-3])$/);if(m){setDay(+m[1]);$('#journey').scrollIntoView();}});
setDay(day);setPerson(person);if(location.hash.startsWith('#day-'))requestAnimationFrame(()=>$('#journey').scrollIntoView({behavior:'instant'}));
})();
